- scss/_patterns_side-navigation.scss
- templates/_layouts/docs.html
- templates/docs/examples/patterns/side-navigation/_default.html
- templates/docs/examples/patterns/side-navigation/_example_script.js
- templates/docs/examples/patterns/side-navigation/_icons.html
- templates/docs/examples/patterns/side-navigation/docs.html
- templates/docs/examples/patterns/side-navigation/icons.html
- templates/docs/examples/patterns/side-navigation/raw-html.html
- templates/docs/examples/templates/maas-docs-grid.html
- templates/docs/examples/templates/maas-docs.html
- templates/docs/examples/templates/snapcraft-publicise.html
- templates/docs/patterns/navigation.md
- templates/static/js/scripts.js
Adds `aria-current="page"` as preferred way to select active page in side navigation.
Updates documentation and examples.
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-3069.run.demo.haus/docs)
- Check [side navigation examples](https://vanilla-framework-canonical-web-and-design-pr-3069.run.demo.haus/docs/examples/patterns/side-navigation/default)
- make sure both `aria-current` and `is-active` class works to select active item
- Check [Vanilla docs side navigation](https://vanilla-framework-canonical-web-and-design-pr-3069.run.demo.haus/docs)
- make sure `aria-current` is used to select current page in the side nav
> Use aria-current to select current page in side navigation

- scss/_patterns_side-navigation.scss
- templates/_layouts/docs.html
- templates/docs/component-status.md
- templates/docs/examples/layouts/documentation.html
- templates/docs/examples/patterns/side-navigation/_default.html
- templates/docs/examples/patterns/side-navigation/_icons.html
- templates/docs/examples/patterns/side-navigation/_toggle_script.js
- templates/docs/examples/patterns/side-navigation/docs.html
- templates/docs/examples/patterns/side-navigation/icons.html
- templates/docs/examples/patterns/side-navigation/raw-html.html
- templates/docs/patterns/navigation.md
Adds no-JS fallback to the side navigation component
Fixes #3026 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-3065.run.demo.haus/docs/)
- Disable JS in browser
- Check [Vanilla docs](https://vanilla-framework-canonical-web-and-design-pr-3065.run.demo.haus/docs/) on small screen, make sure side navigation can be toggled on/off
- Check all [Side navigation examples](https://vanilla-framework-canonical-web-and-design-pr-3065.run.demo.haus/docs/examples), make sure toggle works without JS
- Enable JS in browser
- Check [Side navigation examples](https://vanilla-framework-canonical-web-and-design-pr-3065.run.demo.haus/docs/examples) again, make sure clicking on toggle with JS enabled doesn't change the URL
> Add no-JS fallback to side navigation component

- package.json
Just a version bump for next release.
- './run' or [demo](https://vanilla-framework-canonical-web-and-design-pr-3070.run.demo.haus/docs)
- Check the [docs](https://vanilla-framework-canonical-web-and-design-pr-3070.run.demo.haus/docs) if latest version is 2.11
> Bump Vanilla version to 2.11

- scss/_patterns_lists.scss
- tests/parker.js
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3066
- Pull code
- Run `./run`
- Open docs/examples/patterns/lists/lists-stepped-detailed
- Verify .p-stepped-list__content has margin-left:0 beyond $breakpoint-medium 
Large
Small:
> scope margin-left on p-stepped-list__content  to stepped list only

- scss/_global_functions.scss
Fixes #2955 
- Pull code
- in `_pattern_icons.scss` replace color in any icon mixin `@include vf-icon-anchor($color-mid-dark);` with rgba value (like `@include vf-icon-anchor(rgba(255,255,255,0.5))`;
- rebuild vanilla (there should be no errors)
- check icons example locally, see if transparent color was correctly applied to the icon changed
> Support rgba colors in `vf-url-friendly-color` function

- scss/_patterns_links.scss
- templates/docs/examples/templates/external-links.html
- Pull code
- Run `./run`
- Open /docs/examples/patterns/links/links-external#www.youtube.com/watch?v=Sv3Z_gbRVgQ, verify the appearance of the focused link around the external icon matches the "After" screenshot shown below:
Before: 
After:
> fix external link icon lineheight so it doesn't distort focus outline

- scss/_patterns_navigation.scss
- scss/_patterns_tabs.scss
- templates/docs/examples/patterns/tabs.html
Fix a focus states in the tabstrip and nav. partial fix for https://github.com/canonical-web-and-design/vanilla-framework/issues/3073
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples/patterns/navigation/default-dark and /docs/examples/patterns/tabs
- Verify the focus outline appears within the elements, rather than outside them
Tabs: 
Nav:
Fixes #3073
> Fix focus outline in navigation and tabs

- scss/_patterns_divider.scss
Remove vertical offsets from divider lines
Fixes #3086
- Pull code
- Run `./run`
- Open docs/examples/patterns/lists/divider
- Verify divider lines span the full height of the component.
> Remove vertical offsets from divider lines

- scss/_base_button.scss
- scss/_base_typography-definitions.scss
- scss/_global_functions.scss
- scss/_patterns_buttons.scss
- scss/_patterns_pagination.scss
- scss/_patterns_strip.scss
- scss/_patterns_tabs.scss
- scss/_utilities_muted-text.scss
- scss/_vanilla.scss
- templates/_layouts/docs.html
- templates/docs/base/typography.md
- templates/docs/component-status.md
- templates/docs/examples/utilities/muted-text.html
Fixes  #3063 - Add .p-muted-text class that turns text #666
Drive-by: Fixes #3062 -  change the few instances of text color that are not #111, but #000, to #111.
- Pull code
- Run `./run`
- Open http://192.168.64.2:8101/docs/base/typography, check doc is ok (at bottom)
- Open http://192.168.64.2:8101/docs/examples/patterns/muted-text, make sure text is `#666`
> Add muted text and small refactor

- templates/static/js/example.js
CodePen seems to be using `decodeURI` when reading data from `data-prefill` attribute.
So we need to use `encodeURI` when setting the attribute to make sure it's correctly encoded if it contains any special characters.
Fixes #3093
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-3094.run.demo.haus/docs/layouts/documentation)
- Go to [/docs/layouts/documentation](https://vanilla-framework-canonical-web-and-design-pr-3094.run.demo.haus/docs/layouts/documentation), there should be no errors in console, CodePen should be rendered
- Make sure codepen renders on other pages as well
> Encode CodePen prefill data

- scss/_patterns_contextual-menu.scss
- templates/docs/examples/templates/z-index.html
Fixes a regression issue of z-index between tabs and contextual menu.
Adds an example to make sure we avoid this regression in future.
Fixes #3068
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-3095.run.demo.haus/docs/examples/templates/z-index)
- Check [z-index example](https://vanilla-framework-canonical-web-and-design-pr-3095.run.demo.haus/docs/examples/templates/z-index), make sure contextual menu renders correctly, not overlapping with tabs borders
> Fix z-index issues between contextual menu and tabs

- snapshots.js
Removes non-example screenshots from Percy
Fixes #2957 
- Check if Percy screenshots only examples (not documentation pages)
> Snapshot only example screenshots for Percy

- templates/docs/patterns/heading-icon.md
header ≠ heading. 
As a drive-by, use real multiplication signs, add a missing comma and capitalize “Markdown”.
> Docs: fix typo in heading-icon.md

- scss/_patterns_contextual-menu.scss
- scss/_settings_colors.scss
- templates/docs/examples/patterns/side-navigation/_icons.html
Update light theme border and highlight colors to be transparent to fix hover issue in side navigation on gray (`#f7f7f7`) background.
Fixes usage of proper `--highlight` color on hover in contextual menu light theme.
Fixes #3105 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-3106.run.demo.haus/docs/examples/patterns/side-navigation/default)
- Go to [side navigation light examples](https://vanilla-framework-canonical-web-and-design-pr-3106.run.demo.haus/docs/examples/patterns/side-navigation/default), make sure they look of both on white and light grey backgrounds
- Go to [contextual menu example](https://vanilla-framework-canonical-web-and-design-pr-3106.run.demo.haus/docs/examples/patterns/contextual-menu/default), …
> Update light theme border and highlight colors to be transparent

- package.json
Bumps version of Vanilla to 2.12.1 for the release
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-3108.run.demo.haus/)
- Make sure demo shows correct version
> Bump version to 2.12.1

- scss/_patterns_accordion.scss
- templates/docs/examples/patterns/accordion/_script.js
- templates/docs/examples/patterns/accordion/default.html
- templates/docs/examples/patterns/accordion/headings.html
- templates/docs/patterns/accordion.md
Updates accordion to fix the bug with misaligned icon when text wraps.
Adds a variant to support headings in accordion buttons.
Fixes #2926 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-3107.run.demo.haus/docs/examples/patterns/accordion/headings)
- Check accordion with headings example: https://vanilla-framework-canonical-web-and-design-pr-3107.run.demo.haus/docs/examples/patterns/accordion/headings
- Make sure documentation is fine (Codepen will show unstyled version until released): https://vanilla-framework-canonical-web-and-design-pr-3107.run.demo.haus/docs/patterns/accordion#headings
> Update positioning of accordion icon and support headings in accordion

- scss/_patterns_lists.scss
Fix #1917 as agreed in https://app.zeplin.io/project/5edf6c235bee26b85b117af7/dashboard?seid=5edf6c93b4f7a9982d6866d9
- Pull code
- Run `dotrun`
- Open docs/examples/patterns/lists/lists-stepped-detailed
Verify the list has borders:
> add borders to detailed list

- scss/_patterns_tabs.scss
Fixes tab strip border overflowing focus outline
Fixes #3073
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-3128.run.demo.haus/docs/examples/patterns/tabs)
- Go to [tabs example](https://vanilla-framework-canonical-web-and-design-pr-3128.run.demo.haus/docs/examples/patterns/tabs), check if focus outline looks fine and is not covered by border
> Fix focus outline in tab strip

- scss/_settings_font.scss
- templates/docs/base/typography.md
Uses `font-display: optional` by default to improve perceived loading performance.
Fixes #2569 #2701 
- Pull code
- Run `./run`
- You should see fallback font on first page load (until it is cached)
> Use font-display optional by default

- scss/_patterns_article-pagination.scss
Makes sure we `@extend` only `%placeholders` and not `.classnames` in SCSS.
Fixes #2361 
- CI checks should pass
- There should be no visual regressions
> Extend %placeholder instead of .classname in SCSS

- scss/_patterns_lists.scss
- templates/_layouts/docs.html
- templates/docs/component-status.md
- templates/docs/examples/patterns/lists/lists-inline-stretch-align.html
- templates/docs/examples/patterns/lists/lists-inline-stretch.html
- templates/docs/patterns/lists.md
Adds new list variant to cover cases where flexbox utils on custom styles were used to lay out elements.
Fixes #2923
Fixes #2451 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-3139.k8s.demo.haus/docs/examples/patterns/lists/lists-inline-stretch)
- Check the stretch list example: https://vanilla-framework-3139.k8s.demo.haus/docs/examples/patterns/lists/lists-inline-stretch
- Check the stretch example with align utils: https://vanilla-framework-3139.k8s.demo.haus/docs/examples/patterns/lists/lists-inline-stretch-align
- Check the updated lists documentation page: https://vanilla-framework-3139.k8s.demo.haus/docs/patterns/lists#inline- stretched
- note that CodePen will show unstyled examples (as it uses published version of Vanilla that doesn't …
> Add list inline stretch variant

- templates/docs/examples/patterns/lists/lists-inline-stretch-align.html
Fixes a typo in class name
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-3146.k8s.demo.haus)
- Check [list stretched aligned example](https://vanilla-framework-3146.k8s.demo.haus/docs/examples/patterns/lists/lists-inline-stretch-align), label should be vertically centered
> Fix typo in class name in list example

- package.json
Bump version of Vanilla for next release
- Check if [version is correct](https://vanilla-framework-3156.k8s.demo.haus/docs/)
- Check [component status page](https://vanilla-framework-3156.k8s.demo.haus/docs/component-status)
> Bump version of Vanilla to 2.14.0

- package.json
- scss/_settings_font.scss
- templates/docs/base/typography.md
Because of the cases of Ubuntu font not rendering at all in some cases, even on fast connections, we change default value to 'fallback' - this makes sure the text is rendered immediately, but web font still has a small time window to load to be rendered.
Fixes #3157 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-3164.demos.haus)
- Make sure text is rendered immediately with fallback font, but Ubuntu font is loaded on fast connection
> Change default font-display value to fallback

- Dockerfile
Makes sure building docker image uses yarn.lock
Docker image should build correctly, demo should work as expected
Demo: https://vanilla-framework-3182.demos.haus/
> Add yarn.lock to docker image

- package.json
- templates/_layouts/docs.html
- templates/docs/component-status.md
Bumps version of Vanilla to 2.15, updates component status for new release.
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-3194.demos.haus)
- Check docs if new version is displayed: https://vanilla-framework-3194.demos.haus/docs
- Check if Chip is listed as new in side navigation and status page: https://vanilla-framework-3194.demos.haus/docs/component-status
> Bump version of Vanilla to 2.15.0

- scss/standalone/patterns_chip.scss
Fix icons in standalone examples of chip.
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-3195.demos.haus)
- Go to chip standalone examples, make sure dismiss icon displays correctly
-  https://vanilla-framework-3195.demos.haus/docs/examples/standalone/patterns/chip/with-dismiss
- https://vanilla-framework-3195.demos.haus/docs/examples/standalone/patterns/chip/long-values
before
after
> Fix icons in standalone chip examples

- scss/_patterns_strip.scss
- templates/_layouts/docs.html
- templates/docs/examples/patterns/strips/suru-topped.html
- templates/docs/examples/patterns/strips/suru.html
- templates/docs/patterns/strip.md
- Added new strip classes: p-strip--suru and p-strip--suru-topped
- Added new example templates for the new classes
- Updated the documentation to include the new classes
Fixes #2539 
- Pull code
- Run `./run`
- Navigate to http://0.0.0.0:8101/docs/examples/patterns/strips/suru and ensure that the pattern is congruent with the [specification](https://github.com/canonical-web-and-design/vanilla-framework/issues/2539) and [meeting notes](https://github.com/canonical-web-and-design/meeting-notes/issues/596).
- Do the same for http://0.0.0.0:8101/docs/examples/patterns/strips/suru-topped
- Navigate to the strip section in the [documentation](http://0.0.0.0:8101/docs/patterns/strip) and ensure that the copy is sensible and consistent in style to the rest …
> Add suru strips to Vanilla

- package.json
- templates/_layouts/docs.html
- templates/docs/component-status.md
Bump version of Vanilla and update component status in docs in preparation for next release.
- `./run` or http://0.0.0.0:8101/ or [demo](https://vanilla-framework-3200.demos.haus)
- Visit [docs](https://vanilla-framework-3200.demos.haus), make sure Vanilla version is correct
- Check [component status](https://vanilla-framework-3200.demos.haus/docs/component-status), make sure it's up to date
> Bump version of Vanilla to 2.16, update components status

- scss/_base_tables.scss
- scss/_base_typography-definitions.scss
- Update table header labels to `#111`
- Update header row border to light grey
- Update rest of table borders to a lighter grey
What this aimes to do: 
- Make the end of one table and beginning of next more prominent, as the grey labels are too subtle. We had some discussions around this in the jaas multiple tables on the same page
- Match recent designs:
- Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2836, https://github.com/canonical-web-and-design/vanilla-squad/issues/861
- Pull code
- Run `./run`
- Open docs/examples/patterns/tables/table-mobile-card or [demo]
- Verify it looks like this:
> Update table header labels and border colours

- scss/_patterns_strip.scss
Update the Suru strip topped pattern to match its usage to easy the adoption.
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples/patterns/strips/suru-topped
- Check the `linear-gradients` match the [one used on ubuntu.com](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/scss/_patterns_strip.scss#L176).
- Example pages on ubuntu.com: https://ubuntu.com/appliance
> Update the suru strip topped pattern

- .stylelintrc.json
- scss/_base_forms-tick-elements.scss
Extracts styled tick boxes styling into placeholders, so they can be reused when building new checkbox pattern.
This is just a refactor branch, it only restructures the code, no functionality or styling changes in the branch.
- `./run` or [demo](https://vanilla-framework-3215.demos.haus)
- Make sure [tick elements](https://vanilla-framework-3215.demos.haus/docs/examples/templates/tick-element-comparison) work as before, there should be no regressions or changes to styling
> Base form tick elements refactoring

- scss/_base_forms-tick-elements.scss
- scss/_patterns_form-tick-elements.scss
- scss/_vanilla.scss
- scss/standalone/patterns_form-tick-elements.scss
- templates/_layouts/docs.html
- templates/docs/base/forms.md
- templates/docs/examples/patterns/forms/_checkbox-heading.html
- templates/docs/examples/patterns/forms/_checkbox-inline.html
- templates/docs/examples/patterns/forms/_checkbox.html
- templates/docs/examples/patterns/forms/_radio-heading.html
- templates/docs/examples/patterns/forms/_radio-inline.html
- templates/docs/examples/patterns/forms/_radio.html
- templates/docs/examples/patterns/forms/checkbox-heading.html
- templates/docs/examples/patterns/forms/checkbox-inline.html
- templates/docs/examples/patterns/forms/checkbox.html
- templates/docs/examples/patterns/forms/radio-heading.html
- templates/docs/examples/patterns/forms/radio-inline.html
- templates/docs/examples/patterns/forms/radio.html
- templates/docs/examples/patterns/forms/tick-comparison.html
- templates/static/js/example.js
Replaces #3198
Adds `p-checkbox` and `p-radio` components to have a better control over styling and spacing than with base checkbox styles.
Fixes #2931 
Fixes #3181
Fixes #3177
-  `./run` or [demo](https://vanilla-framework-3224.demos.haus/docs/examples/patterns/forms/tick-comparison)
- Go to [tick elements comparison page](https://vanilla-framework-3224.demos.haus/docs/examples/patterns/forms/tick-comparison), make sure new components work as expected compared to deprecated base styles
- Check [updated docs about checkbox and radio buttons](https://vanilla-framework-3224.demos.haus/docs/base/forms#checkbox), make sure they are correct:
> Add p-checkbox and p-radio components

- package.json
- templates/docs/component-status.md
Bumps version of Vanilla to 2.17.0 and updates component status in preparation for release.
- `./run` or [demo](https://vanilla-framework-3229.demos.haus)
- Make sure the updated version is correct
- Check component status, make sure it lists latest changes (https://vanilla-framework-3229.demos.haus/docs/component-status)
> Bump version of Vanilla to 2.17.0

- templates/docs/examples/patterns/contextual-menu/dark.html
- templates/docs/examples/patterns/contextual-menu/default.html
- templates/docs/examples/patterns/contextual-menu/with-indicator.html
- templates/docs/examples/templates/typographic-spacing.html
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/882
- Pull code
- Search repo for instances of button with href. I used this regular expression:
<button\s+(?:[^>]*?\s+)?href=(["'])(.*?)\1
- Verify none exist.
> Remove `href` from buttons

- .github/workflows/pr.yml
- scss/_base_button.scss
- scss/_patterns_buttons.scss
- scss/_patterns_pagination.scss
Adds missing % unit to lightness parameter of the scale-color function. This fixes errors when building with dart-sass.
Also adds GitHub workflow to test building with dart-sass when PR is pushed to make sure we catch such errors in future.
Fixes #3266
- All CI checks should pass
- Make sure new dart check runs and passes
- Verify the affected patterns look the same
- [base buttons](https://vanilla-framework-3267.demos.haus/docs/examples/base/button)
- [component buttons](https://vanilla-framework-3267.demos.haus/docs/examples/patterns/buttons/positive)
- [pagination](https://vanilla-framework-3267.demos.haus/docs/examples/patterns/pagination/pagination)
> Fix errors when building with dart-sass

- scss/_patterns_pull-quotes.scss
- templates/docs/examples/patterns/pull-quotes/variants.html
Fixes misaligned quotes in pull quotes component (when there was no cite or when cite was wrapped).
Adds new example with all combinations and all variants of pull quotes component.
Fixes #2426
In code review it may seem like a lot of changes were made. It's because most of the code was reordered to avoid specificity warnings from linter and remove unnecessary duplicated code.
- `./run` or [demo](https://vanilla-framework-3268.demos.haus/docs/examples/patterns/pull-quotes/variants)
- Check [pull quotes examples](https://vanilla-framework-3268.demos.haus/docs/examples/patterns/pull-quotes/variants), make sure quote characters are correctly positioned regardless of variant, having `<cite>` or not, wrapping, etc
- make sure to check different screen sizes (as pull quotes font is smaller on …
> Fixes misaligned quotes in pull quotes component

- templates/docs/examples/layouts/application-structure.html
- templates/docs/examples/layouts/application.html
Add landmarks to layout examples
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/890
- Pull code
- Run `./run`
- Open the application examples [1](https://vanillaframework.io/docs/examples/layouts/application-structure), [2](https://vanillaframework.io/docs/examples/layouts/application) 
- Review use of landmarks (tags main, aside)
> Add landmarks to layout examples

- templates/docs/examples/layouts/documentation.html
- templates/docs/examples/patterns/side-navigation/_default.html
- templates/docs/examples/patterns/side-navigation/_icons.html
- templates/docs/examples/patterns/side-navigation/_layout-application.html
- templates/docs/examples/patterns/side-navigation/docs.html
- templates/docs/examples/patterns/side-navigation/icons.html
- templates/docs/examples/templates/maas-docs-grid.html
- templates/docs/examples/templates/maas-docs.html
Add landmark region roles to side navigation. 
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/865
- Pull code
- Run `./run`
- Review use of roles in all side navigation examples
> Add roles and correct tags to side navigation

- package.json
Updates Vanilla version for next release.
- `./run` or [demo](https://vanilla-framework-3275.demos.haus)
- Make sure version is 2.18.0
> Bump version to 2.18.0

- scss/_patterns_navigation.scss
- scss/_patterns_subnav.scss
Increase the prominance of hover and selected navigation items.
This is option 2, (as in charmhub).
Do not merge: the two options need to be presented and whichever is chosen can then be merged.
- Pull code
- Run `./run`
- Open /docs/examples/patterns/navigation/default-dark#navigation or [demo]
- Verify it looks like this:
> Navigation highlight update option 2

- scss/_patterns_table-sortable.scss
- templates/docs/component-status.md
- templates/docs/examples/base/forms/aligned-checkboxes.html
- templates/docs/examples/base/forms/aligned-radio.html
- templates/docs/examples/base/table.html
- templates/docs/examples/layouts/application-structure.html
- templates/docs/examples/layouts/application.html
- templates/docs/examples/layouts/documentation.html
- templates/docs/examples/patterns/forms/_checkbox-inline.html
- templates/docs/examples/patterns/forms/_radio-inline.html
- templates/docs/examples/patterns/forms/tick-comparison.html
- templates/docs/examples/patterns/tables/table-colored-rows.html
- templates/docs/examples/patterns/tables/table-expanding.html
- templates/docs/examples/patterns/tables/table-mobile-card.html
- templates/docs/examples/patterns/tables/table-sortable.html
- templates/docs/examples/templates/maas-docs-grid.html
- templates/docs/examples/templates/maas-layout.html
- templates/docs/examples/templates/tick-element-comparison.html
- templates/docs/examples/utilities/table-cell-padding-overlap.html
- templates/docs/examples/utilities/truncate.html
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/870
- Remove grid and table-related roles from `<table>` elements
- Add aria-labels to all tables
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ table examples, ensure there are no visual or interaction changes
- Review whether aria-labels on tables are clear and understandable
Adding do not merge as this breaks the sortable table example which relies on roles. @bartaz what approach would you recommend to fix that?
> Fix table-related accessibility issues

- templates/_layouts/examples.html
- templates/docs/examples/base/hr-dark.html
- templates/docs/examples/base/hr.html
- templates/docs/examples/layouts/application-structure.html
- templates/docs/examples/layouts/application.html
- templates/docs/examples/layouts/documentation.html
- templates/docs/examples/patterns/grid/responsive.html
- templates/docs/examples/patterns/side-navigation/dark.html
- templates/docs/examples/templates/maas-docs-grid.html
- templates/docs/examples/templates/maas-docs.html
- templates/docs/examples/templates/snapcraft-publicise.html
- templates/docs/examples/templates/typographic-spacing.html
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/869
- Pull code
- Run `./run`
- Verify styles have been moved to the head. There should be no visual changes.
> Accessibility validator fix: Moves any `<style>` tags on example pages to the `<head>`

- package.json
Bump version of Vanilla to 2.19
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-3288.demos.haus/docs)
- Check if version is correct and component status lists the changes https://vanilla-framework-3288.demos.haus/docs/component-status
> Bump version of Vanilla to 2.19

- templates/docs/examples/patterns/contextual-menu/dark.html
- templates/docs/examples/patterns/contextual-menu/default.html
- templates/docs/examples/patterns/contextual-menu/with-indicator.html
- templates/docs/examples/patterns/modal/default.html
- templates/docs/examples/templates/maas-layout.html
- templates/docs/examples/templates/z-index.html
- Remove width from anchor elements ([validator complaints](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fvanillaframework.io%2Fdocs%2Fexamples%2Fpatterns%2Fmodal%2Fdefault))
- Remove "submenu" aria-labels ([validator complaints](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fvanillaframework.io%2Fdocs%2Fexamples%2Ftemplates%2Fz-index))
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/878
- Pull code
- Run `./run`
- Inspect code, verify the issues highlighte by the vbalidator have been resolved (only limited to aria-label and anchor width, the rest will be on separate prs)
> Remove width attrib from anchors, remove invalid aria-labels from contextual menu

- templates/docs/examples/templates/snapcraft-publicise.html
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/873
- Pull code
- Inspect changed files, verify checked is no longer present on select. Or use this 
regex to search the codebase, there should be no occurances: <select\s+(?:[^>]*?\s+)?checked=(["'])(.*?)\1
> Remove attr checked from select

- templates/docs/examples/layouts/documentation.html
- templates/docs/examples/templates/maas-docs-grid.html
- templates/docs/examples/templates/maas-docs.html
- templates/docs/examples/templates/tick-element-comparison.html
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/874
- Pull code
- Search for action="", verify there are no occurances
> Remove empty action attributes from vanilla examples to avoid validator errors

- templates/showcase.html
Removes invalid links from showcase page (missing pages or sites that don't use vanilla anymore)
Fixes #2909 
- Run `./run` or [demo](https://vanilla-framework-3305.demos.haus/showcase)
- Make sure [showcase](https://vanilla-framework-3305.demos.haus/showcase) page doesn't contain invalid links
> Remove invalid links from showcase page

- templates/docs/examples/patterns/list-tree.html
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3228
- Pull code
- Run `./run`
- Ensure tree example isn't broken
- Verify roles down the hierarchy are exactly as described in the [spec](https://www.w3.org/TR/wai-aria-practices/#tree_roles_states_props). There's an [example](https://www.w3.org/TR/wai-aria-practices/examples/treeview/treeview-1/treeview-1a.html) to compare to.
> Fix tree component roles as per spec

- scss/_patterns_list-tree.scss
Before:
After:
- Inspect tree list example docs/examples/patterns/list-tree
- activate focus on an element with classname __toggle
- verify it looks as above
> Apply standard vanilla focus state to treeview items

- scss/_utilities_show.scss
- templates/docs/examples/utilities/show.html
Fix `u-show` utility to correctly set display to `initial` (but keep `inherit` for IE).
Fixes #3321
- Run `./run` or [demo](https://vanilla-framework-3330.demos.haus/docs/examples/utilities/show)
- Check the [show utility example](https://vanilla-framework-3330.demos.haus/docs/examples/utilities/show), make sure it correctly displays elements on relevant screen sizes, resetting inline elements back to inline state.
> Fix show utility to correctly set initial value

- package.json
Update version of Vanilla for next release.
- Run `./run` or [demo](https://vanilla-framework-3331.demos.haus/docs)
- Make sure version is correct in [docs](https://vanilla-framework-3331.demos.haus/docs)
> Bump version to 2.19.1

- templates/_layouts/docs.html
Vanilla docs pages were not using the same stylesheet as 'brochure' site, so cookie policy dialog was not styled properly on docs pages.
This PR fixes it by including site CSS on all pages.
- Run `./run` or [demo](https://vanilla-framework-3332.demos.haus/docs)
- Go to [docs](https://vanilla-framework-3332.demos.haus/docs),  cookie dialog should be correctly styled
> Make sure cookie policy is correctly styled in docs

- .gitignore
- package.json
- yarn.lock
- Bump cookie policy to v3.03
- Update GTM to track initial pageview
- Pull code
- Run `./run`
- See that it is using cookie policy 3.03
> Bump to cookie version v3.03

- scss/_patterns_side-navigation.scss
Fixes #3269 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-3345.demos.haus/docs/examples)
- Check all variants side navigation examples (light / dark, documentation, raw html, etc) - make sure titles render with new color
> Update color of side navigation headings

- templates/docs/examples/patterns/list-tree.html
Quick fix to add treeitem roles on li's that have ul with role group inside.
- Pull code
- Run `./run`
- Open docs/examples/patterns/list-tree
- verify al lli's have a role of treeitem
> Add missing treeitem roles on li that have ul in them

- templates/docs/search.html
- Fixed broken “Previous” and “Next” links in search results.
Fixes #3358.
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/search?q=accordion&start=11&siteSearch=vanillaframework.io/docs
- Follow the “Previous” or “Next” links.
> Fixes broken pagination links in search results

- scss/_base_code.scss
- scss/_base_typography.scss
- templates/docs/base/code.md
- templates/docs/examples/base/code-block.html
- templates/docs/examples/base/code-inline.html
- templates/docs/examples/base/pre.html
Fix #2037
- Pull code
- Run `./run`
- paste this anywhere, ensure the font-family is ubuntu mono: `<pre>Test</pre>`
> Ensure <pre> elements use ubuntu mono instead of browser default

- scss/_patterns_subnav.scss
Remove unnecessary wrong media query from subnav
Fixes #3371
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-3372.demos.haus/docs/examples/patterns/navigation/subnav-dark)
- Subnav should work as before on different screen sizes
> Remove unnecessary wrong media query from subnav

- package.json
- scss/_patterns_table-expanding.scss
- scss/_utilities_hide.scss
- templates/docs/base/tables.md
- templates/docs/component-status.md
- templates/docs/examples/patterns/tables/table-expanding.html
- templates/docs/examples/utilities/hide-table-columns.html
- templates/docs/upgrade-guide-v3.md
- tests/parker.js
- Updates `u-hide` utility to work properly with table columns (we collapse columns to 0 width instead of hiding with display), with an exception of expanding table (which uses flex layout and needs to use display none for hiding).
- Updates expanding table to remove use of `u-hide` util and provide hiding using `aria-hidden`
- Fix IE rendering issues with expanding table
Fixes #3337
Fixes #2726
- `./run` or [demo](https://vanilla-framework-3363.demos.haus/docs)
- Check [new example for hiding table columns](https://vanilla-framework-3363.demos.haus/docs/examples/utilities/hide-table-columns)
- check different screen widths, different browsers
- Check updated [example of expanding table](https://vanilla-framework-3363.demos.haus/docs/examples/patterns/tables/table-expanding)
- Make sure …
> Update u-hide util for table columns and fix table expanding issues

- templates/static/js/scripts.js
- remove scroll block on body when side nav is open to fix in-page anchors in docs
Fixes #3292 
- Run `./run` or [demo](https://vanilla-framework-3380.demos.haus/docs)
- Go to Vanilla docs (desktop and mobile - use real mobile device, not just small browser)
- Go to long page with anchors (code, forms, etc)
- Make sure anchor links scroll correctly
> Fix anchor links in side navigation on mobile

- templates/docs/examples/patterns/navigation/_script.js
Flipped the true/false values in the ternary that sets the `aria-hidden` attribute on sub navs, to ensure that they're showing the appropriate value.
Fixes #3264 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples/patterns/navigation/subnav or [demo]
- Open your console
- Click any of the navigation items, and in the page inspector, see that the `aria-hidden` attribute on the visible `ul.p-subnav__items` is `false`, and `true` on the hidden subnavs.
> fix incorrect aria-hidden value on subnavigation

- scss/_patterns_matrix.scss
Removed top border from first matrix item on small screens
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples/patterns/matrix or [demo]
- At the small screen breakpoint, see that the first list item doesn't have a top border
- Resize your browser through the wider breakpoints and see that the top border shows/hides appropriately
- Compare to https://vanillaframework.io/docs/examples/patterns/matrix
Fixes #2517 
Before:
After:
> remove top border from first item in matrix on small screens

- scss/_utilities_baseline-grid.scss
- scss/standalone/example.scss
- templates/_layouts/examples.html
- templates/static/js/example.js
Fixes rendering examples with custom styles in embeded CodePen examples.
- removes example baseline styles from example template
- adds parsing style from `<head>` and adding them to CodePen as CSS tab
Fixes #3393 
- Run `./run` or [demo](https://vanilla-framework-3395.demos.haus/docs/layouts/application)
- Go to application layout documentation, CodePen examples should show the examples without styling errors (like messy margins): https://vanilla-framework-3395.demos.haus/docs/layouts/application
- Check application layout examples directly, make sure they render ok
- Check some other examples, make sure they display baseline grid as expected
> Fix adding custom styles to embedded examples

- .stylelintrc.json
- scss/docs/_patterns_syntax-highlight.scss
Added a selector-class-pattern regex to stylelint, for BEM linting.
Fixes #3013 
- Pull code
- Run `dotrun`
- Open your editor, and any scss file
- Edit a class selector to be un-BEMmy
- See that the editor highlights the problem with a `selector-class-pattern` error.
> Enforce BEM class naming

- scss/_patterns_forms.scss
- templates/docs/examples/patterns/forms/form-inline.html
Fixed a bug where formgroups and buttons inside a `.p-form--inline` would not wrap and could break out of their parent element.
Fixes #1930 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples/patterns/forms/form-inline or [demo]
- Reduce the width of the viewport, see that the form elements wrap when necessary
Before:
After:
Before:
After:
> Allow .p-form--inline formgroups to wrap when necessary

- templates/docs/examples/index.html
- templates/docs/examples/standalone.html
Build the cookie policy css and import it separately in the example listing and standalone pages.
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3396
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples
- Check you see the cookie policy, if you dont delete the `_cookies_accepted` cookie
- Go to http://0.0.0.0:8101/docs/examples/standalone and see the policy is rendered correctly too
> Fix the cookie policy styling in examples

- .spelling
- package.json
- templates/docs/base/code.md
- templates/docs/base/forms.md
- templates/docs/layouts/documentation.md
- templates/docs/patterns/breadcrumbs.md
- templates/docs/patterns/navigation.md
- templates/docs/patterns/pagination.md
- templates/docs/patterns/strip.md
It seems that since we moved docs to `template/docs` spell checking was silently failing (by not checking any files).
This PR:
- Corrects the path to the docs' markdown files passed to `mdspell` to enable spell checking again
- Fixes spelling errors introduced in the meantime
- Pull code
- Run `dotrun test-spelling`
- Verify that there are no spelling errors and that spell checker checks the files 
- Read the updated docs to check if they are correct
> Fix spell-checking of the docs

- scss/_base_button.scss
- templates/docs/component-status.md
- templates/docs/examples/patterns/buttons/small.html
- templates/docs/patterns/buttons.md
Added `.is-small` modifier class for buttons, and `.is-dense` combo modifier.
Fixes #3341 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples/patterns/buttons/small
- See that the buttons match the visual given in the issue https://github.com/canonical-web-and-design/vanilla-framework/issues/3341
> Add .is-small button class

- scss/_base_icon-definitions.scss
- scss/_patterns_buttons.scss
- templates/docs/examples/patterns/buttons/icon.html
- templates/docs/examples/templates/tick-element-comparison.html
Adds a `fg-color` parameter to the success icon mixin and, when the icon is a child of a button, switches the foreground/tick color to transparent, and sets the background/circle color to white.
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3142
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples/patterns/buttons/icon or [demo](https://vanilla-framework-3410.demos.haus/docs/examples/patterns/buttons/icon)
- See the success icon on each button looks good.
> Add ability to set foreground (tick) color on success icon

- scss/_patterns_buttons.scss
- templates/docs/component-status.md
- templates/docs/examples/patterns/buttons/active.html
- templates/docs/patterns/buttons.md
Adds an `is-active` state class to buttons
Fixes another aspect of https://github.com/canonical-web-and-design/vanilla-framework/issues/3142
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples/patterns/buttons/active or [demo]
- See that the button is not opaque, and also not interactive.
> Add "is-active" button state

- scss/_patterns_form-tick-elements.scss
Set `position: relative;` on `.p-checkbox` to contain the absolutely positioned inputs.
Fixes #3411 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples/patterns/forms/checkbox
- Inspect the `p-checkbox` elements, see that the hidden checkbox element is now contained within its bounds
Before:
After:
> Set position: relative on .p-checkbox

- scss/_base_forms-tick-elements.scss
- scss/_patterns_form-tick-elements.scss
Follow-up to #3414 
Adjusts the positioning of hidden checkbox/radio inputs to align them with their rendered equivalents.
- Run `./run` or [demo](https://vanilla-framework-3415.demos.haus)
- Verify position of the checkbox/radio inputs in different cases:
- [deprecated base styles](https://vanilla-framework-3415.demos.haus/docs/examples/base/forms/checkboxes)
- [checkbox/radio pattern](https://vanilla-framework-3415.demos.haus/docs/examples/patterns/forms/tick-comparison)
Note: It's OK and expected for the input to be misplaced in deprecated base styles (when we don't control the wrapping element in pattern), but in case of p-checkbox and p-radio input should be (more or less) in line with its fake rendered element.
> Adjust position of hidden tick inputs

- scss/_global_functions.scss
Added `:focus-visible` to the vf-focus mixin.
Fixes #3352 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ in Chrome/Chromium
- Tab through the page, see that links still receive a focus state. Click any of the links and see that the focus state is _not_ applied.
This does not yet work on browsers other than Chrome ([MDN Compatibility list](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#Browser_compatibility)). Firefox supposedly supports it using the alternative name `:moz-focusring`, but it seemed to have no effect. Browsers that don't support `:focus-visible` will fall back to the current `:focus` styling.
> Add focus-visible support to vf-focus mixin

- scss/_patterns_code-copyable.scss
Set the `$font-monospace` font family on the command prompt character in the code copyable component.
Fixes #3428 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples/patterns/code-copyable
- See the updated command prompt icon and check that the design is OK
Before:
After:
> Update command prompt font family

- scss/_layouts_application.scss
- scss/_patterns_side-navigation.scss
- templates/docs/component-status.md
- templates/docs/examples/layouts/application/JAAS.html
- templates/docs/examples/patterns/side-navigation/_layout-JAAS.html
- templates/docs/examples/patterns/side-navigation/application.html
- templates/docs/layouts/application.md
- templates/docs/patterns/navigation.md
- Improves the way side navigation component works in application layout
- updates the width of collapsed layout to 4rem to center the icons
- updates side navigation to fade text of the links when collapsing
- Add the documentation to side navigation and application layout pages
- Adds the animation to hiding/showing of side navigation in app layout on small screens
Fixes #3388
- Run `./run` or [demo](https://vanilla-framework-3421.demos.haus/docs/examples/layouts/application/JAAS)
- Check the side navigation in app layout: https://vanilla-framework-3421.demos.haus/docs/examples/layouts/application/JAAS
- Check on small mobile screens if the side navigation animates when showin/hiding - make sure it works as expected in different cases (check other app layout examples)
- Check the …
> Application layout - side navigation improvements

- HACKING.md
- package.json
- scripts/convert-svgs-to-icon-mixins.js
- scss/_base_icon-definitions.scss
- scss/_patterns_icons.scss
- scss/docs/_patterns_icons.scss
- scss/standalone/patterns_contextual-menu.scss
- scss/standalone/patterns_icons-application.scss
- scss/standalone/patterns_pagination.scss
- templates/docs/component-status.md
- templates/docs/examples/patterns/buttons/icon.html
- templates/docs/examples/patterns/contextual-menu/with-indicator.html
- templates/docs/examples/patterns/icons/icons-application.html
- templates/docs/examples/patterns/icons/icons-dark.html
- templates/docs/examples/patterns/icons/icons-light.html
- templates/docs/examples/patterns/pagination/pagination-disabled.html
- templates/docs/examples/patterns/pagination/pagination-truncated.html
- templates/docs/examples/patterns/pagination/pagination-verbose.html
- templates/docs/examples/patterns/pagination/pagination.html
- templates/docs/examples/templates/maas-layout.html
- templates/docs/examples/utilities/font-metrics.html
- templates/docs/patterns/contextual-menu.md
- templates/docs/patterns/icons.md
- templates/docs/patterns/pagination.md
- yarn.lock
Added a subset of application icons per [this request from the JAAS team](https://github.com/canonical-web-and-design/jaas-dashboard/issues/453#issuecomment-630949936), that are not included in Vanilla by default. 
Fixes #3426 
- Pull code
- Run `./run`
- Open https://vanilla-framework-3436.demos.haus/docs/patterns/icons#application
- See the new icons are present, and that there is documentation on how to import them is present at https://vanilla-framework-3436.demos.haus/docs/patterns/icons#import
- See that the examples also look correct: https://vanilla-framework-3436.demos.haus/docs/examples/patterns/icons/icons-application and https://vanilla-framework-3436.demos.haus/docs/examples/standalone/patterns/icons/icons-application
> Add application icons

- scss/_base_button.scss
- scss/_patterns_buttons.scss
Moved `%vf-button-white-success-icon` to the base button styles, so as not to break builds when including just Vanilla base.
Fixes #3438
> Include %vf-button-white-success-icon in base button mixin

- konf/site.yaml
- templates/contribute.html
- webapp/app.py
Get list of contributors from github and show them on /contribute, along with current team members.
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/contribute
- See the list of team members and contributors
> Show team members and contributors on contribute page

- scss/_base_placeholders.scss
- scss/_layouts_application-panels.scss
- scss/_patterns_strip.scss
- templates/docs/component-status.md
- templates/docs/examples/layouts/application/JAAS.html
- templates/docs/examples/layouts/application/_styles.css
- templates/docs/examples/layouts/application/default.html
- templates/docs/examples/layouts/application/split.html
- templates/docs/layouts/application.md
- Updates the styling of application layout panel headers
Fixes #3390 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-3439.demos.haus/docs/examples/layouts/application/JAAS)
- Verify that spacing of panel headers is correct (check all screen sizes)
- https://vanilla-framework-3439.demos.haus/docs/examples/layouts/application/JAAS
- https://vanilla-framework-3439.demos.haus/docs/examples/layouts/application/default
- Check the updated docs: https://vanilla-framework-3439.demos.haus/docs/layouts/application#panels
> Application layout panel header styles

- scss/_layouts_application.scss
Hides scrollbars on collapsed sidebar, on Windows/Ubuntu (the issue is not present on macOS).
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/945
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples/layouts/application/default
- Set the width of your browser window to the point where the sidebar collapses automatically but is still visible. See that there are no scrollbars present, and that they appear when you hover over it.
> Hide overflow when nav sidebar is collapsed.

- scss/_layouts_application.scss
- scss/_patterns_side-navigation.scss
- templates/docs/component-status.md
- templates/docs/examples/patterns/side-navigation/_layout-application.html
- templates/docs/layouts/application.md
- tests/parker.js
Updates app layout side navigation to hide nested levels when navigation is collapsed and to allow selecting top level item with icon when one of the children is active.
Fixes #3394
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-3443.demos.haus/docs/examples/layouts/application/default)
- Check the application layout example, make sure side navigation nested levels behave as expected when nav is collapsed: https://vanilla-framework-3443.demos.haus/docs/examples/layouts/application/default
- Review the updated documentation: https://vanilla-framework-3443.demos.haus/docs/layouts/application#nested-levels-of-navigation-items
> Hide nested levels when side nav is collapsed

- scss/_layouts_application.scss
- templates/docs/examples/layouts/application/_script.js
- tests/parker.js
Added :focus-within support to the expanding sidenav.
Fixes #3377 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/examples/layouts/application/JAAS
- Reduce your browser width until the sidenav automatically collapses, then tab through the page until you see a focus state within the sidenav. The sidenav should expand.
> Expand sidenav when :focus-within is true.

- webapp/app.py
Return a 404 if a standalone template doesn't exist.
- Open [demo](https://vanilla-framework-3457.demos.haus/docs/examples/standalone/base/code)
- See that you see a 404 page, and not a 500 (compare to [live site](https://vanillaframework.io/docs/examples/standalone/base/code))
> If a standalone template does not exist, return a 404 rather than a 500.

- HACKING.md
- README.md
Moved hacking instructions from the readme to the recently introduced HACKING.md, removed outdated copy and added the Vanilla logo to the readme.
Fixes #3449 
- Inspect the [README.md](https://github.com/sowasred2012/vanilla-framework/blob/readme-updates/README.md) and [HACKING.md](https://github.com/sowasred2012/vanilla-framework/blob/readme-updates/README.md), see that the contents are appropriate.
> Move hacking documentation from README.md to HACKING.md

- scss/_base_placeholders.scss
Updated `text-indent` value on `%vf-hide-text` to `110vw`, from a `calc()` value incompatible with IE.
Fixes #3162 
- Login to https://www.browserstack.com/
- Within Browserstack, select IE11 and open [demo](https://vanilla-framework-3461.demos.haus)
- Visit https://vanilla-framework-3461.demos.haus/docs/examples/patterns/chip/with-dismiss
- See that the "X" icon is visible, and not obscured by text.
> Change %vf-hide-text text indent to IE friendly value

- templates/docs/patterns/icons.md
Fixed a broken LinkedIn link in the icons documentation.
Fixes #3475 
- Open [demo](https://vanilla-framework-3476.demos.haus/docs/patterns/icons)
- Under the heading "Share", see that the LinkedIn link takes you to a relevant page, rather than a 404
> Fix broken LinkedIn share plugin link

- scss/_base_tables.scss
Removes unnecessary pseudo-element that is causing rendering issues sometimes.
Fixes #3087 
- Open [demo](https://vanilla-framework-3479.demos.haus/docs/examples)
- Check table examples (and Percy), make sure there are no regressions
> Remove unnecessary pseudo-element from tables

- scss/_patterns_table-sortable.scss
Fix table header text shifting when clicking on sortable columns
Fixes 3120
- Open [demo](https://vanilla-framework-3480.demos.haus/docs/examples/patterns/tables/table-sortable)
- Check table sortable demo - make sure that clicking on sortable columns (when icon appears) doesn't shift the text
> Fix shifting headings in sortable tables

- scss/_base_code.scss
- scss/_patterns_code-numbered.scss
- scss/_patterns_code-snippet.scss
- templates/docs/examples/patterns/code-numbered.html
Updated the base code style, and the code-numbered pattern, to match the one seen in the [new code snippet design](https://app.zeplin.io/project/5fa270d8eee4dbb267e579f1/screen/5fc616c95320fdb32885432e)
Fixes #3463 & #3465
- Open [code block example](https://vanilla-framework-3483.demos.haus/docs/examples/base/code-block)
- Check that the code block matches the design, and looks similar to the blocks in the [code snippet example](/docs/examples/standalone/patterns/code-snippet/code-snippet)
- Open [code numbered example](https://vanilla-framework-3483.demos.haus/docs/examples/patterns/code-numbered)
- Check that the code numbered block matches the design
> Update base code block styles to match code snippet pattern

- scss/_base_code.scss
- scss/_base_icon-definitions.scss
- scss/_patterns_code-copyable.scss
- scss/_patterns_code-snippet.scss
- scss/_settings_colors.scss
- templates/_layouts/docs.html
- templates/docs/base/code.md
- templates/docs/component-status.md
Updated the code copyable to match the code snippet [design](https://app.zeplin.io/project/5fa270d8eee4dbb267e579f1/screen/5fc616c95320fdb32885432e). Notably, this update hides the "copy" button if one is present, without requiring any markup changes. 
Fixes #3464 
- Open [demo](https://vanilla-framework-3484.demos.haus/docs/examples/patterns/code-copyable)
- See that the pattern matches the design
> Update code copyable style to match code snippet

- scss/_base_typography-definitions.scss
padding-top and margin-bottom on x-small text do not add up to an exact multiple of .5rem, throwing vertical rhythm off.
This is due to a typo, using the nudge for small text instead of the x-small text in a couple of places. 
This pr fixes that
Inspect the code change, verify the values of padding-top and margin bottom on x-small text add up to a multiple of .5rem (+ the browser rounding compensation).
Here's a screenshot:
> Use correct key in map for x-small text

- scss/_base_code.scss
- scss/_patterns_code-numbered.scss
- scss/_patterns_code-snippet.scss
- templates/docs/base/code.md
- templates/docs/component-status.md
- templates/docs/examples/patterns/code-numbered.html
- templates/docs/examples/patterns/code-snippet/code-snippet-numbered.html
- templates/docs/examples/patterns/code-snippet/code-snippet.html
Added numbered line variant of code snippet block.
Fixes #3471 
- Open [demo](https://vanilla-framework-3490.demos.haus/docs/examples/patterns/code-snippet/code-snippet-numbered)
- See that it matches the [design](https://app.zeplin.io/project/5fa270d8eee4dbb267e579f1/screen/5fc616c95320fdb32885432e)
- Check the updated [documentation](https://vanilla-framework-3490.demos.haus/docs/base/code) makes sense
> Add numbered variant to code snippet

- package.json
- templates/docs/base/separators.md
Bumps version of Vanilla to 2.22, updates missing labels in docs.
- Open [demo](https://vanilla-framework-3496.demos.haus/docs)
- Check if Vanilla version is correct: https://vanilla-framework-3496.demos.haus/docs
- Check if component status is up to date: https://vanilla-framework-3496.demos.haus/docs/component-status
- Check if component status table links to correct parts of the docs
- Check if the docs linked from component status are correct, have labels, etc
> Prepare Vanilla 2.22 release

- scss/_patterns_buttons.scss
- templates/docs/examples/patterns/buttons/small.html
Reduced the breakpoint at which `is-inline` styles are applied to `button` elements, so that the correct margin is present when the button is not full width.
Related to #3344 - once this PR is merged there's another task to remove unnecessary styles from the SummaryButton in React Components.
Fixes #3387
- Open [demo](https://vanilla-framework-3497.demos.haus/docs/examples/patterns/buttons/small)
- Reduce the width of your browser, see that the second button does not lose its left margin before it becomes full width.
> Apply is-inline button styles at the small breakpoint and up

- scss/_patterns_code-copyable.scss
Removed outline on code copyable input, which was previously visible when tabbing or clicking on it in Chrome.
Fixes #3328
- Open [demo]( https://vanilla-framework-3498.demos.haus/docs/examples/patterns/code-copyable) in Chrome
- Tab to or click on the component, see that text is highlighted, but there is no border/outline (compare to [live site](https://vanillaframework.io/docs/examples/patterns/code-copyable))
Before
After
> Remove outline from code copyable input on Chrome

- scss/_base_code.scss
Fixed broken box shadow when an inline `code` element wrapped to a second line.
Technically fixes #3408 - in investigating that quite old issue, I discovered that the margin no longer seemed to be an issue, but that there was a related problem.
- Open [demo](https://vanilla-framework-3500.demos.haus/docs/examples/base/code-inline)
- Reduce the width of the browser to the point that the code element wraps to a second line (or edit the text in your browser dev tools to add a longer piece of text).
- See that the grey background doesn't look as though it has a chunk missing (compare to [live](https://vanillaframework.io/docs/examples/base/code-inline))
Before:
After:
> Add box-decoration-break: clone to code element

- scss/_base_code.scss
- scss/_patterns_code-snippet.scss
- templates/docs/base/code.md
- templates/docs/component-status.md
- templates/docs/examples/patterns/code-snippet/code-snippet-wrapping.html
- Added `.is-wrapped` utility class for code snippets, to allow content to wrap inside code blocks
Fixes #3478, #2457 & #2184
- Open [demo](https://vanilla-framework-3502.demos.haus/docs/examples/patterns/code-snippet/code-snippet-wrapping)
- If neither block wraps, reduce the browser width
- See that the first block does not wrap, and the second block does
- [Code](https://vanilla-framework-3502.demos.haus/docs/base/code#code-snippet)
- [Component status](https://vanilla-framework-3502.demos.haus/docs/component-status)
> Add .is-wrapped code snippet utility

- scss/_base.scss
- scss/_base_syntax-highlighting.scss
- templates/docs/base/code.md
- templates/docs/examples/patterns/code-snippet/code-snippet-prism.html
- templates/static/js/example.js
Adds Prism syntax highlighting to code snippet
Fixes #3477
- Open [demo](https://vanilla-framework-3494.demos.haus/docs/examples/patterns/code-snippet/code-snippet-prism)
- Make sure syntax coloring works as expected
- https://vanilla-framework-3494.demos.haus/docs/base/code#syntax-highlighting
> Add example of syntax highlighting with Prism

- scss/_patterns_buttons.scss
- templates/_layouts/docs.html
- templates/docs/component-status.md
- templates/docs/examples/patterns/buttons/active.html
- templates/docs/examples/patterns/buttons/processing.html
- templates/docs/patterns/buttons.md
- Renamed existing `.is-active` button utility to the more appropriate `.is-processing`, deprecated `is-active`.
- Open [active button example](https://vanilla-framework-3515.demos.haus/docs/examples/patterns/buttons/processing)
- See that it matches the currently live `is-active` state: https://vanillaframework.io/docs/examples/patterns/buttons/active
- [Deprecated active button docs](https://vanilla-framework-3515.demos.haus/docs/patterns/buttons#active)
- [Processing button docs](https://vanilla-framework-3515.demos.haus/docs/patterns/buttons#processing)
- [Component status](https://vanilla-framework-3515.demos.haus/docs/component-status)
> Deprecate .is-active button utility class and replace with .is-processing

- .spelling
- scss/_patterns_code-snippet.scss
- templates/docs/base/code.md
- templates/docs/component-status.md
- templates/docs/examples/patterns/code-snippet/_script.js
- templates/docs/examples/patterns/code-snippet/code-snippet-dropdown.html
Added example of using a select within a code snippet
Fixes #3469 
- Open [demo](https://vanilla-framework-3511.demos.haus/docs/examples/patterns/code-snippet/code-snippet-dropdown)
- Check that the example works when selecting different options from the menu
- Compare to the [Zeplin design](https://app.zeplin.io/project/5fa270d8eee4dbb267e579f1/screen/5ffc2fdcb65e6a99b78f9d47)
- [Code](https://vanilla-framework-3511.demos.haus/docs/base/code)
- [Component status](https://vanilla-framework-3511.demos.haus/docs/component-status)
> Code snippet dropdowns

- Dockerfile
- package.json
- templates/_layouts/docs.html
Bumped version of Vanilla to 2.23.0 for next release.
Updated labels in docs side nav.
- Open [demo](https://vanilla-framework-3525.demos.haus/docs)
- Make sure Vanilla version is correct next release (2.23.0)
- Check [component status page](https://vanilla-framework-3525.demos.haus/docs/component-status), verify the links in latest changes
- Make sure side navigation labels reflect changes in this version
> Bump 2.23.0

- templates/docs/component-status.md
Typo in the docs - old version in the title
- Open [demo](https://vanilla-framework-3529.demos.haus/docs/component-statusl)
- Check if title says correct 2.23 version number https://vanilla-framework-3529.demos.haus/docs/component-status
> Fix Vanilla version in the docs

- templates/docs/component-status.md
- webapp/app.py
Automate version in title of component status page to avoid updating it manually for release
- Open [demo](https://vanilla-framework-3531.demos.haus/docs/component-status)
- make sure that the page heading shows vanilla version from package.json file
- https://vanilla-framework-3531.demos.haus/docs/component-status
> Automate version in title of component status page

- scss/_base_code.scss
- scss/_settings_spacing.scss
Removed `word-break: break-all;` from `code` elements.
Fixes #3526 
- Open [demo](https://vanilla-framework-3535.demos.haus/docs/examples/layouts/documentation)
- Scroll to the "Notifications" heading
- Reduce the width of your browser, see that as you do, the code element within wraps, but wraps whole words rather than breaking words
> Remove word-break: break-all from code element

- scss/_base_code.scss
- scss/_layouts_application.scss
- scss/_settings_colors.scss
- templates/docs/base/code.md
- templates/docs/component-status.md
- templates/docs/examples/base/code-inline-dark.html
- templates/docs/examples/layouts/application/structure.html
- Updated the background color of the inline code element to match the transparent color in use on the new code snippet
- Added support for code elements within an `is-dark` parent
Fixes #3540 
- Open [demo](https://vanilla-framework-3543.demos.haus/docs/examples/base/code-inline)
- Check that the inline code element looks good, and sits on the baseline.
- Open [dark demo](https://vanilla-framework-3543.demos.haus/docs/examples/base/code-inline-dark)
- See that the code element is nicely visible
- Check the [updated application structure](https://vanilla-framework-3543.demos.haus/docs/examples/layouts/documentation#notifications), see that "l-navigation >l-navigation__drawer" is visible in the side bar.
> Add .is-dark support for inline code element

- scss/_base_typography.scss
- scss/_utilities_content-align.scss
Add small capitalised style, utilities to align small and paragraph text
paste the following markup into any example:
```
<div class="col-1">
<p>paragraph</p>
</div>
<div class="col-1">
<div class="u-align-text--small-to-default p-text--small">small</div>
</div>
<div class="col-9">
<p class="p-text--x-small-capitalized u-align-text--x-small-to-default">small capitalised text aligned to a paragraph</p>
</div>
```
- verify you see this:
> Add small capitalised style, utilities to align small and paragraph text

- scss/_base_hr.scss
- scss/_base_placeholders.scss
- add light hr
- add u-no-margin--bottom that compensaes forthe hr 1px height, thereby avoiding a drift from the baseline grid
- add hr centered (and same width) as a row, which means instead of `.row>hr` or `.u-fixed-width>hr` you can just write `hr.is-fixed-width`
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3510
- Paste this [code](https://pastebin.canonical.com/p/XYm8qkrSs6/) (pastebin link):
- Verify you see the following:
> Add light and dense version of hr

- templates/docs/examples/patterns/contextual-menu/dark.html
- templates/docs/examples/patterns/contextual-menu/default.html
- templates/docs/examples/patterns/modal/default.html
- templates/docs/examples/patterns/modal/modal-scroll.html
- templates/docs/examples/templates/z-index.html
- templates/docs/patterns/contextual-menu.md
- templates/docs/patterns/modal.md
- Updated buttons in modal and contextual menu examples with an ellipsis
- Documented the reason why the ellipsis should be included
Fixes #3566
- Open: 
- [Default modal](https://vanilla-framework-3569.demos.haus/docs/examples/patterns/modal/default)
- [Scrolling modal](https://vanilla-framework-3569.demos.haus/docs/examples/patterns/modal/modal-scroll)
- [z-index example](https://vanilla-framework-3569.demos.haus/docs/examples/templates/z-index)
- [Contextual menu](https://vanilla-framework-3569.demos.haus/docs/examples/patterns/contextual-menu/default)
- [Contextual menu (dark)](https://vanilla-framework-3569.demos.haus/docs/examples/patterns/contextual-menu/dark)
- See that an ellipsis is present on buttons that launch a dialog on click.
- Review documentation updates:
- …
> Show ellipsis on buttons that launch modals

- scss/_base_code.scss
- scss/_base_fontfaces.scss
- scss/_patterns_code-copyable.scss
- scss/_patterns_code-snippet.scss
- Set font-weight to 300 on code copyable component
- Replace font file used in non-subset Ubuntu Mono, font-weight 400 font face with a bold variant, rather than the regular font beign used previously
Fixes #3564 & #3565 
- Pull this branch, `dotrun` the project and visit http://0.0.0.0:8101/docs/examples/patterns/code-copyable
- See that the font weight looks correct
- In `_settings_font.scss`, change `$font-use-subset-latin` value to `true`
- Reload the code copyable page, see that the font looks the same, and isn't bold
> Ubuntu mono font bugs

- scss/_patterns_grid.scss
- templates/docs/component-status.md
- templates/docs/upgrade-guide-v3.md
Remove the `.row` part of the `.row .col-*` selector to prevent breaking layouts that partially override the `.col-*` class behaviour with local styles.
> Temporarily revert namepacing of .col-* classes

- templates/static/js/example.js
Added "Edit on CodePen" link to code examples in Vanilla docs
Fixes #3558 
- Open [demo](https://vanilla-framework-3581.demos.haus/docs)
- Go to any doc with a code example, see that an "Edit on CodePen" link is present at the bottom of the code snippet.
- Click the link, see that any HTML, CSS and JS is present and correct, and that Vanilla styles have been imported.
- Visit [code snippet - syntax highlighting docs](https://vanilla-framework-3581.demos.haus/docs/base/code#syntax-highlighting)
- Click the codepen link, see that syntax highlighing is applied in the new window (this demonstrates external js is being included)
> add "Edit on CodePen" link to code snippet examples

- templates/docs/examples/patterns/contextual-menu/_script.js
- templates/docs/examples/patterns/modal/_script.js
- templates/docs/patterns/contextual-menu.md
- templates/docs/patterns/modal.md
- Added JS to focus on the launched target when a modal or contextual menu is launched.
- Documented recommended behaviour in docs
Fixes #3567 
- Open [contextual menu demo](https://vanilla-framework-3572.demos.haus/docs/examples/patterns/contextual-menu/default)
- Click "Take action"
- Press tab key - the first item in the launched dialog should be highlighted
- Open [modal demo](/docs/examples/patterns/modal/default)
- Press tab key - the first item in the launched dialog should be highlighted
- [Contextual menu](https://vanilla-framework-3572.demos.haus/docs/patterns/contextual-menu#accessibility)
- [Modal](https://vanilla-framework-3572.demos.haus/docs/patterns/modal#accessibility)
> Focus on first focusable element within a dialog when launching

- package.json
- scss/_base_button.scss
- scss/standalone/patterns_buttons.scss
- templates/_layouts/docs.html
- templates/docs/component-status.md
- templates/docs/examples/patterns/buttons/pressed.html
- templates/docs/examples/patterns/contextual-menu/_script.js
- templates/docs/patterns/buttons.md
- tests/parker.js
Added `aria-pressed` styles to buttons.
Fixes #3568 
- Open [demo](https://vanilla-framework-3583.demos.haus/docs/examples/patterns/buttons/pressed)
- Click the button, see that when the dropdown is open, the button remains in a pressed state after releasing the mouse button.
- Click the button again, see that the pressed state is no longer active.
- [Buttons](https://vanilla-framework-3583.demos.haus/docs/patterns/buttons#accessibility)
- [Component status](https://vanilla-framework-3583.demos.haus/docs/component-status)
> Add aria-pressed state to buttons

- templates/docs/base/separators.md
- templates/docs/examples/base/hr-fixed-width.html
- templates/docs/examples/base/hr-muted.html
Document hr classes is-muted, is-fixed-width
- Open /docs/base/separators
- Proofread sections "Muted horizontal rule", "Fixed width horizontal rule"
> Document hr classes is-muted, is-fixed-width

- scss/_base_button.scss
- scss/_patterns_chip.scss
- scss/_patterns_search-box.scss
- scss/standalone/patterns_notifications.scss
- templates/docs/examples/patterns/buttons/alignment.html
- templates/docs/examples/templates/maas-layout.html
Added a slightly modified version of @anthonydillon's suggested fix (see [CodePen example](https://codepen.io/anthonydillon/pen/xxRqBqN)) for #3542 
- Open [button alignment example](/docs/examples/patterns/buttons/alignment/)
- See that each button in each row has a margin right, except for the last buttons in each row
- Review Percy changes
**Breaking change:** this fixes the original issue, but in instances where a button is prevented from being the `:last-child` by a hidden element, such as a contextual menu toggle, a right margin is still applied and needs to be removed with the `u-no-margin--right` utility.
> Fix margin right on multiple buttons of mixed element types

- scss/_patterns_lists.scss
- scss/_settings_themes.scss
- scss/standalone/dark.scss
- templates/docs/component-status.md
- templates/docs/examples/patterns/lists/lists-mid-dot-dark.html
- templates/docs/patterns/lists.md
- templates/docs/settings/color-settings.md
- Added `is-dark` utility class to middot lists
- Increased size of middot
- Added dark theme support for middot lists
Fixes #2395 
- Open [demo](https://vanilla-framework-3588.demos.haus/docs/examples/patterns/lists/lists-mid-dot-dark)
- Check that it looks good
- [Middot lists](https://vanilla-framework-3588.demos.haus/docs/patterns/lists#middot)
- [Component status](https://vanilla-framework-3588.demos.haus/docs/component-status)
- [Color settings](https://vanilla-framework-3588.demos.haus/docs/color-settings#color-theming)
> Add .is-dark utility and theming support to middot list

- templates/_layouts/docs.html
- templates/docs/component-status.md
Updated component status docs for upcoming release
- Open [demo](https://vanilla-framework-3600.demos.haus/docs/component-status)
- https://vanilla-framework-3600.demos.haus/docs/component-status - make sure component status is updated to latest version
- check if all links to docs pages from component status work
- verify if changes are reflected in side navigation
> Update component status for 2.25

- package.json
- scss/_patterns_contextual-menu.scss
- templates/docs/examples/templates/maas-layout.html
Removed margin-right from contextual menu, which was introduced by this PR https://github.com/canonical-web-and-design/vanilla-framework/pull/3584 - since a contextual menu toggle is never the last child, in the previous setup, it _always_ had a margin right applied, when it should never have one.
- Open [demo](https://vanilla-framework-3601.demos.haus/docs/patterns/contextual-menu)
- Inspect the examples, see that each instance of a contextual menu toggle does not have a right margin
> Remove margin right from contextual menu

- .github/workflows/pr.yml
Use ubuntu-18.04 for GH actions job with linkchecker.
Related to: https://github.com/linkchecker/linkchecker/issues/435
Make sure PR checks pass (including linkchecker)
> Fix linkchecker on GH actions

- package.json
- scss/_base_button.scss
- scss/_patterns_accordion.scss
- scss/_patterns_table-expanding.scss
- templates/_layouts/docs.html
- templates/docs/base/tables.md
- templates/docs/component-status.md
- templates/docs/examples/patterns/contextual-menu/_script.js
- templates/docs/examples/patterns/tables/_script-expanding.js
- templates/docs/examples/patterns/tables/table-expanding-deprecated.html
- templates/docs/upgrade-guide-v3.md
Renamed `p-table-expanding` to `p-table--expanding`(and `p-table-expanding__panel` to `p-table__expanding_panel`) for consistency.
Fixes #2946
- Open [demo](https://vanilla-framework-3596.demos.haus/docs/base/tables#expanding)
- Table expanding example should use new class names and look/work as expected: https://vanilla-framework-3596.demos.haus/docs/examples/patterns/tables/table-expanding
- Old deprecated demo should still work as expected: https://vanilla-framework-3596.demos.haus/docs/examples/patterns/tables/table-expanding-deprecated
- https://vanilla-framework-3596.demos.haus/docs/base/tables#expanding
- make sure docs are updated to use new class names
- make sure old class names are mentioned to be deprecated
- Check component status page to see …
> Rename expanding table

- .github/workflows/pr.yml
As suggested by @nottrobin we can use pip3 to install linkchecker.
Make sure CI checks pass (including linkchecker)
> Install linkchecker via pip3

- scss/_patterns_matrix.scss
Fixed a bug introduced in the [2.0 refactor](https://github.com/canonical-web-and-design/vanilla-framework/pull/2138/files#diff-02b46287dfcdad2bcacdccc1da64b1f474cb5cfd855d1e604567e68da4ba8df3R108)* where last-child  `p` elements within `.p-matrix__desc` no longer had their bottom margin reduced.
*noticed while working on https://github.com/canonical-web-and-design/vanilla-framework/pull/3607
- Open [demo](https://vanilla-framework-3609.demos.haus/docs/patterns/matrix)
- See that the margin below the last paragraph in each matrix item has been reduced, compared to [live version](https://vanillaframework.io/docs/examples/patterns/matrix)
Before:
After:
> Fix bottom margin on last p element in p-matrix__desc

- scss/_patterns_table-sortable.scss
- templates/docs/base/tables.md
- templates/docs/component-status.md
- templates/docs/examples/patterns/tables/_script-sorting.js
- templates/docs/examples/patterns/tables/table-expanding-deprecated.html
- templates/docs/examples/patterns/tables/table-expanding.html
- templates/docs/examples/patterns/tables/table-sortable-deprecated.html
- templates/docs/upgrade-guide-v3.md
- Removes `p-table--sortable` class name
- Any table with `aria-sort` on headers can be sorted
Fixes #2948 
- Open [demo](https://vanilla-framework-3608.demos.haus/docs/examples/patterns/tables/table-sortable)
- Check new sortable example:
- https://vanilla-framework-3608.demos.haus/docs/examples/patterns/tables/table-sortable
- make sure it works as expected without any additional class names
- Check old deprecated sortable example:
- https://vanilla-framework-3608.demos.haus/docs/examples/patterns/tables/table-sortable-deprecated
- make sure it still works as expected
- https://vanilla-framework-3608.demos.haus/docs/base/tables#sortable
> Remove the need for `p-table--sortable` class name

- scss/_layouts_application.scss
- templates/docs/component-status.md
- templates/docs/examples/layouts/application/JAAS.html
- templates/docs/examples/layouts/application/_script.js
- templates/docs/examples/layouts/application/default.html
- templates/docs/examples/layouts/application/structure.html
- templates/docs/layouts/application.md
Fixes #3409 
- Open [demo](https://vanilla-framework-3614.demos.haus/docs/examples/layouts/application/default)
- Close/open aside panel - it should be animated
- Lower the screen size until side-nav collapses into vertical bar - hovering it should expand it with animation
- Lower the screen size to mobile view - clicking on "Menu" should open side navigation with animation
- Check if it also works as expected on other examples:
- https://vanilla-framework-3614.demos.haus/docs/examples/layouts/application/JAAS
- https://vanilla-framework-3614.demos.haus/docs/examples/layouts/application/structure
- https://vanilla-framework-3614.demos.haus/docs/layouts/application#aside-area
> Application layout panel animations

- scss/_base_hr.scss
- scss/_layouts_fluid-breakout.scss
- scss/_settings_grid.scss
- scss/standalone/custom.scss
- Uses `calc` in `<hr>` is-fixed-width to make it valid with grid max width is 100%
- Uses `calc` in fluid breakout variables
Fixes #3610
- Open [demo](https://vanilla-framework-3620.demos.haus)
- There should be no visual differences
- Verify that affected patterns work as expected:
- horizontal rule: https://vanilla-framework-3620.demos.haus/docs/examples/base/hr-fixed-width
- breakout layout: https://vanilla-framework-3620.demos.haus/docs/examples/layouts/fluid-breakout/fluid-breakout-cards-and-aside
- Check the build:
- pull this branch
- somewhere in SCSS code try to do a calculation with $grid-max-width (`width: $grid-max-width + $sp-small;`)
- Vanilla should build fine, but `custom.scss` test file should fail, because it uses 100% instead of rem
> Use calc for computations with grid-max-width

- scss/_base_button.scss
- scss/_base_forms-tick-elements.scss
- scss/_base_grid-definitions.scss
- scss/_base_hr.scss
- scss/_base_placeholders.scss
- scss/_base_typography-definitions.scss
- scss/_base_typography.scss
- scss/_layouts_fluid-breakout.scss
- scss/_patterns_chip.scss
- scss/_patterns_forms.scss
- scss/_patterns_grid.scss
- scss/_patterns_heading-icon.scss
- scss/_patterns_inline-images.scss
- scss/_patterns_lists.scss
- scss/_patterns_matrix.scss
- scss/_patterns_modal.scss
- scss/_patterns_navigation.scss
- scss/_patterns_separator.scss
- scss/_patterns_side-navigation.scss
- scss/_patterns_subnav.scss
- scss/_patterns_table-mobile-card.scss
- scss/_patterns_tabs.scss
- scss/_utilities_equal-height.scss
- scss/_utilities_hide.scss
- scss/_utilities_show.scss
- Removed any instances of `only screen` and `screen` media queries
- Removed media queries that _seem_ to be unnecessary - in each instance there was a `max-width` media query that set styles overridden in a subsequent `min-width` media query set to the same breakpoint.
- Reduced number of unique media queries reported by Parker in the project from 31 to 18:
| Before: | After: |
| ---- | ---- |
| (min-width: 460px) | (max-width: 459px) |
| (max-width: 460px) | (max-width: 460px) |
| only screen and (max-width: 460px) | (min-width: 460px) |
| only screen and (min-width: 461px) | (max-width: 620px) |
| (max-width: 620px) | (min-width: 620px) |
| (min-width: 620px) | (min-width: 620px) and (max-width: 772px) |
| (min-width: 620px) and (max-width: 772px) | (min-width: 620px) and (max-width: …
> Consolidate media queries

- templates/_layouts/docs.html
Add missing labels for 2.26 release (for application layout and forms)
- Open [demo](https://vanilla-framework-3630.demos.haus/docs)
- check if side navigation labels are updated for release 2.26
> Add missing labels to side navigation for 2.26

- templates/docs/settings/color-settings.md
Fixes the color code for $color-information in the color settings docs. 
Fixes #3633 
- Open [demo](https://vanilla-framework-3634.demos.haus/docs/settings/color-settings) and view the color settings to ensure it has the correct color.
> Use the correct color code for the $color-information example

- .github/PULL_REQUEST_TEMPLATE.md
To make sure the main branch is always releasable we add 'definition of done' to PR template to make sure during review/QA we don't miss anything.
Fixes #3001
- check if the updated PR template doesn't have errors
> Add the definition of done to PR template

- package.json
- scss/_patterns_code-snippet.scss
- scss/docs/site.scss
- templates/_layouts/docs.html
- templates/docs/base/code.md
- templates/docs/base/forms.md
- templates/docs/base/separators.md
- templates/docs/base/tables.md
- templates/docs/base/typography.md
- templates/docs/component-status.md
- templates/docs/examples/patterns/code-snippet/is-bordered.html
- templates/docs/layouts/application.md
- templates/docs/layouts/fluid-breakout.md
- templates/docs/layouts/sticky-footer.md
- templates/docs/patterns/accordion.md
- templates/docs/patterns/breadcrumbs.md
- templates/docs/patterns/buttons.md
- templates/docs/patterns/contextual-menu.md
- templates/docs/patterns/icons.md
- templates/docs/patterns/lists.md
- templates/docs/patterns/navigation.md
- templates/static/js/example.js
- Added `.is-bordered` utility class to code snippet
- Removed custom styles that previously achieved the same thing in docs examples
Fixes #983 & #3590
- Open [demo](https://vanilla-framework-3632.demos.haus/docs/examples/patterns/code-snippet/is-bordered)
- See that it looks good
- Visit the updated [code docs](https://vanilla-framework-3632.demos.haus/docs/base/code#bordered), where the border is more easily visible.
- [Component status](https://vanilla-framework-3632.demos.haus/docs/component-status)
- if CSS class names are not changed it can be …
> Add .is-bordered to code snippet

- templates/index.html
Adds latest Vanilla version to download buttons on the home page.
Fixes #3032 
- Open [demo](https://vanilla-framework-3641.demos.haus)
- Make sure download buttons (in hero and download section) have latest version in the label
> Add latest Vanilla version to home page

- templates/docs/examples/patterns/search-box/_script.js
- templates/docs/examples/patterns/search-box/default-dark.html
- templates/docs/examples/patterns/search-box/default.html
- templates/docs/examples/patterns/search-box/navigation-dark.html
- templates/docs/examples/patterns/search-box/navigation.html
- templates/docs/patterns/search-box.md
Added example JS to search box pattern to demonstrate how to return focus to the input field when the cancel/clear input button is clicked.
Fixes #2866 
- Open [demo](https://vanilla-framework-3642.demos.haus/docs/examples/patterns/search-box/default)
- Type something into the search field, see that the cancel button becomes visible
- Click the cancel button, see that browser focus is restored to the input field
- [Search box docs](https://vanilla-framework-3642.demos.haus/docs/patterns/search-box) …
> Update search box examples with JS to handle cancel event

- scss/_patterns_buttons.scss
- Remove border from hovered disabled base button
Fixes #3327
- Open [demo](https://vanilla-framework-3644.demos.haus/docs/examples/patterns/buttons/base)
- Make sure that hovering disabled button doesn't change anything (including border)
> Fix border when hovering disabled base button

- scss/standalone/patterns_table-sortable.scss
- templates/docs/base/tables.md
- templates/docs/examples/patterns/tables/table-formatting.html
- adds new table example to show how to use utils to format text in cells
- adds documentation about formatting
Fixes #2963
- Open [demo](https://vanilla-framework-3646.demos.haus/docs/examples/patterns/tables/table-formatting)
- Make sure cell text is aligned and truncated as expected
- https://vanilla-framework-3646.demos.haus/docs/base/tables#formatting …
> Document formatting in table cells

- templates/docs/patterns/buttons.md
- Moved base button below neutral button in docs page order
- Reworded the description of the base button to make its purpose clearer
Fixes #2660 
- Open [button docs](https://vanilla-framework-3645.demos.haus/docs/patterns/buttons#base)
- See that the documentation makes sense and clears up the confusion identified in #2660
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Re …
> Clarify base button role

- scss/_utilities_embedded-media.scss
Added bottom margin to embedded media (which can be removed with the `u-no-margin--bottom` utility as necessary)
Fixes #3343 
- Open [demo](https://vanilla-framework-3647.demos.haus/docs/examples/utilities/embedded-media)
- Inspect the element, see that it has a bottom margin of 1.1rem
> Add bottom margin to embedded-media, to match paragraph bottom margin

- scss/_settings_colors.scss
- scss/_settings_placeholders.scss
- templates/docs/settings/placeholder-settings.md
- Updates border color and box shadow values
Fixes #3492
- Open [demo](https://vanilla-framework-3648.demos.haus/docs)
- https://vanilla-framework-3648.demos.haus/docs/examples/patterns/card/highlighted
- https://vanilla-framework-3648.demos.haus/docs/examples/patterns/navigation/subnav
- https://vanilla-framework-3648.demos.haus/docs/examples/patterns/contextual-menu/default
- https://vanilla-framework-3648.demos.haus/docs/examples/patterns/modal/default
- https://vanilla-framework-3648.demos.haus/docs/examples/patterns/notifications/notifications
- https://vanilla-framework-3648.demos.haus/docs/examples/patterns/switch
If this PR contains Vanilla SCSS code changes, it should contain the following changes to …
> Improvements to borders and box shadows

- scss/docs/site.scss
- templates/404.html
- templates/500.html
- templates/accessibility.html
- templates/browser-support.html
- templates/contribute.html
- templates/index.html
- templates/showcase.html
Removed custom surus (both inline and scss), and replaced with built-in (grey) Vanilla suru
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/986
- Open the following:
- [homepage](https://vanilla-framework-3651.demos.haus)
- [/accessibility](https://vanilla-framework-3651.demos.haus/accessibility)
- [/browser-support](https://vanilla-framework-3651.demos.haus/browser-support)
- [/contribute](https://vanilla-framework-3651.demos.haus/contribute)
- [/showcase](https://vanilla-framework-3651.demos.haus/showcase)
- [/404](https://vanilla-framework-3651.demos.haus/404)
- [/500](https://vanilla-framework-3651.demos.haus/500)
- See that they are all using the [default suru](https://vanilla-framework-3651.demos.haus/docs/examples/patterns/strips/suru)
If this PR contains …
> Replace custom suru scss and inline bg image with built-in suru

- .circleci/config.yml
Updates the CircleCI Percy job to run snapshots on PR merged to master branch, not a source branch.
This means we test the final result of merging.
- Check Percy for this PR
- It should only contain expected changes (Firefox bug)
- It should not contain any other changes (even though the PR branch is made from an old master)
> Merge PR with master before running Percy

- templates/docs/examples/patterns/icons/icons-links.html
- templates/docs/patterns/icons.md
- Documented ability to set `p-icon--` classes on `a` elements
Fixes #3033 
- Open [demo](https://vanilla-framework-3650.demos.haus/docs/examples/patterns/icons/icons-links)
- Hover over the icons, see that no underline/text-decoration appears
- [Icons docs](https://vanilla-framework-3650.demos.haus/docs/patterns/icons#icons-as-links) …
> Document ability to add icon classes to anchor tags

- templates/docs/examples/patterns/links/links-external-typography.html
- templates/docs/examples/patterns/links/links-external.html
- Added simpler external link icon example in place of the existing one
- Renamed existing example to "Icons / External - Typography" so it's still being tracked by Percy
Fixes #3619 
- Open [external link docs](https://vanilla-framework-3657.demos.haus/docs/patterns/links#external)
- See that there is now just one link in the example
- Open [new example](https://vanilla-framework-3657.demos.haus/docs/examples/patterns/links/links-external-typography), see that it contains external links on heading elements
- …
> Simplify external link icon example

- scss/_layouts_application.scss
Adjust the width of medium app panel to be 6 cols not 8.
Fixes #3655
- Open [demo](https://vanilla-framework-3656.demos.haus/docs/examples/layouts/application/structure)
- Make sure medium panel width is around 6 columns wide instead of 8
> Change width of medium application panel

- scss/_patterns_strip.scss
- scss/docs/site.scss
- Updates Vanilla website suru to use new colors
- Exposes more variables needed to customize Suru slant colors
Fixes canonical-web-and-design/vanilla-squad#995
- Open [demo](https://vanilla-framework-3660.demos.haus/)
- Check if the suru matches the design:
- https://app.zeplin.io/project/605b80ed1c5bbb06d5c10fcf/screen/605b8131a94abf41743257c0
- Also check small suru on other pages:
- https://vanilla-framework-3660.demos.haus//accessibility
- if CSS class names are changed/added/removed it should be minor …
> Add Vanilla-branded Suru to the website

- templates/docs/examples/patterns/image/caption.html
- templates/docs/patterns/images.md
Added missing documentation for image/figure caption
Fixes #2930 
- Open [demo](https://vanilla-framework-3661.demos.haus/docs/examples/patterns/image/caption)
- See that the image has an associated caption, styled in italics
- [Image docs](https://vanilla-framework-3661.demos.haus/docs/patterns/images)
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framewo …
> Document figure support on images

- scss/_layouts_application.scss
- templates/docs/examples/layouts/application/structure.html
Remove unnecessary example styling for app layout
Fixes #3575 
- Open [demo](https://vanilla-framework-3669.demos.haus/docs/examples/layouts/application/structure)
- Verify that app layout structure example looks ok on various screen sizes
> Remove unnecessary example styling for app layout

- templates/index.html
Removes aliceOS logo from home page (as they don't use Vanilla anymore).
- Open [demo](https://vanilla-framework-3672.demos.haus)
- Check "Who is using Vanilla" logos. AliceOS should not be there. Logos should be centered and look well on all screen widths.
> Remove aliceOS logo from home page

- scss/_patterns_modal.scss
Set `overflow: auto` on `p-modal__dialog`, previously it was set to `scroll`, and would show empty scrollbars on some browser/OS combos.
Fixes #3674 
- Open each of the modal examples in Vanilla:
- [default modal](https://vanilla-framework-3678.demos.haus/docs/examples/patterns/modal/default)
- [scrollable modal](https://vanilla-framework-3678.demos.haus/docs/examples/patterns/modal/modal-scroll)
- [z-index template](https://vanilla-framework-3678.demos.haus/docs/examples/templates/z-index)
- See that each of them only show scroll bars when there is content that needs to scroll
- if …
> Change modal dialog overflow to auto

- .github/workflows/pr.yml
Revert installing linkchecker via pip to package on ubuntu@18.04 due to building issues.
Created #3682 to investigate why it was failing and try to find a different way to fix it.
- All CI checks should pass, including linkchecker
> Use linkchecker installed on older ubuntu LTS

- scss/_patterns_modal.scss
- scss/standalone/patterns_modal.scss
- templates/_layouts/docs.html
- templates/docs/component-status.md
- templates/docs/examples/patterns/modal/default.html
- templates/docs/examples/patterns/modal/footer.html
- templates/docs/patterns/modal.md
Adds styling for modal dialog footer (as per React components).
Drive-by: fix unnecessary scrollbars in modal #3674
Part of canonical-web-and-design/react-components#411
Fixes #3674
- Open [demo](https://vanilla-framework-3676.demos.haus/docs/examples/patterns/modal/footer)
- Check if modal with footer renders as expected
- Make sure scroll bars don't appear in modal when not needed
- Check if modal can be scrolled when necessary: https://vanilla-framework-3676.demos.haus/docs/examples/patterns/modal/modal-scroll
- https://vanilla-framework-3676.demos.haus/docs/patterns/modal
- `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, …
> Add footer to modal dialog

- scss/_patterns_tooltips.scss
- scss/standalone/patterns_tooltips.scss
- templates/docs/component-status.md
- templates/docs/examples/patterns/tooltips/_tooltips_script.js
- templates/docs/examples/patterns/tooltips/detached.html
- templates/docs/examples/templates/z-index.html
- templates/docs/patterns/tooltips.md
Increased z-index on tooltips, so that they sit above most other elements.
Drive by: changed the `p-tooltip--detached` modifier class to a `is-detached` utility, so that detached tooltips are able to support positioning the tooltip arrow using existing classes i.e. `p-tooltip--top-center`
Fixes #3668 
- Open [demo](https://vanilla-framework-3679.demos.haus/docs/examples/templates/z-index)
- Hover over the "Tooltip" button, see that the tooltip is visible on top of neighboring elements.
- Open [detached example](https://vanilla-framework-3679.demos.haus/docs/examples/patterns/tooltips/detached)
- Hover over the buttons, see that the tooltips appear.
- `Feature 🎁`, …
> Increase z-index on tooltips

- .github/workflows/pr.yml
Yet another attempt to install linkchecker on `ubuntu-latest`, this time via `pip` rather than `pip3`.
Fixes: #3682
Make sure all PR checks pass (including linkchecker)
> Install linkchecker via pip (again)

- package.json
- scss/_patterns_search-and-filter.scss
Fix spacing around chips in the search and filter component.
Fixes #3680
- Open [demo](https://vanilla-framework-3687.demos.haus/docs/examples/patterns/search-and-filter/chip-overflow)
- check if there is a small padding on the left between the border and first chip
- make sure there is enough right padding for the "+2" counter not to overflow the last chip visible
- Open example without chips in search field: https://vanilla-framework-3687.demos.haus/docs/examples/patterns/search-and-filter/default
- make sure the left/right padding doesn't affect the search field (focus should be around whole field)
- compare with current react component: https://canonical-web-and-design.github.io/react-components/?path=/story/search-and-filter--default-story
If this PR contains Vanilla SCSS code …
> Fix spacing around chips in search and filter

- templates/docs/patterns/tooltips.md
- Updated tooltips documentation to advise against using tooltips on disabled elements
- Added a follow up issue regarding potentially creating a new pattern to inform users why an element is disabled https://github.com/canonical-web-and-design/vanilla-framework/issues/3690
Fixes #2180 
- Open [demo](https://vanilla-framework-3689.demos.haus/docs/patterns/tooltips)
- Read the second caution notification, see that it makes sense …
> Update docs with guidance on using tooltips with disabled elements

- scss/_patterns_modal.scss
Added right padding to `p-modal__header` to prevent the `p-modal__close` element overlapping the heading.
Fixes #3639 
- Open [demo](https://vanilla-framework-3691.demos.haus/docs/examples/patterns/modal/footer)
- Reduce the width of the browser window, see that the title of the modal is never obscured by the close button
- Compare to [staging](https://staging.vanillaframework.io/docs/examples/patterns/modal/footer)
- see the …
> Add right padding to modal header to accommodate close button

- scss/_patterns_lists.scss
- templates/docs/examples/patterns/lists/lists-stepped-detailed.html
- templates/docs/examples/patterns/lists/lists-stepped.html
Changed p-stepped-list__title to not use `display: flex;` so child elements don't cause layout problems
Fixes #2518 
- Open [demo](https://vanilla-framework-3694.demos.haus/docs/examples/patterns/lists/lists-stepped)
- Reduce the width of your browser until the fourth item "Design and Build" begins to wrap. It should wrap as expected, unlike https://codepen.io/sowasred2012/pen/xxgXvQg …
> Update p-stepped-list__title to allow child elements

- .github/workflows/pr.yml
- .github/workflows/publish-on-release.yml
Before we implement better automated ways of doing this we can at least print the size of the CSS file in CI logs, so they are easier to check.
- Check the 'Test' CI job, it should print build.css file size in logs
> Print size of build file in CI logs

- scss/_patterns_links.scss
Updates the style of back to top link to make sure it doesn't imply white background.
Fixes #3667
- Open [demo](https://vanilla-framework-3696.demos.haus/docs/examples/patterns/links/links-back-to-top)
- Make sure the updated link looks as expected (as per design in https://github.com/canonical-web-and-design/vanilla-framework/issues/3667#issuecomment-814931499)
- Change the body background to make sure it's not covered
- see …
> Update the style of back to top link

- HACKING.md
- scss/_patterns_side-navigation.scss
- scss/_patterns_tabs.scss
- Fix tab highlights for focus and active so that the underline appears.
- Fix side nav highlights when focusing on the active link so that the left border appears.
- Drive-by update so the examples URL is correct in the hacking doc.
Fixes #3686.
- Go to https://vanilla-framework-3698.demos.haus/docs/examples/patterns/tabs
- Click on the active tab (Machine summary) and the underline should not disappear.
- Click on another tab, the underline should be visible for focus and active states.
- Use your keyboard to tab to the active tab, it should show the blue border and the underline should not be visible.
- Go to https://vanilla-framework-3698.demos.haus/docs/examples/patterns/side-navigation/docs
- Click on the active link (Commissioning and hardware testing scripts) and the border on the …
> Fix focus highlight states for tabs and side nav

- package.json
- scss/_patterns_tabs.scss
- Removed the right arrow on the tabs component, based on [the conclusion](https://github.com/canonical-web-and-design/vanilla-framework/issues/3602#issuecomment-818564147) of a UX battle royale.
- Bumped version to 2.28.1
Fixes #3602 
- Open [demo](https://vanilla-framework-3702.demos.haus/docs/examples/patterns/tabs)
- Reduce the width of your browser so that the tabs overflow horizontally
- Scroll the tabs to the right, see that there is no right arrow obscuring the last tab (compare to [live](https://vanillaframework.io/docs/examples/patterns/tabs))
- if CSS class names are not …
> Remove right arrow from tabs component

- scss/_patterns_contextual-menu.scss
- templates/docs/examples/patterns/contextual-menu/dark.html
- templates/docs/examples/patterns/contextual-menu/default.html
Make sure buttons render correctly in contextual menu
Fixes #3705 
- Open [demo](https://vanilla-framework-3706.demos.haus/docs/examples/patterns/contextual-menu/dark)
- Open menu using "Take action" button, make sure that the items are buttons and look the same as in standard menu with links
- check the light theme as well:
- https://vanilla-framework-3706.demos.haus/docs/examples/patterns/contextual-menu/default
- see the …
> Fix backround of buttons in contextual menu

- templates/docs/examples/patterns/slider/slider-input.html
Remove unnecessary `p-slider` class from the example
Fixes #413
- Open [demo](https://vanilla-framework-3704.demos.haus/docs/examples/patterns/slider/slider-input)
- Check if slider renders correctly and doesn't have `p-slider` class on the input
- Check if JS works (slider and input should update together without errors)
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Relea …
> Remove unnecessary p-slider class from the example

- .github/workflows/pr.yml
- package.json
Adds source maps to build step
- Open [demo](https://vanilla-framework-3709.demos.haus)
- Inspect any element on page, check if inspector shows original scss source
> Enable source maps

- scss/_base_forms-tick-elements.scss
- scss/_base_tables.scss
- scss/_base_typography-definitions.scss
- scss/_patterns_chip.scss
- scss/_patterns_table-mobile-card.scss
- templates/docs/examples/patterns/tables/table-mobile-card.html
Update table mobile card design to match what was agreed in https://github.com/canonical-web-and-design/vanilla-framework/issues/2817
Fixes #2817
-Drive by: makes muted heading same style as table headers, they are close but slightly different which Ithink is unnecesary.
- Open docs/examples/patterns/tables/table-mobile-card
- QA
It is responsive, min column width 12rem, feel free to suggest another value if you think this isn't optimal. Opted for this rather than modifier classes as it is simpler to use.
- if …
> Update table mobile card design

- scss/_patterns_table-mobile-card.scss
- scss/_settings_spacing.scss
- templates/docs/examples/base/small.html
- Increased line height of %small-text placeholder to 1.25rem
- Added example of `p-text--small` to "small" example
Fixes #3482 
- Open [demo](https://vanilla-framework-3697.demos.haus/docs/examples/base/small)
- Reduce the width of your browser until the text wraps, see that the line height in the example is reasonable, and not too small.
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-fr …
> Increase small text line height

- templates/docs/examples/patterns/modal/_script.js
- templates/docs/examples/patterns/modal/default.html
- templates/docs/examples/patterns/modal/footer.html
- templates/docs/examples/patterns/modal/modal-scroll.html
- templates/docs/patterns/modal.md
- Added aria-modal to modal dialogs
- Added example of closing modal on ESC key
- Added example of trapping focus inside the modal, and returning focus to element that triggered modal
- Updated relevant docs
Fixes #3223
- Open [demo](https://vanilla-framework-3712.demos.haus/docs/examples/patterns/modal/default)
- Make sure focus stays in modal when using tab key
- Make sure focus returns to button when modal is closed
- Check other modal examples as well:
- https://vanilla-framework-3712.demos.haus/docs/examples/patterns/modal/footer
- https://vanilla-framework-3712.demos.haus/docs/examples/patterns/modal/modal-scroll
- https://vanilla-framework-3712.demos.haus/docs/patterns/modal#accessibility
If this PR contains Vanilla SCSS code changes, it should …
> Modal focus accessibility improvements

- package.json
- scss/_layouts_fluid-breakout.scss
- templates/_layouts/docs.html
- templates/docs/component-status.md
- templates/docs/examples/layouts/fluid-breakout/_toolbar.html
- templates/docs/examples/layouts/fluid-breakout/fluid-breakout-cards-with-aside-and-toolbar.html
- templates/docs/examples/layouts/fluid-breakout/fluid-breakout-left-aside-and-toolbar.html
- templates/docs/layouts/fluid-breakout.md
- Add toolbar to the fluid-breakout layout
- Go to /docs/layouts/fluid-breakout and see the `toolbar` information makes sense
- Go to /docs/examples/layouts/fluid-breakout/fluid-breakout-left-aside-and-toolbar and see the toolbar example works fine on all screen sizes
- Go to /docs/examples/layouts/fluid-breakout/fluid-breakout-cards-with-aside-and-toolbar and see the layout works fine on all screen sizes
- if CSS class names are not changed …
> Add toolbar to the fluid-breakout layout

- .spelling
- templates/docs/base/code.md
- templates/docs/base/forms.md
- templates/docs/base/tables.md
- templates/docs/patterns/accordion.md
- templates/docs/patterns/buttons.md
- templates/docs/patterns/card.md
- templates/docs/patterns/chip.md
- templates/docs/patterns/contextual-menu.md
- templates/docs/patterns/grid.md
- templates/docs/patterns/icons.md
- templates/docs/patterns/links.md
- templates/docs/patterns/lists.md
- templates/docs/patterns/modal.md
- templates/docs/patterns/notification.md
- templates/docs/patterns/pagination.md
- templates/docs/patterns/search-and-filter.md
- templates/docs/patterns/search-box.md
- templates/docs/patterns/slider.md
- templates/docs/patterns/strip.md
- templates/docs/patterns/tabs.md
- templates/docs/patterns/tooltips.md
Fixes #1003
- Open [demo](https://vanilla-framework-3715.demos.haus/docs/patterns/accordion#react)
- Check the component docs, every component that has React equivalent should have React section at the bottom of the page
> Link from Vanilla to React docs

- templates/docs/examples/patterns/strips/suru.html
- templates/index.html
Add comma to hero text on the marketing site homepage
> Add comma to hero text on marketing site homepage

- package.json
- scss/_base_links.scss
- scss/_base_placeholders.scss
- scss/_patterns_buttons.scss
- templates/_layouts/docs.html
- templates/docs/component-status.md
- templates/docs/examples/patterns/buttons/link.html
- templates/docs/patterns/buttons.md
- Added `p-button--link` variant
- This is the first new feature since the last release, so bumped version to 2.30.0
Fixes #2642 
- Open [demo](https://vanilla-framework-3724.demos.haus/docs/examples/patterns/buttons/link)
- See that the button looks identical to a [default link](https://vanilla-framework-3724.demos.haus/docs/patterns/links#default)
- [Component status](https://vanilla-framework-3724.demos.haus/docs/component-status) …
> Add button link pattern

- scss/_patterns_divider.scss
- scss/_settings_themes.scss
- scss/standalone/dark.scss
- templates/_layouts/docs.html
- templates/docs/component-status.md
- templates/docs/examples/patterns/lists/divider-dark.html
- templates/docs/examples/patterns/lists/divider.html
- templates/docs/patterns/lists.md
- templates/docs/settings/color-settings.md
Added dark theme to `p-divider` pattern
Fixes #2401 
- Open [demo](https://vanilla-framework-3728.demos.haus/docs/examples/patterns/lists/divider-dark)
- Check that the pattern looks good
- [Component status](https://vanilla-framework-3728.demos.haus/docs/component-status)
- [Divider docs](https://vanilla-framework-3728.demos.haus/docs/patterns/lists#responsive-divider) …
> Add dark theme to p-divider

- scss/_base_icon-definitions.scss
Removed hardcoded red color from error icon svg outline
Fixes #3725 
- Check out this branch
- Locally, update the color variable on [line 233 of _patterns_icons.scss](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/scss/_patterns_icons.scss#L233) to any color value.
- `dotrun` the project
- Visit [icons example](/docs/examples/patterns/icons/icons-dark)
- See that error icon does not have a red outline, and that the circle part of the icon is the color you set (the `x` should remain white). …
> Remove hardcoded color from stroke in error icon

- scss/_patterns_lists.scss
- templates/docs/examples/patterns/lists/lists-stepped-without-headings.html
- templates/docs/patterns/lists.md
Makes sure stepped list works with `p` paragraphs used as `p-stepped-list__title`.
Fixes #2489 
- Open [demo](https://vanilla-framework-3731.demos.haus/docs/examples/patterns/lists/lists-stepped-without-headings)
- Make sure titles render as expected when using `p`
- https://vanilla-framework-3731.demos.haus/docs/patterns/lists#vertical-stepped …
> Make stepped list work without headings

- package.json
Fixed the homepage link in package.json
Fixes #3734
- Check the `homepage` value in package.json, see that the URL takes you the Vanilla homepage
> update homepage URL in package.json

- templates/index.html
Added `hostname` param to latest-news call, so links are absolute and not relative
- Open [demo](https://vanilla-framework-3735.demos.haus)
- Scroll to the blog section, click any of the blog links, see that you are taken to the ubuntu.com blog
[if relevant, include a screenshot or screen …
> Fix blog links on homepage

- templates/_layouts/docs.html
- templates/docs/examples/utilities/align/content.html
- templates/docs/examples/utilities/align/text.html
- templates/docs/utilities/align.md
Split the `u-align` example into two, one for `u-align` and another for `u-align-text`
Fixes #2448 
- Open [demo](https://vanilla-framework-3737.demos.haus/docs/utilities/align)
- See that it's clear that there are two different utility classes, each with their own example
> Split align utlity examples to better describe their uses

- scss/_global_functions.scss
- scss/_patterns_navigation.scss
- scss/_patterns_subnav.scss
- scss/_patterns_tabs.scss
- scss/_settings_colors.scss
- scss/_utilities_font-metrics.scss
- Adjusted height of top nav logo, and padding around nav items
- Added new selected/hover/active state to top nav, featuring Ubuntu orange
Fixes #3653 
- Open [default dark nav demo](https://vanilla-framework-3727.demos.haus/docs/examples/patterns/navigation/default-dark)
- Open [default nav demo](https://vanilla-framework-3727.demos.haus/docs/examples/patterns/navigation/default)
- See that the updates comply with the [design](https://app.zeplin.io/project/5ef9d96f06f00111064d6268/screen/6076f590cf53b53d0add509c) …
> Update top left nav logo spacing and selected state

- scss/_patterns_table-mobile-card.scss
Adds a min-width to `p-mobile--card` columns to help enforce their correct display.
Partially fixes #3754 (doesn't address the text overflow issue)
(it's easier to QA this one line fix where the problem was first encountered)
- Go to https://ubuntu.com/cube/microcerts
- Login
- Reduce the width of the browser so it hits the mobile breakpoint, see that the width of the columns is unbearably narrow
- In dev tools, set the min-width of `.p-table--mobile-card td` to 100%
- See that the columns fit the width of the card …
> Add min width to mobile card columns

- scss/_settings_colors.scss
Looking at the git blame of the color-positive, it was accidentally converted from hex to hsl and back, introducing a change in one of the digits  form 4 to 6. This pr corrects it back to whatch the colour settings doc page specifies.
> correct typo in the positive green hex code

- scss/_patterns_navigation.scss
- scss/_settings_colors.scss
- templates/docs/settings/color-settings.md
Add !default to the recently introduced $colors--light-theme--nav-highlight so it can be overriden
- Look ast diff
- Verify the $colors--light-theme--nav-highlight ha sa !default at the end
> Make nav highlight colour overrideable

- scss/_base_button.scss
- scss/_global_functions.scss
- scss/_patterns_article-pagination.scss
- scss/_patterns_buttons.scss
- scss/_patterns_chip.scss
- scss/_patterns_contextual-menu.scss
- scss/_patterns_navigation.scss
- scss/_patterns_side-navigation.scss
- scss/_patterns_subnav.scss
- scss/_patterns_tabs.scss
- scss/_settings_colors.scss
- scss/_settings_placeholders.scss
- tests/parker.js
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3665
- Inspect side navigation, chips, buttons (all flavours), accordion
- Verify states are consistent
> Standardize hover and active states across components

- scss/_patterns_buttons.scss
Removes default white background from link button.
Fixes #3771 
- Open [demo](https://vanilla-framework-3772.demos.haus/docs/examples/patterns/buttons/link)
- Make sure link button looks well when background is not white
> Remove background from link button.

- templates/docs/examples/layouts/documentation.html
- templates/docs/examples/patterns/navigation/default-dark.html
- templates/docs/examples/patterns/navigation/default.html
- templates/docs/examples/patterns/navigation/full-width.html
Fix small typo in navigation examples
Check code and visit the navigation examples.
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3788
> Fix small typo in navigation examples

- package.json
- scss/_base_tables.scss
- scss/_patterns_table-expanding.scss
- scss/standalone/patterns_table-overflow.scss
- templates/_layouts/docs.html
- templates/docs/base/tables.md
- templates/docs/component-status.md
- templates/docs/examples/patterns/tables/table-overflow.html
Added `has-overflow` utility to tables
Fixes #3780 
- Open [demo](/docs/examples/patterns/tables/table-overflow)
- Trigger the tooltip and contextual menus, see that they're not cut off by the cell they're in
- [docs](/docs/base/tables#overflow)
- [component status](/docs/component-status)
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Releas …
> Add `has-overflow` utility to tables

- templates/docs/component-status.md
- webapp/app.py
- Fixed a mislabelled item in component status
- Drive by: updated a role on the contribute page
- Open [demo](https://vanilla-framework-3799.demos.haus/docs/component-status)
- Check that the item in "What's new in Vanilla 2.32" table is "Tables / Overflow" and links to the correct page
> Fix title of `has-overflow` item in component status page

- scss/_patterns_buttons.scss
- templates/docs/component-status.md
- templates/docs/examples/patterns/buttons/alignment.html
- templates/docs/examples/patterns/buttons/default.html
- templates/docs/examples/patterns/buttons/dense.html
- templates/docs/examples/patterns/buttons/inline.html
- templates/docs/examples/patterns/buttons/neutral.html
- templates/docs/examples/patterns/buttons/small.html
- templates/docs/examples/templates/external-links.html
- templates/docs/examples/templates/tick-element-comparison.html
- templates/docs/examples/templates/vertical-spacing.html
- templates/docs/patterns/buttons.md
- templates/docs/upgrade-guide-v3.md
- templates/index.html
Deprecates the unnecessary `p-button--neutral` as it has same styling as `p-button`.
Fixes #3804 
- Open [demo](https://vanilla-framework-3806.demos.haus/docs/examples/patterns/buttons/default)
- Check if default `p-button` looks as expected (like `<button>` and `p-button--neutral` before)
- Check if deprecated neutral button still renders as expected
- https://vanilla-framework-3806.demos.haus/docs/examples/patterns/buttons/neutral
- Check the updated documentation
- https://vanilla-framework-3806.demos.haus/docs/patterns/buttons
- https://vanilla-framework-3806.demos.haus/docs/component-status …
> Deprecate neutral button

- deleted.yaml
- redirects.yaml
- templates/410.html
- added a 410 template
- added `deleted.yaml` and removed the recently added redirect for the [recently removed showcase page](https://github.com/canonical-web-and-design/vanilla-framework/pull/3810) 
- Open [demo](https://vanilla-framework-3812.demos.haus/showcase)
- See that you're presented with a message informing you that the content has been deleted …
> add 410 template for deleted content

- templates/_layouts/_header.html
- templates/accessibility.html
- templates/browser-support.html
- templates/docs/examples/index.html
- templates/docs/examples/standalone.html
- templates/docs/index.html
- templates/index.html
Fixed a number of accessibility errors on top level pages that were highlighted by the WAVE extension
- Open:
- [homepage](https://vanilla-framework-3811.demos.haus)
- [docs index](https://vanilla-framework-3811.demos.haus/docs)
- [examples index](https://vanilla-framework-3811.demos.haus/docs/examples)
- [standalone examples index](https://vanilla-framework-3811.demos.haus/docs/examples/standalone)
- [/accessibility](https://vanilla-framework-3811.demos.haus/accessibility)
- [/browser-support](https://vanilla-framework-3811.demos.haus/browser-support)
- [/contribute](https://vanilla-framework-3811.demos.haus/contribute)
- Open the [WAVE browser extension](https://wave.webaim.org/extension/) on each page
- See that there are zero errors, and fewer alerts compared to the live site.
If this …
> Website accessibility fixes

- scss/_patterns_label.scss
- scss/_settings_colors.scss
- templates/_layouts/docs.html
- templates/docs/component-status.md
- templates/docs/examples/patterns/labels/default.html
- templates/docs/patterns/labels.md
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3201
- Open docs/patterns/labels
- Review the The "Default" section at the top
> Add p-label

- scss/_patterns_table-mobile-card.scss
- scss/standalone/patterns_table-mobile-card.scss
- templates/docs/component-status.md
- templates/docs/examples/patterns/tables/table-mobile-card.html
Removed contextual menu styles from p-table--mobile-card pattern
Fixes #3835 
- Open [demo](https://vanilla-framework-3843.demos.haus/docs/examples/patterns/tables/table-mobile-card)
- Reduce the width of the browser to a small enough breakpoint to see the table turn into its card form
- Click any of the "Actions" buttons, see that the contextual menu behaves as normal
- [Component status](https://vanilla-framework-3843.demos.haus/docs/component-status) …
> Remove contextual menu styles from p-table--mobile-card

- scss/_patterns_notifications.scss
- Updated existing notification pattern to use new styling
Fixes #3822 
- Open [demo](https://vanilla-framework-3844.demos.haus/docs/examples/patterns/notifications/caution)
- Check that it matches the new [design](https://app.zeplin.io/project/5fac06865cfff51271b72cc6/screen/60353ac1f130133007d40217)
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-releas …
> Update existing notification pattern with new styling

- package.json
- scss/_patterns_links.scss
- scss/standalone/patterns_navigation.scss
- scss/standalone/patterns_skip-link.scss
- templates/_layouts/_header.html
- templates/_layouts/docs.html
- templates/docs/component-status.md
- templates/docs/examples/patterns/links/links-skip.html
- templates/docs/examples/patterns/navigation/default-dark.html
- templates/docs/examples/patterns/navigation/default.html
- templates/docs/examples/patterns/navigation/deprecated-dark.html
- templates/docs/examples/patterns/navigation/deprecated-subnav-dark.html
- templates/docs/examples/patterns/navigation/deprecated-subnav.html
- templates/docs/examples/patterns/navigation/deprecated.html
- templates/docs/examples/patterns/navigation/dropdown-dark.html
- templates/docs/examples/patterns/navigation/dropdown.html
- templates/docs/examples/patterns/navigation/full-width.html
- templates/docs/patterns/links.md
- Added `p-link--skip` pattern
- styles were taken from [global-nav](https://github.com/canonical-web-and-design/global-nav/blob/master/src/sass/global-nav.scss#L400)
- Removed skip links nested within navigation components
- skip links should be the first thing that can be tabbed to, and should become visible on focus (see: [WCAG guidance](https://www.w3.org/TR/WCAG20-TECHS/G1.html))
- Added skip link to vf.io
Fixes #3662 
- Open [demo](https://vanilla-framework-3851.demos.haus/docs/examples/patterns/links/links-skip)
- Press tab, see that the skip link appears
- Open [vf.io homepage](https://vanilla-framework-3851.demos.haus/)
- [Link docs](https://vanilla-framework-3851.demos.haus/docs/patterns/links#skip-link)
- [Component …
> Add skip link pattern

- scss/_base_placeholders.scss
- scss/_layouts_application.scss
- scss/_patterns_notifications.scss
- scss/_settings_placeholders.scss
- templates/docs/examples/patterns/notifications/action.html
- templates/docs/examples/patterns/notifications/caution.html
- templates/docs/examples/patterns/notifications/information.html
- templates/docs/examples/patterns/notifications/negative.html
- templates/docs/examples/patterns/notifications/notifications.html
- templates/docs/examples/patterns/notifications/positive.html
- templates/docs/examples/patterns/notifications/variants.html
- Added modal, raised and unread notification variants
- Added action (links, buttons, menu) variants
- The highlight bar and padding are now applied to the root `.p-notification` element instead of the first child
- Changed the text elements `.p-notification__title`, `.p-notification__message`, `.p-notification__time` to use text tags in the examples
Fixes #3825
Fixes #3828
Fixes #3829
Fixes #3830
Fixes #3831
- Open [Notifications - Variants](https://vanilla-framework-3853.demos.haus/docs/examples/patterns/notifications/variants)
> add actions, modal, raised and unread notification variants

- .spelling
- scss/_patterns_notifications.scss
- templates/docs/component-status.md
- templates/docs/examples/patterns/notifications/dismissible.html
- templates/docs/examples/patterns/notifications/timestamp.html
- templates/docs/examples/patterns/notifications/variants.html
- templates/docs/patterns/notification.md
- Added updated and deprecated notices to the component status page.
- Added deprecated class substitutions to the notifications page.
- Reordered the notifications page.
- Renamed time to timestamp.
- Fixed spelling of `dismissible`.
Fixes: #3857.
- Open the [component status](https://vanilla-framework-3859.demos.haus/docs/component-status) page.
- Check that there are entries for notification updates and deprecations.
- Open the [notifications](https://vanilla-framework-3859.demos.haus/docs/patterns/notification) page.
- Check that there is Deprecated table near the bottom.
> Notifications deprecations

- scss/_base_button.scss
- scss/_patterns_buttons.scss
- scss/_patterns_search-and-filter.scss
- tests/parker.js
Adjusted the height of the search and filter input to match standard inputs
- this includes tweaking the position of the clear CTA, and the margin on chips in the input
Fixes #3808
- Open:
- [chip overflow demo](https://vanilla-framework-3864.demos.haus/docs/examples/patterns/search-and-filter/chip-overflow)
- [default demo](https://vanilla-framework-3864.demos.haus/docs/examples/patterns/search-and-filter/default)
- [with chips demo](https://vanilla-framework-3864.demos.haus/docs/examples/patterns/search-and-filter/with-chips)
- [with search prompt demo](https://vanilla-framework-3864.demos.haus/docs/examples/patterns/search-and-filter/with-search-prompt)
- Open dev tools and inspect the height of the div with class `.p-search-and-filter`
- See that it matches the height of the text …
> Bring search and filter height inline with other inputs

- package.json
- scss/_base_placeholders.scss
- templates/docs/examples/templates/z-index.html
- Set z-index of hr.u-no-margin--bottom
- bumped Vanilla version to 2.33.1
Fixes #3878 
- Open [demo](https://vanilla-framework-3880.demos.haus/docs/examples/templates/z-index)
- See that the hr above the tabs is visible, and not obscured in any way
> Set z-index of hr.u-no-margin--bottom

- templates/docs/patterns/notification.md
Added documentation on improving notification accessibility
Fixes #3832 
- Open [demo](https://vanilla-framework-3879.demos.haus/)
- [Notification docs](https://vanilla-framework-3879.demos.haus/docs/patterns/notification#accessibility)
> Add documentation on notification accessibility

- .spelling
- templates/docs/patterns/icons.md
Added note on customising icon color to icon docs
Fixes #3858 
- Open [demo](https://vanilla-framework-3880.demos.haus/docs/patterns/icons#customisation)
- Check that it makes sense and reads well
> Document icon color customisation

- templates/docs/examples/patterns/side-navigation/_layout-application.html
Removed unnecessary comment from application layout example
Fixes #3576 
- Check the code
> Remove unnecessary comment from layout application template

- scss/_base_code.scss
- scss/_base_fontfaces.scss
- scss/_base_syntax-highlighting.scss
- scss/_base_typography-definitions.scss
- scss/_patterns_code-copyable.scss
- scss/_patterns_label.scss
- scss/_settings_font.scss
- templates/docs/settings/font-settings.md
- Documented font-weight variables
- Replaced inline font-weight definitions with variables
- Added `$font-weight-display-heading` variable
Fixes #3348 
- Open [demo](https://vanilla-framework-3894.demos.haus/docs/settings/font-settings#font-weight)
- Check that the documentation makes sense
- Check Percy, nothing should have changed
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framewor …
> Document font-weight variables

- templates/docs/building-vanilla.md
- Added information on building Vanilla css with `dart-sass` package
- Added a note to `node-sass` instructions that it is deprecated, and will be replaced in the Vanilla project by `dart-sass` in 3.0
Fixes #3849 
- Most thorough way to QA is to:
- clone this [Vanilla masterclass repo](https://github.com/sowasred2012/vanilla-playground)
- in the repo's [package.json](https://github.com/sowasred2012/vanilla-playground/blob/master/package.json), remove the dependencies and scripts, then follow the `dart-sass` [build docs in the demo](https://vanilla-framework-3893.demos.haus/docs/building-vanilla#dart-sass).
- When `dart-sass` is successfully set up, opening `index.html` in the masterclass repo should show a very Vanilla looking page
If this PR contains Vanilla SCSS code changes, it should …
> Add dart-sass build info

- scss/_patterns_notifications.scss
Replace the variable used to define margin-bottom on notificaiton content with one that doesn't depend on  the scaling factor `$multi`.
Fixes #3898
- Open docs/examples/patterns/notifications/variants
- Verify notification looks as in the screenshot below regardless of the value of the scaling factor $multi
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre- …
> Make notificaiton margin-bottom not depend on scaling factor

- scss/_base_placeholders.scss
Increase z-index of hr with no bottom margin so that it isn't obscured by focussed tabs (which have a `z-index` of `1` when focussed)
Fixes #3878 
- Open [demo](http://0.0.0.0:8101/docs/examples/templates/z-index)
- Open dev tools and trigger the focus state on any of the `a` elements within the tab patterns
- See that the `hr` above the tabs is still fully visible …
> increase z-index of hr without margin bottom

- scss/_patterns_lists.scss
- templates/_layouts/docs.html
- templates/docs/component-status.md
- templates/docs/examples/patterns/lists/lists-status.html
- templates/docs/patterns/lists.md
Added `is-crossed` modifier pattern to list items
- Also changed the colour of the `is-ticked` icon to `$color-positive`
Fixes #3836 
- Open [demo](https://vanilla-framework-3912.demos.haus/docs/examples/patterns/lists/lists-status)
- See that there is a ticked and crossed list item
- [Docs](https://vanilla-framework-3912.demos.haus/docs/patterns/lists#status)
- [Component status](https://vanilla-framework-3912.demos.haus/docs/component-status) …
> Cross list

- scss/_patterns_search-and-filter.scss
Search and filter pattern: removed the icon/button that Chrome automatically adds to search inputs (we already have [an example where we roll our own](https://vanillaframework.io/docs/examples/patterns/search-and-filter/with-search-prompt))
Fixes #3891 
- In Chrome, open [demo](https://vanilla-framework-3917.demos.haus/docs/examples/patterns/search-and-filter/default)
- Type anything into the search box, no cross icon should appear …
> Hide Chrome's search clear icon on search and filter pattern

- templates/docs/patterns/search-box.md
Added a notification to the `p-search-box` docs explaining that the cancel button is necessary in implementation.
Fixes #3884 
- Open [demo](https://vanilla-framework-3925.demos.haus/docs/patterns/search-box)
- See that the notification makes sense and addresses the concerns in the issue
> Document mandatory nature of cancel button in `p-search-box` pattern

- scss/_patterns_notifications.scss
- scss/standalone/patterns_notifications.scss
- Added missing right padding to deprecated notification pattern
Fixes #3928 
- Open [demo](https://vanilla-framework-3930.demos.haus/docs/patterns/tooltips)
- Check that the text doesn't touch the border
- Compare to [live version](https://vanillaframework.io/docs/patterns/tooltips)
> Add right padding to deprecated notification response element

- scss/_base_forms.scss
- templates/docs/examples/utilities/truncate.html
- Added `width: auto` to the `_base_form` label to enable ellipses when the `.u-truncate` class is added. 
- [#3914](https://github.com/canonical-web-and-design/vanilla-framework/issues/3914)
- Open [demo](https://vanilla-framework-3931.demos.haus/docs/examples/utilities/truncate)
- Check the label truncates and reveals an ellipses
- Compare against [live](https://ubuntu.com/certified/servers)  …
> Enable labels to truncate with ellipses

- templates/_layouts/docs.html
- templates/docs/base/forms.md
Cleaned up doc side nav labels for 2.34.0
- Open [demo](https://vanilla-framework-3933.demos.haus/docs)
- Check that the side nav has status labels relevant to the features in the [upcoming release](https://github.com/canonical-web-and-design/vanilla-framework/releases), and no others
> update side nav labels for 2.34.0

- .github/PULL_REQUEST_TEMPLATE.md
- guides/pull-requests.md
- redirects.yaml
- templates/_layouts/docs.html
- templates/docs/patterns/labels.md
- templates/docs/whats-new.md
Change "Component status" to "What's new in ..." and promote it to top of side navigation to make it more visible and accessible.
- Open [demo](https://vanilla-framework-3937.demos.haus/docs/whats-new)
- Make sure page under new URL works: https://vanilla-framework-3937.demos.haus/docs/whats-new
- Make sure old URL redirects to new page: https://vanilla-framework-3937.demos.haus/docs/component-status
- Make sure any other references to "Component status" are updated
This is just docs update, nothing to release in Vanilla package.
> Change component status to what's new

- package.json
- scss/_patterns_notifications.scss
- templates/docs/examples/patterns/notifications/variants.html
- templates/docs/upgrade-guide-v3.md
Fix max width of notifications text when `<p>` is used.
Fixes #3936 
- Open [demo](https://vanilla-framework-3938.demos.haus/docs/examples/patterns/notifications/variants)
- Make sure both multiline notifications render correctly (text uses whole width of notification):
- https://vanilla-framework-3938.demos.haus/docs/examples/patterns/notifications/variants
- Make sure that changing deprecated `p-notification__response` to `p-notification__content` in this example works correctly:
- https://vanilla-framework-3938.demos.haus/docs/examples/templates/maas-docs-grid
- if CSS class names …
> Fix max-width of notifications text

- scss/_base_typography.scss
- scss/_patterns_buttons.scss
- scss/_patterns_grid.scss
- scss/_patterns_headings.scss
- scss/_patterns_icons.scss
- scss/_settings_grid.scss
- scss/_vanilla.scss
- templates/docs/base/typography.md
- templates/docs/examples/patterns/buttons/neutral.html
- templates/docs/examples/patterns/code-snippet/dropdown.html
- templates/docs/examples/patterns/separator.html
- templates/docs/examples/templates/external-links.html
- templates/docs/examples/templates/snapcraft-publicise.html
- templates/docs/patterns/buttons.md
- templates/docs/search.html
Remove deprecated styles related to:
- headings (`--one`, `--two`, etc class names), updated examples that still used those
- neutral button was removed, updated any examples that still used them
- removed is-active button
- removed unnecessary button icon mixin
- removed deprecated grid settings
Part of #3744 
- Check the code to see which examples were affected
- Make sure affected examples render as expected
- Make sure relevant doc pages don't include deprecated docs anymore
> Remove deprecated styles for headings, buttons and grid

- scss/_patterns_card.scss
- templates/docs/examples/patterns/card/image.html
- templates/docs/patterns/card.md
Updated the documentation to include undocumented `p-card__image` class name.
Fixes #3902 
- Open [demo](https://vanilla-framework-3932.demos.haus/docs/examples/patterns/card/image)
- Check if card demo with image works as expected: https://vanilla-framework-3932.demos.haus/docs/examples/patterns/card/image
- https://vanilla-framework-3932.demos.haus/docs/patterns/card#image
- see the [wiki for …
> Document a card with an image

- package.json
- scss/_base_forms-tick-elements.scss
- scss/_base_forms.scss
- scss/_patterns_form-tick-elements.scss
- templates/docs/base/forms.md
- templates/docs/examples/patterns/forms/forms-required.html
- Change position of asterisk to before text
- Change colour from red to black
- Updated Vanilla version to `2.35.0`, to be inline with this [PR](https://github.com/canonical-web-and-design/vanilla-framework/pull/3935/files) when it is merged 
Fixes #3871 
- Open [demo](https://vanilla-framework-3948.demos.haus/docs/examples/patterns/forms/forms-required)
- Check the asterisk is before the text and the colour is black as seen in [design](https://app.zeplin.io/project/60e5bad7cfc6030846cacd89/screen/6114f46a421e5098c5c1e7df)
- Documentation not updated as only changed scss of current pattern  …
> Update asterisk on required form fields

- scss/_base_icon-definitions.scss
- scss/_patterns_icons.scss
- scss/standalone/patterns_notifications.scss
- templates/docs/patterns/icons.md
Remove last batch of deprecated styling (icons).
Fixes #3744 
- Open [demo](https://vanilla-framework-3960.demos.haus/docs/patterns/icons)
- Make sure all deprecated icons are removed from the docs page and the code
- Drive-by: make sure all icons are correctly displayed in cards in the docs (next to their label)
> Remove deprecated icon styles

- templates/_layouts/docs.html
- templates/docs/whats-new.md
Fixes labels in side navigation and what's new page for new 2.35 release.
- Open [demo](https://vanilla-framework-3964.demos.haus/docs/whats-new)
- Make sure the "Updated" label related to Form Validation change has correct color
- Make sure side navigation only has labels for relevant items (Forms in this case)
> Fix labels in docs for 2.35

- package.json
- scss/_patterns_accordion.scss
- scss/standalone/patterns_accordion.scss
- templates/_layouts/docs.html
- templates/docs/examples/patterns/accordion/tick-elements.html
- templates/docs/patterns/accordion.md
- templates/docs/whats-new.md
Variation to remove indendation for checkboxes.
Removing 2 rems will adjust the indentation/padding for the default accordion, but if we add checkboxes, it will push the content further, therefore, I removed 1 rem to specifically accomodate for checkboxes.
Therefore, something we need to decides is whether we want to accomodate the indentation for checkboxes or general accordions without checkboxes.
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3913
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3885
- Open https://vanilla-framework-3963.demos.haus/docs/examples/patterns/accordion/tick-elements
- Check that paddings have been removed, compare with /docs/examples/patterns/accordion/default
- Added …
> No indentation accordion variation

- scss/_patterns_accordion.scss
Add hover state for uncollpased accordion button
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3950
- Open [demo](https://vanilla-framework-3973.demos.haus//docs/examples/patterns/accordion/default)  compare with [current](https://vanillaframework.io/docs/examples/patterns/accordion/default)
When accordion is opened, hover over the button to highlight the hover state. Now all buttons should have hover state
- Updated existing accordion examples https://vanilla-framework-3973.demos.haus//docs/examples/patterns/accordion/default/docs/patterns/accordion#accordion
- `Feature 🎁`, `Breaking Change 💣`, `Bug …
> Add hover state for uncollpased accordion button

- package.json
- scss/_patterns_modal.scss
- Truncates modal to fit where the content ends and centers the modal when viewing on mobile.
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3906
- Open [demo](https://vanilla-framework-3982.demos.haus/docs/examples/patterns/modal/default)
- Check the modal works as expected and that it limits the size to fit that of the content. …
> Truncates modal to fit content and centers

- scss/_patterns_modal.scss
- Makes header fixed to the top of a modal when scrolling
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3926
- Open [demo](https://vanilla-framework-3983.demos.haus/docs/examples/patterns/modal/modal-scroll)
- Check header is fixed when scrolling in a modal
- Check it works on different screen sizes
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki …
> Make header fixed in modal

- .spelling
- package.json
- scss/_base_forms.scss
- templates/_layouts/docs.html
- templates/docs/base/forms.md
- templates/docs/examples/base/forms/datalist.html
- templates/docs/whats-new.md
- Adds datalist to examples without any styling.
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2673
- Open [demo](https://vanilla-framework-3984.demos.haus/docs/examples/base/forms/datalist)
- Choose your favorite ice cream 
> Add datalist to examples

- templates/docs/patterns/modal.md
Updated accessibility note on modal docs to try to make them less vague.
Fixes #3974 
- Open [demo](https://vanilla-framework-3998.demos.haus/docs/patterns/modal)
- Read the docs, see that they are clear enough
> Update modal accessibility docs

- scss/_base_button.scss
- scss/_base_grid-definitions.scss
- scss/_layouts_fluid-breakout.scss
- scss/_patterns_article-pagination.scss
- scss/_patterns_chip.scss
- scss/_patterns_divider.scss
- scss/_patterns_grid.scss
- scss/_patterns_heading-icon.scss
- scss/_patterns_matrix.scss
- scss/_patterns_pull-quotes.scss
- scss/_patterns_side-navigation.scss
- scss/_patterns_table-mobile-card.scss
- templates/docs/examples/layouts/application/JAAS.html
- templates/docs/examples/layouts/application/split.html
- Remove or rename any remaining misaligned media query breakpoints in compoenents.
- make sure max-width media queries don't overlap min-width media queries by 1px
Fixes #4082
- Make sure there are no unexpected changes in Percy
- Make sure responsive components work as expected, especially around 1px of breakpoints (619px, 620px, 1035px, 1036px): https://vanilla-framework-4107.demos.haus/docs/examples/templates/responsive
> Clean up media query breakpoints in components

- scss/_settings_breakpoints.scss
- templates/docs/patterns/navigation.md
- templates/docs/settings/breakpoint-settings.md
- templates/docs/upgrade-guide-v3.md
Move default value of navigation threshold breakpoint to small screens, update all related docs.
- Open [demo](https://vanilla-framework-4111.demos.haus/docs/examples/patterns/navigation/dropdown)
- check if navigation goes to mobile view on small screen (< 620px)
- https://vanilla-framework-4111.demos.haus/docs/examples/patterns/navigation/dropdown
- Review updated docs:
- https://vanilla-framework-4111.demos.haus/docs/settings/breakpoint-settings
> Update default value of navigation breakpoint

- scss/_base_forms.scss
- scss/_patterns_form-tick-elements.scss
- templates/docs/examples/base/forms/tick-elements.html
- templates/docs/examples/patterns/switch.html
- Set display of labels to `inline-block`, rather than `block`.
- Added an example with base tick elements
Fixes #4104 
- Visit https://vanilla-framework-4110.demos.haus/docs/examples/base/forms/tick-elements
- See that the elements look good
- Check Percy, see that other examples are not affected
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-ta …
> Inline labels

- templates/docs/base/forms.md
- templates/docs/examples/patterns/forms/form-validation.html
- templates/docs/examples/patterns/forms/forms-required.html
add forms input a11y docs section
Fixes https://github.com/canonical-web-and-design/react-components/issues/639
- https://vanilla-framework-4125.demos.haus/docs/base/forms#validation
- https://vanilla-framework-4125.demos.haus/docs/base/forms#required
- https://vanilla-framework-4125.demos.haus/docs/base/forms#accessibility
- focusing on invalid fields (fields that have an error) in examples will make the screen reader announce that it's invalid (e.g. VoiceOver will announce "invalid data"). …
> add forms input a11y docs

- templates/docs/examples/patterns/forms/_form-stacked.html
- templates/docs/examples/patterns/forms/form-help-text.html
- templates/docs/examples/patterns/forms/form-inline.html
- templates/docs/examples/patterns/forms/form-validation.html
- templates/docs/examples/patterns/forms/forms-required.html
- templates/docs/examples/patterns/forms/password-toggle.html
Adds `aria-describedby` to inputs with help text or validation messages.
- Make sure all validation or help text messages are connected to the inputs via aria-describedby and read by screen reader
- Examples to verify:
- https://vanilla-framework-4135.demos.haus/docs/examples/patterns/forms/form-validation
- https://vanilla-framework-4135.demos.haus/docs/examples/patterns/forms/form-help-text
> Add aria-describedby to fields with help or validation messages

- package.json
- Bump version to 3.0.0-beta.2
- check version is correct in `package.json`
> Update version to 3.0.0-beta.2

- .circleci/config.yml
- Dockerfile
- package.json
Moved `node-sass` and other dependencies to `devDependencies` to avoid installing them in project using Vanilla.
Updated our Dockerfile accordingly.
This PR is agains `vanilla-2.0` branch, it's meant to be released as hotfix to Vanilla 2.0.
- Make sure CI passes
> Move unnecessary dependencies to devDependencies

- .circleci/config.yml
Update CircleCI image from our old dev docker image to official image with Python and node.
- Make sure all CI passes (especially circleci/percy)
> Use official image for CircleCi with Python and node

- renovate.json
Prevent renovate from upgrading python in CircleCi image, which fails the build (as in #4165)
> Prevent renovate from upgrading python in CircleCi image

- scss/_patterns_chip.scss
- scss/_settings_colors.scss
- scss/_settings_themes.scss
- templates/docs/examples/patterns/chip/dark.html
- templates/docs/examples/patterns/chip/variants.html
- templates/docs/patterns/chip.md
- Added theming for chips with different shades of border/background/text for each chip type
- Added theme default setting for chips
- Added example in the docs
- Added an example for the dismiss chip as this was missing
Fixes #4158 
- Check the dark chip example
- Check adding `is-dark` or `is-light` class names work as expected
- Chip documentation - new example for the dismiss chip and dark theme
- if CSS class names are changed/added/removed it …
> Add theming for chips

- scss/_base_grid-definitions.scss
- scss/_base_hr.scss
- scss/_layouts_fluid-breakout.scss
- scss/_patterns_divider.scss
- scss/_patterns_grid.scss
- scss/_patterns_logo-section.scss
- scss/_patterns_navigation.scss
- scss/_patterns_side-navigation.scss
- scss/_settings_grid.scss
- templates/docs/upgrade-guide-v3.md
Replace medium with large, delete keys (they use same values so no need forseparate vars)
Fixes #3278
- Ensure no percy changes presnt
- Check code changes, verify no instances of `map-get($grid-gutter-widths, medium)` remain
> Refactor margin/gutter scss maps

- scss/_patterns_table-expanding.scss
Removes unnecessary margin reset from expanding table (which was conflicting with margin in mobile table cards).
Fixes #4163
- Open [demo](https://vanilla-framework-4177.demos.haus)
- Check if expanding table works as expected:
- https://vanilla-framework-4177.demos.haus/docs/examples/patterns/tables/table-expanding
- In mobile-card example, add `p-table--expanding` class to the table and check if it still looks correctly in mobile view
- https://vanilla-framework-4177.demos.haus/docs/examples/patterns/tables/table-mobile-card …
> Remove unnecessary margin reset

- .github/workflows/pr.yml
- .github/workflows/publish-on-release.yml
- package.json
- renovate.json
Attempt to freeze node version in renovate and only allow LTS releases
- Just a code review, we need to merge it to verify if renovate picks it up
> Attempt to force node LTS version in renovate

- scss/_patterns_table-mobile-card.scss
- templates/docs/base/tables.md
- templates/docs/examples/patterns/tables/table-mobile-card.html
- templates/docs/examples/templates/maas-layout.html
- templates/docs/examples/templates/responsive.html
- templates/docs/examples/templates/tick-elements.html
- templates/docs/upgrade-guide-v3.md
- Updated `aria-label` to `data-heading`
- Updated docs to reflect change
Fixes
#4131 
- Turn voice over on while reviewing the table, ensure the content of the cells is read out not just the title. Currently the title is read out twice, not sure how to fix this, I tried to use `content: attr(data-heading) / ' ';` but this hides the title both times. 
- /docs/base/tables#responsive
- if CSS class names are changed/added/removed it should be minor …
> Fix misused `aria-label` on mobile card table

- scss/_patterns_chip.scss
- scss/_patterns_search-and-filter.scss
- scss/_settings_colors.scss
- templates/docs/examples/patterns/chip/colors.html
- templates/docs/examples/patterns/chip/dark.html
- templates/docs/examples/patterns/chip/default.html
- templates/docs/examples/patterns/chip/dense.html
- templates/docs/examples/patterns/chip/inline.html
- templates/docs/examples/patterns/chip/interactive.html
- templates/docs/examples/patterns/chip/long-values.html
- templates/docs/examples/patterns/chip/variants.html
- templates/docs/examples/patterns/chip/with-dismiss.html
- templates/docs/examples/patterns/lists/lists-inline-stretch-align.html
- templates/docs/examples/patterns/search-and-filter/_default-script.js
- templates/docs/examples/patterns/search-and-filter/chip-overflow.html
- templates/docs/examples/patterns/search-and-filter/default.html
- templates/docs/examples/patterns/search-and-filter/expanded.html
- templates/docs/examples/patterns/search-and-filter/with-chips.html
- templates/docs/examples/patterns/side-navigation/_default.html
- templates/docs/examples/patterns/side-navigation/_docs.html
- templates/docs/examples/patterns/side-navigation/_icons.html
- templates/docs/examples/patterns/side-navigation/_layout-JAAS.html
- templates/docs/examples/patterns/side-navigation/_layout-application.html
- templates/docs/examples/patterns/side-navigation/icons.html
- templates/docs/patterns/chip.md
- templates/docs/patterns/notification.md
- templates/docs/upgrade-guide-v3.md
- templates/docs/whats-new.md
- tests/parker.js
Adds interactive chips (using `button` elements). Also makes sure chips respect aria-pressed (#3416)
Drive-by: fix chips overrides in search&filter component.
Fixes #4167
Fixes #3416 
Fixes #4166
- Open [demo](https://vanilla-framework-4169.demos.haus/docs/examples/patterns/chip/interactive)
- Check if new examples with interactive chips work:
- https://vanilla-framework-4169.demos.haus/docs/examples/patterns/chip/interactive
- All variants (interactive are at the end of each row): https://vanilla-framework-4169.demos.haus/docs/examples/patterns/chip/variants
- Make sure search&filter looks as expected (note that Vanilla examples are not fully interactive, just expand/collapse):
- https://vanilla-framework-4169.demos.haus/docs/examples/patterns/search-and-filter/with-chips
- Review …
> Add interactive chips

- templates/docs/layouts/application.md
- templates/docs/layouts/sticky-footer.md
- Added import section to `/docs/layouts/application`
- Drive by: added import section to `/docs/layouts/sticky-footer` as this was also missing
Fixes #4136 
- Check the import section lists all relevant includes on both sticky footer and application layout
> Add missing import sections

- guides/pull-requests.md
- redirects.yaml
- scss/_patterns_label.scss
- scss/_vanilla.scss
- scss/standalone/patterns_label.scss
- scss/standalone/patterns_side-navigation.scss
- templates/_layouts/docs.html
- templates/docs/examples/patterns/labels.html
- templates/docs/examples/patterns/lists/lists-inline-stretch-align.html
- templates/docs/examples/patterns/side-navigation/_default.html
- templates/docs/examples/patterns/side-navigation/_docs.html
- templates/docs/examples/patterns/side-navigation/_icons.html
- templates/docs/examples/patterns/side-navigation/_layout-JAAS.html
- templates/docs/examples/patterns/side-navigation/_layout-application.html
- templates/docs/examples/patterns/side-navigation/icons.html
- templates/docs/patterns/labels.md
- templates/docs/patterns/slider.md
- templates/docs/upgrade-guide-v3.md
- templates/docs/whats-new.md
Labels are back to replace non-interactive chips
Fixes #4183
- Open [demo](https://vanilla-framework-4184.demos.haus/docs/patterns/labels)
- Check labels examples and docs
- https://vanilla-framework-4184.demos.haus/docs/patterns/labels
- Make sure we use labels in all places where they have been before:
- check side navigation in vanilla docs
- check what's new page
- check side navigation and application layout examples
> Bring back labels component

- scss/_base_fontfaces.scss
Make sure font-face declarations are always on root CSS level
Fixes #4182 
- Make sure CI passes and there are no changes in Percy
- Pull the branch locally, and in some local scss file (for example in standalone example) try nesting font declarations:
```
.test {
@include vf-b-placeholders;
@include vf-b-typography;
}
```
Make sure in the result CSS `@font-face` doesn't try to use the `.test` class name.
> Wrap font-face definitions in `@at-root`

- scss/_patterns_chip.scss
- scss/_settings_spacing.scss
- templates/docs/upgrade-guide-v3.md
Make dismiss button in chips round.
Fixes #4189 
- Open [demo](https://vanilla-framework-4191.demos.haus/docs/examples/patterns/chip/variants)
- Verify that rounded dismiss button in chips looks as expected
> Make dismiss in chips round

- templates/docs/building-vanilla.md
- templates/docs/upgrade-guide-v3.md
Initial improvements around 3.0 upgrade guide.
To be continues in canonical-web-and-design/vanilla-squad#1024 epic
Check upgrade guide: https://vanilla-framework-4119.demos.haus/docs/upgrade-guide-v3
Make sure it reads ok
Make sure any missing things are listed as part of canonical-web-and-design/vanilla-squad#1024 epic
> Initial improvements to upgrade guide

- templates/docs/upgrade-guide-v3.md
- Reword the text-max-width section to give more clarity what to do with the removed variables. 
Fixes [#1181](https://github.com/canonical-web-and-design/vanilla-squad/issues/1181)
- upgrade guide
> Reword text-max-width section of upgrade guide

- templates/docs/upgrade-guide-v3.md
- Added description of the `p-icon--contextual-menu` update to chevron icons to the upgrade guide.
Fixes [#1174](https://github.com/canonical-web-and-design/vanilla-squad/issues/1174)
- Open [demo](https://vanilla-framework-4196.demos.haus/docs/upgrade-guide-v3)
- New sentence mentioning update in upgrade guide …
> Add contextual menu icon update to upgrade guide

- package.json
For the sake of renovate we specify the expected node versions in renovate.json, so specifying them in package.json is redundant and unnecessary.
https://github.com/canonical-web-and-design/vanilla-framework/blob/f28cda8560d24f67b14b0ccc93ae3303788a0736/renovate.json#L18-L20
Fixes canonical-web-and-design/vanilla-squad#1187
> Remove specific node versions from package.json

- templates/docs/upgrade-guide-v3.md
- Add code snippet section to upgrade guide
Fixes [#1179](https://github.com/canonical-web-and-design/vanilla-squad/issues/1179)
- Open [demo](https://vanilla-framework-4198.demos.haus/docs/upgrade-guide-v3)
- Code snippet section of upgrade guide
> Add code pattern changes to upgrade guide

- templates/docs/upgrade-guide-v3.md
- Add new Accordion section to upgrade guide
Fixes [#1178](https://github.com/canonical-web-and-design/vanilla-squad/issues/1178)
- Open [demo](https://vanilla-framework-4199.demos.haus/docs/upgrade-guide-v3)
- Accordion section added to upgrade guide
[if …
> Add new Accordion section to upgrade guide

- templates/docs/upgrade-guide-v3.md
- Add a new section to the navigation section in the upgrade guide, describing the use of the new expanding search box component. (Not sure if the link is correct?)
- NOTE: I will change the order of everything when tackling this [issue](https://github.com/canonical-web-and-design/vanilla-squad/issues/1172)
Fixes [#1175](https://github.com/canonical-web-and-design/vanilla-squad/issues/1175)
- Open [demo](https://vanilla-framework-4201.demos.haus)
- new search box paragraph added to navigation section
- if CSS class names are not changed it can be …
> Add search box description to upgrade guide

- templates/docs/upgrade-guide-v3.md
- Add Breadcrumbs section to upgrade guide
Fixes [#1180](https://github.com/canonical-web-and-design/vanilla-squad/issues/1180)
- Open [demo](https://vanilla-framework-4203.demos.haus/docs/upgrade-guide-v3)
- Breadcrumbs section in upgrade guide
> Add breadcrumbs to upgrade guide

- templates/docs/upgrade-guide-v3.md
- Changed the order of variable names to make sure find and replace doesn't break 
Fixes [#1183](https://app.zenhub.com/workspaces/-design-system-tribe-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-squad/1183)
- check order of variable names
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Relea …
> Change order of variable names

- scss/_patterns_chip.scss
- replaced division with `math.div`
Fixes #4206 
- Pull this branch
- run dotrun
- check there are no more deprecation warnings in the terminal
> Fix sass deprecation warning

- templates/docs/upgrade-guide-v3.md
- Update table heading to be more consistent
- Add tables to sections that didn't have them before
- Make sure we consistently don't use `.` in front of class names
Fixes canonical-web-and-design/vanilla-squad#1176
- Check if the docs read better: https://vanilla-framework-4210.demos.haus/docs/upgrade-guide-v3
> Make the naming of tables and class names more consistent

- redirects.yaml
- templates/_layouts/docs.html
- templates/docs/migration-guide-to-v3.md
- templates/docs/upgrade-guide-v3.md
- Add warning alerts to crucial parts of the guide
- Rename the "Upgrade guide" to "Migration guide"
Fixes canonical-web-and-design/vanilla-squad#1184
- Open [demo](https://vanilla-framework-4215.demos.haus/docs/migration-guide-to-v3)
- Review updated documentation - focus on checking the warning notifications added, if they make sense in their context
- Make sure renamed page still works, that the URL is correct, side navigation works and redirect from all URL is in place
> Upgrade warnings

- templates/docs/migration-guide-to-v3.md
- Reorders migration guide sections and improve heading hierarchy.
- Adds links to relevant sections of Vanilla docs.
Fixes canonical-web-and-design/vanilla-squad#1172
- Review updated migration guide: https://vanilla-framework-4218.demos.haus/docs/migration-guide-to-v3
- Make sure the structure of the page is helpful
> Reorder migration guide

- README.md
- Remove gulp instructions and add instructions with Sass
Fixes #4222 
- Check readme text is correct
> Update README on vanilla website

- templates/_layouts/docs.html
- templates/docs/patterns/search-box.md
- templates/docs/whats-new.md
- Added updated labels to components in side navigation
- Added expanding search box example to search box docs
Fixes #4220 
- Open [demo](https://vanilla-framework-4221.demos.haus/docs)
- Check the labels are on correct components - chips, labels, search box and switch
- Check search box docs with expanding search box example
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/ …
> Add updated labels to side navigation

- templates/docs/patterns/accordion.md
- Added accessibility notes - google doc is [here](https://docs.google.com/document/d/1UekmbTagZNVppuiuw3i9aoMpgQBJVdZnSHC2ciW6blY/edit#) and has been QA'd by @sowasred2012 and @wgx 
Fixes #4037 
- Open [demo](https://vanilla-framework-4233.demos.haus/docs/patterns/accordion)
- Check the accessibility docs are the same as the doc
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wi …
> Add accessibility accordion notes

- templates/docs/patterns/lists.md
- Add accessibility notes for lists. copy doc [here](https://docs.google.com/document/d/1pK4kmbo83pyfQ92DuRLCqVAJaY9HdRTWbaAI3yCg59I/edit#)
Fixes #4051 
- Open [demo](https://vanilla-framework-4234.demos.haus/docs/patterns/lists#accessibility)
- Check the Accessibility notes on the lists page reads ok and isn't missing anything 
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wik …
> Add lists accessibility doc

- templates/docs/patterns/links.md
- Add accessibility notes for Links. copy doc [here](https://docs.google.com/document/d/1DcYBpmuLKZGLIWR6jgjYfZc1X64d8HtDt9uKMoB0POE/edit#heading=h.6xtxk46lmbik)
Fixes #4049 
- Open [demo](https://vanilla-framework-4235.demos.haus/docs/patterns/links#accessibility)
- Check the accessibility notes for links
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-r …
> Add link accessibility doc

- templates/docs/patterns/search-box.md
- Add search box accessibility doc
Fixes #4062 
- Open [demo](https://vanilla-framework-4239.demos.haus/docs/patterns/search-box#accessibility)
- Check the accessibility section of the search box docs page.
> Add search box accessibility doc

- templates/docs/patterns/accordion.md
- templates/docs/patterns/breadcrumbs.md
- templates/docs/patterns/card.md
- templates/docs/patterns/lists.md
- Add accessibility doc for Cards. Copy doc [here](https://docs.google.com/document/d/1f_dJS0MquxNm9D6e1OaHohyqXBNG1GwnPfFdxFci60k/edit#heading=h.qxwy2zql3yy7)
Fixes #4040 
- Open [demo](https://vanilla-framework-4237.demos.haus/docs/patterns/card#accessibility)
- Check the accessibility section of the card documentation
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Releas …
> Add accessibility card text

- .spelling
- templates/docs/patterns/links.md
- templates/docs/patterns/tooltips.md
- Add accessibility notes for tooltips
- Filed an [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/4240) as on our example currently the description is read out twice
Fixes #4068 
- Check the tooltips accessibility section
> Add tooltip accessibility doc

- package.json
- scss/_patterns_search-and-filter.scss
Fixes spacing issues in search and filter panel
- Open [demo](https://vanilla-framework-4246.demos.haus/docs/examples/patterns/search-and-filter/expanded)
- Check search and filter examples (make screen smaller for chips to wrap in 2 lines)
- https://vanilla-framework-4246.demos.haus/docs/examples/patterns/search-and-filter/expanded
- Make sure chips are visible as expected …
> Fix spacing issues with chips in search and filter

- templates/docs/base/forms.md
- templates/docs/layouts/application.md
- templates/docs/patterns/accordion.md
- templates/docs/patterns/buttons.md
- templates/docs/patterns/contextual-menu.md
- templates/docs/patterns/labels.md
- templates/docs/patterns/matrix.md
- templates/docs/patterns/navigation.md
- templates/docs/patterns/search-and-filter.md
- templates/docs/patterns/search-box.md
- templates/docs/patterns/strip.md
- templates/docs/patterns/tooltips.md
- templates/docs/settings/animation-settings.md
- templates/docs/settings/color-settings.md
- templates/docs/utilities/image-position.md
Improve HTML structure of notifications in docs to fix missing space issue.
Fixes #4242 
- Code review - make sure notifications use both `p-notification__title` and `p-notification__message`
- Open [demo](https://vanilla-framework-4248.demos.haus/)
- Review updated docs pages, make sure notifications display correctly:
- https://vanilla-framework-4248.demos.haus/docs/base/forms#disabled
- https://vanilla-framework-4248.demos.haus/docs/patterns/accordion
- https://vanilla-framework-4248.demos.haus/docs/patterns/buttons
- https://vanilla-framework-4248.demos.haus/docs/patterns/contextual-menu#indicator
- https://vanilla-framework-4248.demos.haus/docs/patterns/matrix
- https://vanilla-framework-4248.demos.haus/docs/patterns/navigation
- …
> Fix notifications in docs

- templates/docs/patterns/buttons.md
- Included the previous accessibility section as a bullet point in the new section with the example below it. 
Fixes #4251 
- Open [demo]( https://vanilla-framework-4252.demos.haus/docs/patterns/buttons)
- Check the accessibility section of the Button docs
> Merge Button Accessibility sections into one

- package.json
- scss/_base_forms-range.scss
- templates/docs/examples/base/forms/range.html
- templates/docs/examples/patterns/slider/slider-input.html
Update slider's style.
Fixes #4250 
- Open [demo](https://vanilla-framework-4253.demos.haus/docs/patterns/slider)
- Check doc page of slider
- Verify it's style matches with the [design](https://app.zeplin.io/project/6166f0f9aad348b734b978bb/screen/6166f160f367a9bb84e0c02d)
> Update slider style

- templates/docs/migration-guide-to-v3.md
Fixed a link on the migration to 3.0 docs page
- Go to https://vanilla-framework-4255.demos.haus/docs/migration-guide-to-v3
- Click the link in "Refer to grid documentation for more details and examples."
- You should be taken to https://vanilla-framework-4255.demos.haus/docs/patterns/grid
> Fix broken link in docs

- scss/_patterns_switch.scss
Updated switch styling as per [visual update](https://app.zenhub.com/workspaces/-design-system-tribe-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-framework/4036)
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/4249
- Open [demo](https://vanilla-framework-4254.demos.haus/docs/patterns/switch)
- See the the styling changes have been made accurately  …
> Updated switch styling

- scss/_patterns_pagination.scss
- templates/docs/examples/patterns/pagination/pagination-disabled.html
- templates/docs/examples/patterns/pagination/pagination-truncated.html
- templates/docs/examples/patterns/pagination/pagination-verbose.html
- templates/docs/examples/patterns/pagination/pagination.html
Improvements to the accessibility of our pagination component:
- Added `&[aria-current='page']` to the `is-active` styles
- Wrapped all pagination examples in a `<nav>` with an aria-label so users know it's the pagination navigation
- Added `aria-label="page x"` to each of the pages, to be more descriptive about what the number means
- Added `aria-current="page"` to the active pages
Fixes #4256 
- Check nothing has broken on the pagination examples/docs
- Check with voiceover the pagination examples
- Accessibility documentation is currently being written so will be in a separate PR
- The `p-navigation` class should be on the `<nav>` element, but this will be addressed in this [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/4257) …
> Improve accessibility in the pagination component

- templates/docs/examples/patterns/switch.html
- Add `role=switch` to switch component. Without this the screen reader describes this as a checkbox being checked and unchecked. 
- We mention using aria-checked in the description but don't include it in the example. Should we include it as default? https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/switch_role
- Open [demo](https://vanilla-framework-4260.demos.haus/docs/patterns/switch)
- Use VoiceOver and check the switch component. It should read out the label, then the status, then switch. It sounds a little strange with our example but that's because our labels are on and off.
- `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation …
> Add role=switch to switch component

- scss/standalone/patterns_card.scss
- templates/docs/examples/patterns/card/content-bleed.html
- Removed right alignment 
- Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/4175
- Open [demo](https://vanilla-framework-4261.demos.haus)
- See that the `u-align-text--right` has been removed from doc example
- Check that footer is aligned correctly in [examples](https://vanilla-framework-4261.demos.haus/docs/examples/patterns/card/content-bleed) and [patterns](https://vanilla-framework-4261.demos.haus/docs/patterns/card) for all screen sizes …
> Removed right alignment in card example

- package.json
- scss/_patterns_lists.scss
- templates/_layouts/docs.html
- templates/docs/examples/patterns/lists/list-nested-count.html
- templates/docs/patterns/lists.md
- templates/docs/whats-new.md
- Added nested counter to order lists
Fixes #4074 
- Open [docs](https://vanilla-framework-4264.demos.haus/docs/patterns/lists)
- Open "Nested Count" section
- Verify item numbers are displayed correctly
- Open [examples](https://vanilla-framework-4264.demos.haus/docs/examples/patterns/lists/list-nested-count)
- Verify item numbers are displayed correctly …
> Add nested counter to order lists

- .spelling
- templates/docs/examples/patterns/logo-section/logo-section.html
- templates/docs/patterns/logo-section.md
- Removed redundant "logo" from each alt attribute in logo section example
Fixes #4052 
- Open [demo](https://vanilla-framework-4262.demos.haus/docs/patterns/logo-section)
- Check the formatting of the accessibility doc, the content has already been reviewed in the doc
> Logo section accessibility doc

- templates/docs/patterns/labels.md
- Add accessibility notes for labels 
Fixes #4048 
- Open [demo](https://vanilla-framework-4268.demos.haus/docs/patterns/labels)
- Check formatting of accessibility notes on labels. Text has already been reviewed by dev and design. 
> Add label accessibility doc

- scss/_base_code.scss
- scss/_patterns_side-navigation.scss
- templates/docs/examples/patterns/side-navigation/raw-html.html
- Set `display: block` for raw-HTML side nav list text to fix wrapping issue when using the `<code>` tag
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3988
- Open [example demo](https://vanilla-framework-4266.demos.haus/docs/examples/patterns/side-navigation/raw-html)
- Open side nav and make sure everything wraps as expected where `<code>` tag is used …
> Changed display property to fix raw-HTML side nav wrapping

- .spelling
- templates/docs/patterns/pagination.md
- Add [accessibility doc](https://docs.google.com/document/d/1S1Wv8XjYL-q_yLzkmjebjRS1Pqvd4NDLOAyHI7x2Tzk/edit#) for the pagination component
Fixes #4059 
- Open [demo](https://vanilla-framework-4269.demos.haus/docs/patterns/pagination)
- Check the pagination accessibility docs
> Add pagination accessibility docs

- templates/docs/patterns/switch.md
- Add [accessibility doc](https://docs.google.com/document/d/1mvRvpEwtxUQAVRrfMiEgS-QgsWCm4-QsmWFfg6y5NZ0/edit#) to switch component docs
Fixes #4065 
- Open [demo](https://vanilla-framework-4271.demos.haus/docs/patterns/switch)
- Check the accessibility section of the Switch component - the text has already been QA +1'd.
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Relea …
> Add switch accessibility docs

- scss/_patterns_notifications.scss
- Added min height to `.p-notification__close` to fix positioning issue when missing button text
- Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/4034
- Open [demo](https://vanilla-framework-4267.demos.haus)
- Go to patterns > notification > actions > buttons
- Edit on codepen or checkout current branch
- Remove close button text and ensure positioning is unchanged  …
> Added min-height to close button

- templates/docs/patterns/grid.md
- Add accessibility notes for the Grid component - google doc [here](https://docs.google.com/document/d/1cPgsBMHdS0_3fhaLReiN830Ni8uJSNIM-frqvpZTB8E/edit#)
Fixes #4043 
- Open [demo](https://vanilla-framework-4275.demos.haus/docs/patterns/grid)
- Doc text has already been reviewed, just QA on page 
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-t …
> Add grid accessibility notes

- templates/docs/patterns/heading-icon.md
- Added accessibility doc for the heading icon - copy doc [here](https://docs.google.com/document/d/1-pph5kexTYURof_M1WgYbouPUxElhPbubgQq5hbuiXs/edit#)
Fixes #4044 
- Open [demo](https://vanilla-framework-4277.demos.haus)
- The google doc has been reviewed, please just QA the docs on the site
> Add heading icon accessibility docs

- templates/docs/patterns/icons.md
- Add [accessibility doc](https://docs.google.com/document/d/1B3JqDWU25pGuVdmETeM5DCxQog-9aQSciF4_wWPDAaY/edit#heading=h.gd4zn0ids0xg) for icons
Fixes #4045 
- Open [demo](https://vanilla-framework-4286.demos.haus/docs/patterns/icons#accessibility)
- Google doc has had UX and dev +1. Please just review formatting on docs page 
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/ …
> Add icon accessibility docs

- templates/docs/examples/patterns/notifications/action.html
- templates/docs/examples/patterns/notifications/timestamp.html
- templates/docs/patterns/notification.md
- Added notification accessibility docs - google doc [here](https://docs.google.com/document/d/1iw5ZMMzDjnnz3oG1P4wwjj9JYsGOsTPfl6Kzp_H6NoU/edit#)
- Added `aria-controls` attribute to all dismissible example
- Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/4058
- Check that each dismissible notification has the aria-controls attribute on the close button
- QA the accessibility and considerations section of the notification docs  
- if CSS class names …
> Added notification accessibility docs 

- templates/docs/examples/patterns/search-box/navigation-dark.html
- templates/docs/examples/patterns/search-box/navigation.html
- templates/docs/examples/patterns/tabs/navigation.html
- templates/docs/patterns/navigation.md
- Remove mention of navigation in aria-labels to avoid repetition
- Add accessibility docs for navigation
Fixes #4057 
- Open [demo](https://vanilla-framework-4287.demos.haus/docs/patterns/navigation#accessibility)
- Google doc has been reviewed. Check docs page for final QA please
> Add accessibility docs for navigation

- scss/standalone/patterns_empty-state.scss
- templates/docs/examples/patterns/empty-state/no-content.html
- templates/docs/examples/patterns/empty-state/user-triggered.html
- templates/docs/patterns/empty-state.md
Should be merged after https://github.com/canonical-web-and-design/vanilla-framework/pull/4274
-  Variant 2 empty state is added.
Fixes #1010
- Open [second variant of the empty state](https://vanilla-framework-4276.demos.haus/docs/examples/layouts/empty-state/user-triggered)
- Verify its implemented according to [design](https://discourse.ubuntu.com/t/variant-b-user-action-triggers-empty-state/24620)
- Open [docs](https://vanilla-framework-4276.demos.haus/docs/layouts/empty-state#user-action-triggers-empty-state).
- Verify empty state's second variant is documented correctly.
- if …
> Added empty state - Variant 2

- scss/standalone/patterns_empty-state.scss
- templates/docs/examples/patterns/empty-state/error-management.html
- templates/docs/patterns/empty-state.md
Should be merged after https://github.com/canonical-web-and-design/vanilla-framework/pull/4276
-  Variant 3 empty state is added.
Fixes #1010
- Open [third variant of the empty state]( https://vanilla-framework-4279.demos.haus/docs/examples/layouts/empty-state/error-management)
- Verify its implemented according to [design](https://discourse.ubuntu.com/t/variant-c-error-management-empty-state/24621)
- Open [docs]( https://vanilla-framework-4279.demos.haus/docs/layouts/empty-state#error-management-empty-state).
- Verify empty state's third variant is documented correctly.
- if CSS …
> Added empty state - Variant 3

- templates/docs/examples/patterns/search-box/default-dark.html
- templates/docs/examples/patterns/search-box/default.html
- templates/docs/examples/patterns/search-box/navigation-dark.html
- templates/docs/examples/patterns/search-box/navigation.html
- Add labels to inputs
- Add text in icon buttons
Fixes #4280 
- Open [demo](https://vanilla-framework-4291.demos.haus)
- Check the search box examples with VoiceOver, it should be clear what the buttons/inputs are.
> Improve search box accessibility

- templates/_layouts/docs.html
- templates/docs/base/tables.md
- templates/docs/whats-new.md
- Added the new empty state pattern to the Table docs
- Updated the side navigation with correct labels
- Updated what's new 
Fixes #4292 
- Open [demo](https://vanilla-framework-4297.demos.haus/)
- What's new
- Table docs
> Update table docs with empty state

- package.json
- scss/_patterns_pull-quotes.scss
- templates/docs/examples/patterns/pull-quotes/default-image.html
- templates/docs/examples/patterns/pull-quotes/default.html
- templates/docs/examples/patterns/pull-quotes/large.html
- templates/docs/examples/patterns/pull-quotes/small.html
- templates/docs/examples/patterns/pull-quotes/variants.html
- Replace `<cite>` with `<span>` pull-quotes. Semantically, cites should only be used to refer to someone's work, not their name
Fixes #4263 
- Open [demo](https://vanilla-framework-4300.demos.haus/)
- Check there are no visual changes in the pull quote examples
- Check VoiceOver works as expected
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-ta …
> Replace `<cite>` with `<span>` pull-quotes

- Dockerfile
- build.js
- package.json
- templates/_layouts/docs.html
- templates/docs/patterns/notification.md
- templates/static/js/src/demobox/app.tsx
- templates/static/js/src/demobox/components/LiveDemoBox/LiveDemoBox.tsx
- templates/static/js/src/demobox/components/LiveDemoBox/index.ts
- tsconfig.json
- yarn.lock
- Add esbuild for building react components
- Add `react` and `react-dom` packages
- Add TypeScript configuration
- Add a React component as a starting point for the Live Demo Box
- Open [demo](https://vanilla-framework-4312.demos.haus/docs/patterns/notification#live-demo-box)
- Verify that the Live Demo Box react component is rendered (see the screenshot below) …
> Setup tooling to support React

- templates/docs/examples/patterns/notifications/toast.html
- Added notification template that renders HTML based on query parameters in the URL
- Open [demo](https://vanilla-framework-4318.demos.haus/docs/examples/patterns/notifications/toast)
- Add query parameters to the URL -- e.g. https://vanilla-framework-4318.demos.haus/docs/examples/patterns/notifications/toast?type=caution&style=inline&actions=true&dismiss=true&timestamp=true
- Verify that the example changes based on the given query parameters
- if CSS class names are changed/added/removed it should be minor …
> Use query parameters to change notification example

- templates/_class-references/notification.html
- templates/_class-references/side-navigation.html
- templates/docs/patterns/notification.md
- added JS functionality docs to Notifications
- added related components to Notifications docs
- added class reference to Notifications docs
Fixes canonical-web-and-design/vanilla-squad#1197
- Open [demo](https://vanilla-framework-4333.demos.haus/docs/patterns/notification)
- https://vanilla-framework-4333.demos.haus/docs/patterns/notification
- Check if class reference, JS functionality and related components section are all good
> Add new sections to Notification docs

- templates/docs/base/code.md
- templates/docs/examples/patterns/code-snippet/codeSnippet.html
- templates/docs/examples/patterns/code-snippet/codeSnippet.json
- templates/docs/examples/patterns/code-snippet/example.py
- templates/docs/examples/patterns/code-snippet/example.sh
- templates/docs/examples/patterns/code-snippet/example.yaml
- templates/docs/examples/patterns/notifications/toast.json
- templates/docs/patterns/notification.md
- templates/static/js/src/demobox/app.tsx
- templates/static/js/src/demobox/components/LiveDemoBox/LiveDemoBox.tsx
- templates/static/js/src/demobox/components/LiveDemoBox/Switch.tsx
- Construct URL depending on state
- Create `Codesnippet.json`
- Display select/switch components and live demo box
- Disable theme 
Fixes [#1206](https://github.com/canonical-web-and-design/vanilla-squad/issues/1206)
- Open [demo](https://vanilla-framework-4332.demos.haus/docs/base/code)
- Check the initial default "Default" example loads as expected 
- Check the "theme" select is disabled
- Change values of all selects/switches and check the example works as expected  …
> Add live demo box for Code Snippet 

- package.json
- templates/docs/examples/patterns/code-snippet/codeSnippet.html
- templates/docs/examples/patterns/notifications/toast.html
- templates/static/js/src/demobox/app.tsx
- templates/static/js/src/demobox/components/LiveDemoBox/Code.tsx
- templates/static/js/src/demobox/components/LiveDemoBox/LiveDemoBox.tsx
- templates/static/js/src/demobox/hooks/useCode.ts
- templates/static/js/src/demobox/utils/code.ts
- yarn.lock
- Add component to display example code
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/4320
- Open [demo](https://vanilla-framework-4321.demos.haus/docs/patterns/notification)
- Verify that the code is updated when different options are selected
> Add component to display example code

- templates/_layouts/docs.html
- templates/docs/examples/patterns/code-snippet/codeSnippet.html
- templates/static/js/src/demobox/components/LiveDemoBox/Code.tsx
- templates/static/js/src/demobox/components/LiveDemoBox/LiveDemoBox.tsx
- Added a button that, when clicked, opens the rendered example in a new tab
- Update some styling
- Open [demo](https://vanilla-framework-4340.demos.haus/docs/base/code)
- Click the button below the rendered example and verify that it opens in a new tab
> Add fullscreen button for demo box

- scss/_patterns_side-navigation.scss
Fixes color of visited links in dark themed side-nav
Fixes #4341 
- Open [demo](https://vanilla-framework-4342.demos.haus/docs/examples/patterns/side-navigation/dark)
- Click some links in dark theme side nav and make sure visited links don't change color
- https://vanilla-framework-4342.demos.haus/docs/examples/patterns/side-navigation/dark
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla- …
> Fix visited links in dark side navigation

- templates/docs/patterns/strip.md
Added the[ accessibility doc](https://docs.google.com/document/d/1cEkDcilw5irLRLEqkJcozx_-WORdm3Ihu4dPtg8mO2o/edit#) to the website for Strips
Fixes #4316 
- Open [demo](https://vanilla-framework-4358.demos.haus/docs/patterns/strip) of Strip doc
- Check the formatting of the accessibility doc. The text has already been reviewed by UX and Dev
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla- …
> Add accessibility docs for strip

- templates/docs/examples/patterns/contextual-menu/_script.js
- Close contextual menu when the focus leaves
Fixes #4284 
- Open [demo](https://vanilla-framework-4359.demos.haus/docs/patterns/contextual-menu)
- Open the "Take action" contextual menu
- Tab through the dropdown, check when the focus leaves the menu it closes
- Compare this to [live](https://vanillaframework.io/docs/patterns/contextual-menu). See how the menu remains open after the focus leaves. …
> Close contextual menu when focus leaves

- templates/_layouts/_footer.html
- templates/_layouts/_header.html
- templates/_layouts/docs.html
- templates/docs/examples/layouts/documentation.html
- templates/docs/examples/layouts/sticky-footer.html
- templates/docs/examples/patterns/links/links-skip.html
- templates/docs/examples/patterns/navigation/default-dark.html
- templates/docs/examples/patterns/navigation/default.html
- templates/docs/examples/patterns/navigation/dropdown-dark.html
- templates/docs/examples/patterns/navigation/full-width.html
- templates/docs/examples/patterns/navigation/search-dark.html
- templates/docs/examples/patterns/navigation/search-light.html
- templates/docs/examples/patterns/side-navigation/_default.html
- templates/docs/examples/patterns/side-navigation/_docs.html
- templates/docs/examples/patterns/side-navigation/_layout-JAAS.html
- templates/docs/examples/patterns/side-navigation/_layout-application.html
- templates/docs/examples/templates/maas-docs-grid.html
- templates/docs/examples/templates/maas-layout.html
- templates/docs/examples/templates/snapcraft-publicise.html
- templates/docs/examples/templates/z-index.html
- Removed the word "navigation" from all `aria-label`'s on `<nav>` elements, to fix duplication with screen readers. 
- Checked all `<header>` and `<main>` tags too
Fixes #4133 
- Open [demo](https://vanilla-framework-4361.demos.haus/)
- Use VoiceOver on the navigation landmarks such as pagination or side navigation to check duplication has been removed
- Check out this PR, in VsCode search for `navigation"` and there should be no more instances of the word navigation in nav elements …
> Update aria-labels on landmarks

- scss/_patterns_navigation.scss
- templates/docs/examples/patterns/navigation/deprecated.html
- Update deprecated example to include more features
- Adjust the size of the top nav bar from `3.5rem` to `3rem` on small screens as per [design](https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?node-id=0%3A1832)
- Make the highlight the same as text instead of ubuntu orange
Fixes #4383 
- Open [demo](https://vanilla-framework-4386.demos.haus/)
- Go to the Navigation deprecated example and check they work as expected
- Check the highlight colour of the top nav is correct on light and dark themes
- Check on mobile the height of the top nav is correct (3rem) …
> Make top nav adjustments (size and highlight colour)

- templates/docs/base/typography.md
- templates/docs/patterns/breadcrumbs.md
- templates/docs/patterns/heading-icon.md
- templates/docs/patterns/images.md
- templates/docs/patterns/list-tree.md
- templates/docs/patterns/matrix.md
- templates/docs/patterns/media-object.md
- templates/docs/patterns/muted-heading.md
- templates/docs/patterns/pull-quote.md
- templates/docs/patterns/switch.md
- templates/docs/patterns/table-of-contents.md
- templates/docs/settings/animation-settings.md
- templates/docs/settings/color-settings.md
- templates/docs/settings/font-settings.md
- templates/docs/utilities/image-position.md
- Remove the design section from the component docs pages
Fixes [#1312](https://github.com/canonical-web-and-design/vanilla-squad/issues/1312)
- Open [demo](https://github.com/canonical-web-and-design/vanilla-squad/issues/1312)
- Check there is no "Design" section on any of the docs pages
> Remove design section from docs

- templates/_layouts/_header.html
- templates/docs/examples/patterns/navigation/search-dark.html
- templates/docs/examples/patterns/navigation/search-light.html
- templates/static/js/scripts.js
Update Vanilla website to new mobile search dropdown
Drive-by: fix wrongly nested HTML in the search examples
- Open [demo](https://vanilla-framework-4408.demos.haus/)
- make sure vanilla docs website uses new search dropdown on mobile
> Update Vanilla website to new mobile search dropdown 

- templates/_layouts/docs.html
Make sure side nav in Vanilla docs only shows latest relevant status labels.
- Open [demo](https://vanilla-framework-4409.demos.haus/docs)
- Make sure docs side nav only shows relevant status labels (compare with what's new table)
> Update side nav for 3.2

- templates/_layouts/docs.html
- templates/docs/patterns/tab-buttons.md
- templates/docs/patterns/tabs.md
- Separate Tab buttons from tabs
- I didn't include the accessibility docs for now as we might need to take a look at the [spec](https://discourse.ubuntu.com/t/segmented-control/26835) for segmental control and check what applies
- NOTE: Renaming will be done in a separate PR 
Fixes [#1310](https://github.com/canonical-web-and-design/vanilla-squad/issues/1310)
- Open [demo](https://vanilla-framework-4401.demos.haus/docs/patterns/tab-buttons)
- Check the content in the tab buttons docs page makes sense 
- if …
> Separate Tab buttons from tabs

- templates/_class-references/code-snippet.html
- templates/docs/base/code.md
Adds class reference and JavaScript sections to code snippet.
Fixes canonical-web-and-design/vanilla-squad#1198
- Class reference https://vanilla-framework-4415.demos.haus/docs/base/code#class-reference
- JavaScript functionality https://vanilla-framework-4415.demos.haus/docs/base/code#javascript-functionality
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla- …
> Update Code snippet docs

- guides/pull-requests.md
- scss/_patterns_status-label.scss
- templates/_layouts/docs.html
- templates/docs/changelog-v2.md
- templates/docs/examples/patterns/labels.html
- templates/docs/examples/patterns/lists/lists-inline-stretch-align.html
- templates/docs/examples/patterns/side-navigation/_default.html
- templates/docs/examples/patterns/side-navigation/_docs.html
- templates/docs/examples/patterns/side-navigation/_icons.html
- templates/docs/examples/patterns/side-navigation/_layout-JAAS.html
- templates/docs/examples/patterns/side-navigation/_layout-application.html
- templates/docs/examples/patterns/side-navigation/icons.html
- templates/docs/migration-guide-to-v3.md
- templates/docs/patterns/navigation.md
- templates/docs/whats-new.md
- Bring `vf-p-label` mixin back due to compatibility reasons
- Flag the label component as deprecated in the examples section
- Add a notification in the migration to 3.0 guide
- Rename `p-label` to `p-status-label` in the markup
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/4411
> Deprecate label pattern

- scss/_patterns_accordion.scss
~~- Add a media query to change the alignment of the icon when next to a heading, so we use a different line-height to calculate the icon's position depending on the screen size.~~
Update the styling of the accordion.
Fixes #4418 
- Open demo
- Go to the example with headings (https://vanilla-framework-4424.demos.haus/docs/examples/patterns/accordion/headings) and check that the icon looks aligned no matter the screen size. (The problem we had was that the icon was misaligned in small screens).
- if CSS class …
> Align accordion's icon with heading

- templates/static/js/example.js
- Add a fix scroll function to ensure the codepen loading doesn't move the title out of view
Fixes #3017 
- Open [demo](https://vanilla-framework-4432.demos.haus/docs/patterns/navigation#side-navigation)
- Check that the "Side navigation" title is in view. 
- Compare to [main](https://vanillaframework.io/docs/patterns/navigation#side-navigation)
> Fix page jumping after codepen loads

- templates/_layouts/docs.html
- templates/docs/whats-new.md
Fix inconsistencies in what's new table
- Open [demo](https://vanilla-framework-4441.demos.haus/)
- Check what's new table and side nav are consistent with correct labels
> Update "What's new" table

- component_tabs.yaml
- templates/docs/patterns/pull-quote/accessibility.md
- templates/docs/patterns/pull-quote/index.md
- Add accessibility notes to quotes
- Update content to include tabs
Fixes [#1352](https://github.com/canonical-web-and-design/vanilla-squad/issues/1352)
- Open [demo](https://vanilla-framework-4443.demos.haus/docs/patterns/pull-quote)
- Check the tabs work as expected
- The accessibility text has already been reviewed so this is only a QA of them on the site …
> Add accessibility doc for quotes

- component_tabs.yaml
- templates/docs/patterns/contextual-menu/accessibility.md
- templates/docs/patterns/contextual-menu/index.md
- Add [accessibility doc](https://docs.google.com/document/d/1uRHo5Jp034T31E18IuTSdgpzLaF77lOFGHzn7U49hqk/edit?pli=1) for contextual menu component
Fixes #4042 
- Open [demo](https://vanilla-framework-4450.demos.haus/docs)
- Go to contextual menu component
- Contextual menu
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-re …
> Add contextual menu accessibility docs

- templates/docs/examples/patterns/tooltips/_tooltips_script.js
- Ensured the detached tooltip stays open on click of the trigger, and closes when escape is pressed or the user clicks outside or on the trigger
Fixes #4412 
- Open [demo](https://vanilla-framework-4454.demos.haus/docs/examples/patterns/tooltips/detached)
- Hover/focus over the detached tooltip and check the functionality is still the same
- Click on the tooltip and move the mouse away. The tooltip should remain open
- Now press escape and check the tooltip closes
- Do the same again but click outside instead of pressing escape - the tooltip should close.  …
> Add functionality to keep tooltip open on click

- package.json
- scss/_patterns_pagination.scss
- templates/_layouts/docs.html
- templates/docs/examples/patterns/pagination/pagination-deprecated.html
- templates/docs/examples/patterns/pagination/pagination-disabled.html
- templates/docs/examples/patterns/pagination/pagination-truncated.html
- templates/docs/examples/patterns/pagination/pagination-verbose.html
- templates/docs/examples/patterns/pagination/pagination.html
- templates/docs/patterns/pagination/index.md
- templates/docs/whats-new.md
- Move `p-pagination` classname to the `<nav>` element
- Add new `p-pagination__items` class name to the `<ol>` element. 
It seems the styles can be applied to both class names and nothing breaks on old and new structure... 
Fixes #4257 
- Open [demo](https://vanilla-framework-4451.demos.haus)
- Check all examples of Pagination component. Update the HTML in the browser to the older structure to check it's backwards compatible
- What's new table
- Side nav in docs should be updated …
> Update classnames in Pagination component

- templates/docs/examples/patterns/navigation/default-dark.html
- templates/docs/examples/patterns/navigation/default.html
- templates/docs/examples/patterns/navigation/dropdown-dark.html
- templates/docs/examples/patterns/navigation/dropdown.html
- templates/docs/examples/patterns/navigation/full-width.html
- templates/docs/examples/patterns/navigation/search-dark.html
- templates/docs/examples/patterns/navigation/search-light.html
Replaces "Canonical" brand name in new logo examples to Ubuntu, as this is the only one officially published.
- Open [demo](https://vanilla-framework-4468.demos.haus/docs/patterns/navigation)
- Make sure navigation examples show "Ubuntu" name in logo
> Update brand name in navigation example logos

- package.json
- scss/_patterns_side-navigation.scss
- templates/_layouts/docs.html
- templates/docs/examples/patterns/side-navigation/_default.html
- templates/docs/examples/patterns/side-navigation/_docs.html
- templates/docs/examples/patterns/side-navigation/_icons.html
- templates/docs/patterns/navigation/index.md
- templates/docs/whats-new.md
Adds new `p-side-navigation__heading` class (with a `--linked` variant) to be used in docs to provide headings for side navigation item groups.
Drive by: Fixes an issue with too small embedded examples for side nav components
Fixes #4485 
- Open [demo](https://vanilla-framework-4487.demos.haus/docs/examples/patterns/side-navigation/docs)
- Check if side navigation headings look as expected
- Make sure it works in all variants:
- https://vanilla-framework-4487.demos.haus/docs/examples/patterns/side-navigation/default
- https://vanilla-framework-4487.demos.haus/docs/examples/patterns/side-navigation/dark
- `Feature 🎁`, `Breaking …
> Add heading styles for side navigation

- templates/static/js/scripts.js
Closes side navigation when in-page anchors are clicked
Fixes #4484 
- Open [demo](https://vanilla-framework-4489.demos.haus/docs)
- Visit any Vanilla docs page on small screen
- Open the side navigation
- Click on any anchor link to a heading on the current page
- Side nav should close and page should be scrolled to correct position
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framewor …
> Close side nav drawer when anchors are clicked

- package.json
- scss/_patterns_navigation.scss
Fix the font size to the one of a H4 on large screens
Fixes #4460
- resize the window
- the font size should remain the same
> Fix the logo title to a specific font size

- package.json
- scss/_patterns_lists.scss
- Changed middot's position to relative
- Updated the right margin of the middot list item
Fixes #4429 
- Reduce browser width to ~280px
- Verify dots are displayed correctly
> Updated middot list style

- package.json
- scss/_patterns_side-navigation.scss
- templates/docs/examples/patterns/side-navigation/_default.html
- templates/docs/examples/patterns/side-navigation/_icons.html
Fixes font weight and indent of the items nested under the title items.
Fixes #4490 
- Open [demo](https://vanilla-framework-4501.demos.haus/docs/examples/patterns/side-navigation/default)
- Make sure that when parent element is a bolded title, its children are not bolded and are properly indented
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-ta …
> Fix nesting and font weight when parent is a title

- templates/docs/examples/patterns/badge/chips.html
- templates/docs/examples/patterns/badge/colors.html
- templates/docs/examples/patterns/badge/default.html
- templates/docs/examples/patterns/badge/side-navigation.html
- templates/docs/examples/patterns/badge/tabs.html
- templates/docs/patterns/badge/accessibility.md
- Added items to badge's accessibility doc.
- Added "aria-label" to the examples
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/1405
- Open [badge examples](https://vanilla-framework-4503.demos.haus/docs/examples)
- Verify "aria-label" attribute is added to the examples
- Open [accessibility doc](https://vanilla-framework-4503.demos.haus/docs/patterns/badge/accessibility)
- Verify accessibility page is updated.
> Badge accessibility

- package.json
- scss/_patterns_accordion.scss
- templates/docs/examples/patterns/accordion/_script.js
- add a transition to the accordion pattern
Fixes https://github.com/canonical/vanilla-framework/issues/4539
- Open https://vanilla-framework-4542.demos.haus//docs/examples/patterns/accordion/default
- Verify the accordion works as before with the addition of having a transition on expand.
> feat: accordion transition

- package.json
- scss/_base_button.scss
- scss/_layouts_application.scss
- scss/_patterns_accordion.scss
- scss/_patterns_chip.scss
- scss/_patterns_form-tick-elements.scss
- scss/_patterns_navigation.scss
- scss/_patterns_search-and-filter.scss
- scss/_patterns_side-navigation.scss
- scss/_patterns_switch.scss
- scss/_patterns_tabs.scss
- scss/_settings_animations.scss
- templates/_layouts/docs.html
- templates/docs/settings/animation-settings.md
- templates/docs/whats-new.md
- Rename vf-animation to vf-transition
- add vf-animation alias
Fixes #4543
> Rename vf-animation to vf-transition

- package.json
- scss/_patterns_lists.scss
- scss/standalone/patterns_lists-heading-classes.scss
- templates/docs/examples/patterns/lists/lists-stepped-heading-classes.html
- fix: stepped list heading levels via modifier class (`.p-heading--n`)
Fixes #4544
- Open [[demo](https://vanilla-framework-4546.demos.haus/docs/examples/patterns/lists/lists-stepped-heading-classes)](https://vanilla-framework-4546.demos.haus/docs/examples/patterns/lists/lists-stepped-heading-classes)
- ensure the styling is correct
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release- …
> fix: stepped list heading levels 

- scss/_layouts_application.scss
- scss/_patterns_accordion.scss
- scss/_settings_animations.scss
- Update accordion to use the new `vf-transition` syntax
- Make vf-transition require a string
- Automatically escape the property string
[if relevant, include a screenshot or screen …
> Update accordion vf-transition syntax

- cypress/e2e/patterns/accordion.cy.js
- scss/_patterns_accordion.scss
- templates/docs/examples/patterns/accordion/default.html
- templates/docs/examples/patterns/accordion/headings.html
- Update accordion docs to not imply navigation
Fixes #4547
- Open https://vanilla-framework-4549.demos.haus/docs/patterns/accordion
> Update accordion docs to not imply navigation

- scss/_patterns_navigation.scss
New nav logo padding does not align with content #4530
Fixes https://github.com/canonical/vanilla-framework/issues/4530
Added col-12 with a black background to the examples below to …
> New nav logo padding does not align with content #4530

- package.json
- scss/_utilities_off-screen.scss
- fix u-off-screen utility class
Fixes https://github.com/canonical/vanilla-framework/issues/4535
- Open [maas-ui demo with vanilla build based on this PR](https://maas-ui-4364.demos.haus/ ) https://github.com/canonical/maas-ui/pull/4364/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R69
- login
- verify no white line is shown when scrolling to the very bottom in Firefox …
> Fix .u-off-screen utility adding white line on Firefox

- scss/_settings_breakpoints.scss
- templates/docs/migration-guide-to-v3.md
- templates/docs/settings/breakpoint-settings.md
Signed-off-by: David Edler <david.edler@canonical.com>
Change default breakpoint for navigation from small to large
- **Note**: version was updated to 3.8.0 before, which is not yet released.
> Change default breakpoint for navigation to large

- templates/docs/examples/patterns/navigation/_script.js
Signed-off-by: David Edler <david.edler@canonical.com>
Fix navigation: An open dropdown should be closed on click of toggle item.
Dropdown would always stay open before, no matter how often you click on the toggle.
> Fix navigation: close open dropdown on click of toggle item.

- package.json
- scss/_utilities_hide.scss
- Fix u-hide--large hiding tds and ths on medium screens.
Fixes: #4589.
- Open [the mobile table card](https://vanilla-framework-4590.demos.haus/docs/examples/patterns/tables/table-mobile-card)
- Inspect one of the table cells and add `class="u-hide--large"`.
- With your window at full size the cell should be hidden.
- Resize your window to medium and small sizes and the cell should be visible. …
> Fix u-hide--large on table cells on medium screens.

- scss/_patterns_slider.scss
- templates/docs/examples/patterns/slider/slider-input.html
- Remove slider input height to make it the same height as standard inputs.
Fixes: #3163.
- Open the [input demo](https://vanilla-framework-4575.demos.haus/docs/examples/base/forms/input)
- inspect the input and take note of the height.
- Open [slider demo](https://vanilla-framework-4575.demos.haus/docs/examples/patterns/slider/slider-input)
- Inspect the number input and check that it is the same height as the previous input. …
> Fix slider input height

- guides/hacking.md
- guides/release-process.md
- templates/contribute.html
- Replace ./run instructions with dotrun
Fixes: #4576.
n/a
> Update hacking to dotrun

- scss/_patterns_form-password-toggle.scss
- Improve the legibility of readonly passwords that have been displayed via the password toggle component.
Fixes #3975.
- Open the [password toggle example](https://vanilla-framework-4591.demos.haus/docs/examples/patterns/forms/password-toggle)
- Inspect one of the inputs and add `readonly` to the input element.
- You should see the dots in the password field become light grey.
- Click the show button and the password should be displayed and the text should be the same as the default text colour.
- if CSS …
> Make password text easier to read when toggled

- scss/_patterns_lists.scss
- Update stepped lists to use a fixed font size for the counters.
Fixes #4561.
- Open all the list examples:
- https://vanilla-framework-4584.demos.haus/docs/examples/patterns/lists/lists-stepped
- https://vanilla-framework-4584.demos.haus/docs/examples/patterns/lists/lists-stepped-without-headings
- https://vanilla-framework-4584.demos.haus/docs/examples/patterns/lists/lists-stepped-heading-classes
- https://vanilla-framework-4584.demos.haus/docs/examples/patterns/lists/lists-stepped-detailed
- Check that the font size is always the same.
- if CSS class names are not changed it can …
> Stepped counter size

- templates/_layouts/_header.html
- Reverted the changes made in [this PR](https://github.com/canonical/vanilla-framework/pull/4407)
- Open [demo](https://vanilla-framework-4601.demos.haus/)
- See that the logo looks as expected 
> Revert to new logo style

- scss/_patterns_lists.scss
- Fixed warning regarding depreciated use of the division operator 
- Run the site and see that you do not get the above error on your terminal
- See that site runs as expected
> Fix warning for division operator

- package.json
- scss/_base_grid-definitions.scss
- scss/_patterns_grid.scss
- Removed `-  1` from media queries
Fixes  #4592
- Open [demo](https://vanilla-framework-4597.demos.haus/docs/examples/patterns/grid/responsive)
- See that the grid behaves as expected
> Fix responsive grid bug

- package.json
- scss/_patterns_navigation.scss
- Adjusted the logo and logo tag height and width values to match the design :
Fixes https://github.com/canonical/vanilla-framework/issues/4585
- Open [demo](https://vanilla-framework-4598.demos.haus/docs/examples/patterns/navigation/default#)
- Inspect the logo and logo tag and see that they match the above specifications  …
> Fix logo and logo tag height and width values

- scss/_base_links.scss
Updates the style of link hover
Fixes #4600
- Open [demo](https://vanilla-framework-4603.demos.haus/)
- Hover over links and see if the updated style is as expected
> Update the underline style of links on hover

- package.json
- scss/_patterns_form-tick-elements.scss
Added hover state for checkboxes
Fixes https://warthogs.atlassian.net/browse/WD-888
I didn't manage to target the indeterminate state for the checkbox so it looks broken at the moment. If anyone can help!
- Open [demo](https://vanilla-framework-4615.demos.haus/docs/examples/patterns/forms/tick-variants)
- hover over the checkboxes and radio buttons …
> Add hover states for checkboxes

- scss/_patterns_modal.scss
Very small change to let the modal overlay the navigation drawer (`z-index: 103`), by increasing its `z-index` from 101 to 104.
Before:
After:
> Increase z-index of the modal so that it overlays the navigation drawer

- .github/workflows/publish-on-release.yml
- scripts/upload_assets.py
This fixes issues with uploading assets to asset server when we release Vanilla.
Let's not merge it for now, but when we will need to next release Vanilla, and uploading to assets server is not fixed yet, we could merge this to be able to release.
- just code review… we won't know if it works until we run it in GH actions…
> Temporary script to fix the upload assets job

- package.json
- scss/_layouts_application.scss
- fix:  remove collapsed side panel from accessibility tree
- set .l-aside .is-collapsed visibility to hidden
Fixes: https://github.com/canonical/vanilla-framework/issues/4629
- Open [demo](https://vanilla-framework-4628.demos.haus/docs/layouts/application)
- Verify that collapsed side panel contents are hidden for accessibility APIs (you can check that in Chrome devtools accessibility tab and verify that the elements are ignored) …
> fix: remove collapsed side panel from accessibility tree

- templates/accessibility.html
* Fixed the 404 link from the Accessibility page under "Chrome Accessibility Developer Tools" to a new one.
> Fix link for Chrome Accessibility Developer Tools

- package.json
- scss/_layouts_application.scss
- scss/_layouts_full-width.scss
- scss/docs/site.scss
- templates/_layouts/_footer.html
- templates/_layouts/_header.html
- templates/_layouts/docs.html
- templates/accessibility.html
- templates/browser-support.html
- templates/contribute.html
- templates/docs/examples/index.html
- templates/docs/examples/standalone.html
- templates/index.html
- updates Vanilla site to use new full width layout
- small SCSS fixes for the layout
Fixes [WD-778](https://warthogs.atlassian.net/browse/WD-778)
- Open [demo](https://vanilla-framework-4650.demos.haus/)
- Make sure the site works as expected
- check all the pages from top nav
- check documentation section with side navigation
- check search
- verify pages on different screen sizes …
> WD-778 Use new full width layout on Vanilla site

- package.json
- scss/_utilities_off-screen.scss
Updated the `u-off-screen` utility to reflect the recommend standard as recommended here: https://www.tpgi.com/the-anatomy-of-visually-hidden/
- Go to https://vanilla-framework-4639.demos.haus/docs/examples/utilities/off-screen
- Check that the `u-off-screen` example still hides the content
- https://vanilla-framework-4639.demos.haus/docs/utilities/off-screen …
> Update u-off-screen utility

- .github/workflows/publish-on-release.yml
Now that new version of `upload-assets` have been released we can revert our temporary fix.
> Bring back upload-assets CLI tool for release

- templates/_layouts/docs.html
- templates/docs/examples/layouts/full-width/default.html
- templates/docs/examples/layouts/full-width/structure.html
- templates/docs/layouts/full-width.md
- templates/docs/whats-new.md
Adds documentation page for new full-width layout
Fixes WD-777
- Open [demo](https://vanilla-framework-4655.demos.haus/docs/layouts/full-width)
- Review the documentation and examples
> WD-777 Add full-width layout documentation

- scss/_base_typography-definitions.scss
- scss/_patterns_navigation.scss
- scss/_settings_font.scss
Update font weight of top navigation items.
Fixes #4634
- Open [demo](https://vanilla-framework-4658.demos.haus/)
- Check if top nav has correct font weight
> Update top nav font weight

- scss/_utilities_layout.scss
- templates/docs/examples/utilities/fixed-width-container-nesting.html
Fixes #4641
Fixes padding on rows nested inside fixed width container, adds an example to help catch up any regressions around that in future.
- Open [demo](/docs/examples/utilities/fixed-width-container-nesting)
- Make sure nested rows and fixed width containers don't have additional padding
> Fix nesting row in fixed width container

- scss/_base_fontfaces.scss
- scss/_base_typography-definitions.scss
- scss/_base_typography.scss
Use the latest (0.864) beta of the Ubuntu Variable font, which now includes true small caps.
- Open [demo](https://vanilla-framework-4648.demos.haus/docs/examples/base/table)
- Check the table erxamples, see that the headings use true small caps instead of the previous faux small caps.
> Update font files and use small caps in table headers

- scss/_base_hr.scss
Fix wrongly calculated bottom margin of hr.
Fixes #4659 
- Open [demo](https://vanilla-framework-4660.demos.haus/docs/examples/base/hr)
- Make sure bottom margin is correctly offset by 1px (width of the hr)
> Fix the calculation of hr margin

- .github/workflows/publish-on-release.yml
Fix missing secret in asset upload step of release process…
- Review code
- compare with how it looked initially: https://github.com/canonical/vanilla-framework/blob/29d0e0914ad2a616cd053d4a254f0ed756c336fd/.github/workflows/publish-on-release.yml
-  keep fingers crossed until next release…
> Add missing secret for upload-assets snap

- package.json
- redirects.yaml
- scss/_base_typography-definitions.scss
- scss/_base_typography.scss
- scss/_patterns_muted-heading.scss
- templates/docs/base/typography.md
- templates/docs/examples/patterns/text-small-caps.html
- templates/docs/examples/patterns/x-small-capitalised.html
- templates/docs/examples/utilities/align-by-baseline.html
- templates/docs/whats-new.md
- Make sure small caps text always has correct font size.
- Make sure muted heading uses new small caps style.
- Rename `p-text--x-small-capitalised` to `p-text--small-caps`.
- Deprecate old name (comments in the code and documentation).
- Fix the `u-align-text--x-small-to-default` usage on new style of small caps
Fixes #4662 #4664 
Demo: 
- Open [demo](https://vanilla-framework-4665.demos.haus/docs/examples/patterns/text-small-caps)
- make sure it looks ok
- change the element to header (like h2) and make sure the font size is not affected
- add `u-align-text--x-small-to-default` and make sure the style is not affected
- Make sure muted heading uses same small caps style:
- https://vanilla-framework-4665.demos.haus/docs/examples/patterns/headings/muted
- …
> Fix font size of all caps text component

- scss/_patterns_search-and-filter.scss
Set white background for search and filter dropdown.
Fixes https://github.com/canonical/vanilla-framework/issues/4654
- Open [demo](https://vanilla-framework-4671.demos.haus/)
- Go to '[search and filter documentation](https://vanilla-framework-4671.demos.haus/docs/patterns/search-and-filter)'
- Click on the search and filter input
- Dropdown opens
- Dropdown background is now white …
> Set white background for search and filter dropdown [WD-2279]

- templates/_layouts/docs.html
- templates/docs/layouts/application.md
- templates/docs/settings/color-settings.md
Fixes a couple of typos in docs pages.
- Two typos in Application Layout docs page (pabel -> panel)
- Wrong hex code for `color-mid-light` in Color docs page.
- Open [demo](https://vanilla-framework-4670.demos.haus/)
- [/docs/layouts/application](https://vanilla-framework-4670.demos.haus/docs/layouts/application)
- [/docs/settings/color-settings](https://vanilla-framework-4670.demos.haus/docs/settings/color-settings)
- if CSS class names are changed/added/removed it should be …
> Fixed hex code for color-mid-light + a couple of typos

- templates/docs/whats-new.md
Fixed "what's new" page with reverted version 3.12.
- Open [demo](https://vanilla-framework-4673.demos.haus/docs/whats-new)
- Make sure last version is 3.12 and all 3.12 changes are correctly listed in top table.
> Revert What's new page to 3.12 release

- scss/_patterns_article-pagination.scss
- change article pagination chevrons to dedicated icon
Fixes #4604
- Open [demo](https://vanilla-framework-4669.demos.haus/docs/examples/patterns/article-pagination)
- Make sure it uses chevron icons instead of text.
- before
- after
> Use chevron icon in article pagination

- webapp/app.py
Removed highlight of side nav items on the search results page.
Fixes https://github.com/canonical/vanilla-framework/issues/4486
- Open [an example search page](https://vanilla-framework-4682.demos.haus/docs/search?q=tooltip).
- Check that no item is selected in  side nav.
> Removed highlight of side nav items on search results page [WD-2276]

- releases.yml
- scss/_utilities_has-icon.scss
- scss/_vanilla.scss
- templates/_layouts/docs.html
- templates/docs/examples/utilities/text-with-icon.html
- templates/docs/utilities/has-icon.md
Added `u-has-icon` utility class.
Fixes https://github.com/canonical/vanilla-framework/issues/3102
- Open [example](https://vanilla-framework-4677.demos.haus/docs/examples/utilities/text-with-icon)
- Check spacing between icon and text.
- Review new documentation:
- [Has-icon](https://vanilla-framework-4677.demos.haus/docs/utilities/has-icon) …
> Add u-has-icon utility class [WD-2275]

- package.json
- scss/_patterns_lists.scss
- scss/standalone/patterns_lists.scss
- templates/docs/examples/patterns/lists/lists-stepped-dark.html
Fixed issue of numbers not being displayed correctly on stepped lists
Fixes #4656 
- Open [demo](https://vanilla-framework-4674.demos.haus/docs/examples/patterns/lists/lists-stepped-dark)
- The numbers in the title should be white over a dark background
- No update in new classnames 
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-release …
> Fix stepped list in dark mode didn't show numbers

- templates/index.html
Fix the social links section at the bottom of the index page where inline styles were causing a bug.
- Check that the twitter and github logos look ok at the bottom
I tried to used the default icon size of `1.5rem` which makes the icons bigger than they used to 
We could also …
> Fix icon override on the main page

- side-navigation.yaml
This must have got lost in conflicts when navigation was refactored.
- Open [demo](https://vanilla-framework-4700.demos.haus/docs)
- Make sure link to "Text with icon" util is in the navigation, marked as "new"
> Add missing page to side navigation

- templates/docs/examples/patterns/segmented-control/default.html
- templates/docs/examples/patterns/segmented-control/dense.html
- templates/docs/examples/patterns/segmented-control/icons.html
- templates/docs/examples/patterns/tab-buttons/default.html
- templates/docs/examples/patterns/tab-buttons/dense.html
- templates/docs/examples/patterns/tab-buttons/icons.html
- templates/docs/examples/patterns/tabs/content.html
Fixes incorrect aria-label on tabs examples
- Go to /docs/patterns/tabs
- See that the aria-label for the charmhub panel is "charmhub" and not "complex"
> Fixes incorrect aria-label on tabs examples

- package.json
- scss/_patterns_navigation.scss
- tests/parker.js
- Update the style of the navigation on smaller screens to match the new designs on figma.
- Open the [examples page](https://vanilla-framework-4706.demos.haus/docs/examples/)
- Select any of the `navigation` variants/examples under the components column.
- Compare with the [figma designs](https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?node-id=1323%3A3714&t=bHZJdx7PhdV9tjc1-0)
- [WD-2615](https://warthogs.atlassian.net/browse/WD-2615) …
> Update mobile nav to match new design

- package.json
- scss/_patterns_lists.scss
- templates/docs/examples/patterns/lists/lists-dividers-all-wrapping.html
- tests/parker.js
Fix long list elements wrapping under the prefix (bullet, tick, etc.)
Fixes https://github.com/canonical/vanilla-framework/issues/4696
- Open https://vanilla-framework-4702.demos.haus/docs/examples/patterns/lists/lists-dividers-all-wrapping
- check that all is well
> Fix lists wrapping under the prefix

- package.json
- releases.yml
- scss/_settings_spacing.scss
- scss/_utilities_vertical-spacing.scss
- templates/docs/examples/utilities/vertical-spacing-unit.html
- templates/docs/examples/utilities/vertical-spacing.html
- templates/docs/utilities/vertical-spacing.md
- Added common spacing classes to be used between elements.
Fixes [WD-2884](https://warthogs.atlassian.net/browse/WD-2884)
- Open [demo](https://vanilla-framework-4714.demos.haus/docs/examples/utilities/vertical-spacing-common)
- Check the new example page
- Review [updated documentation](https://vanilla-framework-4714.demos.haus/docs/utilities/vertical-spacing) …
> Add unified spacing utils

- scss/_patterns_lists.scss
- templates/docs/examples/patterns/lists/lists-split.html
Fix long split list items overflowing in the second column.
Added an example of long list item to catch the regression
Fixes https://github.com/canonical/vanilla-framework/issues/4719
- Open [demo](https://vanilla-framework-4722.demos.haus/docs/examples/patterns/lists/lists-split)
- check that it displays correctly
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-release …
> Fix split list items overflowing in the other column

- releases.yml
- scss/_patterns_lists.scss
Remove separator from the first list item
Fixes WD-3017
- Open [demo](https://vanilla-framework-4723.demos.haus/docs/patterns/lists)
- check that it displays correctly
> Remove separator for the first item in the list (except if nested)

- Dockerfile
After moving dependencies and installing them all when building docker image, our jenkins builds started to fail.
This should fix that.
- Open [demo](https://vanilla-framework-4732.demos.haus/)
- Make sure all CI checks pass
- Make sure demo runs
> Skip installing Chromium for production on jenkins

- releases.yml
Revert some unnecessary old release notes (likely showed up because of some rebase).
- Open https://vanilla-framework-4738.demos.haus/docs/whats-new
- Make sure vertical spacing utils are not in release notes
> Remove unnecessary release notes

- scss/_base_tables.scss
- scss/_base_typography-definitions.scss
- scss/_settings_font.scss
- scss/_settings_spacing.scss
Update fontsizes of headings; cleanup some unneeded stuff
> Update small screen font-sizes, remove some unnecessary stuff

- scss/_patterns_heading-icon.scss
Fixes heading icon alignment
Fixes WD-3211
- Open [demo](https://vanilla-framework-4736.demos.haus/docs/patterns/heading-icon)
- Make sure icons in heading icon are aligned as expected
> Fix alignment of heading icon

- scss/_patterns_lists.scss
- templates/docs/examples/patterns/lists/lists-stepped-detailed-headings.html
- templates/docs/examples/patterns/lists/lists-stepped-detailed.html
- templates/docs/examples/patterns/lists/lists-stepped-headings.html
Align stepped lists prefixes
[/docs/examples/patterns/lists/lists-stepped-detailed](https://vanilla-framework-4735.demos.haus/docs/examples/patterns/lists/lists-stepped-detailed)
> Align prefix for stepped lists

- scss/_patterns_navigation.scss
Reverts logo sizing, not to use new h4 size, but specific size adjusted to logo itself.
Fixes [WD-3214](https://warthogs.atlassian.net/browse/WD-3214)
- Open [demo](https://vanilla-framework-4756.demos.haus/)
- Check logo in top navigation. Make sure it uses font size the same as on Vanilla 3 (https://vanillaframework.io)
[WD-3214]: https://warthogs.atlassian.net/browse/WD-3214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert logo font size to match logo sizing

- package.json
- scss/_settings_colors.scss
Adds `$color-paper` variable for new page background (fully introduced in v4.0).
Just check the code if new variable is added with correct value `#f3f3f3`.
> Add paper colour variable

- releases.yml
- scss/_patterns_strip.scss
- templates/docs/examples/layouts/brochure-site/_25-75-offset.html
- templates/docs/examples/patterns/strips/white.html
- templates/docs/patterns/strip/index.md
Adds new white variant of strip `p-strip--white` that can be used with new paper background.
Fixes WD-3892
- Open [demo](https://vanilla-framework-4773.demos.haus/docs/patterns/strip#white-strip) with new white strip docs
- Review the docs and the example
NOTE: Circle CI job for running Percy is failing because or attempted merge with main branch. We are merging this PR to vanilla-4.0 branch, so it's fine for it to fail here. …
> Implement white strips for paper background

- side-navigation.yaml
- templates/docs/migration-guide-to-v4.md
Adds migration docs for 4.0
Fixes WD-3589
- Open [demo](https://vanilla-framework-4774.demos.haus/docs/migration-guide-to-v4)
- Review the guide:
- https://vanilla-framework-4774.demos.haus/docs/migration-guide-to-v4
> Migration docs 4.0

- .spelling
- templates/docs/base/typography.md
Updates typography docs for Vanilla 4.0 based on top 3 sections of new typography guidelines ([figma](https://www.figma.com/file/DZ7V6EFl18u72JLJrFDB2v/Building-brochure-pages-with-Vanilla-4.0?type=design&node-id=897-11564&t=pDZPyiV4MP5j8QnI-0))
Fixes [WD-3955](https://warthogs.atlassian.net/browse/WD-3955)
- Open [demo](https://vanilla-framework-4780.demos.haus/docs/base/typography)
- https://vanilla-framework-4780.demos.haus/docs/base/typography
- Check top sections about the font and scale …
> Update typography docs for Vanilla 4.0

- releases.yml
- scss/_utilities_text-max-width.scss
- scss/_vanilla.scss
- side-navigation.yaml
- templates/docs/examples/utilities/text-max-width-container.html
- templates/docs/examples/utilities/text-max-width-divided.html
- templates/docs/examples/utilities/text-max-width.html
- templates/docs/layouts/brochure.md
- templates/docs/migration-guide-to-v4.md
- templates/docs/utilities/text-max-width.md
Adds utility to limit max width of text lists to match text elements.
Fixes [WD-2949](https://warthogs.atlassian.net/browse/WD-2949)
- Open [demo](https://vanilla-framework-4781.demos.haus/docs/utilities/text-max-width)
- Review new examples:
- Util class on list: https://vanilla-framework-4781.demos.haus/docs/examples/utilities/text-max-width-container
- Util class on container: https://vanilla-framework-4781.demos.haus/docs/examples/utilities/text-max-width-container
- Util on divided list: https://vanilla-framework-4781.demos.haus/docs/examples/utilities/text-max-width-divided
- https://vanilla-framework-4781.demos.haus/docs/utilities/text-max-width
If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's …
> Add utility to limit max width of text lists

- scss/_base_code.scss
- scss/_base_forms.scss
- scss/_base_placeholders.scss
- scss/_base_typography.scss
- scss/_global_functions.scss
- scss/_patterns_article-pagination.scss
- scss/_patterns_badge.scss
- scss/_patterns_card.scss
- scss/_patterns_code-snippet.scss
- scss/_patterns_form-password-toggle.scss
- scss/_patterns_links.scss
- scss/_patterns_lists.scss
- scss/_patterns_media-object.scss
- scss/_patterns_pagination.scss
- scss/_patterns_status-label.scss
- scss/_patterns_strip.scss
- scss/_patterns_table-of-contents.scss
- scss/_patterns_tabs.scss
- scss/_settings_colors.scss
- templates/docs/migration-guide-to-v4.md
- templates/docs/utilities/functions.md
Updates default text colour to be black `#000` instead of dark grey `#111`
Fixes [WD-4561](https://warthogs.atlassian.net/browse/WD-4561)
Fixes #4784 
- Open [demo](https://vanilla-framework-4786.demos.haus/)
- Make sure all default text is black.
- Check that migration guide mentions the colour change: https://vanilla-framework-4786.demos.haus/docs/migration-guide-to-v4#updated-text-colour
- …
> Update text colour to 000

- releases.yml
- scss/_base_typography-definitions.scss
- scss/_patterns_navigation.scss
- scss/_patterns_rule.scss
- scss/_settings_colors.scss
- templates/docs/base/typography.md
- templates/docs/examples/base/headings-accented.html
- templates/docs/examples/layouts/brochure-site/_25-75-nested.html
- templates/docs/migration-guide-to-v4.md
- templates/docs/patterns/rule.md
- templates/docs/settings/color-settings.md
Adds teal as accent colour, Ubuntu orange is now properly the brand colour.
Fixes [WD-3103](https://warthogs.atlassian.net/browse/WD-3103)
- Open [demo](https://vanilla-framework-4799.demos.haus/docs/settings/color-settings)
- Review examples with accented headings and rules
- https://vanilla-framework-4799.demos.haus/docs/examples/base/headings-accented
- https://vanilla-framework-4799.demos.haus/docs/examples/patterns/rule/highlight
- Colour docs:  https://vanilla-framework-4799.demos.haus/docs/settings/color-settings
- Accented headings: https://vanilla-framework-4799.demos.haus/docs/base/typography#accented-headings
- Accented rule: https://vanilla-framework-4799.demos.haus/docs/patterns/rule#highlighted
If this PR contains Vanilla SCSS code changes, it …
> Add teal accent colour

- package.json
- scss/_base_forms.scss
Reduced the input width to remedy the issue with the form input field on a smaller screen window. 
Fixes https://github.com/canonical/vanilla-framework/issues/4761
- Open [demo](https://vanilla-framework-4798.demos.haus/docs/examples/base/forms/input)
- Visit Examples Tab > Forms/Input link (under base)
- https://vanilla-framework-4798.demos.haus/docs/examples/base/forms/input
- Inspect <input> div and check min-width property. Should have changed from 10em to 8em
What for:
- Visit https://ubuntu.com/blog.
- Before fix, when window has width just over 620px the input field border line is cut off
- After fix, the line stays centred 
- `Feature 🎁`, `Breaking Change …
> Reduce form input width - 10em to 8em

- konf/site.yaml
I've updated https://jenkins.canonical.com/webteam/job/vanillaframework.io-staging/ and https://jenkins.canonical.com/webteam/job/vanillaframework.io-production/ to pull the appropriate registry from the konf file.
> Use ps5 registry

- releases.yml
- scss/_base_code.scss
- scss/_base_forms.scss
- scss/_base_placeholders.scss
- scss/_patterns_card.scss
- scss/_patterns_contextual-menu.scss
- scss/_patterns_media-object.scss
- scss/_patterns_modal.scss
- scss/_patterns_navigation.scss
- scss/_patterns_notifications.scss
- scss/_patterns_search-and-filter.scss
- scss/_patterns_search-box.scss
- scss/_patterns_segmented-control.scss
- scss/_patterns_status-label.scss
- scss/_patterns_switch.scss
- scss/_patterns_table-mobile-card.scss
- scss/_patterns_tooltips.scss
- scss/_settings_placeholders.scss
- templates/docs/settings/placeholder-settings.md
Removes rounded corners (changes border-radius to 0), deprecates the use of `$border-radius` variable and `%vf-has-rounded-corners` placeholder.
Fixes [WD-539](https://warthogs.atlassian.net/browse/WD-539)
- Open [demo](https://vanilla-framework-4810.demos.haus/docs/settings/placeholder-settings)
- Review affected components:
- Cards https://vanilla-framework-4810.demos.haus/docs/patterns/card
- Code https://vanilla-framework-4810.demos.haus/docs/base/code
- Contextual menu https://vanilla-framework-4810.demos.haus/docs/patterns/contextual-menu
- Fieldset: https://vanilla-framework-4810.demos.haus/docs/base/forms#fieldset
- Modal https://vanilla-framework-4810.demos.haus/docs/patterns/modal
- Media object https://vanilla-framework-4810.demos.haus/docs/patterns/media-object
- Navigation …
> Remove rounded corners

- scss/_base_typography-definitions.scss
- scss/_patterns_muted-heading.scss
- scss/_settings_spacing.scss
Increase margin-bottom on muted heading
Fixes: https://github.com/canonical/vanilla-framework/pull/4713
Before: 
After:
> Update muted heading

- package.json
- scss/_patterns_breadcrumbs.scss
Changed the breadcrumb style from chevrons to forward slashes on the breadcrumbs component 
Fixes https://github.com/canonical/vanilla-framework/issues/4768
- Open demo https://vanilla-framework-4811.demos.haus/docs/examples/patterns/breadcrumbs
- Go to Examples tab > [Breadcrumbs](https://vanilla-framework-4811.demos.haus/docs/examples/patterns/breadcrumbs) (under Components heading)
- Inspect the ".p-breadcrumbs__item:not(:first-of-type)::before" markup - The content unicode has been changed to a forward slash …
> Breadcrumbs - chevrons to slashes

- package.json
- releases.yml
- scss/_base_hr.scss
- scss/_base_links.scss
- scss/_patterns_rule.scss
- templates/docs/examples/patterns/links/links-dark.html
- templates/docs/examples/patterns/rule/dark.html
- templates/docs/migration-guide-to-v4.md
- templates/docs/patterns/links/index.md
- templates/docs/patterns/rule.md
Revert from using `on-dark` class to switch theme, to keep new components consistent with existing themes.
- Open [demo](https://vanilla-framework-4819.demos.haus/docs/patterns/rule#dark-theme)
- Dark rules: https://vanilla-framework-4819.demos.haus/docs/patterns/rule#dark-theme
- Dark links: https://vanilla-framework-4819.demos.haus/docs/patterns/links#dark
> Use is-dark class name for consistency

- scss/_patterns_navigation.scss
- scss/_settings_colors.scss
Uses Ubuntu orange colour directly in logo tag, to make sure it can't be changed via `$color-brand` variable.
Demo: https://vanilla-framework-4821.demos.haus/
> Make sure logo tag backround is not configurable

- templates/docs/migration-guide-to-v4.md
Remove outdated info about alpha releases
- Open [demo](https://vanilla-framework-4835.demos.haus/docs/migration-guide-to-v4)
- Review the migration guide, it should not mention alpha releases anymore: https://vanilla-framework-4835.demos.haus/docs/migration-guide-to-v4
> Remove outdated info about alpha releases

- templates/docs/migration-guide-to-v4.md
Small updates to migration guide:
- mentions how to revert strips to old grey "brand" colour
- mentions removal of rounded corners
- Open [demo](https://vanilla-framework-4830.demos.haus/docs/migration-guide-to-v4)
- https://vanilla-framework-4830.demos.haus/docs/migration-guide-to-v4
> Migration guide updates

- package.json
- releases.yml
- scss/_base_typography-definitions.scss
- scss/_patterns_headings.scss
- scss/_settings_spacing.scss
- templates/docs/base/typography.md
- templates/docs/examples/patterns/headings/display.html
Adds display variant of heading component `p-heading--display`
Fixes [WD-5124](https://warthogs.atlassian.net/browse/WD-5124)
- Open [demo](https://vanilla-framework-4840.demos.haus/docs/base/typography#display-headings)
- Check if display headings work correctly (on different screen sizes)
- https://vanilla-framework-4840.demos.haus/docs/base/typography#display-headings
- see the [wiki for …
> Add display headings

- releases.yml
- scss/_patterns_grid.scss
- templates/docs/examples/brochure/25-75-split-responsive-structure.html
- templates/docs/examples/brochure/_25-75-responsive-structure.html
- templates/docs/examples/brochure/_25-75.html
- templates/docs/examples/patterns/grid/25-75-responsive.html
- templates/docs/layouts/brochure.md
- templates/docs/patterns/grid/index.md
Adds responsive variant to 25/75 grid
Fixes [WD-5125](https://warthogs.atlassian.net/browse/WD-5125)
- Open [demo](https://vanilla-framework-4846.demos.haus/docs/patterns/grid#2575-responsive)
- Make sure responsive variant works as expected on medium screens
- https://vanilla-framework-4846.demos.haus/docs/patterns/grid#2575-responsive
- https://vanilla-framework-4846.demos.haus/docs/layouts/brochure#-the-2575-split-
- if CSS class names are changed/added/removed it should be …
> Add responsive variant of 25/75 grid

- releases.yml
- scss/_patterns_suru.scss
- scss/_vanilla.scss
- scss/standalone/patterns_suru.scss
- side-navigation.yaml
- templates/410.html
- templates/docs/examples/brochure/_50-50.html
- templates/docs/examples/patterns/suru/dark.html
- templates/docs/examples/patterns/suru/default.html
- templates/docs/patterns/strip/index.md
- templates/docs/patterns/suru.md
Adds new suru component, for the new style of suru.
Deprecates the use of old suru strip.
Fixes [WD-5196](https://warthogs.atlassian.net/browse/WD-5196)
- Open [demo](https://vanilla-framework-4849.demos.haus/docs/patterns/suru)
- Review suru examples:
- https://vanilla-framework-4849.demos.haus/docs/examples/patterns/suru/dark
- https://vanilla-framework-4849.demos.haus/docs/examples/patterns/suru/default
- https://vanilla-framework-4849.demos.haus/docs/patterns/suru
- https://vanilla-framework-4849.demos.haus/docs/patterns/strip#suru-strip
- if CSS …
> Add suru component

- releases.yml
- scss/_patterns_grid.scss
- templates/docs/examples/brochure/hero-25-75.html
- templates/docs/examples/brochure/hero-50-50.html
- templates/docs/examples/brochure/hero-75-offset.html
- templates/docs/layouts/brochure.md
Add examples of new brochure site hero sections
Fixes [WD-5139](https://warthogs.atlassian.net/browse/WD-5139)
- Open [demo](https://vanilla-framework-4843.demos.haus/docs/layouts/brochure#section-examples)
- Review new hero section examples:
- https://vanilla-framework-4843.demos.haus/docs/examples/brochure/hero-25-75
- https://vanilla-framework-4843.demos.haus/docs/examples/brochure/hero-50-50
- https://vanilla-framework-4843.demos.haus/docs/examples/brochure/hero-75-offset
- https://vanilla-framework-4843.demos.haus/docs/layouts/brochure#section-examples …
> Add examples of hero sections

- templates/docs/changelog-v2.md
- templates/docs/changelog-v3.html
- templates/docs/whats-new.html
Removes Vanilla 3 changelog from "What's new" page and moves it to separate changelog page.
- Open [demo](https://vanilla-framework-4851.demos.haus/docs/whats-new)
- Make sure what's new page only lists changes from Vanilla 4: https://vanilla-framework-4851.demos.haus/docs/whats-new
- Check if new v3 page lists all changes from Vanilla 3: https://vanilla-framework-4851.demos.haus/docs/changelog-v3 …
> Remove Vanilla 3 changes from "What's new" page

- scss/_patterns_chip.scss
reduce width of the border
change font weight
use real small caps (instead of small uppercase)
Fixes [WD-5198](https://warthogs.atlassian.net/browse/WD-5198)
- Open [demo](https://vanilla-framework-4850.demos.haus/docs/examples/patterns/chip/variants)
- Check that it looks ok
[WD-5198]: …
> Update border and font in chips

- package.json
- scss/_patterns_navigation.scss
Set chevron top to 1rem on mobile and 1.25rem on desktop
Fixes [#4758](https://github.com/canonical/vanilla-framework/issues/4758)
- Open [demo](http://0.0.0.0:8101/docs/examples/patterns/navigation/dropdown#navigation)
- Check chevron height in mobile and desktop mode using developer tools
> Fix chevron top on mobile

- package.json
- releases.yml
- scss/_base_forms.scss
- scss/_base_icon-definitions.scss
- scss/_patterns_form-help-text.scss
- scss/_patterns_form-validation.scss
- scss/_settings_colors.scss
- templates/docs/base/forms.md
- templates/docs/examples/patterns/forms/form-validation-dark.html
- templates/docs/examples/patterns/forms/forms-dark.html
- tests/parker.js
Adds dark theme to form inputs
Fixes [WD-5201](https://warthogs.atlassian.net/browse/WD-5201)
- Open [demo](https://vanilla-framework-4857.demos.haus/docs/base/forms#dark-theme)
- Check new examples
- https://vanilla-framework-4857.demos.haus/docs/examples/patterns/forms/forms-dark
- https://vanilla-framework-4857.demos.haus/docs/base/forms#dark-theme
- https://vanilla-framework-4857.demos.haus/docs/examples/patterns/forms/form-validation-dark …
> Dark theme for forms

- templates/contribute.html
Fixes #4860
- Open [demo](https://vanilla-framework-4861.demos.haus/contribute)
- Make sure Licenses part at the bottom doesn't use old Canonical logo
> Remove old Canonical logo from contribute page

- package.json
- releases.yml
- scss/_patterns_logo-section.scss
- side-navigation.yaml
- templates/docs/examples/patterns/logo-section/logo-section-fallback.html
- templates/docs/migration-guide-to-v4.md
- templates/docs/patterns/logo-section/index.md
Fixes the issue introduced in Vanilla 4.2 where logo section was updated.
If logo section uses images that are not spaced out by design team it may render them in odd sizes (because in new version we switched to variable width keeping the height of logos equal).
This fallback variant introduces a class name that can be used temporary on such old logo sections before they get updated logo images. It will make logos have fixed width again, to avoid size issue. It is meant as temporary fallback to help migrate to latest Vanilla quicker (just by adding the `has-misaligned-images` class without waiting for new logos to be created. Eventually all logos should be updated by visual design team.
- Open [demo](https://vanilla-framework-4870.demos.haus/docs/examples/patterns/logo-section/logo-section …
> Add fallback variant for legacy misaligned logos

- package.json
- scss/_base_typography-definitions.scss
- scss/_base_typography.scss
- scss/_patterns_muted-heading.scss
- adjust font weight of small caps and h5 to 550
- Verify new weight
> Adjust font-weight of small caps and h5

- .github/workflows/pr.yml
Version 10.3 of linkchecker throws warnings on redirects and fails the build (https://linkchecker.github.io/linkchecker/upgrading.html#migrating-from-10-2-to-10-3).
This PR ignores linkchecker redirect warnings to prevent them from failing the CI.
- Make sure linkchecker CI job passes
> Ignore warnings to prevent redirects from failing the build

- package.json
- releases.yml
- scss/_patterns_side-navigation.scss
- templates/docs/examples/patterns/side-navigation/_icons.html
- templates/docs/examples/patterns/side-navigation/paper.html
- tests/parker.js
As part one building block of new documentation layout this PR updates side navigation component by adding new paper background colour support to the light theme.
- Open [demo](https://vanilla-framework-4881.demos.haus/docs/examples/patterns/side-navigation/paper)
- Make sure side navigation looks fine on paper background (check mobile view as well).
- example contains 3 variants (standard, with icons and sticky)
- see the …
> Add paper background support to side navigation

- releases.yml
- scss/_base_typography-definitions.scss
- scss/_patterns_table-of-contents.scss
- templates/docs/examples/patterns/table-of-contents-sections.html
- templates/docs/examples/patterns/table-of-contents/default.html
- templates/docs/examples/patterns/table-of-contents/sections.html
- templates/docs/patterns/table-of-contents.md
As part of working on documentation layout we are refreshing the styling of an old table of contents component:
- use muted heading for title style
- use link styles on table of contents items to make them accessible
- add spacing between items similar to side navigation
- Open [demo](https://vanilla-framework-4885.demos.haus/docs/examples/patterns/table-of-contents)
- Review updated examples:
- https://vanilla-framework-4885.demos.haus/docs/examples/patterns/table-of-contents-sections
- https://vanilla-framework-4885.demos.haus/docs/examples/patterns/table-of-contents
- Make sure they work fine
> Refresh styles of table of contents component

- templates/_layouts/_header.html
Uses dark theme of search box in the (dark) top navigation.
Workaround for #4887 - while it "fixes" the issue on the Vanilla site, ideally it needs to be fixed in search box component so it doesn't require the dark class name to not be broken.
- Open [demo](https://vanilla-framework-4888.demos.haus/)
- Open search, type something, make sure it looks OK
- Check both in Chrome and Firefox
> Use dark search in the top navbar

- releases.yml
- scss/_layouts_docs.scss
- scss/_layouts_full-width.scss
- scss/_vanilla.scss
- templates/docs/examples/layouts/docs.html
- templates/docs/examples/layouts/documentation.html
- templates/docs/layouts/documentation-brochure.md
- templates/docs/layouts/documentation.md
- templates/docs/layouts/full-width.md
Adds new full-width documentation layout to Vanilla.
Fixes [WD-6054](https://warthogs.atlassian.net/browse/WD-6054)
- Open [demo](https://vanilla-framework-4886.demos.haus/docs/examples/layouts/docs)
- QA an example of the new docs layout, check on different screen sizes
- https://vanilla-framework-4886.demos.haus/docs/examples/layouts/docs
- Documentation layout docs: https://vanilla-framework-4886.demos.haus/docs/layouts/documentation …
> New documentation layout

- .github/workflows/publish-on-release.yml
Reverts pushing to `release` branch on release to deploy website until we figure out how to improve the process better.
- Review the code of GH action
- Check if one step of the job was removed
> Revert pushing to release branch

- templates/docs/examples/patterns/forms/_checkbox-inline.html
- templates/docs/examples/patterns/forms/_radio-inline.html
* Fixed documentation typos for Forms/Radio and Forms/Checkbox inline
> Fixed minor typos for Inline Radio and Checkbox docs

- package.json
- releases.yml
- scss/_layouts_docs.scss
- scss/_patterns_side-navigation-expandable.scss
- templates/docs/examples/layouts/docs.html
- add a sticky container to documentation layout to make table of contents sticky and scrollable
- drive-by: fix overflow in expandable side nav when collapsed
- Open [demo](https://vanilla-framework-4895.demos.haus/docs/examples/layouts/docs)
- Review docs layout example
- https://vanilla-framework-4895.demos.haus/docs/examples/layouts/docs
- make sure table of contents on right is sticky when you scroll
- adjust window height to make is smaller than the table of contents (or add some items to it in dev tools), make sure you can scroll the table of contents if it doesn't fit on screen
> Sticky container for docs layout

- package.json
- scss/_patterns_suru.scss
- Suru component was hidden on smaller screens, now it's visible on all screens.
Fixes #4894 
Fixes [WD-7506](https://warthogs.atlassian.net/browse/WD-7506)
- Open demo url
- Go to /docs/examples/patterns/suru/default and try resizing the page. …
> Show suru on all screens

- scss/_layouts_application-panels.scss
Light mode sticky panels were missing a background, added the light background.
Fixes #4907 
Fixes [WD-7507](https://warthogs.atlassian.net/browse/WD-7507)
[WD-7507]: …
> Add missing white background to sticky panel

- templates/docs/patterns/navigation/accessibility.md
- Made the changes highlighted in the copydoc: https://docs.google.com/document/d/1WAmoXaiy6bSBXitwglNAg5PFls-Zi5R8K4jIlzFR1Sw/edit
- Open [demo](https://vanilla-framework-4916.demos.haus/)
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-rele …
> Update navigation component a11y documentation [WD-6207]

- templates/docs/patterns/empty-state.md
- Updated the introduction of the empty state component according to the copydoc: https://docs.google.com/document/d/1YoVeZU2fgSwiPmqidcMe4pQ_TnlIFS_3uHa4lIV3XPQ/edit.
Fixes WD-6189 …
> Update empty state documentation [WD-6189]

- templates/docs/patterns/tooltips/index.md
- Updated implementation tab according to the copydoc: https://docs.google.com/document/d/1YLEcTVR7wXQAzbNWObsE8VVIIviQvcVfM9AOMoMVSVs/edit
- Omitted the notification title "Avoid" because its grammar did not align well with the copydoc update.
Fixes WD-6188
- Open [demo](https://vanilla-framework-4913.demos.haus/docs/patterns/tooltips)
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Relea …
> Update implementation tab for tooltips [WD-6188]

- templates/docs/patterns/links/accessibility.md
- Updated a11y documentation for links component from the copydoc: https://docs.google.com/document/d/1DcYBpmuLKZGLIWR6jgjYfZc1X64d8HtDt9uKMoB0POE/edit
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-release-tas …
> Update links component a11y documentation [WD-6190]

- templates/docs/examples/brochure/hero-75-offset.html
- Added u-no-margin--bottom to the h1 so that it looks like one paragraph with a line break.
Fixes https://github.com/canonical/vanilla-framework/issues/4859
[if relevant, include a …
> Fix margin in brochure example

- scss/_patterns_grid.scss
- Remove off by one that was preventing `col-start-*` classes work up to 11, not 12.
Fixes #4808 
> Fix grid column reordering off by one err [WD-7580]

- scss/_patterns_navigation.scss
- Added 0.19rem (~3px) space between logo tag and the text besides it (padding-left).
Fixes https://github.com/canonical/vanilla-framework/issues/4789
Fixes  WD-7614
- Open [demo](https://vanilla-framework-4924.demos.haus/)
- Open navigation example with Ubuntu logo (like https://vanilla-framework-4924.demos.haus/docs/examples/patterns/navigation/default-dark)
- Verify spacing on the logos
Before: 
After:
> Add more space between logo tag and text

- package.json
- yarn.lock
This reverts commit 54ba7f2301ead8f36d411bbf0c9d4a28dccdb4b1.
Dotrun still runs on node v16, so we can't update.
Pull the branch, run `dotrun install`, make sure it not fails on node version incompatibility
> Reverts postcss-cli update to v11 as it breaks dotrun

- releases.yml
- scss/_base_typography-definitions.scss
- scss/_base_typography-heading-mixins.scss
- templates/docs/base/typography.md
Adjusts spacing between pairs of h1+h2, h3+h4 and h5+h6.
Also refactors shared styles of headings for better code clarity.
Fixes [WD-7708](https://warthogs.atlassian.net/browse/WD-7708)
- Open [demo](https://vanilla-framework-4941.demos.haus/docs/base/typography)
- Review heading examples
- Make sure there is no margins between headings of the same size: h1 and h2s, h3 and h4s, h5 and h6s, both when using elements `h1` etc and classes `p-heading--1` etc.
- https://vanilla-framework-4941.demos.haus/docs/examples/base/headings
- https://vanilla-framework-4941.demos.haus/docs/examples/patterns/headings/default
- https://vanilla-framework-4941.demos.haus/docs/examples/patterns/headings/mixed
- https://vanilla-framework-4941.demos.haus/docs/examples/templates/typographic-spacing
- Review …
> Adjust spacing between heading groups

- templates/docs/whats-new.html
Fixes missing label for removed feature in Vanilla changelog.
- Open [demo](https://vanilla-framework-4943.demos.haus/docs/whats-new)
- Make sure that "Removed" status label in changelog appears correctly.
[Before](https://staging.vanillaframework.io/docs/whats-new)
[After](https://vanilla-framework-4943.demos.haus/docs/whats-new)
> Add support for "Removed" status label to Vanilla changelog

- templates/contribute.html
To fix bot contributors, uses proper URL from API instead of trying to build one based on user name.
Fixes #4945
- Open [demo](https://vanilla-framework-4946.demos.haus/contribute)
- Click on dependabot, or renovate contributors links. Make sure they work.
> Fix GitHub contributors URLs

- renovate.json
Uses node versioning scheme in renovate config to avoid hardcoding stable node LTS versions.
See renovate docs in: https://docs.renovatebot.com/modules/versioning/#nodejs-versioning
> Configure renovate versioning for node stable versions only

- package.json
- scss/_base_forms.scss
- scss/_patterns_navigation.scss
- scss/docs/site.scss
- templates/docs/examples/patterns/navigation/dropdown-alignment.html
This increases the padding of top navigation items to align then with grid margin on large screens. This improves the alignment of the top navigation with grid below it in documentation layout.
Part of https://github.com/canonical/vanilla-framework/issues/4898
Part of https://warthogs.atlassian.net/browse/WD-8284
Note: separately to this PR we will need to improve alignment of the navigation items when used in top navigation with 25/75 grid split.
- Open [demo](https://vanilla-framework-4948.demos.haus/docs/examples/patterns/navigation/dropdown-alignment)
- Make sure padding of top items is the same as grid margin
- Make sure position of dropdown chevron icon on right aligned navigation item is aligned with icons in search and select inputs below it
- Check the example of documentation …
> Align top navigation items padding with grid margin

- templates/_layouts/_footer.html
When `Manage your tracker settings` is clicked, the modal pops up as expected. 
Fixes https://github.com/canonical/vanilla-framework/issues/4959
- Run [demo](https://vanilla-framework-4962.demos.haus/)
- Scroll down to footer and click on `Manage your tracker settings`
- Tracker window should appear
> Fix tracker popup

- scss/_base_background.scss
- scss/_base_themes.scss
- scss/_settings_colors.scss
- templates/_layouts/examples.html
- templates/docs/examples/base/hr-dark.html
- tests/parker.js
Adds support for theme class names on body element (to change page background).
Adds basic paper theme support.
Fixes https://warthogs.atlassian.net/browse/WD-7604
- Open [demo](https://vanilla-framework-4970.demos.haus/)
- Open demo: https://vanilla-framework-4970.demos.haus/
- Change class on `body` from `is-paper` to `is-light` or `is-dark`, make sure background of the page and text colour changes as expected.
- Open `hr` demo: https://vanilla-framework-4970.demos.haus/docs/examples/base/hr-dark
- Remove class `is-dark` from `<hr>`, make sure it still is dark (inherited from body)
- Change body class to `is-light` or `is-paper`, make sure background color, and line adjusted accordingly
This is merged into feature branch, we are fine with some CI jobs (like Percy) to fail on this one.
> Add paper theme and theme setting on body element

- .circleci/config.yml
- scss/_patterns_tabs.scss
- templates/docs/examples/patterns/tabs/content-dark.html
Update Tab component to use new theme variables
Fixes [WD-7601](https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/970?selectedIssue=WD-7601)
- Open [demo](https://vanilla-framework-4963.demos.haus/)
- Go to `/docs/examples/patterns/tabs/navigation`, `/docs/examples/patterns/tabs/content-dark`, `/docs/examples/patterns/tabs/content`
- Inspect page and modify the class of <body> tag to `is-dark`, `is-light`, `is-paper`
- Tabs should update accordingly based on the body theme
[WD-7601]: https://warthogs.atlassian.net/browse/WD-7601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update tab with new theme variables

- scss/_patterns_side-navigation-expandable.scss
- scss/_patterns_side-navigation.scss
- templates/docs/examples/patterns/side-navigation/_accordion.html
- templates/docs/examples/patterns/side-navigation/_default.html
- templates/docs/examples/patterns/side-navigation/_expandable.html
- templates/docs/examples/patterns/side-navigation/_icons.html
- templates/docs/examples/patterns/side-navigation/_layout-JAAS.html
- templates/docs/examples/patterns/side-navigation/_layout-application.html
- templates/docs/examples/patterns/side-navigation/accordion-dark.html
- templates/docs/examples/patterns/side-navigation/application.html
- templates/docs/examples/patterns/side-navigation/dark.html
- templates/docs/examples/patterns/side-navigation/expandable-dark.html
* Added new CSS theme support for Side Navigation component
* Note:
* ~Added dark stylings for `Toggle side navigation` button - previously only had light theme in the examples~
* Added workaround for unsupported dark themed icons, currently only done for chevron for Expandables and Accordion but there are more icons used as seen in `/docs/examples/patterns/side-navigation/icons`
Fixes [WD-7599](https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/970?selectedIssue=WD-7599)
- Open [demo](https://vanilla-framework-4972.demos.haus/)
- Go to `/docs/examples` and check out `Side navigation /  XXX` examples
- Side navigation theming should be consistent with the current examples in [vanillaframework.io](vanillaframework.io)
If this PR contains Vanilla SCSS code changes, it should …
> Add CSS theme support for Side Navigation 

- releases.yml
- scss/_patterns_section.scss
- templates/docs/examples/brochure/hero-50-50.html
- templates/docs/examples/patterns/section/hero.html
- templates/docs/patterns/section.md
- templates/index.html
Adds new variant to p-section component for hero sections, as `p-section--hero`.
This is supposed to have asymetrical section padding (regular on bottom, shallow on top) as per [Figma design spec](https://www.figma.com/file/Hll6ZRvHyTTGBZZSoRd8ei/Hero-component?type=design&node-id=184-1566&mode=design)
Fixes [WD-7707](https://warthogs.atlassian.net/browse/WD-7707)
https://warthogs.atlassian.net/browse/WD-7707
- Open [demo](https://vanilla-framework-4973.demos.haus/)
- https://vanilla-framework-4973.demos.haus//docs/examples/patterns/section/hero
- make sure hero section has correct paddings
- https://vanilla-framework-4973.demos.haus/docs/examples/brochure/hero-50-50
- make sure that hero example uses correct new padding
- …
> Hero section

- scss/_base_forms.scss
- templates/docs/examples/base/forms/labels.html
- templates/docs/examples/patterns/forms/forms-dark.html
- Add CSS variables theme support for base forms
- Fixed a minor typo
- Note: base forms now use `border-high-contrast` for the light & paper theme
Fixes [WD-7596](https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/970?selectedIssue=WD-7596)
- Go to `/docs/example`
- Make sure the base forms are consistent with their themes …
> Add new theme support for base forms

- scss/_patterns_form-help-text.scss
- Depends on base forms theme update: https://github.com/canonical/vanilla-framework/pull/4974
- Add theme support for Forms / Help text
- Go to `/docs/examples/patterns/forms/help-text`
- Check if themes are updated accordingly for help text
- Note: checkbox label shouldn't be updating with the theme as it's still WIP …
> Add theme support for forms help text

- scss/_patterns_form-password-toggle.scss
- Depends on base forms theme update: https://github.com/canonical/vanilla-framework/pull/4974
- Added CSS variable theme support for Forms / Password toggle
- Go to `/docs/examples/patterns/forms/password-toggle`
- Add `readonly="readonly"` to one of the input texts and click on Show password toggle
- The readonly text should inherit the correct colour according to its theme
- Note: Show button shouldn't be updating with the theme as it's still WIP …
> Add theme support for forms password toggle

- scss/_settings_colors.scss
- Export status color variables as CSS custom properties
> Export status color variables as CSS custom properties

- scss/_settings_colors.scss
- rename css custom properties for status colors
> Rename color variables for consistency

- scss/_patterns_form-tick-elements.scss
- scss/_settings_colors.scss
- templates/docs/examples/patterns/forms/forms-dark.html
- Added theme support for `Forms / Tick Elements` - radio & checkbox 
- Go to `/docs/examples/patterns/forms/tick-variants` and `/docs/examples/patterns/forms/forms-dark`
- Change body theme to light/dark/paper and see themes update accordingly
[if relevant, include a …
> Add theme support for forms tick elements

- scss/_patterns_search-box.scss
- templates/docs/examples/patterns/search-box/default-dark.html
- Add theme support for search box
Fixes [WD-7597](https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/970?selectedIssue=WD-7597)
- Go to `/docs/examples/patterns/search-box/default` and `/docs/examples/patterns/search-box/default-dark`
- Search boxes should be styled according to their themes
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Rele …
> Add theme support for search box

- scss/_patterns_form-validation.scss
- templates/docs/examples/patterns/forms/form-validation-dark.html
- Depends on new custom colour variables: https://github.com/canonical/vanilla-framework/pull/4979
- Added theme support for form validation: success, error, warning
- Go to `/docs/examples/patterns/forms/form-validation` and `/docs/examples/patterns/forms/form-validation-dark`
- Check if stylings are similar. 
- Additionally, try to change the theme on body tag to see changes.
- see the [wiki …
> Add theme support for form validation

- .spelling
- releases.yml
- scss/_patterns_suru.scss
- scss/standalone/patterns_suru.scss
- templates/docs/examples/brochure/_50-50.html
- templates/docs/examples/brochure/hero-25-75.html
- templates/docs/examples/brochure/hero-75-offset.html
- templates/docs/examples/patterns/suru/50-50-dark.html
- templates/docs/examples/patterns/suru/50-50.html
- templates/docs/examples/patterns/suru/dark.html
- templates/docs/examples/patterns/suru/default.html
- templates/docs/examples/patterns/suru/deprecared.html
- templates/docs/examples/patterns/suru/standalone.html
- templates/docs/patterns/suru.md
- Updates background of default 25/75 suru to latest version of images
- Adds `p-suru--25-75` as an alias to `p-suru` for consistency with other variants
- Updates `p-suru`/`p-suru--25-75` to work as a hero section container, providing correct padding and background
- Updates suru component to use new CSS variables themes for Suru backgrounds
- Adds `p-suru--50-50` variant
Fixes [WD-8771](https://warthogs.atlassian.net/browse/WD-8771)
Fixes [WD-8772](https://warthogs.atlassian.net/browse/WD-8772)
- Open [demo](https://vanilla-framework-4985.demos.haus/docs/patterns/suru)
- Check if 25/75 suru works as expected
- https://vanilla-framework-4985.demos.haus/docs/examples/patterns/suru/default
- https://vanilla-framework-4985.demos.haus/docs/examples/patterns/suru/dark
- Check if 50/50 suru …
> Update Suru to support hero sections with 25/75 and 50/50 main suru backgrounds

- .spelling
- releases.yml
- scss/_patterns_suru.scss
- templates/docs/examples/patterns/suru/fan-bottom.html
- templates/docs/examples/patterns/suru/fan-pyramid-left.html
- templates/docs/examples/patterns/suru/fan-pyramid-right.html
- templates/docs/examples/patterns/suru/fan-top.html
- templates/docs/examples/patterns/suru/variants.html
- templates/docs/patterns/suru.md
Adds more hero suru "corner" backgrounds (fan and pyramid shaped).
Fixes [WD-8773](https://warthogs.atlassian.net/browse/WD-8773)
- Open [demo](https://vanilla-framework-4989.demos.haus/docs/examples/patterns/suru/variants)
- Review Suru examples, make sure they look as expected:
- https://vanilla-framework-4989.demos.haus/docs/examples/patterns/suru/variants
- https://vanilla-framework-4989.demos.haus/docs/patterns/suru
- if CSS class names are changed/added/removed it should …
> Add more hero suru variants

- scss/_layouts_application-panels.scss
Increases z-index of sticky application layout panel headers (to avoid overlap with notifications and possibly other elements on z-index 1).
Fixes #4990
- Open [demo](https://vanilla-framework-4991.demos.haus/docs/examples/layouts/application/JAAS)
- Find `p-panel__header` add `is-sticky` class to it, check if it has z-index of 5
- 
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-p …
> Fix overlap issues with sticky app layout panel headers

- releases.yml
- scss/_base_links.scss
- scss/_patterns_form-tick-elements.scss
- scss/_patterns_links.scss
- scss/_settings_colors.scss
- templates/docs/examples/patterns/links/links-dark.html
- templates/docs/examples/patterns/links/links-inverted.html
- templates/docs/patterns/links/index.md
Updated links (and link related components) to use new theming.
Fixes [WD-8894](https://warthogs.atlassian.net/browse/WD-8894)
- Open [demo](https://vanilla-framework-4997.demos.haus/docs/patterns/links)
- Check links examples, make sure they update as expected when body class is changed (`is-paper` `is-dark`):
- https://vanilla-framework-4997.demos.haus/docs/examples/base/links
- https://vanilla-framework-4997.demos.haus/docs/examples/patterns/links/links-dark
- https://vanilla-framework-4997.demos.haus/docs/examples/patterns/links/links-soft
- https://vanilla-framework-4997.demos.haus/docs/examples/patterns/links/links-back-to-top
- https://vanilla-framework-4997.demos.haus/docs/patterns/links
If this PR contains Vanilla SCSS code changes, it should …
> Update links to use new theming

- scss/_base_grid-definitions.scss
- scss/_utilities_layout.scss
- Use more general selectors to target all classes that start with 'row':
`[class^="row"]` for if it is the first class in the class list
`[class*=" row"]` for if it is not
Another option here is to use `[class*="row"]`, which will target any class where 'row' is a substring, however this is very general and could have some unintended targets such as 'p-navigation__row' 
Fixes https://github.com/canonical/vanilla-framework/issues/4925
- Find or create a page where there is a `u-fixed-width` contained withing one of the new 'row' patterns (ex. `row--25-75`)
- See that the padding is reset
- `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, …
> Fix bug where u-fixed-width wasn't having its padding reset when inside the new row classes

- scss/_patterns_side-navigation.scss
- templates/docs/examples/patterns/side-navigation/_accordion.html
- templates/docs/examples/patterns/side-navigation/_expandable.html
- templates/docs/patterns/navigation/index.md
- Adds a fourth level of nesting to the side navigation component
Fixes https://warthogs.atlassian.net/browse/WD-9262
- Open [accordion demo](https://vanilla-framework-5010.demos.haus/docs/examples/patterns/side-navigation/accordion)
- Open [expandable demo](https://vanilla-framework-5010.demos.haus/docs/examples/patterns/side-navigation/expandable)
- See that the fourth level of nesting works …
> Add a fourth level of nesting to the side navigation component

- templates/accessibility.html
Fixes an outdated link to accessibility resources.
Fixes #5017
- Check the [accessibility page](https://vanilla-framework-5020.demos.haus/accessibility), make sure link to Accessibility Alphabet links (in Useful tools section) to (archived) version of the article
> Update link to Accessibility Alphabet

- scss/_patterns_lists.scss
- templates/docs/examples/base/lists/nested-ordered-list.html
- templates/docs/examples/patterns/lists/list-nested-stepped-detailed.html
- Fix nested list counter
https://github.com/canonical/vanilla-framework/issues/4998
[if relevant, include …
> Fix nested list counter

- releases.yml
- scss/_base_button.scss
- scss/_patterns_buttons.scss
- scss/_patterns_side-navigation.scss
- scss/_settings_colors.scss
- templates/docs/examples/patterns/buttons/dark.html
- templates/docs/examples/patterns/contextual-menu/dark.html
- templates/docs/patterns/buttons/index.md
Updates buttons to use new theming.
Deprecates brand buton.
Fixes [WD-7595](https://warthogs.atlassian.net/browse/WD-7595)
- Open [demo](https://vanilla-framework-5024.demos.haus/docs/examples/patterns/buttons/dark)
- Check if dark buttons look as expected
- Change class on body to `is-light` or `is-paper`, make sure buttons adjust accordingly
- https://vanilla-framework-5024.demos.haus/docs/patterns/buttons#theming
- if CSS class names are changed/added/removed it should be …
> Buttons themes

- scss/_base_icon-definitions.scss
- scss/_patterns_lists.scss
Fixes a regression issue caused by icon theming where success "tick" icon in lists got replaced with "filled" version instead of lined one.
This fixes the typo that caused this, reverting back to correct icon and switches lists to use themed icons as well.
- Open [demo](https://vanilla-framework-5028.demos.haus/docs/examples/patterns/lists/lists-dividers-ticked)
- Check ticked list example: https://vanilla-framework-5028.demos.haus/docs/examples/patterns/lists/lists-dividers-ticked
- make sure it uses correct lined tick icons, not filled ones
- switch the theme (with buttons on the bottom), check if icon colour adjusts accordingly on dark
- Check other examples with tick icons in lists:
- https://vanilla-framework-5028.demos.haus/docs/examples/patterns/lists/lists-status
Before (wrong): …
> Fix regression that caused wrong success icon being used in lists

- package.json
- scss/_patterns_buttons.scss
- scss/_settings_colors.scss
Moved active and hover button background variables to colour settings (where they are needed), so that button pattern file does not need to be imported for settings to work.
- Just make sure CI is good (all builds and tests pass)
> Move active/hover button opacity variables to settings

- scss/_base_icon-definitions.scss
- scss/_patterns_notifications.scss
Reverts the default info icon to standard icon colour while keeping the icon in notification coloured blue.
- Open [demo](https://vanilla-framework-5027.demos.haus/docs/examples/patterns/icons/icons-light)
- Check icons example, make sure information icon is using default icon colour: https://vanilla-framework-5027.demos.haus/docs/examples/patterns/icons/icons-light
- Verify the same in other contexts, like side navigation: https://vanilla-framework-5027.demos.haus/docs/examples/patterns/side-navigation/icons
- Check info notification, make sure the icon is blue as the left border: https://vanilla-framework-5027.demos.haus/docs/examples/patterns/notifications/information
> Revert default info icon to standard colour

- scss/_base_tables.scss
- scss/_patterns_table-mobile-card.scss
- Fixed the issue where top border wasn't consistent with the other border sides
Fixes https://github.com/canonical/vanilla-framework/issues/5001, [WD-9104](https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?selectedIssue=WD-9104)
- Open [demo](https://vanilla-framework-5005.demos.haus/)
- Go to https://vanilla-framework-5005.demos.haus/docs/examples/patterns/tables/table-mobile-card or https://vanilla-framework-5005.demos.haus/docs/examples/patterns/tables/table-mobile-card-dark
- Make sure border sides are all equal size and same colour …
> Fix table mobile card top border

- snapshots.js
Fixes running Percy job on CircleCI by changing localhost to IP.
For some reason access by hostname stopped working 🤷 
- Make sure `circleci / percy` job on the PR passes
> Fix access to localhost server on CircleCI

- .circleci/config.yml
- snapshots.js
On Thursday 04.04 CircleCI builds for Percy started to timeout.
For some reason we don't fully understand yet, the process of crawling example links out of the website started to be very slow and time consuming which in the end led to timeout.
To remedy the issue this PR replaces the process of crawling the website (to get example URLs) to simply getting list of example files from file system and constructing URLs out of the file names (because they are jinja templates and there is 1:1 relation between the file paths and URLs).
We also increase CircleCI resources (as suggested by CircleCI itself) to use environment with more CPU cores and RAM.
- Make sure CircleCI Percy job is passing
> Fix Percy on CircleCI performance issues

- package.json
- yarn.lock
We are not using `get-site-urls` for getting example URLs, so we can remove this dependency.
> Remove get-site-urls dependency

- scss/_base_icon-definitions.scss
Reverts a regression that caused link icon to be replaced by chevron (possibly during theming refactor).
- Open [demo](https://vanilla-framework-5046.demos.haus/docs/patterns/icons)
- Find `p-icon--get-link`, make sure it's showing link icon (chain) instead of chevron
> Fix link icon

- releases.yml
Fixes typo in changelog data that prevented link to appear on what's new page
- Open [demo](https://vanilla-framework-5050.demos.haus/docs/whats-new)
- Make sure that the first item in changelog links correctly to Navigation page
> Fix typo in release notes

- releases.yml
- scss/_patterns_equal-height-row.scss
- scss/_patterns_media-container.scss
- scss/_vanilla.scss
- scss/standalone/patterns_equal-height-row.scss
- side-navigation.yaml
- templates/docs/examples/patterns/equal-height-row/3-column-row.html
- templates/docs/examples/patterns/equal-height-row/4-items-per-column.html
- templates/docs/examples/patterns/equal-height-row/default.html
- templates/docs/patterns/equal-height-row.md
Added the equal height row component which includes the following features:
- Consistent alignment of grid items across all column in a row
- Out of box responsive behaviour for grid items
- Support for use in standard and 25-75 grid layouts
- Insert dividers that can span across all columns in a row (bridges grid gaps) on large screens and breaks up into smaller per column dividers on smaller screen sizes
Fixes: WD-10102
- Open [demo](https://vanilla-framework-5039.demos.haus/docs/patterns/equal-height-row)
- Inspect the following component examples and make sure behaviour on all screen sizes align with the functionalities outlined above: [Equal height row / Three column row](https://vanilla-framework-5039.demos.haus/docs/examples/patterns/equal-height-row/3-column-row), [Equal height …
> Add equal height row component

- package.json
- releases.yml
- scss/_patterns_suru.scss
- templates/docs/examples/patterns/suru/divider.html
- templates/docs/patterns/suru.md
Adds new divider suru variant
Fixes [WD-8774](https://warthogs.atlassian.net/browse/WD-8774)
- Open [demo](https://vanilla-framework-5053.demos.haus/docs/examples/patterns/suru/divider)
- Check the example, make sure it works as expected
- https://vanilla-framework-5053.demos.haus/docs/examples/patterns/suru/divider
- check the dark and paper versions (light version with white background is not supported)
- check smaller screen sizes (suru should be hidden)
- https://vanilla-framework-5053.demos.haus/docs/patterns/suru#divider-suru
[WD-8774]: https://warthogs.atlassian.net/browse/WD-8774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add divider Suru variant

- templates/docs/base/typography.md
Fixed some of the typography docs to reflect the css more accuratly
- Look at the typography docs: https://vanilla-framework-5055.demos.haus/docs/base/typography
- Look at vanilla-framework/scss/_base_typography-definitions.scss, vanilla-framework/scss/_settings_font.scss and vanilla-framework/scss/_settings_spacing.scss
- Compare and make sure the typography docs are correct
> Fix typography docs

- scss/_patterns_lists.scss
> Update divided list to use new theme colours

- scss/_settings_colors.scss
Muted borders are currently very faint, and the values aren't consistent between the light and dark theme. This pr makes them consistent (.2 opacity for default border contrast, .1 for muted)  …
> fix border color discrepancy between themes

- scss/_patterns_pagination.scss
* Add theme support for active pagination button
Fixes [WD-10537](https://warthogs.atlassian.net/browse/WD-10537)
- Go to `/docs/examples/patterns/pagination/pagination`
- Switch themes and see active pagination button's styles update correctly
[if relevant, include a …
> Add theme support for active pagination button

- scss/_patterns_rule.scss
Update rule component to use new theme colours
- Open [demo](https://vanilla-framework-5064.demos.haus/docs/examples/patterns/rule/muted)
- Check rule component example (with muted rules): https://vanilla-framework-5064.demos.haus/docs/examples/patterns/rule/muted
- Make sure it works fine across themes
- Check inspector if the lines use CSS variables
> Update rule component to use new theme variables

- scss/_patterns_navigation.scss
- Fixes a suspected regression in the navigation pattern that causes the "back" button in smaller breakpoints to point right instead of left.
Fixes #5059 
- Reduce screen size to the medium breakpoint such that the mobile version of the nav appears.
- Tap `Menu`
- Select any sub-menu (such as LXD). Verify that its chevron to open the nested navigation is pointing to the right, indicating drilling into the navigation.
- Open the sub-menu.
- Verify that the back button is visible and its chevron points left.
- if CSS class names are not changed it can be …
> Navigation "back" button chevron points left instead of right

- scss/_base_forms.scss
On the largest breakpoint the labels line-height wasn't set correctly. It was `30.375px` when it should be 1.5rem with 18px as 1rem, so 27px. This made the base line drift on large view ports.
- Open demo
- Check labels line-height on largest view port
> Label line-height on large breakpoint fix

- side-navigation.yaml
- templates/docs/patterns/hero.md
Update Hero documentation by removing "pattern" from page title.
- Open [demo](https://vanilla-framework-5082.demos.haus/docs/patterns/hero)
- Make sure "Hero" is not called pattern in side nav or title
> Don't name hero a pattern

- releases.yml
- scss/_patterns_equal-height-row.scss
- templates/docs/examples/patterns/equal-height-row/4-items-per-column.html
- templates/docs/patterns/equal-height-row.md
- removes bottom spacing from the component
- removes full width dividers 
- updates dividers to use low contrast border colour
- updates divider class names to be easier to handle (from `has-1st-divider` to `has-divider-1`) (this is technically breaking change, but as it's [barely used](https://github.com/canonical/ubuntu.com/blob/28474baeadf613058bd506048969df92fc2bd720/templates/desktop/index.html#L372) we can get away with it)
Fixes [WD-10920](https://warthogs.atlassian.net/browse/WD-10920)
- Open [demo](https://vanilla-framework-5081.demos.haus/docs/examples/patterns/equal-height-row/4-items-per-column)
- Check the divider line (across columns) on large screen, make sure it's using low contrast border color
- Check if the divider is removed on smaller screens (medium and small)
- …
> Equal heights updates

- side-navigation.yaml
- templates/_layouts/docs.html
- webapp/app.py
@bartaz noticed today that the ordering of items in the side-nav is not alphabetical (as he was expecting it to be). This PR alphabetizes the sidenav items by title using Python, hopefully eliminating the tech debt of manually ensuring the nav items are alphabetized and preventing this sort of issue from arising in the future.
This is configurable in `side-navigation.yaml` so that only nav items with `ordering: alphabetical` have their subheadings sorted (since there are still some cases where we want fine-grain control over subheading order, such as "Welcome".
This results in a few changes to the sidenav ordering vs our current setup:
- Base elements
- "Paper background" moved to the end
- Components
- "Equal height row" moved to after "Empty state"
- Utilities
- "Show" moved to after …
> Alphabetize documentation sidenav elements

- templates/docs/patterns/accordion/accessibility.md
Updates accessibility docs for accordions
Fixes [WD-5698](https://warthogs.atlassian.net/browse/WD-5698)
- Open [demo](https://vanilla-framework-5083.demos.haus/docs/patterns/accordion/accessibility)
- Open [copy doc](https://warthogs.atlassian.net/browse/WD-5698)
- Verify that accessiblity documentation matches copy doc
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-r …
> Update accordion accessibility documentation

- scss/standalone/patterns_empty-state.scss
- templates/docs/examples/patterns/empty-state/error-management.html
- templates/docs/patterns/empty-state.md
Updates the empty state error management pattern to match the updated branding / copy seen on [c.com](https://canonical.com/404_example).
Fixes [WD-7904](https://warthogs.atlassian.net/browse/WD-7904)
- Open [demo](https://vanilla-framework-5079.demos.haus/docs/examples/patterns/empty-state/error-management)
- Open [c.com 404](https://canonical.com/404_example)
- Verify that the branding / copy matches between the error management empty state example and the c.com 404 page. …
> Update empty state 404 documentation example to match new branding

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Release drafter reads the version number from `package.json` and automatically populates tag and release name.
Closes [WD-11112](https://warthogs.atlassian.net/browse/WD-11112)
Due to the release drafter action being run on pushes to `main`, I tested this in my fork to avoid unnecessarily cluttering our draft releases / `main` commit history.
- View the [release](https://github.com/jmuzina/vanilla-framework/releases/tag/v4.12.0) automatically created by [this workflow run](https://github.com/jmuzina/vanilla-framework/actions/runs/9003871537) (ran by [this action](https://github.com/jmuzina/vanilla-framework/blob/2cc11acf87fb8a851c0c02aeab03097ebb307829/.github/workflows/release-drafter.yml) with [this config](https://github.com/jmuzina/vanilla-framework/blob/2cc11acf87fb8a851c0c02aeab03097 …
> Release drafter pulls tag number from package.json automatically

- package.json
- releases.yml
- scss/_base_typography.scss
- Added `text-wrap: pretty` to _base_typography.scss in order to prevent text widows on browsers that support the `pretty` value.
- Open [demo](https://vanilla-framework-5090.demos.haus/)
- QA: Examine text elements across documentation site and see that no text widows should exist
See below comments for any …
> Add text-wrap: pretty to _base_typography.scss

- templates/docs/examples/patterns/links/links-skip.html
- Updates the logo used in the [skip-link example](https://vanillaframework.io/docs/examples/standalone/patterns/links/links-skip) to the new CoF logo.
- Updates the skip-link nav example to follow new default nav layout.
Fixes [WD-11267](https://warthogs.atlassian.net/browse/WD-11267)
- Open [demo](https://vanilla-framework-5091.demos.haus/docs/examples/standalone/patterns/links/links-skip)
- Verify that the navigation on the skip-link component matches the updated branding. Compare it to the [navigation pattern](https://vanillaframework.io/docs/examples/standalone/patterns/navigation/default). 
- Verify that the skip-link functionality still works (appears on keyboard focus, & skips to main content on activation)
If this PR contains Vanilla SCSS code changes, it should contain the …
> Update skiplink example docs to match new branding

- scss/_patterns_modal.scss
Updates modal component to support dark theme (via new color variables).
Related to: https://warthogs.atlassian.net/browse/WD-11799
Fixes: [WD-11829](https://warthogs.atlassian.net/browse/WD-11829)
- Make sure modal examples work well in dark theme:
- https://vanilla-framework-5106.demos.haus/docs/examples/patterns/modal/default?theme=dark
- https://vanilla-framework-5106.demos.haus/docs/examples/patterns/modal/footer?theme=dark
- https://vanilla-framework-5106.demos.haus/docs/examples/patterns/modal/modal-scroll?theme=dark …
> Update modal component to support new theming variables

- scss/_patterns_segmented-control.scss
Updates segmented control component so that the divider line between segmented control buttons uses new color theme variables.
This results in a change to the dark theme appearance of the segmented control, as previously it was always using the light theme appearance. 
Fixes [WD-11861](https://warthogs.atlassian.net/browse/WD-11861)
- Open [segmented control example](https://vanilla-framework-5111.demos.haus/docs/examples/patterns/segmented-control/dense?theme=light)
- Verify that the color of the separator bar between segmented control buttons is correct in each theme.
- if CSS …
> Update segmented control to use new color theme variables

- templates/docs/patterns/icons/index.md
Fixes misleading documentation for importing icon mixins. The [current documentation](https://vanillaframework.io/docs/patterns/icons#import) directs users to import 3 mixins that do not exist (and would cause build errors if used):
- `vf-p-icon-chevron-up`
- `vf-p-icon-chevron-down`
- `vf-p-icon-information`
This updates the documentation to direct users to import `vf-p-icon-chevron` and `vf-p-icon-info` instead.
Fixes #5094, [WD-11768](https://warthogs.atlassian.net/browse/WD-11768)
The [icons page](https://vanillaframework.io/docs/patterns/icons) uses the same [array of icon names](https://github.com/canonical/vanilla-framework/blob/d0197b27f5733789d6d23536eabe68356e045ae1/templates/docs/patterns/icons/index.md?plain=1#L21) to do two different things:
- Generate the icons sections that …
> Fix misleading icon import documentation

- package.json
- scss/_base_forms.scss
- scss/_patterns_navigation.scss
- scss/_patterns_search-box.scss
In #4948 we increased the top navigation padding (to better align with the grid in documentation layout), but this increased padding causes issues in navigations with many elements (most importantly the meganav).
So, to better align with meganav needs we are reverting this change back. Top navigation items no longer use grid margin as their padding value, but are back to using standard large spacing variable.
This change affects navigation paddings, their alignment, and the alignment of navigation search and dropdown icons with form elements.
Fixes https://warthogs.atlassian.net/browse/WD-11984
- Open [demo](https://vanilla-framework-5116.demos.haus/docs/examples/patterns/navigation/default?theme=light)
- Review updated examples to make sure they look correct (the change should only …
> Reduce padding on navigation items

- package.json
- scss/_patterns_table-of-contents.scss
- Replaced old color variables with new color theme variables for improved theming support
Fixes [WD-11872](https://warthogs.atlassian.net/browse/WD-11872)
- Open [Table of Contents demo](https://vanilla-framework-5113.demos.haus/docs/examples/patterns/table-of-contents/sections?theme=light)
- Verify Table of Contents appears as expected (with slight, intentional change to bottom border color) …
> Update Table of Contents to use new color theme variables

- scss/_base_placeholders.scss
- scss/_patterns_card.scss
- scss/_settings_placeholders.scss
- templates/docs/examples/patterns/card/header.html
- templates/docs/examples/patterns/card/overlay.html
Updates the card component to use new color theme variables & thus support theming.
Note that the image used in the header example was changed as the [old one](https://vanillaframework.io/docs/examples/patterns/card/header) is not friendly to all themes (dark text becomes impossible to read on dark theme)
Fixes [WD-11865](https://warthogs.atlassian.net/browse/WD-11865)
- Review [card docs](https://vanilla-framework-5112.demos.haus/docs/patterns/card) & verify cards appear as expected.
- Review all card examples and verify they look as expected in all color themes.
- [Default](https://vanilla-framework-5112.demos.haus/docs/examples/patterns/card/default?theme=light)
- [Content bleed](https://vanilla-framework-5112.demos.haus/docs/examples/patterns/card/content-bleed?theme=light)
- …
> Update card pattern to support color themes

- scss/_patterns_navigation.scss
- scss/_settings_colors.scss
Updates dark theme alt background colour to `#202020` to make it darker than default `#262626`.
Drive-by: top navigation items were updated to use hover theme colours instead of alt background.
- Review affected examples, make sure they are using correct value.
- https://vanilla-framework-5128.demos.haus/docs/examples/patterns/strips/highlighted?theme=dark
- highlighted strip in dark mode should be #202020 (background alt variable) …
> Update alternative background colour in dark theme

- scss/_patterns_lists.scss
Updates the lists pattern to use newer color theme variables.
Affects the following:
- Color of bullets in unordered lists
- Color of sequence numbers in ordered lists
- Color of the bottom border of the last list element in a split list
Fixes [WD-11866](https://warthogs.atlassian.net/browse/WD-11866)
- Open Ordered list examples: Verify that sequence numbers color is correct in all thtmes
- [Stepped/Detailed](https://vanilla-framework-5124.demos.haus/docs/examples/patterns/lists/list-nested-stepped-detailed?theme=light)
- [With dividers](https://vanilla-framework-5124.demos.haus/docs/examples/patterns/lists/lists-dividers-ordered?theme=light)
- [Split list example](https://vanilla-framework-5124.demos.haus/docs/examples/patterns/lists/lists-split?theme=light): Verify that the color of …
> Update lists pattern to use new color theme variables

- scss/_patterns_article-pagination.scss
- templates/docs/examples/patterns/article-pagination.html
Updates Article Pagination pattern to use new theme variables.
This affects:
- Color of the previous/next button text. It now uses the default text color.
- Color of the previous/next button chevrons. It now uses the default icon color.
Fixes [WD-11864](https://warthogs.atlassian.net/browse/WD-11864)
While working on this, I also noticed that the back/next buttons can be updated to use the new chevron left/right code, and made #5125. 
- Open [demo](https://vanilla-framework-5126.demos.haus/docs/examples/patterns/article-pagination?theme=light).
- Verify that the color of all text & chevrons is correct in all themes.
- `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, …
> Update article pagination to use new theme variables

- .github/workflows/publish-on-release.yml
As part of my efforts for creating a new Figma library I have added a [script to the webteam bot](https://github.com/canonical/webteam-hubot/blob/main/scripts/figma-library-alerts.js) which can be used to alert Figma library maintainers in the `~Figma library maintainers` chat of changes of sources of truth. Amongst those sources of truth we need to keep track of to keep the Figma libraries up to date is of course Vanilla CSS.
This PR adds a job to the Github action that is triggered on release of a new Vanilla version and sends the sections 🚀 Features, 🐛 Bug Fixes and 🔨 Maintenance of the release notes as an alert to the bot to notify Figma library maintainers of the changes to Vanilla CSS
Additionally to these changes we would need to add the chat bots URL to the action secrets of the …
> Notify Figma library maintainers on release

- scss/_patterns_accordion.scss
Updated the accordion pattern to use new color theme variables, making it theme-friendly.
Affects:
- Accordion open/close state chevrons are now themed
- Accordion header hover color is now themed
Fixes [WD-11863](https://warthogs.atlassian.net/browse/WD-11863)
- Open [demo](https://vanilla-framework-5138.demos.haus/docs/examples/patterns/accordion/tick-elements?theme=light)
- Verify that the color of the expand/collapse chevrons and header section hover colors is correct on all color themes.
- if CSS class …
> Update accordion pattern to use new color theme variables

- package.json
- releases.yml
- scss/_patterns_image.scss
- templates/docs/examples/patterns/image/container/aspect-ratio/16-9.html
- templates/docs/examples/patterns/image/container/aspect-ratio/all.html
- templates/docs/examples/patterns/image/container/highlighted.html
- templates/docs/patterns/images.md
Added several classes that will help unify the appearance of images in projects that use Vanilla, and deprecated some styles that are no longer part of branding.
- `p-image-container--` classes for setting element aspect ratio.
- `p-image-container--16-9`
- `p-image-container--3-2`
- `p-image-container--2-3`
- `p-image-container--cinematic`
- `p-image-container--square`
- `p-image-container .is-highlighted` for distinguishing an image from its surroundings by applying a slight underlay.
- Deprecated image modifiers `p-image--bordered` and `p-image--shadowed`
Closes: #4876 [WD-11412](https://warthogs.atlassian.net/browse/WD-11412)
- Review updated [Images pattern documentation](https://vanilla-framework-5097.demos.haus/docs/patterns/images)
- Review [updated release notes for …
> Add new image container component and deprecate legacy image variants

- templates/_layouts/examples.html
- webapp/app.py
This is some preparatory code that the example combination PRs that are coming next depend on.
- Adds flag `is_combined` to the examples base template. If the flag is set, the stylesheet/scripts will not be added to the header, as otherwise they would be requested multiple times in the case of a combined example. This lets the examples embedded in combined examples use the scripts/styling loaded in their parent example.
- Hides 'combined' examples from the examples index view, since they are really only intended for usage by testing agents, not users.
> Percy examples combination preparation (jinja/python enablement code)

- scss/standalone/combined.scss
- templates/docs/examples/base/paper/combined.html
- templates/docs/examples/base/paper/input-on-paper.html
- templates/docs/examples/base/paper/search-box-on-paper.html
Combines `base/paper` examples.
Depends on #5142 (includes its code)
- Review [combined paper example](https://vanilla-framework-5148.demos.haus/docs/examples/base/paper/combined)
This example should be revisited later - it is [very theme-specific](https://vanillaframework.io/docs/base/paper) and I'm not yet sure what `.on-paper` is for (is it to be deprecated once all sites move to paper background?) - in this implementation this combined example will be screenshotted on light & dark for no reason, but I think it's worth it since we are decreasing our usage so much in other areas.
> Percy examples combination - `base/paper`

- scss/standalone/combined.scss
- templates/docs/examples/patterns/accordion/combined.html
- templates/docs/examples/patterns/badge/combined.html
- templates/docs/examples/patterns/card/combined.html
- templates/docs/examples/patterns/empty-state/combined.html
- templates/docs/examples/patterns/equal-height-row/combined.html
- templates/docs/examples/patterns/grid/combined.html
- templates/docs/examples/patterns/heading-icon/combined.html
- templates/docs/examples/patterns/headings/combined.html
- templates/docs/examples/patterns/hero/combined.html
- templates/docs/examples/patterns/image/combined.html
- templates/docs/examples/patterns/image/container/aspect-ratio/all.html
- templates/docs/examples/patterns/media-object/combined.html
- templates/docs/examples/patterns/pagination/combined.html
- templates/docs/examples/patterns/pull-quotes/combined.html
- templates/docs/examples/patterns/section/combined.html
- templates/docs/examples/patterns/segmented-control/combined.html
- templates/docs/examples/patterns/strips/combined.html
- templates/docs/examples/patterns/tab-buttons/combined.html
- templates/docs/examples/patterns/table-of-contents/combined.html
- templates/docs/examples/patterns/tooltips/combined.html
Combines simpler examples from `patterns/` directory. Simple examples are examples for which we are not deleting or moving any example files; we are simply adding a `combined.html` file that includes all of the other examples for that component. This was done to prevent having to separately review many PRs with identical QA tasks.
This PR adds combinations for:
- accordion
- badge
- card
- empty state
- equal height row
- grid
- heading icons
- headings
- hero
- image
- media object
- pagination
- pull quote
- section
- segmented control
- strip
- tab button
- table of contents
- tooltips
As a drive-by, I also altered the all aspect ratios image container example to embed the 16-9 example instead of duplicating its code.
Depends on #5142 (includes its code)
- Visit all combined examples …
> Percy examples combination - `patterns/` simple combinations

- redirects.yaml
- scss/standalone/combined.scss
- templates/docs/examples/patterns/code-snippet/combined.html
- templates/docs/examples/patterns/code-snippet/default-dark.html
- templates/docs/examples/patterns/code-snippet/dropdown-multiple-dark.html
- templates/docs/examples/patterns/code-snippet/icon-dark.html
Combines code snippet
Depends on #5142 (includes its code)
Deletes the dark button examples
- Review [combined code snippet example](https://vanilla-framework-5155.demos.haus/docs/examples/patterns/code-snippet/combined)
- Verify redirects
- https://vanilla-framework-5155.demos.haus/docs/examples/patterns/code-snippet/default-dark -> https://vanilla-framework-5155.demos.haus/docs/examples/patterns/code-snippet/default?theme=dark
- https://vanilla-framework-5155.demos.haus/docs/examples/patterns/code-snippet/dropdown-multiple-dark -> https://vanilla-framework-5155.demos.haus/docs/examples/patterns/code-snippet/dropdown-multiple?theme=dark
- https://vanilla-framework-5155.demos.haus/docs/examples/patterns/code-snippet/icon-dark -> https://vanilla-framework-5155.demos.haus/docs/examples/patte …
> Percy examples combination - `patterns/code-snippet`

- .github/workflows/pr-percy-prepare-label.yml
- .github/workflows/pr-percy-prepare-push.yml
Fixes Percy tests [not being run properly against](https://github.com/canonical/vanilla-framework/actions/runs/9648272740/job/26609053207?pr=5185) PRs with multiple labels.
The array of label names was being converted to "Array" and my if checks were failing. I quoted the conditionals on the jobs, converted them to JSON, and also removed the dependence on a repo variable for the label name.
- Review comments / action runs on test PR: https://github.com/jmuzina/vanilla-framework/pull/23
- Verify labeled workflow was run against this PR while it had the Percy needed label: https://github.com/canonical/vanilla-framework/actions/runs/9650404273
- `Feature 🎁`, …
> fix Percy workflows not running correctly in multi-label case

- package.json
- scss/_patterns_image.scss
- templates/docs/examples/patterns/image/container/aspect-ratio/all.html
Fixes image container aspect ratio not being respected on smaller displays.
Fixes #5159 
- Open [demo](https://vanilla-framework-5179.demos.haus/docs/examples/patterns/image/container/aspect-ratio/all)
- Verify that all images are the correct aspect ratio in all breakpoints.
> Fix aspect ratio in image container component on smaller screens

- scss/standalone/patterns_logo-section.scss
In #5164 , we made the dark logo section example use a `.p-strip .is-dark` to ensure its background is always dark. We did not add the strip to the logo-section's standalone styles, causing this in the standalone view:
As a drive-by, I also added `vf-u-layout` to the standalone styles, as the logo section examples use `.u-fixed-width` which is exported there. This causes the logo section to have the wrong width, even on current `main`:
- Verify dark logo section appears the same on [standalone](https://vanilla-framework-5193.demos.haus/docs/examples/standalone/patterns/logo-section/logo-section-dark) and [non-standalone](https://vanilla-framework-5193.demos.haus/docs/examples/patterns/logo-section/logo-section-dark) views
> Fix standalone logo section scss

- scss/_settings_colors.scss
Update alt background in paper theme from white to `#EBEBEB` (to be darker than default) 
Fixes #5197
- Open [demo](https://vanilla-framework-5198.demos.haus/docs/examples/patterns/image/container/highlighted?theme=paper)
- Make sure that the highlighted colour on paper theme is correct
- Check other affected components:
- https://vanilla-framework-5198.demos.haus/docs/examples/patterns/strips/highlighted
- see the [wiki for …
> Update alt background in paper theme

- releases.yml
- scss/_patterns_image.scss
- templates/docs/examples/patterns/image/combined.html
- templates/docs/examples/patterns/image/container/cover.html
- templates/docs/patterns/images.md
Adds image cover option to image container component, using `is-cover` modifier class.
Fixes [WD-12281](https://warthogs.atlassian.net/browse/WD-12281)
- Open [demo](https://vanilla-framework-5199.demos.haus/docs/examples/patterns/image/container/cover?theme=light)
- Check if the image covers the container
- Change the container class to some other aspect ratio, such as `p-image-container--3-2` or `p-image-container--square`, verify that image adapts correctly (and still covers the container)
- https://vanilla-framework-5199.demos.haus/docs/patterns/images#cover-image …
> Add cover option to image container component

- .github/actions/percy-snapshot/action.yml
- snapshots.js
Improves error logging of the Percy snapshots action
Fixes [MM thread](https://chat.canonical.com/canonical/pl/5ixu487xjpgduntgmzxyohipaw)
As a drive-by, fixes [snapshots being taken of the examples index page](https://chat.canonical.com/canonical/pl/fjfpwwkph3f6ukme4nytmjym4w). This removes 8 snapshots from the Percy tests:
- `docs/examples/index` (in all themes, in mobile & desktop breakpoints) (4 snapshots)
- `docs/examples/standalone` (in all themes, in mobile & desktop breakpoints) (4 snapshots)
- Review [failing Percy workflow](https://github.com/jmuzina/vanilla-framework/actions/runs/9746570483/job/26897246078); verify you can see the Percy command output
- Review [passing Percy workflow](https://github.com/jmuzina/vanilla-framework/actions/runs/9746567016); verify you can see the …
> Percy Error Logging Improvement

- scss/_patterns_image.scss
#5199 added the `is-cover` variant of `p-image-container` but did not add it to the class reference table. This is a small PR to add `is-cover` to the class reference list.
- Open [image container class reference docs](https://vanilla-framework-5207.demos.haus/docs/patterns/images#class-reference) and verify they are correct (`.is-cover` added correctly) …
> Add `is-cover` to image container class reference

- package.json
- scss/_base_icon-definitions.scss
- scss/_patterns_navigation-reduced.scss
Visual adjustments for reduced navigation:
- shifting Canonical logo to make it aligned with logo text below it and with nav items on mobile
- updateing icon colours to use muted colour in reduced nav on desktop
Fixes https://warthogs.atlassian.net/browse/WD-12921
Fixes https://warthogs.atlassian.net/browse/WD-12922
- Open [demo](https://vanilla-framework-5206.demos.haus/docs/examples/patterns/navigation/reduced?theme=light)
- Make sure that chevron and search icons are the same colour as text it top reduced navigation bar
- Make sure "Canonical Ubuntu" logo text is aligned with Ubuntu text below
- On small screen open the top "Menu", make sure "Canonical Ubuntu" is aligned with menu items
If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure …
> Styling updates for reduced navigation

- scss/_patterns_navigation-reduced.scss
- scss/_patterns_navigation.scss
- templates/docs/examples/patterns/navigation/_script-sliding.js
- templates/docs/examples/patterns/navigation/reduced.html
When reduced navigation is used (with secondary navigation) the search is displayed on top of secondary navigation (and used to be defined there in markup). But to simplify templating we want to keep the search in the top (reduced) navigation that triggers it.
This PR addresses it by moving search HTML from secondary nav to top reduced navigation and adjusts the styling to use absolute positioning to display open search on top of the secondary navigation.
Fixes https://warthogs.atlassian.net/browse/WD-13032
- Open [demo](https://vanilla-framework-5210.demos.haus/docs/examples/patterns/navigation/reduced?theme=light)
- Check the search functionality, both on desktop and mobile screen sizes
If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure …
> Move search into the reduced navigation

- scss/_patterns_navigation-reduced.scss
Aligns Canonical logo in reduced navigation with the grid.
- Open [demo](https://vanilla-framework-5215.demos.haus/docs/examples/patterns/navigation/reduced?theme=light)
- Make sure "Canonical" in top reduced navigation is aligned with left side of the page/grid on desktop view
- Make sure "Canonical" is shifted to be aligned with "Ubuntu" logo text and navigation menu items on small screens
> Align logo in reduced nav with the grid

- templates/docs/examples/patterns/grid/empty-columns.html
- templates/docs/examples/patterns/grid/incorrect-empty-columns.html
- templates/docs/examples/patterns/grid/nested-medium.html
- templates/docs/examples/patterns/grid/nested-small.html
- templates/docs/examples/patterns/grid/nested.html
- templates/docs/examples/patterns/grid/offsets.html
- templates/docs/examples/patterns/grid/responsive.html
- Fixed incorrect labels on Nested and Offset grid examples
- Added missing periods on other grid examples
Fixes #5221 
- Open the following grid examples:
- [empty columns](https://vanilla-framework-5222.demos.haus/docs/examples/patterns/grid/empty-columns?theme=light)
- [incorrect empty columns](https://vanilla-framework-5222.demos.haus/docs/examples/patterns/grid/incorrect-empty-columns?theme=light)
- [nested medium](https://vanilla-framework-5222.demos.haus/docs/examples/patterns/grid/nested-medium?theme=light)
- [nested small](https://vanilla-framework-5222.demos.haus/docs/examples/patterns/grid/nested-small?theme=light)
- [nested all](https://vanilla-framework-5222.demos.haus/docs/examples/patterns/grid/nested?theme=light)
- …
> Correct labels on grid examples

- .github/actions/percy-snapshot/action.yml
Performs the following Percy configuration changes per debugging instructions from Browserstack support (see [Jira ticket](https://warthogs.atlassian.net/browse/WD-13163)):
- Increase page load timeout from 30s to 120s
- Set debug log level to "debug" to show more logging output
Hopefully, this will prevent snapshots from timing out.
Fixes [WD-13163](https://warthogs.atlassian.net/browse/WD-13163)
- Verify that [test workflow](https://github.com/jmuzina/vanilla-framework/actions/runs/9962635580/job/27526861741) ran successfully and includes verbose logging output.
- if CSS class …
> Fix Intermittent Percy Snapshot Timeouts

- .github/.jira_sync_config.yaml
Add GH-Jira issues integration. Uses [Canonical gh-jira-sync-bot](https://github.com/canonical/gh-jira-sync-bot).
This is configured to synchronize GH issues with the [Vanilla Maintenance epic on Jira](https://warthogs.atlassian.net/browse/WD-189).
Fixes [WD-11827](https://warthogs.atlassian.net/browse/WD-11827)
- Review [sync bot README](https://github.com/canonical/gh-jira-sync-bot/blob/main/README.md). Verify that the configuration introduced by this PR is correct. …
> Sync Github Issues to Jira Issues

- templates/docs/patterns/suru.md
Fixes duplication of suru fan-top and fan-bottom examples in the pyramid suru section
Fixes [WD-12500](https://warthogs.atlassian.net/browse/WD-12500)
- Open [suru docs](https://vanilla-framework-5232.demos.haus/docs/patterns/suru)
- Verify that the "pyramid suru" section shows Suru pyramid left & right examples, instead of "fan top" & "fan bottom" examples that are shown on [production](https://vanillaframework.io/docs/patterns/suru). …
> Fix duplicated suru fan examples

- webapp/app.py
Removes bots from the contributors list
Fixes #5098 
- Open [contributors page](insert-demo-url)
- Check if bots are removed from the contributors list.
> Remove bots from the contributors list

- templates/docs/examples/patterns/strips/image.html
Changes background image used in deprecated strip with image example to hopefully reduce load time on Percy and reduce instances of the strips example being dropped from Percy tests.
Fixes [WD-13163](https://warthogs.atlassian.net/browse/WD-13163)
- Verify [strip image example](https://vanilla-framework-5237.demos.haus/docs/examples/patterns/strips/image?theme=light) background is loaded  …
> Change strips image example background to decrease load time

- .github/workflows/percy-prepare.yml
- .github/workflows/pr-percy-prepare-push.yml
- .github/workflows/pr-percy-snapshots.yml
- guides/pull-requests.md
Adds the `templates/_macros` directory to the list of directories copied from PRs into Percy test context.
Fixes Macros not being included in Percy tests, causing 404/500 errors as in #5212 such as [this](https://percy.io/bb49709b/vanilla-framework/builds/35523329/changed/1941417829?browser=chrome&browser_ids=59&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280).
Adds some additional logging to the Percy workflows to help uncover what's happening in cases like this quicker in the future.
- Review [test PR ](https://github.com/jmuzina/vanilla-framework/pull/29)
- Verify that the split list examples snapshotted in the [linked build](https://percy.io/bb49709b/test-vanilla-gha-migration/builds/35525138/chan …
> Add `templates/_macros` to percy tests

- .github/workflows/pr-percy-snapshots.yml
Fixes PRs that don't have `templates/_macros` folders causing [Percy snapshots to fail](https://github.com/canonical/vanilla-framework/actions/runs/10114433037)
- Verify [test PR](https://github.com/jmuzina/vanilla-framework/pull/30) has no `templates/_macros` folder and runs [Percy snapshots workflow](https://github.com/jmuzina/vanilla-framework/actions/runs/10114547016) successfully …
> Percy macros artifact fix

- .github/workflows/pr-percy-snapshots.yml
Removes the `percy_upload` status check that is applied to PRs once Percy has been run on them. [WD-11227](https://warthogs.atlassian.net/browse/WD-11227) [integrated Github with Percy ](https://www.browserstack.com/docs/percy/source-code-integrations/github), and the Percy integration now applies its own status check that is more helpful.
- Review [testing PR](https://github.com/jmuzina/vanilla-framework/pull/28) and its comments. …
> Remove percy_upload status check

- templates/_layouts/_class-reference.html
Reduces extra whitespace used by documentation class reference tables.
Previous implementation was using old nested grid implementation. This updates grid as such:
- Top level grid is now 25/75 split on large instead of 16/58
- Nested grid is now 33/66 on large and medium instead of 43/57 on large and 40/60 on medium
Fixes #5238, [WD-13574](https://warthogs.atlassian.net/browse/WD-13574)
- Open some class reference tables and verify they look good across all breakpoints. The following components have class reference tables:
- [Code snippet](https://vanilla-framework-5247.demos.haus/docs/base/code#class-reference)
- [CTA block](https://vanilla-framework-5247.demos.haus/docs/patterns/cta-block#class-reference)
- [Image](https://vanilla-framework-5247.demos.haus/docs/patterns/images#class-ref …
> Remove excess whitespace in class reference table

- scss/_base_placeholders.scss
Fixes #5228 Duplicate css of overflow and padding 
> Fixes #5228 duplicate css

- scss/_base_forms.scss
- Remove deprecated -webkit-search-cancel-button pseudo-element styles
This pseudo-element appears to have been deprecated and removed from Webkit, displaying the following console alert on pages it's used on:
```
The keyword 'searchfield-cancel-button' used on the 'appearance' property was deprecated and has now been removed. It will no longer have any effect.
```
I believe this means it can be safely removed with no ill effects. See linked Issue for more context.
Fixes #5088 
- Open [search box demo](https://vanilla-framework-5265.demos.haus/docs/examples/patterns/search-box/default?theme=light)
- Input some text into the search input
- Witness no browser-styled reset button; only 2 buttons should be Vanilla-provided
If this PR contains Vanilla SCSS code changes, it should contain the …
> Remove deprecated -webkit-search-cancel-button pseudo-element styles

- releases.yml
- scss/_patterns_grid.scss
- templates/docs/examples/layouts/fluid-breakout/visualize-grid.css
- templates/docs/examples/patterns/grid/bordered.html
Removes old color theme variables from `patterns_grid`
- Changes background of the red grid rows in grid examples to a themed value
- Changes border color of `row.is-bordered` to a themed value
- Deprecates `.row.is-bordered`
Fixes [WD-11876](https://warthogs.atlassian.net/browse/WD-11876)
- Open [combined grid example](https://vanilla-framework-5256.demos.haus/docs/examples/patterns/grid/combined) and verify the red boxes look as expected on all themes
- Open [bordered grid example](https://vanilla-framework-5256.demos.haus/docs/examples/patterns/grid/bordered) and verify the border looks as expected on all themes
- Review [deprecation notice](https://vanilla-framework-5256.demos.haus/docs/whats-new) for `.row.is-bordered`
If this PR contains Vanilla SCSS code changes, it should contain …
> Fix theming of grid examples

- scss/_patterns_navigation-reduced.scss
Updates the styling of top reduced navigation on mobile screens to match desktop:
- changes background to alternative
- changes text colour (and icons) to muted
Fixes https://warthogs.atlassian.net/browse/WD-13652
- Open [demo](https://vanilla-framework-5246.demos.haus/docs/examples/patterns/navigation/reduced?theme=light)
- Check the very top navigation bar (the one that says Canonical) on mobile screen
- Make sure that the background and text colour is the same as on large screen (not the same as navigation below it)
- if CSS class names are not changed it can be bugfix release …
> Update styling of reduced nav on small screens

- snapshots.js
- tests/snapshots.test.js
- Light examples are snapshotted responsively
- Dark/paper examples are snapshotted on desktop only
- Slightly simplified / cleaned up snapshots JS code by adding some constants to reduce literal duplication
Fixes [WD-13804](https://warthogs.atlassian.net/browse/WD-13804)
- View [test build](https://percy.io/bb49709b/test-vanilla-gha-migration/builds/35631002/changed/1946954265?browser=chrome&browser_ids=59&group_snapshots_by=similar_diff&subcategories=approved&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C800%2C1280) and verify snapshots are captured as expected
- Pay special attention to the relationship between theme and breakpoints
- All snapshots are captured at 1280px (desktop/large size)
- Light-theme examples are also captured at 375px (mobile/small size)
- Examples that …
> Simplify Percy Breakpoint/Theme snapshots

- scss/_patterns_navigation.scss
Moves tagged navigation icon closer to official logo design
Fixes #5186, [WD-12707](https://warthogs.atlassian.net/browse/WD-12707)
- Verify that navigation logos are properly aligned and the wordmark is properly spaced in relation to the logo
- Check CoF logo by checking a [navigation example](https://vanilla-framework-5258.demos.haus/docs/examples/patterns/navigation/dropdown?theme=dark)
- Check Vanilla logo by visiting the [homepage](https://vanilla-framework-5258.demos.haus/)
- Verify that the header's height is a multiple of baseline grid units (8px)
- if CSS class names are not …
> Fix tagged navigation icon spacing

- package.json
- releases.yml
- scss/_patterns_cta.scss
- templates/docs/examples/patterns/cta-block/borderless.html
- templates/docs/examples/patterns/cta-block/combined.html
- templates/docs/patterns/cta-block/index.md
- Adds `.p-cta-block.is-borderless`. It was not initially needed in #5196 but it has become necessary for completion of #5275.
- CTA block now has two examples, so I've added a `combined.html` example for them. This means that Percy will be missing the existing CTA block snapshot, and snapshot the new combined example instead.
Fixes #5277, [WD-13924](https://warthogs.atlassian.net/browse/WD-13924)
- Verify [borderless CTA block example](https://vanilla-framework-5278.demos.haus/docs/examples/patterns/cta-block/borderless?theme=light) has no top border and no top padding
- Verify [default CTA block example](https://vanilla-framework-5278.demos.haus/docs/examples/patterns/cta-block/default?theme=light) has a top border
- Verify all of the above is still true for the [combined …
> Add borderless CTA block variant

- scss/docs/example.scss
- templates/docs/examples/patterns/grid/responsive.html
Fixes the responsive grid example not being rendered correctly in the combined grid example. I moved its style block from the responsive example itself into a example-specific utility class that is applied to the example's main container.
Fixes #5284, [WD-13997](https://warthogs.atlassian.net/browse/WD-13997)
- Open [combined grid example](https://vanilla-framework-5285.demos.haus/docs/examples/patterns/grid/combined?theme=light) and verify that the responsive example's contents are rendered as expected. It should be at the bottom of the page.
- Very this is still true on [standalone](https://vanilla-framework-5285.demos.haus/docs/examples/standalone/patterns/grid/combined?theme=light) mode.
- Open the [responsive grid example by …
> Fix responsive grid example not rendering correctly in combined view

- package.json
- templates/docs/examples/patterns/navigation/_script-sliding.js
- Stop closing navigation on vertical resize, as this was causing the navigation to close unexpectedly when the top bar would automatically hide
- Open [demo](https://vanilla-framework-5302.demos.haus/)
- Check that the navigation closes on horizontal resize on desktop and mobile
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-release-t …
> bug: Don't close navigation on vertical resize

- scss/docs/example.scss
- templates/static/js/example-tools.js
Adds a button to the example controls toolbar that closes the controls toolbar. This allows content behind the toolbar to be seen.
Fixes #5283 , [WD-13996](https://warthogs.atlassian.net/browse/WD-13996)
- Open any example. Try [button](https://vanilla-framework-5309.demos.haus/docs/examples/base/button?theme=light).
- Click the "Close" button in the example toolbar.
- Verify the example controls toolbar is removed from view.
- Refresh the page.
- Verify the toolbar is rendered again. …
> Add button to close example toolbar

- releases.yml
- scss/_patterns_image.scss
- scss/_settings_breakpoints.scss
- templates/docs/examples/patterns/image/container/aspect-ratio/all.html
- templates/docs/examples/patterns/image/container/aspect-ratio/responsive-all.html
- templates/docs/examples/patterns/image/container/aspect-ratio/responsive.html
- templates/docs/patterns/images.md
- tests/snapshots.test.js
Adds new `-on-(large|medium|small)` variants of each aspect ratio image container class for more precise control over aspect ratios, depending on the screen size.
Fixes #5274, [WD-13920](https://warthogs.atlassian.net/browse/WD-13920)
- Open the [responsive-all example](https://vanilla-framework-5308.demos.haus/docs/examples/patterns/image/container/aspect-ratio/responsive-all?theme=light) and verify that the aspect ratio labels above each example there are correct by resizing the window. 
- Make sure to check at the breakpoints. As long as there are not two classes for the same breakpoint, no two responsive aspect ratio classes should be active.
- Large: `width >=1036px`
- Medium: `620px >= width < 1036px`
- Small: `width < 620px`
- Verify the responsive examples were added to the …
> Responsive image aspect ratio variants 

- templates/_layouts/examples.html
Wraps the links/names for examples embedded in combined examples in a `p` rather than a `div`. This improves the baseline alignment of combined examples, as the links themselves should not throw the combined example off of the baseline.
Note that individual examples may still throw the combined example off of the baseline, if the component itself has margin/padding issues.
Fixes #5324, [WD-14463](https://warthogs.atlassian.net/browse/WD-14463)
- Open any combined example. For example, [typography combined](https://vanilla-framework-5327.demos.haus/docs/examples/base/typography/combined?theme=light).
- Verify that the embedded example links are wrapped in a `<p>` and have correct paragraph padding & margin.
If this PR contains Vanilla SCSS code changes, it should contain the following …
> Improve combined example baseline alignment

- scss/_patterns_status-label.scss
- scss/_settings_colors.scss
This PR adds a comment above the `vf-p-status-label` to explain its use of hard-coded colors. The team has decided not to theme this component yet, but we still want to note it as needing revisiting in the future.
Fixes [WD-11860](https://warthogs.atlassian.net/browse/WD-11860)
[WD-11860]: …
> Add color theming explanation comment to status label mixin

- snapshots.js
- tests/snapshots.test.js
Groups Percy snapshots by example test case name. The example's path relative to repo root (ignoring `standalone/` and query parameters) is used as a test case name.
So, for example, given snapshots of `docs/examples/patterns/suru/combined?theme=light` and `docs/examples/standalone/patterns/suru/combined?theme=paper`, both snapshots are grouped under `docs/examples/patterns/suru/combined`
This means we can expect each base & pattern test case to have 6 snapshots (3 per color theme in non-standalone, and another 3 in standalone), and all other test cases will have 3 snapshots.
Read [Percy blog](https://www.browserstack.com/blog/introducing-test-case-base-grouping/) for more information on this feature.
Fixes [WD-13805](https://warthogs.atlassian.net/browse/WD-13805)
- Review [test …
> Group Percy snapshots by test case name

- snapshots.js
- tests/snapshots.test.js
This reverts commit 7ff9e824d74db75188468f5b51bb2f37079f79f0 (#5299). 
Upon merging #5299 to main, the resulting [baseline build](https://percy.io/bb49709b/vanilla-framework/builds/36215893/changed/1980308620?browser=chrome&browser_ids=59&category=changed%2Cunchanged&group_snapshots_by=test_case&subcategories=approved&test_case_category=changed&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C800%2C1280) was missing ~30 screenshots, which did not occur in QA. It appears there is still an intermittent issue to be fixed by Browserstack. They have been contacted for a fix, but this PR will revert the change in the meantime.
Until this is merged, Percy tests may have unpredictable screenshots missing.
If this PR contains Vanilla SCSS code changes, it should contain the following …
> Revert "Group Percy snapshots by test case name (#5299)"

- scss/_patterns_tooltips.scss
- templates/docs/examples/patterns/tooltips/_nesting-theme-override.jinja
- templates/docs/examples/patterns/tooltips/combined.html
- templates/docs/examples/patterns/tooltips/nesting-theme-override-dark.html
- templates/docs/examples/patterns/tooltips/nesting-theme-override-light.html
- templates/docs/patterns/tooltips/index.md
- Updates tooltips to invert their ancestor's color theme. I.E.: tooltips on dark use light theme, tooltips on light/paper use dark theme.
- Tooltips can be set to use a different theme than the inverse of the body, to handle cases where the tooltip is contained within an element that has a theme different from the body.
Fixes [WD-11871](https://warthogs.atlassian.net/browse/WD-11871)
- Verify that all tooltip examples look correct on all color themes. They should always use the opposite color theme.
- [Default](https://vanilla-framework-5326.demos.haus/docs/examples/patterns/tooltips/default?theme=light)
- [Detached](https://vanilla-framework-5326.demos.haus/docs/examples/patterns/tooltips/detached?theme=light)
- Theme overrides - ensure that the "correct" tooltip inverts the theme of …
> Add theme support to tooltip component

- .github/actions/percy-snapshot/action.yml
#5300 updated the Percy workflow to merge `main` into a PR before it is tested, but our dual-workflow approach seems to throw a wrench in Percy's [baseline build detection](https://www.browserstack.com/docs/percy/baseline-management/git#how-are-the-base-builds-selected-with-git): even though the files being tested are a merge of `main` with a PR, Percy may select a baseline build that is older than the current baseline build, causing false positive test results.
This occurred in #5338 (PR branch was cut from main before merge of #5270). However the [Percy build](https://percy.io/bb49709b/vanilla-framework/builds/36326870) used a baseline build from before the merge of #5270), causing the tree list snapshots to incorrectly appear as new.  It appears Percy needs to be manually instructed to …
> Manually set baseline build commit signature

- package.json
- scss/_global_functions.scss
- scss/_patterns_image.scss
- scss/_patterns_strip.scss
- scss/_patterns_switch.scss
- scss/_settings_colors.scss
- scss/_settings_placeholders.scss
- scss/_utilities_baseline-grid.scss
- scss/_utilities_font-metrics.scss
Change SASS function, which is tagged as **deprecated**
- `lightness` to `color.channel`
- `darken`, `lighten`, `transparentize` to `color.scale`
Use [SASS documentation](https://sass-lang.com/documentation/modules/color/)
- Unfortunately, I don't know how better to show a demo for checking the absence of warnings. But everything should work and not show SASS warnings in the console. …
> Remove SASS warnings by using color.scale and color.channel functions

- scss/_patterns_links.scss
- Updated style for the "skip link" pattern - see comparison screenshots below.
Fixes #5356
- Open [demo](https://vanilla-framework-5371.demos.haus/docs/patterns/links#skip-link) for the skip link pattern
- Click inside the iframe of the example, then press SHIFT + TAB to make the skip link appear
- Check the new appearance of the skip link
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Re …
> fix(skip-link): give the skip link a more modern styling

- package.json
Adds `sass` as a peer dependency. This should help flag incompatible installations of `sass`, as our [recently added usage](https://github.com/canonical/vanilla-framework/pull/5370) of `color.scale` [requires version 1.70](https://sass-lang.com/documentation/modules/color/#channel).
Fixes [MM thread](https://chat.canonical.com/canonical/pl/xq3fh15uqfriuj9bfuyfro5yde) …
> Add `sass` as a peer dependency

- templates/docs/base/code.md
- templates/docs/base/forms.md
- templates/docs/base/tables.md
- templates/docs/patterns/accordion/index.md
- templates/docs/patterns/buttons/index.md
- templates/docs/patterns/card/index.md
- templates/docs/patterns/chip/index.md
- templates/docs/patterns/contextual-menu/index.md
- templates/docs/patterns/grid/index.md
- templates/docs/patterns/links/index.md
- templates/docs/patterns/lists/index.md
- templates/docs/patterns/modal/index.md
- templates/docs/patterns/notification/index.md
- templates/docs/patterns/pagination/index.md
- templates/docs/patterns/search-and-filter.md
- templates/docs/patterns/search-box/index.md
- templates/docs/patterns/slider/index.md
- templates/docs/patterns/strip/index.md
- templates/docs/patterns/tabs/index.md
- templates/docs/patterns/tooltips/index.md
Fix all links to the react components storybook by a new pattern.
Fixes #5374 
Fixes [WD-15774](https://warthogs.atlassian.net/browse/WD-15774)
- Check new links
[WD-15774]: https://warthogs.atlassian.net/browse/WD-15774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
> Change links for react components

- .github/.jira_sync_config.yaml
Changes JIRA epic where new issues are synchronised to our new "Incoming" epic (https://warthogs.atlassian.net/browse/WD-15821)
> Change the JIRA epic where new issues are synchronised

- templates/docs/base/forms.md
- templates/docs/patterns/badge/index.md
- templates/docs/patterns/navigation/index.md
- templates/docs/patterns/status-labels/index.md
- templates/docs/patterns/switch/index.md
I have identified several missing links to the React Storybook documentation for certain existing components, and I have added them accordingly.
Check new links for:
- Base elements/Forms (I've added a few more)
- Components/Badge
- Components/Navigation
- Components/Status labels
- Components/Switch
> Add links to react storybook for existing components

- scss/_layouts_full-width.scss
- scss/_patterns_badge.scss
- scss/_patterns_image.scss
Updates couple remaining small components (badge, deprecated image options, deprecated full-width layout) to use new theming variables.
Fixes https://warthogs.atlassian.net/browse/WD-11862
Fixes https://warthogs.atlassian.net/browse/WD-11870
Fixes https://warthogs.atlassian.net/browse/WD-11884
- Check updated components, make sure they work well in all themes:
- badge (https://vanilla-framework-5377.demos.haus/docs/examples/patterns/badge/colors?theme=light)
- image (border): https://vanilla-framework-5377.demos.haus/docs/examples/patterns/image/bordered?theme=light
- full width layout: https://vanilla-framework-5377.demos.haus/docs/examples/layouts/full-width/default?theme=light
> Update remaining legacy components to use new theme colours.

- scss/_patterns_icons.scss
- Set icons in paragraph to have a `vertical-align` set to `middle`
Fixes #5103 
Fixes [WD-13630](https://warthogs.atlassian.net/browse/WD-13630)
- Open [demo](https://vanilla-framework-5314.demos.haus/docs/patterns/icons#standard)
- Verify icons are aligned to the middle. Increase font-size if necessary to test.
- No Changes in documentation …
> Set icon alignment in paragraph to text-bottom

- templates/docs/settings/breakpoint-settings.md
Updated breakpoints settings page to use new CSS range syntax, based on conversation in #5287
Fixes #5394
- Open `breakpoint-settings` page
> Add CSS range syntax to breakpoints settings page

- scss/_base_forms-range.scss
Based on the comment of @lyubomir-popov, it seems we need to reduce the top and bottom margins by half the height of the track. 
I'm not sure if the calculations needed to be enclosed in parentheses, but I did so for better code readability.
Fixes #5391
- Please review the [updated component Slider(Range input)](https://vanilla-framework-5392.demos.haus/docs/examples/base/forms/range) …
> Fix slider margin

- scss/_base_forms.scss
- scss/_patterns_search-box.scss
- scss/_settings_placeholders.scss
- scss/_settings_spacing.scss
Reimplementation of #4954
Makes sure that input border width is correctly applied to top and bottom padding of inputs.
Drive-by: remove theming from search box (as it can inherit it from base inputs).
- Open [demo](https://vanilla-framework-5389.demos.haus/docs/examples/base/forms/labels?theme=light)
- Check form examples: https://vanilla-framework-5389.demos.haus/docs/examples/base/forms/combined?theme=light
- Check buttons: https://vanilla-framework-5389.demos.haus/docs/examples/patterns/buttons/combined?theme=light
- if CSS class names are not changed it can be bugfix release …
> Fix input padding alignment

- scss/_base_placeholders.scss
- scss/_patterns_search-and-filter.scss
- scss/_utilities_off-screen.scss
- templates/docs/examples/patterns/search-and-filter/chip-overflow.html
- templates/docs/examples/patterns/search-and-filter/default.html
- templates/docs/examples/patterns/search-and-filter/expanded.html
- templates/docs/examples/patterns/search-and-filter/with-chips.html
- templates/docs/examples/patterns/search-and-filter/with-search-prompt.html
- tests/parker.js
- Fixes the search and filter hidden search button throwing off the vertical alignment of the rest of the search and filter container.
- Fixes incorrect stack order of the hidden search button, which was being hidden by the search input text field.
Fixes #5289 , [WD-14048](https://warthogs.atlassian.net/browse/WD-14048)
- Open [search and filter examples](https://vanilla-framework-5339.demos.haus/docs/examples/patterns/search-and-filter/combined?theme=light)
- Tab through the examples and make sure that the "Search" hidden button does not throw off alignment of its container when it is visible. Also check that it is rendered above its search input element.
- …
> fix: Search and filter hidden search button alignment and stacking order adjustment

- templates/index.html
I arranged the cards to display in a 50/50 split under the heading when viewed on a medium screen size.
Fixes #5367
- Open the [homepage](https://vanilla-framework-5400.demos.haus/) and check the downloads section on different screen sizes.
> Update layout of the homepage "downloads" section on medium screens

- scss/_patterns_search-and-filter.scss
Adjust search and filter component height calculations and its internal input styling to better align with standard inputs.
Fixes #4984
Supersedes #5019
- Open [demo](https://vanilla-framework-5399.demos.haus/docs/examples/patterns/search-and-filter/default?theme=light)
- Review search & filter examples, make sure that in all cases and stated the root element `p-search-and-filter` has height of 36px (same as standard input)
- https://vanilla-framework-5399.demos.haus/docs/examples/patterns/search-and-filter/default?theme=light
- https://vanilla-framework-5399.demos.haus/docs/examples/patterns/search-and-filter/expanded?theme=light
- https://vanilla-framework-5399.demos.haus/docs/examples/patterns/search-and-filter/with-chips?theme=light
- …
> Adjust search and filter component height to align with standard inputs

- package.json
- scss/_patterns_image.scss
Specifically targets `.lazyloaded` images for `display: contents` to avoid applying contents display to `.lazyload`
- Check out https://github.com/canonical/canonical.com/pull/1409
- Set `vanilla-framework` version to `jmuzina/vanilla-framework#5402-image-aspect-ratio-lazyloaded-fix`
- Set `sass` version to `1.79.0`
- Open [what is Spark page](http://0.0.0.0:8002/data/spark/what-is-spark)
- Verify the lazily loaded "how do companies use spark" images load and have the correct aspect ratio
- if CSS class names …
> Fix using the image container with lazyloaded images

- side-navigation.yaml
- templates/index.html
- Changed UI kit reference on home page from sketch to Figma
- Changed UI kit reference in the side navigation of the docs from Sketch to Figma
- Open Demo
- Look at UI kit card on home page
- Verify it looks good and links work
- Look at Resources group in side nav
- Verify it looks good and links work
> Changed UI kit references to Figma community

- templates/docs/layouts/fluid-breakout.md
- templates/docs/layouts/full-width.md
The utility class for breakpoint `$breakpoint-large` is referenced in the [fluid-breakout](https://vanillaframework.io/docs/layouts/fluid-breakout) documentation with an extra dash (`-`). This PR simply corrects the small typo.
Please note - I can't seem to be able to add any label to this PR. I wanted to add `Documentation 📝`. 
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-proces …
> Fix typo in breakpoint class name used in documentation

- templates/docs/patterns/quote-wrapper/index.md
- Corrected documentation for importing quote macro
- `vf_quote-wrapper` gave error when imported
- Open [demo](https://vanilla-framework-5422.demos.haus/docs/patterns/quote-wrapper) and see if the import statement is corrected
> Corrected documentation for importing quote macro

- scss/_patterns_search-and-filter.scss
- templates/docs/examples/patterns/search-and-filter/chip-overflow.html
- templates/docs/examples/patterns/search-and-filter/default.html
- templates/docs/examples/patterns/search-and-filter/expanded.html
- templates/docs/examples/patterns/search-and-filter/with-chips.html
Removed extra spacing between search & filter chips that are only present in the Vanilla examples by setting the font-size to 0 as suggested by @lyubomir-popov in the issue conversation.
Fixes #5227
- Open [search & filter examples](https://vanilla-framework-5414.demos.haus/docs/examples/patterns/search-and-filter/combined) and verify they look correct
- Open [search & filter docs](https://vanilla-framework-5414.demos.haus/docs/patterns/search-and-filter) and verify the markup in the example code snippets is easy to read
- if CSS class names are not changed it can be bugfix release …
> fix: removed the extra spacing between the chips in search and filter from vanilla example

- .github/PULL_REQUEST_TEMPLATE.md
- package.json
- templates/_macros/vf_quote-wrapper.jinja
- templates/docs/patterns/quote-wrapper/index.md
- Updates the quote wrapper to always have a muted rule
- Updates the quote wrapper documentation to clearly show when the quote wrapper heading is required
- Drive by: Updates the PR template to reflect that changes to macros should also result in a package bump.
Fixes #5423, [WD-17509](https://warthogs.atlassian.net/browse/WD-17509)
- Review [quote wrapper without header docs](https://vanilla-framework-5424.demos.haus/docs/patterns/quote-wrapper#without-heading) 
- Review [combined quote wrapper example](https://vanilla-framework-5424.demos.haus/docs/examples/patterns/quote-wrapper/combined?theme=light) and verify that the rule above the quote text is always muted. 
If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the …
> fix: make quote wrapper quote separator always use `.p-rule--muted`

- templates/accessibility.html
The [accessibility page in Vanilla's documentation](https://vanillaframework.io/accessibility) links to WAI's report tool however, the link appears to be broken. 
Currently the link navigates to the [Overview Page](https://www.w3.org/WAI/eval/report-tool) (instead of the [Audit Page](https://www.w3.org/WAI/eval/report-tool/evaluation/audit-sample)) of the report tool and the broken link also throws an error in browser console. 
The W3C report tool [changed their route links](https://github.com/Dinika/wai-wcag-em-report-tool/commit/329a637c69c726fab9d7f6dfec40509fa9c1913f#diff-79cbc9000cd82c2fb5785502b45377ec6948531a359e0be13f5369a2adb52184L77). This PR update the link to navigate to their new audit page.
- Open [accessibility page](https://vanilla-framework-5428.demos.haus/accessibility) …
> fix: Update link to accessibility report tool

- package.json
- templates/_macros/vf_quote-wrapper.jinja
- Updates the `title_text` of the quote wrapper to an `h2` to improve semantic structure of pages that use it.
Fixes #5426 , [WD-17584](https://warthogs.atlassian.net/browse/WD-17584)
- Open [combined quote wrapper example](https://vanilla-framework-5427.demos.haus/docs/examples/patterns/quote-wrapper/combined) and verify that the examples that have title bars use an `h2` for for the title text.
- if existing APIs (CSS classes & macro APIs) are changed/added/removed it should …
> fix: quote wrapper's `title_text` is now a semantic `h2`.

- side-navigation.yaml
- templates/docs/content-guidelines.md
- templates/docs/customising-vanilla.md
- Added Content Guidelines page from [copydoc](https://docs.google.com/document/d/12nLPp3ktElJCNl_i3q5fGOjWMPhPXXFsIJGH-AuxduQ/edit?tab=t.0)
This is a draft. A few things are missing. Would love to hear your thoughts @bartaz @jmuzina on those : 
- Display the images in reasonable sizes
- Figure out a better way to display notessuch as in "contact form submission"
- Run vanilla-framework (`dotrun`)
- Go to Docs/Content Guidelines
- Review documentation
- if existing APIs (CSS …
> Ft: add content guidelines page

- templates/docs/examples/patterns/tiered-list/50-50-desktop-with-description-cta.html
- templates/docs/examples/patterns/tiered-list/50-50-desktop-with-description.html
- templates/docs/examples/patterns/tiered-list/50-50-desktop-with-list-item-cta.html
- templates/docs/examples/patterns/tiered-list/50-50-tablet-with-description.html
- templates/docs/examples/patterns/tiered-list/50-50-tablet-without-description.html
- templates/docs/examples/patterns/tiered-list/50-50-with-description.html
- templates/docs/examples/patterns/tiered-list/full-width-with-description.html
- templates/docs/examples/patterns/tiered-list/full-width-without-description.html
- templates/docs/patterns/tiered-list/index.md
- Update `<h5>` to `<h3 class="p-heading--5">` in tiered list jinja template docs
- Add `data-lang="jinja"` to some examples that were missing it
- Open [demo](https://vanilla-framework-5429.demos.haus/)
- Check the headings follow semantic structure ie. not skipping levels, [see reference](https://webaim.org/techniques/headings/)
- Check all examples display jinja templates
- if existing APIs (CSS classes & macro APIs) are …
> docs: Update tiered list jinja template docs to use semantic structure

- package.json
- templates/_macros/vf_hero.jinja
- templates/docs/examples/patterns/hero/combined.html
- templates/docs/examples/patterns/hero/hero-50-50-full-width-image-without-subtitle_text.html
- Conditional rendering of shallow padded block for the hero pattern `hero-50-50-full-width-image`.
- Check out this branch
- Open the file `docs/examples/patterns/hero/hero-50-50-full-width-image`
- Remove the `subtitle_text` parameter from macro call.
-  View the site locally at http://localhost:8101/docs/examples/patterns/hero/hero-50-50-full-width-image
- Note that the left heading and right description are now aligned and there's no shallow padded empty block above description.
Before, without providing subtitle_text
After, without providing subtitle_text
> Conditionally render the shallow padded block for subtitle_text

- .github/ISSUE_TEMPLATE/propose-changes-to-existing-component.md
- .github/ISSUE_TEMPLATE/propose-new-component.md
- .github/ISSUE_TEMPLATE/report-a-bug.md
- CONTRIBUTING.md
- Updates link in the contribution documentation to go to the [issue template chooser](https://github.com/canonical/vanilla-framework/issues/new/choose), instead of an [empty new issue](https://github.com/canonical/vanilla-framework/issues/new/).
- Auto-suggests a title for new issues created by the issue templates
Fixes [thread](https://chat.canonical.com/canonical/pl/34ytx7p7pfgomr7uoxexogu8cy) by @EnzoYD
- See that the link in the contribution guidelines for this PR links to the issue template chooser.
- I'm not aware of a way to QA the issue names.
- if existing APIs …
> chore: contribution guidelines/issue creation updates

- package.json
- templates/_macros/vf_hero.jinja
- Removed margin from H1 only when the subtitle_text is not provided.
- View the old [hero-50-50-full-width-image](https://vanillaframework.io/docs/examples/patterns/hero/hero-50-50-full-width-image-without-subtitle_text) in your web browser.
- Make sure you are previewing in a smaller screen size.
- Notice the missing space between H1 and description paragraph.
- Now, open the [hero-50-50-full-width-image](https://vanilla-framework-5443.demos.haus/docs/examples/patterns/hero/hero-50-50-full-width-image-without-subtitle_text) in your web browser.
- Make sure you are previewing in a smaller screen size.
- Verify the presence of spacing between H1 and the description paragraph.
Before:
After:
> Full width image Hero - Remove margin bottom from H1 only if the subtitle_text is missing

- templates/_macros/vf_tiered-list.jinja
- Removes `u-hide--small` class from top `<hr>` in vf_tiered-list jinja template
- Open [demo](https://vanilla-framework-5444.demos.haus/docs/examples/patterns/tiered-list/combined?theme=light)
- Check the top hr in the pattern is retained on all screen sizes
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-re …
> fix(vf_tiered-list.jinja): Update to have top hr on all screen sizes

- package.json
- releases.yml
- templates/_macros/vf_hero.jinja
- templates/docs/examples/patterns/hero/combined.html
- templates/docs/examples/patterns/hero/hero-50-50-no-image.html
- templates/docs/patterns/hero/index.md
- templates/docs/patterns/tiered-list/index.md
- templates/docs/utilities/align.md
- Adjusts the hero pattern to split its left and right columns when `layout="50/50"` and no image is provided. 
- Drive-by: removes docs section new/updated status labels for changes that were made several months ago.
No API changes have been made. 
Fixes #5449 
Fixes [WD-18357](https://warthogs.atlassian.net/browse/WD-18357)
- Open [example](https://vanilla-framework-5450.demos.haus/docs/examples/patterns/hero/hero-50-50-no-image) and verify it appears as expected.
- Review [updated Hero docs](https://vanilla-framework-5450.demos.haus/docs/patterns/hero#5050-with-no-image-new)
- Review [4.20.1 release notes](https://vanilla-framework-5450.demos.haus/docs/whats-new)
If this PR contains Vanilla SCSS or macro code changes, it should contain the following changes to make sure it's ready for …
> fix(hero): 50/50 with no image is laid out in split columns

- package.json
- scss/_patterns_tabs.scss
Adjusts the border of the `p-tabs__list` so that it spans full width on all screen sizes.
Previously, a pseudoelement `.p-tabs__list::after` was used as a pseudo-border, but this pseudo-border spanned the width of `.p-tabs__list`, which is a horizontally scrolling flex container. So, the border spans the constrained width of the container, not the width of the list itself.
This alters the border to use an inset box shadow, basing the border sizing off of the box model of `p-tabs__list` instead. This correctly forces the bottom border to span the full width of the tabs list on all screen sizes. 
Fixes #5446 
Fixes [WD-18333](https://warthogs.atlassian.net/browse/WD-18333)
- Open tab variants and verify the bottom border of the tabs list spans the full width of the body on all screen sizes, …
> fix(tabs): Bottom border of `.p-tabs__list` spans full width on all screen sizes

- package.json
- scss/_patterns_navigation.scss
- templates/docs/examples/patterns/navigation/search.html
- templates/docs/examples/patterns/navigation/sliding-search.html
Fixes issue found when debugging WD-18308.
When right part of top navigation contains more than one item, they get wrapped.
This seems to be caused by width set on `p-navigation__items` (needed for when it's the only part of navigation).
This PR moves the width setting to specifically the situation when it's needed (when it's the first and the only element with `p-navigation__items` class).
TBA (when demo is ready)…
- Open [demo](https://vanilla-framework-5461.demos.haus/docs/examples/patterns/navigation/search?theme=dark)
- Make sure that "search" and "sign in" items don't wrap
- Review [all navigation examples](https://vanilla-framework-5461.demos.haus/docs/examples/patterns/navigation/combined?theme=light) to make sure there are no regressions
If this PR contains Vanilla SCSS or macro …
> Fix wrapping items in right side of navigation

- templates/docs/examples/base/forms/range.html
Added an aria-label to the inputs in Range example for accessibility purposes. 
Fixes #5416 
- Check /docs/examples/base/forms/range
Not sure if I should update the package.json version
Before
After
> Added aria-label to Range example

- templates/docs/examples/patterns/navigation/_script-sliding.js
For the non-mobile version of the component: closing a nested drop-down doesn't dismiss the overlay anymore. Now it is only dismissed when closing the root drop-down.
Fixes #5288
- Open any of the "sliding" patterns, for example /docs/examples/patterns/navigation/sliding-dark.
- Open "LXCFS" menu, then "Nested Layer". 
- Close "Nested Layer" and compare the behavior with closing "LXCFS" directly. 
- if existing APIs (CSS classes & macro APIs) are changed/added/removed it …
> Nested dropdowns no longer dismiss overlay

- templates/docs/settings/layout-settings.md
Updates the layout settings documentation per the new 8 column grid
Fixes #5481, [WD-19930](https://warthogs.atlassian.net/browse/WD-19930) 
- Review [Layout settings docs](https://vanilla-framework-5483.demos.haus/docs/settings/layout-settings) …
> docs(layout settings): Update layout settings docs to reflect new grid variable

- package.json
- scss/_base_code.scss
fix(code) allow code line selection with triple click
Fixes #5505
- Open [/docs](https://vanilla-framework-5506.demos.haus/docs) page and triple click on the box `yarn add vanilla-framework`
- This should select the whole text, while on the [current page](https://vanillaframework.io/docs) it only selects the first letter when browsing with Chrome.
- see the [wiki …
> fix(code) allow code line selection with triple click

- package.json
- scss/_patterns_badge.scss
- Set `display: inline-block` on the badge component, to ensure its `max-width` and `line-height` are properly enforced
- Set a minimum width on badges so that badges with the smallest size possible are perfect 16x16 circles
- Set badge text to center-align (otherwise very short badge text would not be horizontally centered)
Fixes [WD-23540](https://warthogs.atlassian.net/browse/WD-23540)
Fixes #5568 
- Open [badge](https://vanilla-framework-5569.demos.haus/docs/examples/patterns/badge/default?theme=light)
- Verify that the "9" badge is a perfect 16x16 circle
- Use "Inspect element" to change any badge to have very long text, longer than 4 characters.
- Verify that the badge with the long text does not show more than 4 full characters, and the rest of the characters are cut off (not …
> fix(Badge): Truncate badges with long text, make the smallest badge a perfect circle

- package.json
- releases.yml
- side-navigation.yaml
- templates/_macros/vf_text-spotlight.jinja
- templates/docs/examples/patterns/text-spotlight/combined.html
- templates/docs/examples/patterns/text-spotlight/default.html
- templates/docs/examples/patterns/text-spotlight/links.html
- templates/docs/patterns/text-spotlight/index.md
- Implemented Text Spotlight section pattern
- Added Docs
- Added Examples
Fixes [WD-22567](https://warthogs.atlassian.net/browse/WD-22567)
- Open demos:
- [Default](https://vanilla-framework-5572.demos.haus/docs/examples/patterns/text-spotlight/default.html)
- [Links](https://vanilla-framework-5572.demos.haus/docs/examples/patterns/text-spotlight/links.html)
- [All combined](https://vanilla-framework-5572.demos.haus/docs/examples/patterns/text-spotlight/combined.html)
- Match the above demos with [figma](https://www.figma.com/design/1brHCsyeTE6FU7hfJd6ao2/%F0%9F%9A%A7---WIP--Sites---Core-component-library?node-id=362-18300&p=f&t=gKjFSDfyAErg2OUz-0)
- Review [documentation](https://vanilla-framework-5572.demos.haus/docs/patterns/text-spotlight)
If this PR contains Vanilla SCSS or macro …
> [WD-22567] feat: Implement Text Spotlight section pattern

- package.json
- releases.yml
- templates/_macros/vf_equal-heights.jinja
- templates/docs/examples/patterns/equal-heights/4-columns-highlighted-images.html
- templates/docs/examples/patterns/equal-heights/combined.html
- templates/docs/patterns/equal-heights/index.md
added support for highlighting images in equal-heights macro
- Check out demo [demo](https://canonical-com-1818.demos.haus/mlops/kubeflow) and code at https://github.com/canonical/canonical.com/pull/1818
- Documentation for equal-height-row …
> feat: added support for highlighting images in equal-heights macro

- package.json
- scss/_patterns_image.scss
The change from ^= to *= ensures the selector matches any class containing 'p-image-container--' rather than just those starting with it, fixing potential styling issues
Fixes [Percy regression](https://percy.io/bb49709b/web/ubuntu.com-eaf28f99/builds/42016720/changed/2248032285?browser=chrome&browser_ids=64&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&utm_source=github_status_private&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280) blocking [Vanilla upgrade](https://github.com/canonical/ubuntu.com/pull/15231)
- Open [demo](https://ubuntu-com-15417.demos.haus/) and check that images display well compared to https://ubuntu-com-15231.demos.haus/  where  when the class name of the image container does not begin with p-container, it breaks the …
> fix: correct image container class selector to use * instead of ^

- package.json
- releases.yml
- templates/_macros/vf_pricing-block.jinja
- templates/docs/examples/patterns/pricing-block/1-block.html
- templates/docs/examples/patterns/pricing-block/block-with-description-and-highlighted-rule.html
- templates/docs/examples/patterns/pricing-block/block-without-description-and-muted-rule.html
- templates/docs/examples/patterns/pricing-block/combined.html
- templates/docs/patterns/pricing-block/index.md
- Implemented the single tier pricing block variant for pricing block pattern.
Fixes [WD-24276](https://warthogs.atlassian.net/browse/WD-24276) and #5584 
- Open Demos
- [Single Pricing Block](https://vanilla-framework-5607.demos.haus/docs/examples/patterns/pricing-block/1-block?theme=light)
- [Pricing Block without Description and a Muted Rule](https://vanilla-framework-5607.demos.haus/docs/examples/patterns/pricing-block/block-without-description-and-muted-rule?theme=light)
-  [Pricing Block with Description and Highlighted Rule](https://vanilla-framework-5607.demos.haus/docs/examples/patterns/pricing-block/block-with-description-and-highlighted-rule?theme=light)
- Match with [Figma](https://www.figma.com/design/1brHCsyeTE6FU7hfJd6ao2/%F0%9F%9A%A7---WIP--Sites---Core-component-library?no …
> [WD-24276] feat: implemented Single Pricing Block pattern variant

- package.json
- templates/_macros/vf_text-spotlight.jinja
- Fixed H4 style not applied to items in text-spotlight pattern
Fixes [WD-26329](https://warthogs.atlassian.net/browse/WD-26329)
- Open [combined examples](https://vanilla-framework-5631.demos.haus/docs/examples/patterns/text-spotlight/combined)
- Verify all examples are working as expected …
> [WD-26329] fix: h4 style not applied to text spotlight pattern

- package.json
- releases.yml
- templates/_macros/vf_newsletter-signup.jinja
- templates/docs/examples/patterns/newsletter-signup/2-col.html
- templates/docs/examples/patterns/newsletter-signup/25-75.html
- templates/docs/examples/patterns/newsletter-signup/4-col.html
- templates/docs/examples/patterns/newsletter-signup/50-50.html
- templates/docs/examples/patterns/newsletter-signup/x-col-without-newsletter-block-rule.html
- templates/docs/patterns/newsletter-signup/index.md
- Added `honeypot_fields` slot with default values, for spam prevention
- Added `hide_newsletter_block_rule` param, to hide the block-level muted rule on medium/smaller screens for 2-col, 4-col variants.
Fixes [WD-26516](https://warthogs.atlassian.net/browse/WD-26516)
- Review [Newsletter pattern docs](https://vanilla-framework-5637.demos.haus/docs/patterns/newsletter-signup)
- Review [release notes](https://vanilla-framework-5637.demos.haus/docs/whats-new)
- Review [new example](https://vanilla-framework-5637.demos.haus/docs/examples/patterns/newsletter-signup/x-col-without-newsletter-block-rule)
- Review [combined examples](https://vanilla-framework-5637.demos.haus/docs/examples/patterns/newsletter-signup/combined)
If this PR contains Vanilla SCSS or macro code changes, it should …
> [WD-26516] feat: Introduced new param and slot to the Newsletter signup pattern

- README.md
- templates/docs/index.html
- templates/static/js/example.js
A recent [asset API change](https://github.com/canonical/assets.ubuntu.com/pull/295) has changed asset handling such that asset names are now sanitized before uploading. This has caused our asset manager CSS uploads, which used to live at, for example, https://assets.ubuntu.com/v1/vanilla_framework_version-4.33.0.min.css, to instead be uploaded as https://assets.ubuntu.com/v1/vanilla_framework_version_4_33_0_min.css .
This PR changes the places we consume the asset manager URLs to use the new asset name format.
Fixes https://chat.canonical.com/canonical/pl/mxgy18rwjigcig8koeurcefn7h
- Checkout PR locally, run with `dotrun`
- Open [get started page hotlink section](http://0.0.0.0:8101/docs#hotlink). Copy the asset link and verify it goes to …
> adjust asset manager asset link

- scss/_settings.scss
- scss/_settings_font.scss
Sets the root font size to the default text side introduced by #5578 
Fixes #5573 
Fixes [WD-23671](https://warthogs.atlassian.net/browse/WD-23671)
Fixes #5615 
Fixes [WD-24793](https://warthogs.atlassian.net/browse/WD-24793)
- See that Percy passes
- Click around the demo and see nothing looks out of place …
> fix(Typography): root font size is derived from `$settings-text-default`

- scss/_patterns_modal.scss
- For modal height use dvh to make it respect open url bars in mobile browsers
- Related issue reported in https://github.com/canonical/lxd-ui/issues/1496 with respect to a Network ACL configuration modal. The buttons in the footer are cut, as the height of the modal (100vh) does not take into account the reduced available height due to the open url bar. The change to 100dvh respects that and resolves the issue.
> For modal height use dvh to make it respect open url bars in mobile browsers
