canonical/vanilla-framework

.gitignore, .travis.yml, gulpfile.js, package.json
- None
- Added sassdoc to gulp script
- Structured the gulp commands
- Run gulp and see commands available
- Run gulp build is should build the css and docs into a build folder
=> Add sassdoc to gulp

scss/_core-constants.scss, scss/core-print.scss
===
Make Travis succeed again by fixing syntax and compile errors in scss files.
Done
---
- Add $black and $white variables to core-constants
- Import core-constants into code-print
QA
---
``` bash
npm install
node_modules/gulp/bin/gulp.js build
```
^ succeeds
=> Fix errors which prevent sass from building

scss/core-print.scss
- None
- Fixed the lint issues in core-print
- Run gulp test and check there are no lint issues in core-print.scss
=> Lint the print stylesheet

README.md, gulpfile.js
Changed the gulpfile to recurse over all scss files, not just the root.
run "gulp test" and then ensure that it's reading deeper files in the file structure.
=> Scss linting recusion

gulpfile.js, scss/_core-grid.scss, scss/patterns/_header.scss, scss/patterns/_image-centered.scss
Done
Changed the gulpfile to recurse over all scss files, not just the root. Fix lint issues.
QA
run "gulp test" and then ensure that it's reading deeper files in the file structure.
=> SCSS linting recursion

scss/_core-grid.scss, scss/patterns/_blockquotes.scss, scss/patterns/_boxes.scss, scss/patterns/_buttons.scss, scss/patterns/_contextual-footer.scss, scss/patterns/_footer.scss, scss/patterns/_forms.scss, scss/patterns/_helpers.scss, scss/patterns/_image-centered.scss, scss/patterns/_inline-logos.scss, scss/patterns/_lists.scss, scss/patterns/_notifications.scss, scss/patterns/_search.scss, scss/patterns/_structure.scss, scss/patterns/_tabbed-content.scss, scss/patterns/_vertical-divider.scss, scss/patterns/patterns.scss
Remove tabs in all SCSS files.
QA
---
`git diff -w` - no significant non-whitespace changes
=> Remove tabs

scss/patterns/_helpers.scss
- None
- Linted the patterns/_helpers.scss
- Run gulp test and check there are no lint issues for _helpers.scss
=> Lint _helpers.scss

scss/patterns/patterns.scss
- None
- Linted the patterns.scss file
Run ```scss-lint scss/patterns/patterns.scss``` and check there are no warnings or errors
=> Lint patterns.scss

scss/patterns/_header.scss, scss/patterns/_image-centered.scss
Done
Lint fixes in _header (WIP) 
box-sizing in _image-centered
QA
gulp sass
=> SCSS lint fixes.

scss/patterns/_image-centered.scss
Done
---
Remove references to the deleted mixin "box-sizing" so sass compiles.
QA
---
`gulp sass`
=> Get `gulp sass` working again

scss/_core-constants.scss, scss/patterns/_tooltips.scss
linted the tooltips with the help of Ant
=> Linted the tooltips

scss/_core-constants.scss, scss/patterns/_boxes.scss
linted _boxes.scss, removed old rules added some constants.
lint _boxes.scss and ensure that there are no errors
=> lint _boxes.scss

scss/patterns/_typography.scss
- None
- Linted the typography file
- Run ```gulp test --file patterns/_typography.scss``` and check there are no warnings
=> Lint typography

scss/patterns/_tabbed-content.scss
- None
- Linted the tabbed-content file
- Run ```gulp test --file patterns/_tabbed-content.scss``` and see there are no issues
=> linted tadded-content

scss/patterns/_structure.scss
- None
- Linted the structure scss file
- Run ```gulp test --file patterns/structure.scss``` and check there is no output.
=> Lint structure

scss/_core-constants.scss, scss/patterns/_buttons.scss, scss/patterns/_lists.scss, scss/patterns/_rows.scss
linted and fixed _rows
gulp test --file patterns/_rows.scss
=> linted rows

scss/patterns/_search.scss
- None
- Linted the search file 
- Run ```gulp test --file patterns/_search.scss``` and check there are no warnings
=> Lint search

.scss-lint.yml, scss/_core-constants.scss, scss/_core.scss
- None
- Linted the core file
- Enabled allow_element_with_attribute for QualifyingElement when linting
- Run ```gulp test --file scss/_core.scss``` and check there are no warnings
=> Lint core file

scss/patterns/_arrows.scss
- None
- Linted the arrows file
- Removed unused media queries
- Run ```gulp test --file scss/pattern/_arrow.scss``` and check there are no issues
=> Lint arrows

scss/patterns/_inline-logos.scss
- None
- Linted the inline-logos
- Run ```gulp test --file scss/patterns/_inline-logos.scss``` and check there is no warnings
=> Lint inline logos

scss/patterns/_slider.scss
- None
- Lint the _slider.scss file
- Run ```gulp test --file scss/patterns/_slider.scss``` and check there are no warnings
=> Lint slider

scss/patterns/_footer.scss
Linted footer and added exceptions for dirty rules.
gulp test --file scss/patterns/_footer.scss
=> Linted footer

scss/_core-constants.scss, scss/_core-grid-desktop.scss, scss/_core-grid-tablet.scss, scss/patterns/_rows.scss
- None
- Moved row styles from grid to row styles
- Do ```gulp build``` and check the index.html rows have good padding
=> Fixed the row padding

scss/_core-constants.scss, scss/_core-grid-tablet.scss, scss/_core.scss, scss/patterns/_blockquotes.scss, scss/patterns/_boxes.scss, scss/patterns/_buttons.scss, scss/patterns/_contextual-footer.scss, scss/patterns/_footer.scss, scss/patterns/_header.scss, scss/patterns/_rows.scss, scss/patterns/_search.scss, scss/patterns/_slider.scss, scss/patterns/_tabbed-content.scss, scss/patterns/_tooltips.scss
- None
- Renamed $ubuntu-orange to $branch-color
- Created $base-color and set the font colours to it
- Added !default to scss vars
- Run ```gulp build``` and check there are no issues
- Check the index.html looks ok
=> Change some vars

scss/_core-grid-tablet.scss
- None
- Linted the _core-grid-tablet.scss
- Run ```gulp test --file scss/_core-grid-tablet.scss``` and check there are no warnings
=> Lint the core-grid-tablet

gulpfile.js, package.json, scss/patterns/_header.scss
Done
SCSS lint cleanup header.scss
QA
Run gulp build
=> SCSS lint error fixes for header

scss/patterns/_blockquotes.scss
Fixed the issues with brand-color variable
```$ gulp test --file scss/patterns/_header.scss``` and then run ```$ gulp build```
=> changing ubuntu-color to brand-color

scss/modules/_typography.scss
=> typography mixin

scss/_vanilla.scss, scss/modules/_lists.scss
Done:
Includes the lists styles and wraps it in a mixin
To test:
gulp test
=> Add list module

scss/_vanilla.scss, scss/modules/_rows.scss
Wrapped rows in a mixin
Fixed all the mixin naming
=> Framework update

scss/_vanilla.scss
Done:
Added mixin vf-footer
Test:
run gulp test
=> add mixin footer

scss/_vanilla.scss, scss/modules/_blockquotes.scss
Done:
Added block quote module
Test: 
Run gulp test
=> Add blockquotes module

scss/_vanilla.scss, scss/modules/_header.scss, scss/modules/_search.scss
Done:
Add header module
Test:
Run gulp test
=> Add header module

scss/modules/_footer.scss
=> add footer module

scss/_global-settings.scss, scss/_vanilla.scss, scss/modules/_grid.scss
Updated the import file
```gulp test``` ```gulp build```
=> Updating the modules include

scss/styles.scss
Adding the mixin include
run ```gulp build```
=> fixing vanilla mixin include

index.html, scss/_global-settings.scss, scss/modules/_blockquotes.scss, scss/modules/_typography.scss
Done:
Amended asset path. Added fonts.
Test:
Run gulp build. Check font is ubuntu.
=> Amend asset path variable. Add fonts.

scss/_vanilla.scss, scss/modules/_forms.scss, scss/modules/_reset.scss, scss/modules/_tables.scss
Done:
Added old core styles as a reset file. Separated out into forms/tables where appropriate.
QA:
gulp buld
=> add reset styles and split out core into forms/tables

scss/modules/_blockquotes.scss, scss/modules/_forms.scss, scss/modules/_reset.scss, scss/modules/_typography.scss
Done:
Stripped some styles out of reset and into where they make more sense.
QA:
gulp build
=> reset etc.

scss/modules/_reset.scss, scss/modules/_typography.scss
Done:
Cleaned reset styles, moved some into typography
QA:
gulp build
=> strip and clean reset styles

scss/modules/_typography.scss
Done:
Fixed H(n) styles
QA:
gulp build
test the index page fro sizes
=> fix for H(n) styles

index.html, scss/modules/_lists.scss
- Added Sass doc comments
- Wrapped varieties in mixins
- Updated demo to reflect available lists
- Run ```gulp build```
- Run ```google-chome index.html``` and check the list section looks ok.
- Run ```google-chome build/docs/index.html``` and check the doc for lists contain all the versions.
=> [Lists] Document and update demo

scss/_global-settings.scss, scss/modules/_blockquotes.scss, scss/modules/_buttons.scss, scss/modules/_forms.scss, scss/modules/_grid.scss, scss/modules/_header.scss, scss/modules/_rows.scss, scss/modules/_search.scss, scss/modules/_tables.scss, scss/modules/_typography.scss
Done:
updated global settings, made some of the variables more semantic, removed silly ones
QA:
gulp build
=> consolidate global settings and make neccessary edits in dependent files

scss/_global-settings.scss, scss/_vanilla.scss, scss/modules/_header.scss, scss/modules/_helpers.scss, scss/modules/_rows.scss, scss/modules/_search.scss
Done: Add helpers. Rebuild header.
Test: Run gulp build.
=> Add helpers. Rebuild header.

scss/_vanilla.scss, scss/modules/_footer.scss
- Striped out the footer to only include simple footer styles
- Add doc comments
- Run ```gulp build```
- Check the docs under General > vf-footer
=> [Footer] Strip out and document

scss/modules/_forms.scss
Done:
Added comment block
Changed hard-coded min-width to use a var
QA:
gulp build
=> commented and updated variables

scss/modules/_header.scss, scss/modules/_helpers.scss
Done: Added documentalistic comments.
Test: Open files, read comments. Always run gulp build, always.
=> Add header comments

scss/modules/_header.scss, scss/modules/_helpers.scss
Done: Add breakpoint variables. Fix comments in helpers file.
Test: Run gulp build.
=> Add breakpoint variables. Fix comments in helpers file.

scss/modules/_typography.scss
Done:
Added a header to the file and set the default font size
QA:
gulp build, no errors
=> Typography

scss/modules/_rows.scss
Done:
Cleaned and added heading to rows file
QA:
gulp build without errors
=> clean up and add heading comment to rows

README.md, package.json
- Metadata updates to package.json
- Readme h1 tweak
na
have a look at the additions in package.json and also `npm run clean && npm install`
=> updated readme, added lots of metadata to package.json

scss/modules/_search.scss
Done:
Added comment block to the top of the file and cleaned vars and comments
QA:
gulp build without errors & check docs are generated, why not!?
=> add heading comments to search and tidy scss

scss/_global-settings.scss, scss/modules/_grid.scss
- Striped the grid styles down
- Added doc comments
- Run ```gulp build```
- Run ```google-chrome index.html``` and check the grid at the top aligns correctly
- Run ```google-chrome build/docs/index.html``` and check the Grid section is documented
=> Updated grid with docs and striping out old styles

package.json
- Moved gulp-utils to devdependences
- Run ```rm -rf node_modules``` 
- Run ```npm install```
- Check all's ok
=> Move utils to dev-dependencies

scss/modules/_blockquotes.scss, scss/modules/_buttons.scss, scss/modules/_footer.scss, scss/modules/_grid.scss, scss/modules/_lists.scss, scss/modules/_rows.scss, scss/modules/_tables.scss
Done:
A couple of examples
QA:
gulp build
=> add some examples

scss/modules/_forms.scss
Done:
Reordered rules alphabetically
QA:
gulp build check nothing is on fire
=> cleaned up forms (mostly by pressing f9)

index.html, scss/modules/_header.scss
=> Fix header in demo

README.md
QA
--
Checkout [the README.md](https://github.com/nottrobin/vanilla-framework/blob/downloads-badge/README.md). It has downloads!
=> Add downloads badge!

.travis.yml
QA
--
Check gitter - maybe it will have posted something in there?
https://gitter.im/ubuntudesign/vanilla-framework
=> Add gitter integration to travis

README.md, package.json
QA
--
Check out [the README](https://github.com/nottrobin/vanilla-framework/blob/david-badges/README.md)! See all those awesome badges!
=> Add dependency badges from David-dm.org

README.md
To QA, look at the README on [my branch](https://github.com/nottrobin/vanilla-framework/blob/readme-improvements/README.md).
=> Simplify and improve readme

scss/modules/_footer.scss, scss/modules/_helpers.scss
Add new helpers
Add additional footer css
Run gulp build.
=> Add extra helper and footer classes

demo/index.html, scss/_vanilla.scss, scss/modules/_vertical-divider.scss
- Added the vertical-divider module
- Added new module to demo
- Linted the vertical-divider module
- Run `google-chrome demo/index.html`
- Check the vertical-divider section looks ok
=> Added vertical dividers module

demo/index.html, scss/_vanilla.scss, scss/modules/_equal-height.scss, scss/modules/_lists.scss, scss/modules/_typography.scss
- Added the equal-heights module
- Added it to the demo
- Check `google-chrome demo/index.html` has a equal height section
- Check the heights are equal
=> Equal heights

scss/_global-settings.scss
- Aligned the values
- Updated the brand color
- Check all values line up in global-settings
- Check the header background is #F5F5F5
=> Align values with update to brand color

scss/modules/_footer.scss
- Changed the structure of the _footer module to lint
- Please run `gulp test` and see there are no issues
=> Fix lint issues in footer module

demo/index.html, gulpfile.js, scss/modules/_forms.scss
- Issue: https://github.com/ubuntudesign/vanilla-framework/issues/173
- Added field state styles
- Added fields with all four states in the demo
- Added inline gulp sass errors
- Run `make build && google-chrome demo/index.html`
- Check the field states look ok
=> Add input field states

demo/index.html, scss/modules/_helpers.scss
Removed ‘The end’ comment after </html>
Added two new helper classes.
These changes have been made to test the Jenkins build.
Make sure the comment has gone from /demo/index.html
Run gulp build
=> White space type demo change and add new helper classes.

demo/index.html, scss/_global-settings.scss, scss/modules/_helpers.scss, scss/modules/_media.scss
- Added all our helper classes to _helpers.scss
- Documented the helper mixins
- Added demos of the helpers to the bottom demo/index.html
- Lint and check no errors
- Check the demo works
- Check they are all documented in the docs
=> Add helper classes

scss/modules/_helpers.scss
- Added missing wrapper for pull-bottom-right 
- Check pull-bottom-right class is wrapping its styles
- Check its working on canonical and ubuntu sites
=> Add pull-bottom-right wrapper to patch helpers issue

scss/modules/_helpers.scss
- This is a partial of this card: https://canonical.leankit.com/Boards/View/111185042/115572517
- Removed the pixel value pull mixins from the helpers module
- Check the .pull-left-20, .pull-right-20, pull-left-40 and .pull-right-40 have been removed
- Check `gulp build` has no errors
=> Remove pixel value pull classes from helper

demo/index.html, scss/modules/_helpers.scss, scss/modules/_rows.scss
- Updated the pull modules to use the `$gutter-width` var
- Updated the rows module to use the `$gutter-width` var
- Added all the pull modules to the pattern library (demo)
- Removed pull-top-* as there is no easy way to do that
- Check the demo contains all the modules in the helpers module
- Check all view ports that the modules perform as expected
- Check rows are acting the same on all view ports
=> Rows and pulls now respect gutter-width

demo/index.html, scss/modules/_lists.scss
- Card: https://canonical.leankit.com/Boards/View/111185042/114833204
- Added stepped list to the lists module
- Added a demo to the list section of the demo
- Added doc strings for the component
- Check there are no lint errors
- Check the stepped-list in the demo looks good and matches [1]
- Check the docs is ok
- Check all view ports
*This will require mark up changes to the sites for usage*
[1] https://jujucharms.com/big-data
=> Added stepped list to the lists module

demo/index.html, scss/modules/_helpers.scss, scss/modules/_reset.scss
- Issue: https://github.com/ubuntudesign/vanilla-framework/issues/190
- Card: https://canonical.leankit.com/Boards/View/111185042/115595592
- Added a med-six-col class to helpers
- Added an example to the demo page
- Added comments for the docs
- Run `gulp check` and see there are no errors
- Check the demo of the med-six-col (last row) works as expected
- Check the docs are ok
=> Add med six col

demo/index.html, scss/_global-settings.scss, scss/modules/_lists.scss
#Done
Add ubuntu and canonical list tick styles to demo
##QA
Run ‘gulp build’ then open the demo.
=> Add list ubuntu and list canonical styles

scss/modules/_lists.scss
Refactor list-ticks to be a placeholder 
Pull the branch and then open the demo in your browser and not that the example list-ticks is still working.
=> Change list-ticks to a placeholder

scss/modules/_lists.scss
Refactor list-ticks to add border. Re-use .list styles as placeholder.
Pull then gulp build and check that .list and .list-ticks look okay in the demo.
=> Refactor list-ticks to add border

demo/index.html, scss/modules/_breadcrumbs.scss
Refactor breadcrumb
Pull this branch then gulp build and pop on over to /demo/index.html and make sure the breadcrumb looks okay.
Card: https://canonical.leankit.com/Boards/View/111185042/116353975
=> Refactor breadcrumb

README.md
- Added With ♥ from Canonical to README
- Check is there
- Card: https://canonical.leankit.com/Boards/View/111185042/118888617
=> Add with love from Canonical

demo/index.html, scss/modules/_inline-logos.scss
Add more logo and redesign .inline-logos SASS
Run ‘gulp build’ then have a look at /demo/index.html and check the inline-logos in large, medium and small viewports.
Card: https://canonical.leankit.com/Boards/View/111185042/119397373
=> Inline logos

package.json
This reverts commit 7ff026e21223d663c9ac79fd73a6eaf2abca0964.
I made a silly commit as I thought I knew the release process but it turns out I did not. :-1:
=> Revert "Bump package.json version to 0.0.6"

demo/index.html, scss/modules/_equal-height.scss, scss/modules/_helpers.scss
Add align-vertically helper
Run gulp build, pop on over to demo/index.html and have a lookie at .align-vertically there in the helper section.
Card: https://canonical.leankit.com/Boards/View/111185042/115594581
=> Add align-vertically helper

scss/modules/_reset.scss
Remove img max-width: none
May just need a visual
Card: https://trello.com/c/ubifVSdr
=> Remove img max-width: none

demo/index.html, scss/_vanilla.scss, scss/modules/_equal-height.scss
Merge vertical-divider into equal-height
Run gulp build the head over to the demo and make sure it's all good
Card: https://trello.com/c/XeMta6PC
=> Merge vertical-divider into equal-height

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, scss/_global-settings.scss
Creates new PR and issue templates for vanilla
Pull down branch ```git@github.com:richmccartney/vanilla-framework.git```
Create a PR of the branch and attempt to merge or create an issue on the branch
_n/a_
_n/a_
_n/a_
_n/a_
=> Pull request and issues template

demo/index.html, scss/_global-settings.scss, scss/_vanilla.scss, scss/modules/_boxes.scss
Add .box to the demo
Run ‘gulp build’ then go to /demo/index.html#box and have a look at the boxes
Card: https://trello.com/c/EL60P80G
=> Add boxes to demo

demo/index.html, scss/modules/_forms.scss, scss/modules/_header.scss, scss/modules/_search.scss
Add header search.
Use asset server for assets in header and search SASS files.
Run gulp build, head over to the demo. Check the search box in large, medium and small screens.
Also check that the search icon on small changes colour if $brand-color is below a certain lightness. 
Card: https://canonical.leankit.com/Boards/View/111185042/117138508
Fixes: #232
=> Add header site search

scss/_global-settings.scss, scss/modules/_header.scss, scss/modules/_search.scss
Refactor search
Run 'gulp build’ then check the demo at various viewports.  
Card: https://trello.com/c/dn6XDJte
=> Refactor search

scss/modules/_search.scss
Change lightness setting of contrast function
=> Change lightness setting of contrast function

.travis.yml
=> Specify node version

scss/modules/_rows.scss
- Moved row--grey to accompany row so it has higher specificity 
- Run `gulp build` and check the .grey--row section in the demo looks good
=> Nest row--grey in row

scss/modules/_boxes.scss, scss/modules/_breadcrumbs.scss, scss/modules/_buttons.scss, scss/modules/_equal-height.scss, scss/modules/_footer.scss, scss/modules/_forms.scss, scss/modules/_grid.scss, scss/modules/_header.scss, scss/modules/_reset.scss, scss/modules/_rows.scss, scss/modules/_search.scss
Added font-smoothing and box-sizing rules under global star selector. Removed other redundant box-sizing rules.
Pull down code, build and check demo for breakage.
Fixes: #325
=> #325 Add box-sizing and font-smoothing globally

scss/modules/_grid.scss
- Added `inline-block` to grid elements
- `gulp build`
- Check the grid section in the demo looks the same
=> Add inline-block to grid element

scss/modules/_lists.scss
Modified the step-lists at small and medium viewports.
```gulp build```
Load the demo in the browser and check that step-lists look good at all viewports
=> fix step-lists at smaller viewports

scss/_global-settings.scss
- Make all settings !default so they can be overriden
- `gulp build`
- Check the fonts load of in the demo
=> Make all settings to !default

scss/modules/_buttons.scss
- Style just the background-colour as it was effecting images on buttons
- `gulp build`
- Check the buttons look and work the same
=> Target just backound-color for button styling

scss/modules/_typography.scss
- Add antialising styling to all elements
- Check the demo is ok
=> Add antialiasing to all

scss/modules/_buttons.scss
Remove erroneous filename from _buttons include.
=> Remove erroneous duplicate filename

scss/modules/_reset.scss
Update `reset.scss` to use latest and greatest thinking from [Normalize 4](http://necolas.github.io/normalize.css/)
Pull down latest changes and scour demo page for breakage.
Fixes: #324
=> Update reset to use Normalize 4.1.1

README.md
Using this updated method should remove the conflict caused by moving from NPM 2 to NPM 3.
Read the new instructions, try them out and make sure they work.
Fixes: #364, #211
=> Update local usage instructions in README to include @import method

demo/index.html
Add deep linking id to each demo section
Navigate to /demo and check that you can jump to each section using the relevant id.
Fixes: #292
=> Add deep linking id to each demo section

.travis.yml, demo/index.html, gulpfile.js
- Add percy.io visual regression testing
- Update freenode channel for Travis CI ping
- Export CSS into demo folder so index page is not dependant on external resource
Sanity check code. Check that percy check in this PR passes.
=> Percy spike

index.html
- Update code and bug links on project page to point to the real project
- Probably just need a visual but check the links work
=> Update code and bug links on project page

.github/ISSUE_TEMPLATE.md
Amend Issue Template to allow for new pattern proposal process.
Check for grammar and spelling.
Trello: https://trello.com/c/6g9sNGQk
=> Propose amendment to Issue Template

docs/partials/footer.hbt, docs/templates/page.hbt, scss/_tools_grid.scss, scss/pattern-lib.scss
Fix Sass linting errors which were breaking the build.
Pull down code and run `gulp test` from project root. There should be no errors.
Fixes: #410
=> 410 -  Fix Sass linting errors

V1_RELEASE_NOTES.md, scss/_utilities_visibility.scss, scss/_vanilla.scss
Added visibility utility classes. These allow a develop to positively state whether an element should be visible or hidden within a specific breakpoint.
- Code should be identical in this demo which should show it working; http://codepen.io/barrymcgee/pen/jAZxZp
- Divs with `.u-hidden--*` should be hidden when in `$breakpoint-*`
- Divs with `.u-visible--*` should be visible when in `$breakpoint-*`
Fixes: #430
=> Add visibility utility classes

V1_RELEASE_NOTES.md, demo/index.html, docs/patterns/_buttons.md, docs/patterns/_grid-list.md, docs/patterns/_links.md, docs/utilities/_helpers.md, scss/_base_links.scss, scss/_base_typography.scss, scss/_patterns_buttons.scss, scss/_patterns_links.scss, scss/_utilities_helpers.scss, scss/_vanilla.scss
- Updated base styling of links
- Update `.external` link pattern to become `.p-link--external`
- Update `.link-top` link pattern to become `.p-link--top`
- Update documentation
- Temporarily add back `demo` folder for QA purposes
- Run `gulp develop` and check `demo/index.html` for new and improved links as above.
Fixes: #417
=> Audit links

V1_RELEASE_NOTES.md, scss/_utilities_helpers.scss
Remove superfluous pull utils as their use cases are too specific for Vanilla.
Sanity check code.
Fixes: #429
=> Remove superfluous pull utils

V1_RELEASE_NOTES.md, demo/index.html, docs/utilities/_helpers.md, docs/utilities/_off-screen.md, scss/_utilities_helpers.scss, scss/_utilities_off-screen.scss, scss/_vanilla.scss
- Refactored `.accessibility-aid` as `.u-off-screen` and moved into separate util file.
- Updates docs
- Pull into vf.io pattern lib and check docs load as expected
Fixes: #423
=> Abstract .accessibility-aid as .u-off-screen

V1_RELEASE_NOTES.md, demo/index.html, docs/layout/_grid.md, docs/layout/_vertically-center.md, docs/utilities/_helpers.md, docs/utilities/_text-center.md, scss/_layout_equal-height.scss, scss/_utilities_helpers.scss, scss/_utilities_text-center.scss, scss/_vanilla.scss
- Refactored the `.align-center` util to `.u-text-center`
- Make sure I haven't changed anything I should not have
- View corresponding docs in vf.io
- View nested grid docs in vf.io to labels are centered using this util class.
Fixes: #425
=> Abstract .align-center to .u-text-center

V1_RELEASE_NOTES.md, docs/base/_code.md, docs/patterns/_code-snippets.md, docs/patterns/_code.md, docs/settings/_color-settings.md, scss/_base_code.scss, scss/_patterns_boxes.scss, scss/_patterns_breadcrumbs.scss, scss/_patterns_buttons.scss, scss/_patterns_code-snippets.scss, scss/_patterns_code.scss, scss/_patterns_lists.scss, scss/_patterns_search.scss, scss/_settings_colors.scss, scss/_settings_font.scss, scss/_vanilla.scss
- Changed color white/black to light/dark
- Simplified code patterns
- Abstracted code snippets into separate pattern
- Abstracted monospace font family into settings file
- Sync up vf.io and test `base/code`, `patterns/code` and `patterns/code-snippets`
Fixes #398
=> Audit code & code snippets patterns

docs/patterns/_header.md, docs/utilities/_text-center.md, scss/_patterns_header.scss, scss/_vanilla.scss
- Removed complexity from header pattern, including second level nav
- Added lean pattern for mvp use-case - logo and list of nav links
- Fixed typo in `.u-text-center` docs
Note: This pattern will be revisited when we have the new logo and styling will be finalised.
Pull down code, check revised pattern in vf.io
Fixes #420, #148, #234, #184
=> Simplify and refactor header pattern

docs/patterns/_footer.md, scss/_patterns_footer.scss, scss/_vanilla.scss
Vastly simplify footer styling to cater for the minimum viable use case of a footer - copyright/legal text and a list of links.
- Sync and check footer pattern in vf.io
Fixes #399
=> Refactor and simplify footer pattern

docs/base/_lists.md, scss/_base_lists.scss
- Simplified base list styles
- Updated docs to include ordered, unordered and nested lists
- Sync and test with vf.io
Fixes #392
=> Clean up base lists

docs/patterns/_strip.md, scss/_patterns_strip.scss, scss/_vanilla.scss
- Added `.strip` pattern to allow full-width container.
- Sanity check code and docs.
Fixes #351
=> Add strip pattern

docs/patterns/_code-snippets.md, scss/_patterns_code-snippets.scss
Change code pattern to use single class modification convention
- Test with vf.io
Fixes #463
=> Convert code pattern to use single class modification

V1_RELEASE_NOTES.md, docs/base/_button.md, docs/patterns/_buttons.md, docs/settings/_color-settings.md, scss/_base_button.scss, scss/_patterns_buttons.scss, scss/_patterns_forms.scss, scss/_settings_colors.scss, scss/_vanilla.scss
- Add base styles for buttons
- Add button patterns as per spec in #397 
- Compare spec & button examples in `vf.io `
Fixes #397, #373, #354
=> Simplify and audit buttons

docs/patterns/_breadcrumbs.md, scss/_patterns_breadcrumbs.scss, scss/_patterns_strip.scss, scss/_vanilla.scss
- Reduce complexity
- BEMify all the things
- Remove nested levels of breadcrumbs
- Sync vf.io and test breadcrumbs pattern in browser
Fixes #396
=> Refactor breadcrumbs styling

scss/_base_links.scss
Fonts should not be bold - they should be font-weight 400.
Pull down and test that links are not bold
=> Change font-weight of links to 400

docs/patterns/_notification.md, scss/_patterns_notifications.scss, scss/_settings_colors.scss, scss/_vanilla.scss
- Added notification component
- Added notification documentation
- Updated the negative colour slightly to be accessible with white text
- Check out the notification pattern in the vf.io
- Remove the action link and see the components responses
- Increase the text content of both the action and content. Check the component works well.
- Design: https://github.com/CanonicalLtd/juju-design/tree/master/Notifications
- Issue: https://github.com/ubuntudesign/vanilla-framework/issues/458
=> Added notification component

docs/base/_blockquote.md, docs/base/_button.md, docs/base/_code.md, docs/base/_lists.md, docs/base/_reset.md, docs/base/_tables.md, docs/base/_typography.md, docs/layout/_clearfix.md, docs/layout/_equal-height.md, docs/layout/_grid.md, docs/layout/_number-word.md, docs/patterns/_breadcrumbs.md, docs/patterns/_buttons.md, docs/patterns/_card.md, docs/patterns/_code-snippet.md, docs/patterns/_code.md, docs/patterns/_footer.md, docs/patterns/_forms.md, docs/patterns/_grid-list.md, docs/patterns/_header.md, docs/patterns/_image-grid.md, docs/patterns/_links.md, docs/patterns/_pull-quote.md, docs/patterns/_search.md, docs/patterns/_strip.md, docs/patterns/_tabs.md
Corrected the titles of the docs.
Read the changes to the docs.
Partial fix for https://github.com/ubuntudesign/vanillaframework.io/issues/14
=> fix capitalisation of docs titles

docs/base/_tables.md, scss/_base_tables.scss
- Simplify base table styling
- Reduce specificity caused by nested selectors
- QA base table pattern in vf.io
Fixes #390
=> Clean up base table styling

scss/_patterns_code-snippet.scss, scss/_patterns_links.scss
Convert all asset server based SVG images inline SVGs
Check each of the replaced SVGs and make sure they are loading
=> Make icons inline svgs

V1_RELEASE_NOTES.md, docs/settings/_color-settings.md, scss/_patterns_header.scss, scss/_settings_colors.scss
* removed color-brand-light
* removed color-alto-grey
* set color-brand to 333
* swapped colors for color-warm-grey and color-mid-grey
* drive-by - updated header pattern to use the color-brand
1. look at /settings/color/ to see all the colors
2. look at /patterns/header/ to see the header update
Fixes #499
=> updating and removing colors

scss/_base_blockquotes.scss
Add top/bottom margin to base blockquotes
Pull code, QA with `vf.io`
=> Add top/bottom base blockquote margins

docs/patterns/_notification.md, docs/settings/_assets-settings.md
- Removed a colon
- Made notification pattern title capitalised
=> Hygiene: Fix up two typos

docs/base/_code.md, scss/_base_code.scss
* changed whitespace pre-line to line for code and pre
* see that code indents work
=> removed ‘pre-‘ from whitespace on pre and code

docs/base/_table.md
* make table singular in documentation
* renamed file as well
1. go to /base/table/ and see that it is singular
Fixes [vanillaframework.io bug 28](https://github.com/ubuntudesign/vanillaframework.io/issues/28)
=> update table documentation

docs/base/_button.md, docs/patterns/_buttons.md, scss/_base_button.scss, scss/_patterns_buttons.scss
- Clean up of button patterns
- Add styles to work with hyperlink buttons
- Tested on Firefox, Chrome, Safar, IE9+
- Code QA
- Visual QA on vf.io
#191
=> Resolving button styles to work along side anchor tags

docs/base/_lists.md
Removed a list item with the wrong text.
Check that the rendered list doesn't look broken (compare with the demo)
=> remove erroneous list item

scss/_base_typography.scss, scss/_settings_font.scss
Fixed two linting errors:
- Over indentation
- Domain in font import URL
Linting should pass in this PR
=> Font linting fix

docs/patterns/_links.md, scss/_patterns_links.scss
- Created a new back to top link style
- Code QA
- Visual QA
#515
=> Updating the top style and docs

docs/patterns/_stepped_list.md
- Fixed typo on stepped list
Fixes: https://github.com/ubuntudesign/vanillaframework.io/issues/47
=> Fix spelling mistake on stepped list

docs/base/_forms.md
- Code check required
Fixes: https://github.com/ubuntudesign/vanillaframework.io/issues/46
=> Uppercase Base.Forms in navigation

docs/base/_blockquote.md
- Fixes: https://github.com/ubuntudesign/vanillaframework.io/issues/38
=> Update example blockquote copy

docs/base/_blockquote.md, docs/patterns/_strip.md, docs/utilities/_padding-collapse.md, docs/utilities/_vertically-center.md, docs/utilities/_visibility.md
- Added exampled to the visibility utility documentation
- Go http://localhost:3000/utilities/visibility/
- Check there are examples.
- Check the issues are all resolved.
- Fixes: https://github.com/ubuntudesign/vanillaframework.io/issues/37
- Fixes: https://github.com/ubuntudesign/vanillaframework.io/issues/36
- Fixes: https://github.com/ubuntudesign/vanillaframework.io/issues/35
- Fixes: https://github.com/ubuntudesign/vanillaframework.io/issues/34
- Fixes: https://github.com/ubuntudesign/vanillaframework.io/issues/33
=> Add visibility examples

docs/patterns/_buttons.md, scss/_base_button.scss, scss/_patterns_buttons.scss, test.scss
* merged Ant and Rich's button code based on [Spencer's juju designs](https://github.com/ubuntudesign/vanilla-framework/issues/397#issuecomment-240381885)
* created a mixin rather than a pattern
1. go to /patterns/buttons
2. see that the buttons match [Spencer's doc](https://github.com/ubuntudesign/vanilla-framework/issues/397#issuecomment-240381885)
Fixes #51, #228, #191 and #551
=> 551 button bugs

scss/_patterns_lists.scss
- Lint lists pattern 
- change `em` units to `rem`
- change `px` units to `rem`
- change middot to HTML entity
- Check code
- QA with `vf.io`
=> Lint lists pattern

scss/_patterns_navigation.scss
Re-ordered source order to pacify linter
- Qa with vf.io
=> Lint navigation pattern

scss/_patterns_notifications.scss
- Re-ordered source order
- Swapped out modified alpha border color of cool grey to light grey as colors should only be defined in color settings file.
- QA in vf.io
=> Linting notification pattern

scss/_patterns_pull-quotes.scss
Addressed all warnings when linting pull quote pattern by re-ordering source order
Sanity check code, check I haven't broken pattern in vf.io
=> Pacify linter - pull quotes pattern

scss/_patterns_grid-list.scss, scss/_patterns_image-grid.scss
- Lint grid-list pattern
- Lint image-grid pattern
Check patterns in vf.io
=> Lint grid-list / image-grid patterns

scss/_base_links.scss, scss/_patterns_links.scss
- Lint base links styling
- Lint links patterns styling
- Check nothing breaks in vf.io
=> Lint links scss

scss/_base_tables.scss, scss/_layout_equal-height.scss, scss/_patterns_grid-list.scss, scss/_patterns_lists.scss, scss/_vanilla.scss
- Refactor remaining scss files to use same format and naming convention as other scss partials.
- Check code still builds
=> Tidy up _vanilla.scss manifest

scss/_patterns_card.scss
- Re-order source order
- Refactor extend pattern to use placeholder
- Use $color-light-grey instead of alpha transparency of $color-mid-grey
- Check code
- Check pattern in vf.io
=> Lint card pattern

scss/_patterns_code-numbered.scss
- Re-order selector order to pacify linter
- Check code
- Check pattern in vf.io
=> Lint code numbered pattern

scss/_patterns_code-snippet.scss
- Re-order source order
- Change extend class to placeholder
- Remove transition all
Check code
Check pattern in vf.io
=> Lint code snippet

docs/patterns/_grid-list.md, scss/_patterns_grid-list.scss, scss/_settings_colors.scss
Rebuild grid list using flex box
View the grid list example in s, m & l
=> Grid list audit

scss/_layout_equal-height.scss
- Re-ordered source order
Check code
=> Lint equal height

scss/_base_code.scss
=> Lint base code

scss/_base_lists.scss
Re-order source order
Check code
=> Lint base lists

scss/_base_media.scss
Lint base media by reordering source
Check code
=> Lint base media

scss/_base_tables.scss
Re-ordered source order
Check code
=> Lint base tables

scss/_patterns_footer.scss
- Lint footer pattern by re-ordering sort order
- Check code
- Check pattern in vf.io
=> Lint footer scss

docs/settings/_color-settings.md, scss/_settings_colors.scss
- Re-add information color variable
- Use color variable for input shadow setting
- Check code
- Check color settings in vf.io
Fixes: #539
=> Re-add information color variable

scss/_base_forms.scss
Reduce border-radius on default fieldset to 2px
Check fieldset example in base/forms on vf.io
Fix #604
=> Reduce border-radius on default fieldset to 2px

.gitignore
- Add node modules ignore
- Run `npm install` and check there is nothing staging as uncommited
=> Add node_modules to the .gitignore file

docs/patterns/_card.md
- Remove the double modification on card hightlight
- Check out vf.io with this branch
- Go to http://localhost:3000/patterns/card/
- Check that the highlighted version has no border and a single class of `p-box--highlighted`
=> Remove the double modification on card hightlight

scss/_base_box-sizing.scss, scss/_base_forms.scss, scss/_layout_grid.scss, scss/_vanilla.scss
Added box-sizing rule to make working with box model more consistent across the framework.
- Check code
- Run through vf.io patterns and look for breakage
Fix #603 
More info: https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/
=> Add box-sizing: border-box rule

scss/_base_button.scss
Added disabled pointer to disabled buttons on hover
Check base buttons in vf.io
Fixes #637
=> Disabled buttons should have disabled pointer

docs/patterns/_navigation.md
Remove role=navigation from nav as it's implied.
Check code
=> Remove role=navigation from header

docs/patterns/_links.md
This will allow the code example below to clear meaning it can expand to 100% width of container.
- Go to /patterns/links
- Check that code blocks are same width on large screens
Fixes #635
Should look like: https://www.dropbox.com/s/gmeai7zjpvfu6mo/Screenshot%202016-09-15%2010.44.50.png?dl=0
=> Fix patterns/links code width issue

README.md
- Remove reference to _global_settings.scss as it's now been removed
- change forms mixin reference
Check README makes sense
=> Update README to reflect v1 changes

scss/_base_typography.scss
H1s and P tags should not have top margin
- Check code
- Sync up with vf.io
=> Remove top margin from headers and paragraphs

.travis.yml
- Updated the Travis-CI node version to render svgo's use of for...of
- If CI passed then its QA'ed
=> Update node version for CI

scss/_settings_colors.scss
Change $color-mid-grey from `#888` to `#666` for accessibility reasons.
- Check code
- Qa with `vf.io`
Fixes #660
=> Change $color-mid-grey from #888 to #666

docs/patterns/_code-snippet.md, scss/_patterns_code-snippet.scss
- Namespace code snippets with `p-`
- Fix up nested placeholders with appropriate extends
- Sync code with vf.io and check pattern display across breakpoints
Fixes #621
=> Fix up code snippets pattern

README.md, docs/patterns/_notification.md, scss/_patterns_notifications.scss
- Amends the notification design to follow the new updates from the Cloud workshop
- Changes the documentation in conjunction with the changes
- QA the front end code
- Visual QA from the designs @spencerbygraves created.
Detail of the new notification designs:
https://github.com/CanonicalLtd/juju-design/issues/151#issuecomment-246964507
=> Notifications pattern

scss/_patterns_footer.scss
- Removed padding-top from footer copy
Check code, sync with vf.io
Fixes #664
=> Remove padding-top from footer copy

docs/base/_forms.md, docs/patterns/_buttons.md, docs/patterns/_code-numbered.md, docs/patterns/_strip.md, scss/_patterns_buttons.scss, scss/_patterns_code-numbered.scss, scss/_patterns_strip.scss
Namespace these patterns with `p-` for consistency with rest of the framework. Remove redundant sassdoc comments.
- Check code
- Check `vf.io` for inconsistencies
=> Hygiene: clean up naming of buttons / code-numbered / strip

scss/_patterns_pull-quotes.scss
Tweaks styling to match designs
Test changes against design here: https://github.com/ubuntudesign/vanilla-design/blob/master/Pull%20quote/Pull%20quote.png
Fixes #634
=> Fix up pull quotes

scss/_patterns_lists.scss
Fix up pattern to match designs: https://github.com/ubuntudesign/vanilla-design/blob/master/Lists/Stepped/Stepped.png
Check pattern against designs
Fix #636
=> Fix up stepped list

README.md
- Clean up copy a little
- Remove reference to themes for now as ubuntu-vanilla-theme and canonical-vanilla-theme are not compatible with this version of VF yet
- Update bash commands example to accurately reflect gulp commands
Read the copy, ensure no mistakes
=> Tweak the README copy

scss/_base_hr.scss, scss/_vanilla.scss
Added basic HR styling into base layer
- Review the code
Fixes: #710
=> Add base HR styling

scss/_patterns_grid.scss, scss/_vanilla.scss
Encapsulated grid partial into a mixin to be consistent with all other patterns.
- Pull code
- Run `gulp build` and ensure the build still runs
Fixes: #716
=> Encapsulate grid in mixin for consistency

scss/_patterns_matrix.scss
- Fixed up `.p-matrix` pattern to allow for differing line lengths of content in each list item
- Pull code
- Create demo.html page
- Check differing matrixes by pasting the mark-up below
```html
<html>
<head>
</head>
<body>
<div class="p-strip">
<h2>5 item matrix</h2>
<ul class="p-matrix u-clearfix">
<li class="p-matrix__item">
<div class="p-matrix__content">
<h3 class="p-matrix__title"><a class="p-matrix__link" href="#">Title</a></h3>
<p class="p-matrix__desc">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem ipsum, eum. Necessitatibus, unde, nesciunt! Esse incidunt quaerat voluptatem nemo quisquam, maiores beatae delectus quas, suscipit assumenda quam cumque …
```
=> Fix up breaking pattern - .p-matrix

README.md
It's freenode.net not freenode.com
- Fix IRC link in README.md
1. Does README.md show a valid IRC server?
N/A
N/A
=> Fix freenode IRC address

scss/_base_links.scss, scss/_patterns_links.scss, scss/_settings_colors.scss
Note: *Design QA required before merging*
- Update base link styles
- Added `p-link--strong`
- Added `p-link--soft`
- Added `p-link--inverted`
View demo here: https://vanilla-8faed.firebaseapp.com/
Fixes #717
=> Update link styles

.travis.yml
Added Percy integration 
Checking if Tavis passes this PR
=> Adding Percy integration

docs/patterns/_matrix.md
- Update Matrix docs to reflect column changes in 1.1.4 release.
- Check docs
=> Update Matrix docs

.travis.yml
=> Update .travis.yml to add --baseurl flag

.travis.yml, gulp/styles.js
- Refactored travis.yml to remove race conditions between jekyll and the CSS build
- Check code
- Ensure all tests in the PR pass
=> Simplify .travis.yml for percy testing

docs/patterns/_headings.md
Check that the updated intro sentence is OK.
=> Changed the headings doc copy

README.md
=> Add package manager install instructions

docs/en/settings/breakpoint-settings.md
- Changed h3 to h2s so it doesn't skip a level
- Changed gerund to infinitive form in headings
Go to settings > breakpoints.md and review the three h2 headings
=> Updated headings in breakpoints.md

docs/en/settings/color-settings.md
In settings > color-settings.md moved final paragraph to before table so it doesn't get lost.
See above.
=> Updated color-settings.md

docs/en/settings/font-settings.md
Merged first and last paragraph into one as the ideas are similar, and clarified rule in second paragraph ("should").
Go to docs > en > settings > font-settings.md and review the text.
=> Updated font-settings.md

docs/en/base/forms.md
Added related section at the bottom of forms.md to link to buttons
Go to docs > en > base > forms.md and scroll to bottom of page
=> Updated forms.md

docs/en/base/code.md
- Added intro to this page
- Rephrased inline code sentence
- Added description to code block section
- Added related patterns section
Go to docs > en > base > code.md
=> Updated code.md

docs/en/base/lists.md
- Added description to each list type
- Renamed definition list to description list (as it's now refered to in w3c standard)
- Added related section at the end
Go to docs > en > base > lists.md and check sections listed above.
=> Updated lists.md

examples/base/code.html, examples/patterns/code-numbered.html, scss/_base_code.scss, scss/_patterns_code-numbered.scss, scss/_patterns_code-snippet.scss
Fixed a number of design review issues.
- Step through the issue and make sure they are fixed
Fixes https://github.com/ubuntudesign/vanilla-framework/issues/848
=> Code block design review issues

docs/en/base/table.md
Added description text to tables.md
Go to docs > en > base > table.md and review the text above the example.
=> Updated table.md

docs/en/patterns/breadcrumbs.md
Added a description to the breadcrumbs pattern
Go to docs > en > patterns > breadcrumbs.md and read the intro text
=> Updated breadcrumbs.md

scss/_base_links.scss
- Pacify Sass linter
- No warnings should report
(Note: Percy should also now run here)
=> Hygiene: Fix linter & Percy test

examples/patterns/lists/lists-stepped.html, scss/_patterns_lists.scss
Rename `.list-step` to `.p-list-step` for consistency
- Pull code
- Review [http://127.0.0.1:3002/vanilla-framework/examples/patterns/lists/lists-stepped/](http://127.0.0.1:3002/vanilla-framework/examples/patterns/lists/lists-stepped/)
Fixes #874
=> Rename .list-step to .p-list-step

docs/en/patterns/footer.md
Added a short description to the footer pattern
Visit docs > en > patterns > footer.md and read the intro text
=> Updated footer.md

docs/en/patterns/pull-quote.md
Added description and related link to pull quote doc
Go to docs > en > patterns > pull-quote.md and read the description at the start and related content at the end
=> Updated pull-quote.md

docs/en/patterns/matrix.md
Updated the text in patterns > matrix.md
Go to docs > en > patterns > matrix.md and read the description above the examples.
=> Updated matrix.md pattern

docs/en/patterns/lists.md
Added descriptions to each pattern on patterns > lists.md
Go to docs > en > patterns > lists.md
Read the descriptions to each of the 7 list styles and the intro to the page
=> Updated patterns lists.md

docs/en/settings/assets-settings.md
=> Update settings/assets docs

docs/en/settings/layout-settings.md
Fixes #863
Proof read the docs.
=> Update docs for settings/layout

docs/en/patterns/pull-quote.md
Remove the link breaking forward slash
Should just need a visual review
=> Fix example blockquote link

docs/en/patterns/card.md
Change wording of highlighted card example link
Should only need a visual
=> Highlighted card incorrect link wording

scss/_patterns_pull-quotes.scss
Update pull quote pattern styling
- Pull code
- Check [example](http://127.0.0.1:4000/vanilla-framework/examples/patterns/pull-quotes/) against [design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Pull%20quote)
Fixes #807
=> Update pull quote style

package.json
- Run `npm i`
- There should no errors with any of the above.
=> chore(package): update gulp-shell to version 0.6.1

scss/_base_blockquotes.scss, scss/_base_code.scss, scss/_base_images.scss, scss/_base_links.scss, scss/_patterns_card.scss, scss/_patterns_lists.scss, scss/_patterns_navigation.scss, scss/_patterns_notifications.scss, scss/_patterns_pull-quotes.scss, scss/_patterns_strip.scss, scss/_utilities_clearfix.scss
- Move placeholders outside mixins
- Standardise whitespace
- Fix base images include
- Pull code
=> Global placeholders and fix whitespace

docs/en/metadata.yaml
Make docs sidebar alphabetical
Sanity check code and ensure alphabeticalness
Fixes https://github.com/ubuntudesign/docs.vanillaframework.io/issues/40
=> Make docs sidebar alphabetical

docs/en/settings/color-settings.md, scss/_settings_colors.scss
Updated Vanilla color variables and docs
Fixes #852
=> Update Vanilla colors

.travis.yml
=> Add travis slack notifications

docs/en/base/code.md, docs/en/base/forms.md, docs/en/base/lists.md, docs/en/patterns/grid.md, docs/en/patterns/lists.md, docs/en/patterns/pull-quote.md
Fix related links in docs
- Run docs locally and ensure link work
Fixes #920
=> Fix related links in docs

scss/_base_button.scss, scss/_patterns_buttons.scss
- Updated the base and neutral button property values to match the [design spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Buttons/buttons.md).
- Check the following patterns match the spec:
- Base - http://127.0.0.1:4321/vanilla-framework/examples/patterns/buttons/base/
- Neutral - http://127.0.0.1:4321/vanilla-framework/examples/patterns/buttons/neutral/
- Check the code is ok
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/916
=> Update the buttons to match the design spec

docs/en/metadata.yaml
Fix parse issues in the docs metadata file
- Check the yaml is valid
=> Fix the docs metadata

docs/en/metadata.yaml
Removed base/lists from docs navigation
- Check the code is correct.
=> Remove base/lists from docs navigation

docs/en/patterns/code-snippet.md
Remove dark code snippet from docs
- Check the copy has been removed and the link matches the example
=> Remove dark code snippet from docs

docs/en/patterns/navigation.md
Update the navigation documentation to include full and fixed width example
- Check copy is correct
=> Update the navigation documentation

_config.yml, scss/_base_forms.scss, scss/_base_typography.scss, scss/_patterns_card.scss, scss/_patterns_form-validation.scss, scss/_patterns_headings.scss, scss/_patterns_links.scss, scss/_patterns_lists.scss, scss/_patterns_notifications.scss, scss/_patterns_pull-quotes.scss, scss/_patterns_strip.scss
Convert @extends to @mixins to avoid hoisting issues which break the cascade
- Pull code
Fixes #913
=> Convert @extends to @mixins

docs/en/patterns/card.md, examples/patterns/links/links-external.html, scss/_patterns_links.scss
- Raise icon off the baseline
- Change color of icon on link hover
- Pull code
- Check [example](http://127.0.0.1:4325/vanilla-framework/examples/patterns/links/links-external/) against [design spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Links/links.png)
Fixes #720
=> Fix up .p-link—external

examples/utilities/align.html
- `gulp jekyll`
- Check http://127.0.0.1:4000/vanilla-framework/examples/utilities/align/
- Should look like: https://cl.ly/1t1F3d0Y1e1s
Fixes #938
=> Fix align utility example

docs/en/metadata.yaml
Switch settings/base in docs sidebar
- Run docs locally and ensure sidebar displays correctly
Fixes #945
=> Switch settings/base in docs sidebar

docs/en/base/typography.md
Fix broken Related link on Typography docs
- Check code
Fixes #937
=> Fix broken Related link on Typography docs

docs/en/settings/_animation-settings.md
Fix incorrect animation-settings file location and removed redundant front-matter attribute
- Check code
- Run docs and check animations setting page is accessible
=> Fix incorrect animation-settings file

examples/utilities/vertically-center.html
=> Fix title typo

scss/_patterns_card.scss, scss/_patterns_form-validation.scss, scss/_patterns_pull-quotes.scss, scss/_patterns_strip.scss
Moved the common mixins to the global scope. So they can be used by themes.
- Percy shouldn't have picked anything up
- Run `gulp build` and check there are no errors
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/961
=> Globalise mixins

examples/patterns/navigation/fixed-width.html, examples/patterns/navigation/full-width.html
Add a tag around item text, move href from list item to a tag
Pull code and run gulp jekyll
Make sure the navigation example still works with the updated code
=> Fix navigation example

CHANGELOG.md
Remove redundant CHANGELOG.md file. This is no longer needed.
Check file has been removed.
=> Remove redundant CHANGELOG.md file

docs/en/patterns/buttons.md, examples/patterns/buttons/inline.html, scss/_base_button.scss, scss/_patterns_buttons.scss
- Fixed neutral/negative example mixup
- Remove neutral button border color change on hover
- Refactored inline button to make explicit state class
- Pull code
- Check [examples](http://127.0.0.1:4000/vanilla-framework/) against [spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Buttons)
Fixes #976
=> Update buttons pattern to match spec

CONTRIBUTING.md
This is the same info that appears on repos like: docs.ubuntu.com
Fixes #778
=> Update CONTRIBUTING.md with licensing info

docs/en/settings/assets-settings.md
- Updated to match copy styleguide
- Changed word "specific" to "specify"
- visit /en/settings/assets-settings in Vanilla docs and read text
=> Updated assets-settings.md

docs/en/settings/animation-settings.md
Rephrased some of the content to read better.
Updated text content
Got to /en/settings/breakpoint-settings and read the whole text on the page to make sure it still makes sense and there's no mistakes.
=> Updated animation-settings.md

docs/en/base/typography.md
- Reordered the sub-sections in order of importance
- Made some small text changes
- Added more related content
Go to /en/base/typography and make sure the changes to copy make sense.
Fixes #944
=> Updated typography.md docs

examples/base/forms/checkboxes.html
Removed top and bottom whitespace from checkboxes example
View /en/base/forms and check the Checkbox and radio button example
=> Updated checkboxes example

examples/base/code.html
- removed top and bottom whitespace from code example
Check example in /en/base/code
=> Remove whitespace code example

examples/base/forms/disabled-input.html
Removed white space from top/bottom of example
View /en/base/forms and see Disabled state example
=> Updated disabled-input example

examples/base/forms/textarea.html
remove top/bottom space from example
Visit /en/base/forms go to Textarea example
=> Update textarea example

examples/base/forms/selects.html
remove top/bottom whitespace from example
visit /en/base/forms and look at Select example
=> Update selects example

examples/base/forms/fieldset.html
remove top/bottom whitespace from example
go to /en/base/forms and look at Fieldset example
=> Updated fieldset example

examples/base/forms/input.html
removed top/bottom whitespace from example
go to /en/base/forms and look at input example
=> Updated input example

examples/base/forms/labels.html
Visit /en/base/forms and look at … I can't find the labels example on the page.
=> Update labels example

examples/base/forms/radio-buttons.html
remove top/bottom whitespace from example
View /en/base/forms and look at second example in Checkbox and radio button
=> Update radio buttons

examples/base/forms/select-multiple.html
remove top/bottom margin from example
visit /en/base/forms and look at second Select example
=> Update select-multiple example

examples/base/forms/feedback.html
Removed top/bottom margin from example
View /en/base/forms and see Feedback classes example
=> Updated form feedback example

examples/base/blockquotes.html, examples/base/button.html, examples/base/forms/form.html, examples/base/forms/labels.html, examples/base/headings.html, examples/base/hr.html, examples/base/links.html, examples/base/lists/definition-list.html, examples/base/table.html, examples/patterns/buttons/base.html, examples/patterns/buttons/brand.html, examples/patterns/buttons/inline.html, examples/patterns/buttons/negative.html, examples/patterns/buttons/neutral.html, examples/patterns/buttons/positive.html
Remove whitespace from examples
- Check code
=> Remove whitespace from examples

.travis.yml
Added a step to Travis to ensure the Sass CLI build command runs successfully.
This PR should pass all checks below.
Fixes #1018
=> Add sass-cli check to .travis.yml build steps

docs/en/base/forms.md
Added formatting to related section
Added h2 heading to Related section
Go to /en/base/forms in docs, scroll to bottom to check Related section has correct formatting: h2 + list
=> Updated forms docs

examples/patterns/navigation/full-width.html
Add id to parent element so hide/show works for mobile
Run `gulp jekyll`, check example in small screen
=> Fix full-width nav example so mobile nav works

examples/patterns/navigation/fixed-width.html
Add id to parent element so hide/show works for mobile
Run `gulp jekyll`, check example in small screen
=> Fix fixed-width nav example so mobile nav works

docs/en/patterns/links.md
=> Update links.md to fix link error

scss/_settings_system.scss
Bump app version ready for release.
Check the version is `1.2.0`
=> Bump app version

scss/_settings_system.scss
Bump app version ready for release.
Check the version is `1.2.1`
=> Update system version for 1.2.1 release

scss/_settings_system.scss
Bump the system version
- Check the version is correct
=> Bump version to v1.2.2

.env
Default env should be development
Check code
=> Default env should be development

scss/_patterns_card.scss
This is a clone of PR https://github.com/vanilla-framework/vanilla-framework/pull/1088 which was causing weirdness in Percy/Travis due to double dashes in the feature branch name.
=> 1074 - recreated border

scss/_settings_assets.scss, scss/_settings_breakpoints.scss, scss/_settings_colors.scss, scss/_settings_font.scss, scss/_settings_grid.scss, scss/_settings_spacing.scss, scss/_settings_system.scss
- Add `!default` to all settings rules
- Make spacings consistent in settings files
- Check code
- Verify no visual changes in Percy
Fixes #1115
=> Clean up settings files

docs/en/settings/layout-settings.md
Change layout example of $grid-gutter-widths to $grid-gutter-width as per the variable in _settings_grid.scss
Make sure I’m not lying and the variable in _settings_grid.scss is actually $grid-gutter-width and not $grid-gutter-widths
=> Change grid-gutter-widths

docs/en/patterns/notification.md, examples/patterns/notifications/information.html, scss/_patterns_notifications.scss
Add information notification pattern & docs
- Pull code
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/notifications/information/
- Run docs build
- Check that docs reflect correct notifications pattern 
Fixes #1060
=> Add information notification pattern & docs

scss/_settings_system.scss
Release notes:
- Make sure nav pattern last item has bottom border (#1123)
- Vertically align 'Menu' toggle on small screens (#1121)
- Add information notification pattern & docs (#1125)
- Add documentation for spacing settings
- Ensure correct alignment of double-digit stepped list (#1106)
- Tweak border and padding styling of `.p-card`
- Correct base button text color to match spec
- Refactor `.u-vertically-center` so it only applies to medium and large breakpoints
- Update default button styling to be the same as neutral button styling
- Update the floats utility and add breakpoint support
- Add support for Cyrillic, Greek and Latin fonts
- Improve local …
=> Release 1.2.3

docs/en/patterns/card.md, examples/patterns/card/card.html, scss/_patterns_card.scss
* added a header to p-card per the [spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Card/card.md)
* updated the example
* updated the documentation
1. run locally
2. see the [jekyll example](http://127.0.0.1:4000/vanilla-framework/examples/patterns/card/card/)
3. compare to the spec and [image](https://github.com/ubuntudesign/vanilla-design/blob/master/Card/cards.png)
Fixes #1052
=> add header to p-card

docs/en/index.md
Update docs index file from https://docs.google.com/document/d/1OJJHIiTVHDKhXCZOStbsJpf2IXVdMkldsTjiq1tUUYw/edit#
- Pull code
- Ensure no errors
- Run process to build docs
- Cross ref with Google doc
=> Update docs index

scss/_base_button.scss
Ensure spacing between consecutive buttons
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/buttons/positive/
- Duplicate the buttons and place them beside the originals using Inspector
- Move through breakpoints and check spacing is appropriate
Fixes #1144
=> Ensure spacing between consecutive buttons

examples/patterns/footer.html, scss/_patterns_footer.scss
Update footer styling to match spec
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/footer/
- Cross ref with [spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Footer) and verify example matches design
Fixes #1151
=> Update footer styling to match spec

scss/_settings_system.scss
- Refactor footer pattern to improve stability (requires HTML changes) (#1156)
- Remove implicit top margin on `<pre>` elements (#1153)
- Ensure spacing between consecutive buttons (#1145)
- Add bottom border to L screen navigation pattern (#1155)
- Update documentation index (#1136)
- Update styling inline-images pattern to improve stability
- Allow for cherry-picking of patterns for modular builds
- Remove padding jump from input elements between breakpoints
- Fix bug with spacing between consecutive fieldsets
- Improve clarity of copy icon in code-snippet pattern
=> Release 1.4.0

scss/_patterns_lists.scss
Fix tick position
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/lists/lists-ticked/
- Check the position of the ticks
@yaili demo: http://vanilla-framework-fix-1057-list-ticks.demo.haus/vanilla-framework/examples/patterns/lists/lists-ticked/
Fixes #1057
=> Fix tick position

scss/_settings_system.scss
- Remove text underline on hover from `.p-navigation` pattern (#1193)
- Multiple small improvements to the documentation across the board.
- Bug fixes and optimisations across the framework.
=> Release 1.4.2

docs/en/index.md
Add git submodule instructions to Getting Started
- Pull code
- Review code to verify it makes sense.
Fixes #1199
=> Add git submodule instructions to Getting Started

docs/en/patterns/card.md, examples/patterns/card/overlay.html, scss/_patterns_card.scss
Tidy up the cards pattern some. Added the overlay card pattern. Added doc and example. 
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/card/overlay/
- Check it looks ok
- Check docs are present
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1207
=> Combine brochure theme card pattern

docs/en/metadata.yaml, docs/en/patterns/media-object.md, examples/patterns/media-object.html, scss/_patterns_media-object.scss, scss/_vanilla.scss
Port the media-object pattern from brochure theme
- Pull code
- Check that the media-object pattern looks ok
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1177
=> Port the media-object pattern from brochure theme

.spelling, docs/en/patterns/lists.md, docs/en/settings/color-settings.md, examples/patterns/lists/lists-split.html, examples/patterns/lists/split-list.html, scss/_patterns_lists.scss, scss/_settings_colors.scss
Ported over the two list patterns from brochure theme.
- Pull code
- Check http://0.0.0.0:8101/examples/patterns/lists/lists-ticked/
- Check http://0.0.0.0:8101/examples/patterns/lists/split-list/
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1210
=> Combine brochure theme list patterns

scss/_vanilla.scss, scss/base.scss
Removed the duplication in the include files. Added a brochure-theme mixin.
- Pull code
- Check it all works as before
- The brochure theme is, in fact, the same as the Vanilla but will differ to other themes when added.
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1261
=> Create the brochure theme mixin

package.json, yarn.lock
Update yarn deps in `package.json`
- Pull code
- Check no errors
- Check no errors in travis build
=> Update yarn deps

scss/_settings_system.scss
- Vanilla brochure theme is now part of Vanilla Framework. All themes will be added to Vanilla directly in the near future simplifying the ecosystem while increasing flexibility of Vanilla.
- Improve `<sup>` and `<sub>` positioning.
- Redefine the single element vertical spacing to resolve a couple of edge case bugs in utility patterns.
- Remove border-radius from card-overlay pattern.
- Add git submodule instructions to 'Getting started' section of docs.
- Escape hash in code snippet svg. (#1203)
- Add aria and accessibility improvements to navigation pattern. (#1202)
- Fix typographic inconsistencies to ensure `<small>` text should be 14px through all …
=> Update $app-version to 1.4.3

docs/en/patterns/card.md, examples/patterns/card/card.html, examples/patterns/card/highlighted.html, scss/_patterns_card.scss
Remove card content spacing
- Pull code
- Check that card content reflects vertical rhythm 
Fixes #1277
=> Remove card content spacing

scss/_vanilla.scss, scss/base.scss
Moved the includes around and removed repetition of includes
- Check Percy doesn't pick up any regressions.
=> Removed repetition of includes

docs/en/patterns/navigation.md, examples/patterns/icons/icons-dark.html, examples/patterns/icons/icons-light.html, examples/patterns/navigation/sidebar.html, scss/_patterns_icons.scss, scss/_patterns_navigation.scss, scss/_vanilla.scss
Add navigation--sidebar pattern
- Pull code
- View http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/sidebar/
- Check docs make sense
Fixes https://www.github.com/vanilla-framework/vanilla-docs-theme/issues/45
=> Add sidebar nav

docs/en/metadata.yaml, docs/en/utilities/spin.md, examples/utilities/animations/spin.html, scss/_utilities_animations.scss, scss/_vanilla.scss
- Port over the animations spin util
- Create HTML and docs example.
- Pull code
- View pattern here http://0.0.0.0:8101/vanilla-framework/examples/utilities/animations/spin/
Fixes #1239
=> 1239 animations util

docs/en/metadata.yaml, docs/en/patterns/switch.md, examples/patterns/switch.html, scss/_patterns_card.scss, scss/_patterns_switch.scss, scss/_vanilla.scss
- Porting over the switch pattern from the dashboard theme
- Creates HTML and documentation for the new pattern
- Pull code
- View the new pattern at http://0.0.0.0:8101/vanilla-framework/examples/patterns/switch/
Fixes #1233
=> 1233 port dashboard switch pattern

docs/en/metadata.yaml, docs/en/patterns/list-tree.md, examples/patterns/list-tree.html, scss/_base_button.scss, scss/_base_typography.scss, scss/_patterns_list-tree.scss, scss/_vanilla.scss
Copied over and integrated the list tree pattern from the dashboard theme. Created an example with JS. Created documentation for the pattern.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/list-tree/
- Check it works
- Check file paths from the docs to examples will be correct
- Check documentation is good
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1231
=> Combine list tree pattern from dashboard theme

docs/en/base/typography.md
Update the headings docs to match the headings spec.
- Check the copy matches the headings spec: https://github.com/ubuntudesign/vanilla-design/blob/master/Typography/typography.md
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1270
=> Update the headings docs to match the headings spec

docs/en/metadata.yaml
Add missing entries to docs metadata and alphabetise
- Pull code
- Pull this feature branch into your local docs build
- Check all the links to docs work correctly
Fixes #1324
=> Add missing entries to docs metadata and alphabetise

docs/en/metadata.yaml, docs/en/patterns/images.md, examples/patterns/image/bordered.html, examples/patterns/image/shadowed.html, scss/_base_media.scss, scss/_patterns_image.scss, scss/_patterns_notifications.scss, scss/_vanilla.scss
Add image pattern 
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/image/bordered/ and http://0.0.0.0:8101/vanilla-framework/examples/patterns/image/shadowed/
- Cross ref with the [spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Image/image.md)
Fixes #1220
=> Add image pattern

scss/_utilities_image-position.scss
- Removed margins from images using image-position util
- Refactored code to remove duplication by using scoped %placeholder
- Verify no Percy regressions on this PR
Fixes #1339
=> Removed margins from images using image-position util

.spelling, docs/en/patterns/navigation.md, examples/patterns/navigation/sidebar.html, scss/_patterns_navigation.scss
Add tagline to side navigation pattern
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/sidebar/
- View through small > large breakpoints
- Cross ref with [spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Sidebar%20navigation)
Fixes #1221
=> Add tagline to side navigation pattern

scss/_base_typography.scss
Update Ubuntu web fonts
- Check Percy for style regressions
Fixes #1303
=> Update Ubuntu web fonts

docs/en/patterns/aside.md, examples/patterns/aside.html, scss/_patterns_aside.scss, scss/_vanilla.scss
Add aside pattern from docs
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/aside/
- Check pattern matches spec
Fixes #1217
=> Add aside pattern from docs

docs/en/base/typography.md, examples/base/font-weights.html, scss/_base_typography.scss
* uploaded the new thin font to the asset server
* added the thin font to base typography
* created an example
* added the example to the typography documentation 
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/font-weights/
=> Add thin font

examples/templates/docs-layout.html
Add example of docs layout
- Pull code
- Open and review http://0.0.0.0:8101/vanilla-framework/examples/templates/docs-layout/
Fixes #1216
=> Add example of docs layout

scss/_settings_system.scss
- Add visual `:focus` state to form elements to improve accessibility.
- Remove navigation dark/light variants and abstract background color to a Sass variable setting
- Refactor and remove layout quirks to vertical spacing across the framework
- Update table pattern to match design spec
- Add fuzzy versioning to `package.json` to improve stability of npm dependencies
- Fix bug where bottom of text was being cut off on `<select>` elements
=> Update system settings to 1.6.0

docs/en/patterns/strip.md
`/strip/` when it should be `/strips/`
=> Fix strip example import

README.md
=> Update README to point to @vanillaframewrk Twitter

package-lock.json
- Fix the search icon to work across supported browsers
- Update README to point to @vanillaframewrk Twitter
- Increase threshold for text color contrast in navigation pattern
=> Bump system settings to 1.6.1

CODE_OF_CONDUCT.md
This is the final step recommended by Github for good Community Relations: https://github.com/vanilla-framework/vanilla-framework/community
=> Create code of Conduct (provided by Github template)

scss/_patterns_tabs.scss
Fixes the color of the visited tab
- Pull code
Fixes #1399 
=> Adds correct color for visited tab state. Closes #1399

docs/en/patterns/media-object.md, examples/patterns/media-object/media-object-circ-img.html, scss/_patterns_media-object.scss
Add circle image option to media object
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/media-object/media-object-circ-img/
- Cross-ref with [the design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Profile)
Fixes #1392
=> Add circle image option to media object

docs/en/patterns/icons.md
Notes: these changes are built on #1409 - that should be merged first.
Add share icons recommendations to docs
- Sanity check docs
Fixes #1393
=> Add share icons recommendations to docs

docs/en/patterns/code-snippet.md
..as there is only one type of code snippet.
=> Update code snippet docs to remove title 'light'

scss/_settings_system.scss
Update app-version to the new version number 1.6.2
- Just check the code matches the next version
=> Update app-version to the new version number 1.6.2

docs/en/patterns/icons.md
- Sentence case the h2s
- Replaced semi-colon for colon
- Pull code
- Check updated text
=> Updated icons docs

docs/en/metadata.yaml
Add Pagination to the docs navigation 
- Check the code
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1435
=> Add Pagination to the docs navigation

scss/_base_button.scss, scss/_base_code.scss, scss/_base_forms.scss, scss/_base_typography.scss, scss/_base_vertical-spacing.scss, scss/_global_functions.scss, scss/_patterns_buttons.scss, scss/_patterns_form-validation.scss, scss/_patterns_heading-icon.scss, scss/_patterns_headings.scss, scss/_patterns_links.scss, scss/_patterns_media-object.scss, scss/_patterns_modal.scss, scss/_patterns_navigation.scss, scss/_patterns_notifications.scss, scss/_patterns_pull-quotes.scss, scss/_patterns_switch.scss, scss/_settings_animations.scss
Add vf namespace for all mixins in the framework
- Pull code
- Check there are no errors
- Run `./run test`
- Also should be no errors
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/985
=> Add vf namespace for all mixins

scss/_settings_system.scss
Bump system version to v1.6.3
Check version is correct
=> Bump system version to v1.6.3

scss/_patterns_code-numbered.scss
Update border-right color on code numbered pattern
- Pull code
- View Code Numbered pattern
- Verify right border is `#cdcdcd`
Fixes #1553
=> Update border-right color on code numbered pattern

examples/patterns/footer.html
Update copyright date in Footer example
- Pull code
- Check code
=> Update copyright date in Footer example

scss/_base_forms.scss, scss/_patterns_form-validation.scss, scss/_patterns_heading-icon.scss, scss/_patterns_lists.scss, scss/_patterns_notifications.scss
- Updated warning icon in Notification and Form validation components with new icon ([issue](https://github.com/vanilla-framework/vanilla-framework/issues/1561))
- Fixed spacing in stacked forms that have a button ([issue](https://github.com/vanilla-framework/vanilla-framework/issues/1562))
- Fixed vertical spacing and alignment of Heading icon ([issue](https://github.com/vanilla-framework/vanilla-framework/issues/1566))
- Fixed spacing in list items ([issue](https://github.com/vanilla-framework/vanilla-framework/issues/1582))
- Pull code
- Check that the Notification/Caution component and Form validation Warning component contain the new icon ([see here](https://github.com/vanilla-framework/vanilla-framework/issues/ …
=> Component spec updates #2

package.json
Bump the version to 1.7.0-alpha
=> Bump the version to 1.7.0-alpha

docs/en/patterns/card.md
Update the cards design link to the correct one
- Check the new link works
Fixes #1662
=> Update the cards design link to the correct one

scss/_patterns_code-snippet.scss
=> Add margin overrides to allow swapping div with p

scss/_patterns_card.scss, scss/_patterns_notifications.scss
=> Fix box-shadows - #1672

scss/_base_forms.scss, scss/_patterns_lists.scss
=> Address 1668 - spacing around checkboxes in p-lists

scss/_patterns_lists.scss, scss/_patterns_matrix.scss, scss/_patterns_navigation.scss
=> Fix #1670 - gap in matrix when no image is present

package.json, scss/_settings_system.scss
- Changed version number to 1.7.0-beta-1 for release
=> Update to v1.7.0-beta-1

docs/en/index.md
Change the term 'theme' for 'framework' on docs homepage
Check everything still passes
=> Change the term 'theme' for 'framework'

_jekyll/_layouts/default.html
=> set VF_ENV to PRODUCTION to disable debug baseline grid

scss/_patterns_inline-images.scss
=> Inline-images: Fix image distortion

scss/_patterns_heading-icon.scss, scss/_settings_spacing.scss
=> Improve heading-icon to accomodate muted heading to h3 next to icon

package.json, scss/_settings_system.scss
- Re-releasing with heading icon revert
=> Bump version to 1.7.0-beta-2.1

examples/utilities/align.html
- Updated alignment utility example with `u-align-text` examples
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/utilities/align/
- Check that each instance of alignment works as expected
=> Update alignment utility example with text-alignment

scss/_settings_system.scss
- Updated version number to 1.7.1
=> Bump version to 1.7.1

examples/templates/typographic-spacing.html
- Created a new example page `/vanilla-framework/examples/templates/typographic-spacing/`
- It will be helpful for debugging this issue: https://github.com/vanilla-framework/vanilla-framework/issues/1855
- It will mainly be used for Percy diffs once that issue is resolved, which should catch any unintended spacing regressions
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/templates/typographic-spacing/
- Check that all typographic combinations have been considered
- **Please suggest any additional typographic spacing things you think should be tracked by Percy**
=> Create a Typographic spacing page to easier track spacing changes

docs/template.html
Updated hero background image, based on feedback from Marcus in design review. Recently applied to vf.io so it needs to be the same on docs.vf.io for consistency. 
Make sure new proposed image is correct.
=> Update background hero image on docs.vf.io

docs/en/base/typography.md, examples/base/abbr.html, scss/_base_typography.scss
- Update abbr pattern according to original issue (#1602) + added an example and an entry in the Vanilla docs
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/abbr/
- Check that it looks good and works
Fixes #1602
=> Update abbr pattern + add example and docs entry

scss/_settings_system.scss
Updated version in system settings to 1.8.0
=> Bump to v1.8.0

examples/patterns/accordion.html
Fix accordion toggle so it opens & closes
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/accordion/
- Check that accordion opens and closes when individually clicked
Fixes #1909
=> Fix accordion toggle so it opens & closes

examples/patterns/navigation/default.html, examples/patterns/navigation/sidebar.html, examples/templates/docs-layout.html
Removed the unnecessary roles `banner` from header and `menubar` from nav.
- Pull code
- Check the pages that have changed and HTML validate them
=> Remove unnecessary roles from examples

scss/_base_forms.scss
Update fieldset to match the design spec
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/forms/fieldset/
- Check that the styles matches the [design spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Forms/forms.md)
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1906
=> Update fieldset to match the design spec

package.json, tests/output/.gitignore, tests/test-sass.js, yarn.lock
Created a new script to run each pattern scss file through Parker.
- Pull code
- `docker exec -it _YOUR-DOCKER-CONTAINER-ID_ /bin/bash`
- `./tests/test-sass.js`
- Check that report files are generated in `./tests/output/`
Fixes #1971
=> Add script to generate CSS and run Parker test for each of the patterns

scss/_base_typography.scss, scss/_patterns_media-object.scss, scss/_patterns_table-mobile-card.scss
Escape map-get() negation correctly as Prettier was catching them and reformatting them incorrectly.
- Ensure no Percy regressions.
=> Escape map-get() negation correctly

docs/en/patterns/icons.md
- Fixes broken links on the “Icons” page
- Pull code
- Open http://0.0.0.0:8101/en/patterns/icons#share-icons
- Follow each of the links
=> Fixes broken links on Icons page

scss/_base_forms.scss
Ordered the base forms stylesheet to avoid linting errors
- Pull code
- See that there are no warnings during the css build
=> Alphabetically order scss

scss/_settings_grid.scss
Update fixed-width to 72rem 
- Pull code
=> Update fixed-width to 72rem

examples/templates/typographic-spacing.html, scss/_base_button.scss, scss/_base_typography.scss, scss/_patterns_card.scss, scss/_patterns_heading-icon.scss, scss/_patterns_lists.scss, scss/_patterns_matrix.scss, scss/_patterns_media-object.scss, scss/_settings_spacing.scss
Adjust spacing between text elements and apply adjustment to affected patterns.
- Pull code
=> Typographic adjustments

scss/_base.scss, scss/_base_forms.scss
=> move base typography rules at beginning of base includes

scss/_base_tables.scss, scss/_patterns_form-help-text.scss, scss/_patterns_form-validation.scss, scss/_patterns_matrix.scss
Fix regressions in patterns due to the updated spacing
- Pull code
=> pattern-fixes

docs/template.html
Cherry-picked @kwm14's usabilla work into this branch.
- Pull code
- Open http://0.0.0.0:8104
- See the "site feedback" link at the bottom right of the viewport
=> add usabilla to documentation

scss/_patterns_matrix.scss
matrix: properly target p:last-child in and outside of __desc class
- Pull code
=> fix selectors in matrix

examples/templates/typographic-spacing.html
The previous PRs did not include the full version of the typographic-spacing.html example file. Making a separate pr for it.
- Pull code
=> 2.0 Refactor: More extensive testcase markup

examples/templates/typographic-spacing.html
Same as [this](https://github.com/vanilla-framework/vanilla-framework/pull/2144), but against the correct branch 
- Pull code
=> Improve typographic spacing examples (new pr against branch develop)

docs/en/patterns/icons.md, docs/en/settings/color-settings.md, docs/template.html, examples/patterns/icons/icons-dark.html, examples/patterns/icons/icons-light.html, examples/patterns/icons/icons-social.html
Backport docs changes:
**Remove versioning** - https://github.com/vanilla-framework/vanilla-framework/pull/2039
**Colors layout** - https://github.com/vanilla-framework/vanilla-framework/pull/2131
**Icons layout** - https://github.com/vanilla-framework/vanilla-framework/pull/2120
- Pull code
- cd into docs
- Run `./run`
- Check the docs looks good
=> Back port docs changes to v1.8

scss/_base.scss, scss/_base_background.scss, scss/_base_backgroundscss
=> Add background-color to root element (html) so we don't rely on browser defaults

scss/_patterns_navigation.scss, scss/_settings_colors.scss
Implemented the new primary navigation design.
- Pull code
- Compare the large and small viewport styling to the design notes: #1652
Fixes: #1652
=> Restyle primary navigation

.spelling, docs/en/patterns/navigation.md, examples/patterns/navigation/subnav.html, scss/_base_blockquotes.scss, scss/_base_placeholders.scss, scss/_base_tables.scss, scss/_patterns_card.scss, scss/_patterns_navigation.scss, scss/_patterns_subnav.scss, scss/_patterns_tabs.scss, scss/_settings_spacing.scss, scss/_vanilla.scss
Added the new sub-navigation component
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/subnav/
- Test functionality at all viewports
- Compare to the [design](https://github.com/ubuntudesign/vanilla-design/blob/master/Navigation/sub-navigation.md)
Fixes #2034
=> Added new subnavigation pattern, documented and added example

docs/en/settings/breakpoint-settings.md
- Added new devices row to breakpoint table
- Added imagery to breakpoint threshold 
- Check content matches copy doc [here](https://docs.google.com/document/d/1eq56B2iEauk9g4bRVEJtiO9hQ7Y6yuJP6zcLN-tLess/edit#heading=h.ldypsxh84552)
- Pull code
- Check https://docs.vanillaframework.io/en/settings/breakpoint-settings
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/340
=> Update docs/breakpoints page content

.spelling, docs/en/patterns/grid.md
- Updated design spec section
- Check content matches copy doc [here](https://docs.google.com/document/d/1eq56B2iEauk9g4bRVEJtiO9hQ7Y6yuJP6zcLN-tLess/edit#heading=h.6m1ugjjre85)
- Pull code
- Check https://docs.vanillaframework.io/en/settings/grid
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/341
=> Update design link copy

docs/run
- `./run`
- should have a message at the end: `Serve at http://0.0.0.0:8104`
=> Add message on end build

scss/_base_code.scss, scss/_base_forms.scss, scss/_patterns_code-numbered.scss, scss/_patterns_contextual-menu.scss, scss/_patterns_lists.scss, scss/_patterns_navigation.scss, scss/_patterns_slider.scss, scss/_patterns_table-sortable.scss, scss/_patterns_tooltips.scss, scss/_utilities_animations.scss
Add prefixes to properties that need them
- Pull code
- Check that the patterns are ok
=> Add prefixes to properties that need them

docs/en/patterns/aside.md, examples/patterns/aside.html
- Updated design section copy
- Check content matches copy doc [here](https://docs.google.com/document/d/1FK485n4m21iCU_yt3DrsAcBPeiukpWUUQZLX4_PGXSM/edit#heading=h.2iegp7r10no)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/accordion
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/aside/
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/378
=> Update docs/aside page content

docs/en/patterns/accordion.md, examples/patterns/accordion.html
- Added note notification
- Check content matches copy doc [here](https://docs.google.com/document/d/1FK485n4m21iCU_yt3DrsAcBPeiukpWUUQZLX4_PGXSM/edit#heading=h.ldypsxh84552)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/accordion
- Review updated note notifications
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/accordion/
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/343
**Content**
**Example**
=> Update docs/accordion page content

docs/en/patterns/footer.md, examples/patterns/footer.html
- Updated copy
- Check content matches copy doc [here](https://docs.google.com/document/d/1FK485n4m21iCU_yt3DrsAcBPeiukpWUUQZLX4_PGXSM/edit#heading=h.bogeg45pxnah)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/footer/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/footer/
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/380
=> Update docs/footer page content

docs/en/base/code.md, examples/base/code.html, examples/patterns/code-numbered.html
- Updated copy and merged all Code examples into one place 👍 
- Check content matches copy doc [here](https://docs.google.com/document/d/1vPTLiX-9nkUdc1le8q709_Lg12XZk1qGDK_Z8i13mco/edit#heading=h.ldypsxh84552)
- Pull code
- Check http://0.0.0.0:8104/en/base/code
- Pull code
- Run ./run
- Check http://0.0.0.0:8101/vanilla-framework/examples/base/code/ and http://0.0.0.0:8101/vanilla-framework/examples/patterns/code-numbered/
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/348
=> Update docs/code page content

docs/en/patterns/tabs.md, examples/patterns/tabs.html
- Updated copy 
- Check content matches copy doc [here](https://docs.google.com/document/d/1FK485n4m21iCU_yt3DrsAcBPeiukpWUUQZLX4_PGXSM/edit#heading=h.swowixwnuyvl)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/tabs
- Pull code
- Run ./run
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/tabs/
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/346
=> Update docs/tabs page content

docs/en/patterns/pagination.md
- Updated and reordered copy 
- Check content matches copy doc [here](https://docs.google.com/document/d/1FK485n4m21iCU_yt3DrsAcBPeiukpWUUQZLX4_PGXSM/edit#heading=h.bj3bavtmjnfx)
- Pull code
- Run /docs
- Check http://0.0.0.0:8104/en/patterns/pagination/
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/382
=> Update docs/pagination page content

docs/en/base/typography.md, examples/base/lists/definition-list.html, examples/base/lists/ordered-list.html, examples/base/lists/unordered-list.html, examples/patterns/headings/default.html, examples/patterns/headings/mixed.html, examples/patterns/headings/muted.html
- Updated copy and layout 👍 
- Check content matches copy doc [here](https://docs.google.com/document/d/1vPTLiX-9nkUdc1le8q709_Lg12XZk1qGDK_Z8i13mco/edit#heading=h.m8r6djutwkm5)
- Pull code
- Check http://0.0.0.0:8104/en/base/typography
- Pull code
- Run ./run
- Check http://0.0.0.0:8101/vanilla-framework/examples/base/lists/definition-list/
- Check http://0.0.0.0:8101/vanilla-framework/examples/base/lists/ordered-list/
- Check http://0.0.0.0:8101/vanilla-framework/examples/base/lists/unordered-list/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/headings/default/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/headings/mixed/
- Check …
=> Update docs/typography page content

docs/en/patterns/pull-quote.md, examples/patterns/pull-quotes/default-image.html, examples/patterns/pull-quotes/default.html, examples/patterns/pull-quotes/large.html, examples/patterns/pull-quotes/small.html
- Check content matches copy doc [here](https://docs.google.com/document/d/1vPTLiX-9nkUdc1le8q709_Lg12XZk1qGDK_Z8i13mco/edit#heading=h.5e8rszvymdec)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/pull-quote
- Pull code
- Run ./run
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/pull-quotes/default/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/pull-quotes/default-image/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/pull-quotes/large/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/pull-quotes/small/
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/383
=> Update docs/pull quote page content

scss/_base_typography-definitions.scss, scss/_base_typography.scss, scss/_patterns_icons.scss, scss/_settings_colors.scss, scss/_settings_font.scss
Renamed a few variables for consistency.
- Pull code
- See that there are no visible changes
Fixes #2093 
Fixes #2094
=> Variable audit

docs/en/settings/animation-settings.md
- Updated minor copy changes 👍 
- Check content matches copy doc [here](https://docs.google.com/document/d/1BaY3k01-6zvhC67PMxZD44IKHs4_pTpPm_ix98rHW98/edit#heading=h.ldypsxh84552)
- Pull code
- Check http://0.0.0.0:8104/en/settings/animation-settings
=> Update docs/animations page content

docs/en/settings/assets-settings.md
- Add divider line under the title
- Pull code
- Check http://0.0.0.0:8104/en/settings/assets-settings
=> Update docs/assets page content

docs/en/utilities/embedded-media.md
- Add divider line under the title
- Pull code
- Check http://0.0.0.0:8104/en/utilities/embedded-media
=> Update docs/embedded-media page content

docs/en/patterns/icons.md
- Check content matches copy doc [here](https://docs.google.com/document/d/1BaY3k01-6zvhC67PMxZD44IKHs4_pTpPm_ix98rHW98/edit#heading=h.80am5mpd28r8)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/icons
=> Update docs/icons page content

docs/en/patterns/images.md, examples/patterns/image/bordered.html, examples/patterns/image/shadowed.html
- Check content matches copy doc [here](https://docs.google.com/document/d/1BaY3k01-6zvhC67PMxZD44IKHs4_pTpPm_ix98rHW98/edit#heading=h.onl5fl8z5o6w)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/images
- Pull code
- Run ./run
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/image/bordered/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/image/shadowed/
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/357
=> Update docs/images page content

docs/en/patterns/buttons.md, examples/patterns/buttons/base.html, examples/patterns/buttons/brand.html, examples/patterns/buttons/inline.html, examples/patterns/buttons/negative.html, examples/patterns/buttons/neutral.html, examples/patterns/buttons/positive.html
- Check content matches copy doc [here](https://docs.google.com/document/d/1n_FNUUnBt3Mnka_c6w3lp2ov84IpC8p0Na6t7THP16s/edit#heading=h.ldypsxh84552)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/buttons
- Pull code
- Run ./run
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/buttons/base/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/buttons/brand/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/buttons/icon/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/buttons/inline/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/buttons/negative/
- Check …
=> Update docs/buttons page content

docs/en/patterns/modal.md, examples/patterns/modal.html
- Updated copy to new tempplate 👍 
- Updated demo exmaple 💯 
- Check content matches copy doc [here](https://docs.google.com/document/d/1n_FNUUnBt3Mnka_c6w3lp2ov84IpC8p0Na6t7THP16s/edit#heading=h.cmd24hl3d2j9)
- Pull code
- Run /docs
- Check http://0.0.0.0:8104/en/patterns/modal
- Pull code
- Run /docs
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/modal/
=> Update docs/modal content

docs/en/patterns/links.md, examples/base/links.html, examples/patterns/links/links-external.html, examples/patterns/links/links-inverted.html, examples/patterns/links/links-soft.html
- Updated demo example to showcase live example 💯 
- Check content matches copy doc [here](https://docs.google.com/document/d/1n_FNUUnBt3Mnka_c6w3lp2ov84IpC8p0Na6t7THP16s/edit#heading=h.ifh1f0ulklnm)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/links
- Pull code
- Run ./run
- Check http://0.0.0.0:8101/vanilla-framework/examples/base/links/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/links/links-external/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/links/links-inverted/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/links/links-soft/
- Fixes https://github.com/ubuntudesign/design-vanilla-framework/issues/353
=> Update docs/links page content

docs/en/patterns/list-tree.md
- Updated copy to new tempplate 👍 
- Check content matches copy doc [here](https://docs.google.com/document/d/1n_FNUUnBt3Mnka_c6w3lp2ov84IpC8p0Na6t7THP16s/edit#heading=h.m8r6djutwkm5)
- Pull code
- Run /docs
- Check http://0.0.0.0:8104/en/patterns/list-tree
=> Update docs/list tree content

docs/en/patterns/notification.md, examples/patterns/notifications/action.html, examples/patterns/notifications/caution.html, examples/patterns/notifications/information.html, examples/patterns/notifications/negative.html, examples/patterns/notifications/notifications.html, examples/patterns/notifications/positive.html
- Updated demo example to showcase live example 💯 
- Check content matches copy doc [here](https://docs.google.com/document/d/1n_FNUUnBt3Mnka_c6w3lp2ov84IpC8p0Na6t7THP16s/edit#heading=h.fa3f4jl2pq5a)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/notification
- Pull code
- Run ./run
- Review many many many updated examples
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/notifications/action/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/notifications/caution/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/notifications/notifications/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/notifications/negative/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/notifications …
=> Update docs/notification page content

docs/en/patterns/switch.md, examples/patterns/switch.html
- Updated demo example layout 
- Check content matches copy doc [here](https://docs.google.com/document/d/1n_FNUUnBt3Mnka_c6w3lp2ov84IpC8p0Na6t7THP16s/edit#heading=h.pmpk7ux1pz9)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/switch
- Pull code
- Run ./run
- Review example
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/switch/
=> Update docs/switch page content

docs/en/patterns/slider.md
- Check content matches copy doc [here](https://docs.google.com/document/d/1n_FNUUnBt3Mnka_c6w3lp2ov84IpC8p0Na6t7THP16s/edit#heading=h.7najqv5kx11a)
- Pull code
- Run /docs
- Check http://0.0.0.0:8104/en/patterns/slider
=> Update docs/slider page content

docs/en/patterns/search-box.md, examples/patterns/search-box/navigation.html
- Updated demo example to showcase live example 💯 
- Check content matches copy doc [here](https://docs.google.com/document/d/1n_FNUUnBt3Mnka_c6w3lp2ov84IpC8p0Na6t7THP16s/edit#heading=h.4lqm93m0gv6f)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/search-box
- Pull code
- Run ./run
- Review example
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/search-box/navigation/
=> Update docs/search page content

docs/en/patterns/matrix.md, examples/patterns/matrix.html
- Updated demo example 💯 
- Check content matches copy doc [here](https://docs.google.com/document/d/1ZFRd4z7TsU4oifxgky77337v_1fkE2ak12tGPNivD70/edit#heading=h.m8r6djutwkm5)
- Pull code
- Run /docs
- Check http://0.0.0.0:8104/en/patterns/matrix
- Pull code
- Run ./run
- Review example 😉 
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/matrix/
- Fixes https://github.com/ubuntudesign/design-vanilla-framework/issues/347
=> Update docs/matrix page content

docs/en/patterns/muted-heading.md, examples/patterns/muted-heading.html
- Updated demo example 💯 
- Check content matches copy doc [here](https://docs.google.com/document/d/1ZFRd4z7TsU4oifxgky77337v_1fkE2ak12tGPNivD70/edit#heading=h.r9fmkym6ojv6)
- Pull code
- Run /docs
- Check http://0.0.0.0:8104/en/patterns/muted-heading
- Pull code
- Run ./run
- Review example 😉 
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/muted-heading/
- Fixes https://github.com/ubuntudesign/design-vanilla-framework/issues/388
=> Update docs/muted heading page content

scss/_settings_spacing.scss
Upped 38em to 40em
- Pull code
- Look through components but it's probably better to use Percy to see all of the impact
Fixes #1794
=> Upped the default max-width for typography

package.json, scss/_settings_system.scss
Bumped the version number ahead of the release
=> Bump project version fo 2.0.0-alpha

scss/_base_forms.scss
Fix rule order in forms.scss
- Pull code
=> fix rule order

docs/examples/patterns/grid/bordered.html, docs/examples/patterns/grid/default.html, scss/_base_hr.scss
Fix bordered row
- Pull code
- Open http://0.0.0.0:8101/examples/patterns/grid/bordered/
- Verify it works as expected
=> Bordered row

scss/_base_typography-definitions.scss, scss/_patterns_links.scss, scss/_patterns_table-of-contents.scss, scss/_settings_font.scss
[- adds new variable `$font-weight-bold`
- uses variable where appropriate in code
- Pull code
- Confirm that the heading the navbar still have `font-weight: 400`
=> Introduces new variable to change the font-weight for bold fonts

package.json
Upgraded Husky config as the old way is deprecated.
- Make a test change that doesn't adhere to Prettier rules
- Stage and commit that change
- Observe that your committed changes do now adhere to Prettier rules
=> Upgraded Husky config

package.json, scss/_settings_system.scss
Prep vanilla framework for 2.0.0-alpha.1 release
=> Bump package version to 2.0.0-alpha.1

docs/patterns/media-object.md
Updated the documentation for the circular variant of the media object pattern
- Pull code
- Open http://0.0.0.0:8101/patterns/media-object/
- See the updated documentation
Fixes #2341
=> Added clarification to media-object docs re: circular format needing square images

docs/settings/breakpoint-settings.md
Update breakpoints docs
- Pull code
=> update breakpoint documentaiton to match actual breakpoints

package.json, scss/_settings_system.scss
Bump project version to 2.0.0-beta
=> Bump project version to 2.0.0-beta

scss/_base.scss, scss/_base_placeholders-fixed-width-container.scss, scss/_base_placeholders-margin-collapse.scss, scss/_base_placeholders.scss, scss/_base_typography-definitions.scss, scss/_patterns_grid.scss, scss/_utilities_layout.scss
Fixes #2360
Remove mixins wrapping placeholders; move %u-fixed-width-container in… to separate file
- Pull code
- Open /examples/
- QA (there should be no visual changes or percy diff)
=> Placeholders refactor

package.json, scss/_settings_system.scss
Bump package version to 2.0.0-beta.1
=> Bump package version to 2.0.0-beta.1

package.json, scss/_settings_system.scss
Bumping the package number to 2.0.0 ahead of release
=> Update package to 2.0.0

docs/index.md, package.json, scss/_settings_system.scss
=> Bump version to 2.0.1

docs/_layouts/default.html
Fixed docs search
- Pull code
- Run `./run`
- Use the search box and see that it now works
Fixes #2407
=> Add back duplicate navifation for search

scss/_utilities_layout.scss
```
Error: expected "=".
╷
8 │   @if ($table-layout-fixed = 'true') {
│                             ^
╵
style/vanillaframework/scss/_utilities_layout.scss 8:29  @import
style/vanillaframework/scss/_vanilla.scss 57:9           @import
style/main.scss 1:9                                      root stylesheet
```
=> fix build, broken $table-layout-fixed

docs/patterns/icons.md, docs/settings/animation-settings.md
- Moved [spin](https://docs.vanillaframework.io/patterns/icons/#animation) from icons page to animations page
- Reordered sections
- Updated copy base on the comments made #1530 
- Updated `br` to `hr` reduced the large spacing between sections with tables
- Pull code
- Open http://0.0.0.0:8101/settings/animation-settings/
- Check the page looks good 
- Fixes #1530
=> Animations - Reorder and update content

docs/examples/index.html
- Match page heading to side-bar navigation
- Added a beautiful dividing line
- Pull code
- Open http://0.0.0.0:8101/examples/
- Check the page heading matches side-bar navigation under _**Resources**_
- #consistency
=> Update page heading

docs/base/code.md, docs/base/tables.md, docs/patterns/accordion.md, docs/settings/spacing-settings.md, docs/utilities/baseline-grid.md
Added JS warning notifications
For pages Accordion, Code, Tables, Baseline grid, and Spacing settings.
- Pull code
=> JS notifications

package.json
=> Remove dead link from package.json

docs/patterns/modal.md
Increase the height of the modal iframe
- Pull code
- Open http://0.0.0.0:8101/patterns/modal/
- Check the example is fully visible on all screen sizes
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2492
=> Increase the height of the modal iframe

docs/_layouts/default.html
Bump the version of example-js to v1.2.0
- Pull code
- Click through some docs and check the examples are working
=> Bump the version of example-js to v1.2.0

scss/_patterns_icons.scss, scss/_patterns_pagination.scss
Fixes  #2459
- Pull code
- /examples/patterns/pagination/pagination/
- add u-align--center to the pattern
- observe lack of margins on first/last element, which fixes the alignment issue mentioned in #2459
=> Fix pagination margins

docs/examples/base/forms/checkboxes.html, scss/_base_forms-tick-elements.scss, scss/_patterns_switch.scss
Fixes #1983
- Pull code
- Open http://0.0.0.0:8101/examples/
- paste ```  <label for="checkExample2">CSS
<input type="checkbox" id="checkExample2">
</label>```
- verify it looks as expected
-repeat for radio
=> Labels wrapping checkboxes

docs/utilities/hide.md
Add a reference to the unmodified hide utility
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/utilities/hide/
- Check the new content
=> Update hide utility docs

docs/examples/patterns/tables/table-expanding.html, scss/_base_tables.scss, scss/_settings_breakpoints.scss
fix table td padding
move fontsize bump query 1px
=> fix table td padding; move fontsize bump query 1px

docs/index.md, package.json, scss/_settings_system.scss
=> Bump project version to v2.4.0

docs/_layouts/default.html, package.json, yarn.lock
Update the vanilla dep used by docs (fixed nav)
Update example JS
- Pull code
- Run `./run`
- Check pages visually
=> Update docs to vanilla v2.4.0 and example JS to 1.2.1

docs/settings/animation-settings.md
Updated the animation docs
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/settings/animation-settings/
- Check that the content is valid
Fixes #2576
=> Clarify animation mixing usage example in docs

docs/patterns/lists.md
- Pull code
- Open /patterns/lists/#responsive-divider
- QA copy
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2603
=> Rename vertical divider to responsive divider

docs/examples/patterns/links/links-external.html, scss/_patterns_links.scss
Fix wrapping of external icons
- Pull code
- Open patterns/links/#external
- Resize window, verify wrapping keeps icon attached to the last word
Fix #2632
=> External link

docs/_layouts/default.html, docs/examples/utilities/truncate.html, docs/utilities/truncate.md, scss/_utilities_truncate.scss, scss/_vanilla.scss, tests/parker.js
Add utility called u-truncate that truncates text.
- Pull code
- Open http://192.168.64.2:8101/utilities/truncate/
- QA copy and example
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2625
=> Add truncate util; increase size limit to pass tests

docs/index.md, package.json, scss/_settings_system.scss
Version updated to 2.5.0 release
- Pull code
- Make sure version is updated in docs
=> Bump version to 2.5.0

docs/base/typography.md, docs/examples/base/strong.html
Add strong text example to typography using Codepen
- Pull code
- Open http://0.0.0.0:8101/base/typography/
- Make sure the strong text example in Codepen is visible
=> Add strong text example to typography

scss/_settings_grid.scss, scss/_settings_placeholders.scss
Adds some necessary dependencies to settings files, to make sure they are independent and can be build separately in any order.
Fixes #2210 
Fixes #2211
- Pull code
- Make sure build passes
=> Make sure all settings files are independent

docs/_includes/patterns/grid/bordered.html, docs/_includes/patterns/grid/default.html, docs/_includes/patterns/grid/empty-columns.html, docs/_includes/patterns/grid/incorrect-empty-columns.html, docs/_includes/patterns/grid/nested-medium.html, docs/_includes/patterns/grid/nested-small.html, docs/_includes/patterns/grid/nested.html, docs/_includes/patterns/grid/offsets.html, docs/examples/individual/grid/bordered.html, docs/examples/individual/grid/default.html, docs/examples/individual/grid/empty-columns.html, docs/examples/individual/grid/incorrect-empty-columns.html, docs/examples/individual/grid/nested-medium.html, docs/examples/individual/grid/nested-small.html, docs/examples/individual/grid/nested.html, docs/examples/individual/grid/offsets.html, scss/individual/patterns_grid.scss
Builds grid pattern separately and adds individual example page to test it.
Part of #2736 
- Pull code
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2742.run.demo.haus/)
- Check if all previous full Vanilla examples work as before:
[default](https://vanilla-framework-canonical-web-and-design-pr-2742.run.demo.haus/examples/patterns/grid/default/)
[bordered](https://vanilla-framework-canonical-web-and-design-pr-2742.run.demo.haus/examples/patterns/grid/bordered/) 
[empty columns](https://vanilla-framework-canonical-web-and-design-pr-2742.run.demo.haus/examples/patterns/grid/empty-columns/) 
[incorrect empty columns](https://vanilla-framework-canonical-web-and-design-pr-2742.run.demo.haus/examples/patterns/grid/incorrec …
=> Add example pages for individually build grid

docs/_includes/patterns/tables/table-expanding.html, docs/_includes/patterns/tables/table-mobile-card.html, docs/_includes/patterns/tables/table-sortable.html, docs/examples/individual/tables/table-expanding.html, docs/examples/individual/tables/table-mobile-card.html, docs/examples/individual/tables/table-sortable.html, scss/individual/patterns_table-expanding.scss, scss/individual/patterns_table-mobile-card.scss, scss/individual/patterns_table-sortable.scss
Builds table components into individual CSS, adds examples to test individual CSS for tables.
- Pull code
- Check if existing full Vanilla examples didn't change
[expanding](https://vanilla-framework-canonical-web-and-design-pr-2743.run.demo.haus/examples/patterns/tables/table-expanding/)
[mobile card](https://vanilla-framework-canonical-web-and-design-pr-2743.run.demo.haus/examples/patterns/tables/table-mobile-card/)
[sortable](https://vanilla-framework-canonical-web-and-design-pr-2743.run.demo.haus/examples/patterns/tables/table-sortable/)
- Check if new individual examples work and look the same as full Vanilla examples:
[expanding](https://vanilla-framework-canonical-web-and-design-pr-2743.run.demo.haus/examples/individual …
=> Add examples for individually built table components

docs/_includes/patterns/forms/dense.html, docs/_includes/patterns/forms/form-help-text.html, docs/_includes/patterns/forms/form-inline.html, docs/_includes/patterns/forms/form-stacked.html, docs/_includes/patterns/forms/form-validation.html, docs/_includes/patterns/forms/forms-required.html, docs/_includes/patterns/slider/slider-input.html, docs/_includes/patterns/switch.html, docs/examples/individual/forms/dense.html, docs/examples/individual/forms/form-help-text.html, docs/examples/individual/forms/form-inline.html, docs/examples/individual/forms/form-stacked.html, docs/examples/individual/forms/form-validation.html, docs/examples/individual/forms/forms-required.html, docs/examples/individual/slider/slider-input.html, docs/examples/individual/switch.html, scss/individual/patterns_forms.scss, scss/individual/patterns_slider.scss, scss/individual/patterns_switch.scss
Makes sure form related patterns and component can be built individually.
Removed grid elements form switch example to make it independent.
Part of #2736 
- Pull code
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2745.run.demo.haus/examples/)
- Check if existing examples look the same:
[forms dense](https://vanilla-framework-canonical-web-and-design-pr-2745.run.demo.haus/examples/patterns/forms/dense/)
[forms help text](https://vanilla-framework-canonical-web-and-design-pr-2745.run.demo.haus/examples/patterns/forms/form-help-text/)
[forms inline](https://vanilla-framework-canonical-web-and-design-pr-2745.run.demo.haus/examples/patterns/forms/form-inline/)
[forms …
=> Add examples for individually built form styles and components

docs/_includes/patterns/lists/divider.html, docs/_includes/patterns/lists/list.html, docs/_includes/patterns/lists/lists-dividers-ticked.html, docs/_includes/patterns/lists/lists-dividers.html, docs/_includes/patterns/lists/lists-inline.html, docs/_includes/patterns/lists/lists-mid-dot.html, docs/_includes/patterns/lists/lists-split.html, docs/_includes/patterns/lists/lists-stepped-detailed.html, docs/_includes/patterns/lists/lists-stepped.html, docs/_includes/patterns/lists/lists-ticked.html, docs/examples/individual/lists/divider.html, docs/examples/individual/lists/list.html, docs/examples/individual/lists/lists-dividers-ticked.html, docs/examples/individual/lists/lists-dividers.html, docs/examples/individual/lists/lists-inline.html, docs/examples/individual/lists/lists-mid-dot.html, docs/examples/individual/lists/lists-split.html, docs/examples/individual/lists/lists-stepped-detailed.html, docs/examples/individual/lists/lists-stepped.html, docs/examples/individual/lists/lists-ticked.html, scss/_base.scss, scss/_base_grid-definitions.scss, scss/_patterns_divider.scss, scss/_patterns_grid.scss, scss/_patterns_lists.scss, scss/individual/patterns_divider.scss, scss/individual/patterns_lists.scss
Fixes #2207
Makes sure list styles can be built independently, adds examples for them.
- Pull code
- Check if existing full vanilla examples work as before
[list](https://vanilla-framework-canonical-web-and-design-pr-2735.run.demo.haus/examples/patterns/lists/list/)
[divider](https://vanilla-framework-canonical-web-and-design-pr-2735.run.demo.haus/examples/patterns/lists/divider/)
[lists divider](https://vanilla-framework-canonical-web-and-design-pr-2735.run.demo.haus/examples/patterns/lists/lists-dividers/)
[lists inline](https://vanilla-framework-canonical-web-and-design-pr-2735.run.demo.haus/examples/patterns/lists/lists-inline/)
[lists mid dot](https://vanilla-framework-canonical-web-and-design-pr-2735.run.demo.haus/exampl …
=> Encapsulate lists

docs/examples/utilities/truncate.html
=> Fix spelling typo

package.json, scss/_settings_system.scss
Updated version of Vanilla framework
=> Bump version of Vanilla framework to 2.6.0

docs/_layouts/default.html
Remove trailing slashes to fix marking pages as selected in side nav
- Pull code
=> Fix selected pages in side nav

docs/_layouts/default.html
Remove trailing slashes from navigation URLs to avoid redirects
- Pull code
=> Remove trailing slashes from URLs

docs/patterns/icons.md
Added a missing = to the example
- Pull code
- Is there an =?
=> Add missing equal sign

docs/examples/index.html, docs/examples/standalone.html, webapp/app.py
=> /standalone at the end of the URL

Dockerfile
QA
--
``` bash
./run clean  # To make sure we're not relying on any locally built assets
DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=sdfgds --tag vd .
docker run --env FLASK_DEBUG=true -ti -p 8666:80 vd
```
=> Dockerfile for Flask version

.github/workflows/pr_docker_build.yml, Dockerfile
Fixes building scss files in Docker image (regression introduced in #2839).
Adds a workflow to test building docker image automatically for each PR.
- Pull branch
- run `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag vanilla .`
- Make sure docker image builds successfully
- Check if newly added **Docker / Build and run Docker image** status check on PR passed
=> Fix building Sass in Docker build

package.json
Bumped version of Vanilla to 2.7.1 (to test automated release process).
=> Bump version to 2.7.1

.prettierignore
- Pull code
- Make changes to some .html in docs
- Commit
- Prettier should ignore .html files
=> Fix prettier after moving docs

site/_layouts/default.html, site/docs/base/typography.md, site/docs/component-status.md, site/docs/customising-vanilla.md, site/docs/patterns/grid.md, site/docs/settings/placeholder-settings.md
Fix links for `Utilities` and `Settings`
- Pull code
- Run `./run`
=> Fix links for Utilities and Settings

.github/workflows/pr_docker_build.yml, docs/examples/templates/typographic-spacing.html
Add GitHub Action for `linkchecker`
- Pull code
- Run `./run`
=> Linkchecker GH Action

site/_layouts/site.html, site/accessibility.html, site/browser-support.html, site/contribute.html, site/index.html, site/showcase.html
=> Move Jekyll metadata to Flask template blocks

site/_layouts/default.html
- Pull code
- Run `./run`
- Check if all links in docs main nav work (to home page, accessibility, contribute, etc)
=> Fix links in docs main nav

site/_layouts/site.html, site/docs/examples/patterns/contextual-menu/dark.html, site/docs/examples/patterns/contextual-menu/default.html, site/docs/examples/patterns/contextual-menu/with-indicator.html, site/docs/examples/patterns/navigation/deprecated-dark.html, site/docs/examples/patterns/navigation/deprecated.html, site/docs/examples/patterns/navigation/subnav-dark.html, site/docs/examples/patterns/navigation/subnav.html
Fix some examples pages, like: http://127.0.0.1:8101/docs/examples/patterns/contextual-menu/dark
Remove manifest.json
- Pull code
- Run `./run`
=> Small changes

README.md, site/_layouts/default.html, site/index.html, webapp/app.py
=> Fix docs references

.github/workflows/pr_docker_build.yml
Removes duplicated docker image building from PR workflow.
Check PR status for updated workflow.
=> Clean up PR GitHub workflow

.github/release-drafter.yml
Updated release drafter with new link to docs.
=> Update docs link in release drafter template

package.json
Prepare Vanilla release - bump Vanilla version to 2.9.0
Check if `package.json` version change looks good.
=> Bump Vanilla version to 2.9.0

.env, .github/workflows/pr_docker_build.yml, requirements.txt
- Update `flask-base` to 0.5.1 to fix gevent issue
- Update `templatefinder` to 0.2.5
- PR checks should pass
=> Update Flask dependencies

package.json
Bumped version of Vanilla to 2.9.1 in preparation for release
- Code review
- PR checks should pass
=> Bump Vanilla version to 2.9.1

templates/docs/examples/patterns/links/links-external.html, templates/docs/examples/patterns/modal.html, templates/docs/examples/templates/maas-docs-grid.html, templates/docs/examples/templates/snapcraft-publicise.html, templates/docs/examples/templates/vertical-spacing.html, templates/docs/examples/utilities/align.html
Remove references to external images and sites from examples to make them more reliable.
Fixes #2998
- Review code for link changes
- CI should pass
=> Remove external resources from examples

package.json
Just a version bump for new Vanilla release.
Check if version in package.json is correct
=> Bump Vanilla version to 2.10.0

.github/workflows/pr.yml, tests/parker.js
Updates the file size threshold to make sure current Vanilla code passes the test.
Makes sure we test it on each PR.
- Review the code
- There should be new PR check "Test"
- All PR check should pass
=> Update PR workflow to test SCSS on PRs

package.json
Just bumps version in package.json
- PR checks should pass
=> Bump Vanilla to 2.10.1 for the release

package.json
Updates version of Vanilla for next release.
- Pull code
- Run `./run`
=> Bump version of Vanilla to 2.12

scss/_patterns_contextual-menu.scss, scss/_patterns_form-validation.scss, scss/_patterns_modal.scss, templates/docs/examples/templates/z-index.html
Make sure different patterns are correctly stacked on top of each other.
Fix z-index collisions discovered.
Follow up to #3095 
- Pull code
- Run `./run`
- Check [z-index example](https://vanilla-framework-canonical-web-and-design-pr-3095.run.demo.haus/docs/examples/templates/z-index), make sure contextual menu renders correctly, not overlapping with tabs borders
=> Fix z-index collisions between patterns

package.json, templates/_layouts/docs.html, templates/docs/component-status.md, templates/docs/patterns/accordion.md
Updates version of Vanilla and updates component status
- ./run  or [demo](https://vanilla-framework-canonical-web-and-design-pr-3122.run.demo.haus/docs/)
- Check if version is 2.13.0
- Check if component status page lists accordion changes: https://vanilla-framework-canonical-web-and-design-pr-3122.run.demo.haus/docs/component-status
=> Bump version to 2.13

scss/_base_code.scss, templates/docs/examples/base/code.html
Fixes bold text not being styled properly in code.
Fixes #3112
- Pull code
- Run `./run`
- Check code pattern example
=> Fix bold in code

scss/_patterns_lists.scss, templates/docs/patterns/lists.md
Separates list placeholders from list pattern styles to allow including them independently.
Fixes #2808 
- CI checks should pass, there should be no regressions
=> Make list placeholders includable separately from patterns

scss/_patterns_matrix.scss
Increase title margin on small screens
Fixes #3123
- Pull code
- Run `./run`
- Open /docs/examples/patterns/matrix
- Verify margin is increased on small screens
=> Increase title margin on small screens

scss/_patterns_switch.scss, templates/_layouts/examples.html, templates/docs/examples/patterns/switch.html, templates/docs/examples/utilities/baseline-grid.html
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/885
- Pull code
- Run `./run`
- Open docs/examples/patterns/switch, verify there are no visual changes
=> Switch component: Fix validator issue

templates/_layouts/examples.html, templates/docs/building-vanilla.md
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/868
- Pull code
- Search for `<html`
- Verify there are no instances without lang attribute
=> Add lang attrib to html tag 

templates/docs/examples/layouts/documentation.html, templates/docs/examples/patterns/navigation/default-dark.html, templates/docs/examples/patterns/navigation/default.html, templates/docs/examples/patterns/navigation/deprecated-dark.html, templates/docs/examples/patterns/navigation/deprecated.html, templates/docs/examples/patterns/navigation/full-width.html, templates/docs/examples/patterns/navigation/subnav-dark.html, templates/docs/examples/patterns/navigation/subnav.html, templates/docs/examples/patterns/search-box/navigation-dark.html, templates/docs/examples/patterns/search-box/navigation.html, templates/docs/examples/templates/maas-layout.html, templates/docs/examples/templates/snapcraft-publicise.html, templates/docs/examples/templates/z-index.html
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3225
- Pull code
- Run `./run`
- review code changes in all navigation examples
=> Accessibility fixes: Navigation

scss/_patterns_breadcrumbs.scss, templates/_layouts/docs.html, templates/docs/component-status.md, templates/docs/examples/layouts/application.html, templates/docs/examples/patterns/breadcrumbs-deprecated.html, templates/docs/examples/patterns/breadcrumbs.html, templates/docs/patterns/breadcrumbs.md
Fix #3218
- Pull code
- Run `./run`
- Open docs/patterns/breadcrumbs
- verify that the features mentioned in the original bug have been implemented
=> Breadcrumbs (fix #3218)

templates/_layouts/_header.html, templates/docs/examples/layouts/documentation.html, templates/docs/examples/patterns/search-box/default-dark.html, templates/docs/examples/patterns/search-box/default.html, templates/docs/examples/patterns/search-box/navigation-dark.html, templates/docs/examples/patterns/search-box/navigation.html, templates/docs/examples/templates/maas-docs-grid.html, templates/docs/examples/templates/maas-docs.html, templates/docs/examples/templates/maas-layout.html
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/872
- Pull code
- Inspect list of changes, verify all alt attributes on buttons have been removed
=> Accessibility fix: Remove alt attribs from all buttons

templates/_layouts/_footer.html, templates/_layouts/_header.html, templates/docs/examples/index.html, templates/docs/examples/layouts/documentation.html, templates/docs/examples/patterns/breadcrumbs.html, templates/docs/examples/patterns/navigation/default-dark.html, templates/docs/examples/patterns/navigation/default.html, templates/docs/examples/patterns/navigation/deprecated-dark.html, templates/docs/examples/patterns/navigation/deprecated.html, templates/docs/examples/patterns/navigation/full-width.html, templates/docs/examples/patterns/navigation/subnav-dark.html, templates/docs/examples/patterns/navigation/subnav.html, templates/docs/examples/patterns/search-box/navigation-dark.html, templates/docs/examples/patterns/search-box/navigation.html, templates/docs/examples/patterns/side-navigation/_default.html, templates/docs/examples/patterns/side-navigation/_icons.html, templates/docs/examples/patterns/side-navigation/docs.html, templates/docs/examples/patterns/side-navigation/icons.html, templates/docs/examples/patterns/table-of-contents.html, templates/docs/examples/patterns/tabs.html, templates/docs/examples/standalone.html, templates/docs/examples/templates/maas-docs-grid.html, templates/docs/examples/templates/maas-docs.html, templates/docs/examples/templates/maas-layout.html, templates/docs/examples/templates/snapcraft-publicise.html, templates/docs/examples/templates/z-index.html
Fixes Accessibility: Nav tag should have aria-label #3252
- Pull code
- Review aria-labels on nav elements, verify they make sense
=> Add aria-labels to all nav elements

requirements.txt
=> Update flask-base to 0.6.4

templates/docs/examples/patterns/slider/slider-input.html
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3226 as per the [spec](https://www.w3.org/TR/wai-aria-practices/#x3-18-slider)
- aria-valuemin, valuemax, valuenow
- aria-labels
- tabindex="0"
- Pull code
- Run `./run`
- Verify the added attributes are correct
=> Add aria-attributes to slider component

templates/_layouts/examples.html, templates/docs/examples/patterns/forms/_checkbox-heading.html, templates/docs/examples/patterns/forms/_checkbox-inline.html, templates/docs/examples/patterns/forms/_checkbox.html, templates/docs/examples/patterns/forms/_radio-heading.html, templates/docs/examples/patterns/forms/_radio-inline.html, templates/docs/examples/patterns/forms/_radio.html, templates/docs/examples/patterns/forms/tick-comparison.html, templates/docs/examples/patterns/switch.html, templates/docs/examples/templates/tick-element-comparison.html, templates/docs/examples/templates/typographic-spacing.html, templates/docs/examples/utilities/baseline-grid.html
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3222
Inspect changes, verify the ids do not repeat and that all checkboxes/radios either:
- have an aria-labelled-by attr
have accompanying labels with `for`
=> Add aria-labels to tick elements, make ids in examples unique

templates/_layouts/_header.html, templates/docs/examples/base/forms/fieldset.html, templates/docs/examples/base/forms/form.html, templates/docs/examples/base/forms/input.html, templates/docs/examples/base/forms/labels.html, templates/docs/examples/layouts/documentation.html, templates/docs/examples/patterns/forms/_form-stacked.html, templates/docs/examples/patterns/forms/dense.html, templates/docs/examples/patterns/forms/form-help-text.html, templates/docs/examples/patterns/forms/form-inline.html, templates/docs/examples/patterns/forms/form-validation.html, templates/docs/examples/patterns/forms/forms-required.html, templates/docs/examples/patterns/forms/tick-comparison.html, templates/docs/examples/patterns/search-box/default-dark.html, templates/docs/examples/patterns/search-box/default.html, templates/docs/examples/patterns/search-box/navigation-dark.html, templates/docs/examples/patterns/search-box/navigation.html, templates/docs/examples/templates/maas-docs-grid.html, templates/docs/examples/templates/maas-docs.html, templates/docs/examples/templates/maas-layout.html, templates/docs/examples/templates/tick-element-comparison.html, templates/docs/examples/templates/typographic-spacing.html, templates/index.html
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/867
- Add autocomplete
- Add some missing name attribs
- Fix repeating ids in a few places
- Correct type="text" to type="email" for all email fields
- Pull code
- Inspect changes, verify autocomplete uses the correct values as specced [here](https://www.w3.org/TR/WCAG21/#input-purposes)
- Verify the other changes are correct too
=> Add autocomplete and fix types in a few places

templates/docs/examples/layouts/application.html, templates/docs/examples/patterns/accordion/headings.html, templates/docs/examples/patterns/forms/_checkbox.html, templates/docs/examples/patterns/forms/_form-stacked.html, templates/docs/examples/patterns/forms/_radio-heading.html, templates/docs/examples/patterns/tables/table-expanding.html, templates/docs/examples/templates/maas-docs.html, templates/docs/examples/templates/snapcraft-publicise.html, templates/docs/examples/templates/typographic-spacing.html
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/871
- Pull code
- Inspect changes, verify they don't break anything
- Bonus: use a better tool than regex to locate duplicate ids. [Apparently ](https://stackoverflow.com/questions/29681442/find-duplicated-id-keys-in-html-using-a-regex) regex is not ideal for parsing html, so another tool may reveal more duplicates.
=> Remove duplicate ids

templates/docs/examples/patterns/forms/form-validation.html, templates/docs/examples/patterns/notifications/action.html, templates/docs/examples/patterns/notifications/caution.html, templates/docs/examples/patterns/notifications/information.html, templates/docs/examples/patterns/notifications/negative.html, templates/docs/examples/patterns/notifications/positive.html
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3322
- Pull code
- Inspect role additions, verify they are on the correct element
=> Add status and alerts roles to notifications and validation messages

templates/docs/examples/patterns/accordion/default.html, templates/docs/examples/patterns/accordion/headings.html, templates/docs/examples/patterns/list-tree.html, templates/docs/examples/templates/maas-layout.html
Fixes the validator complaints on https://github.com/canonical-web-and-design/vanilla-framework/issues/3217
- Pull code
- Verify the changes look correct and do not break functionality.
=> Accordion: fix accessibility validator errors

templates/docs/examples/layouts/application.html
aria-describedby on all tooltips in the application layout were pointing to the same id. This pr corrects that.
##QA
- Inspect changes, verify the aria-describedby points to the correct id for each tooltip.
=> Applicaiton layout: Point aria-describedby to correct ids

templates/docs/examples/layouts/application.html, templates/docs/examples/patterns/forms/_form-stacked.html, templates/docs/examples/templates/snapcraft-publicise.html, templates/docs/examples/templates/tick-element-comparison.html
When I rerun the alidator on a few example pages it produced a few validation complaints I had previously missed, this resolves them.
- Pull code
- Inspect code, verify the changes correct issues currently seen on the specified pages when run through the validator [here](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fvanillaframework.io%2Fdocs%2Fexamples%2Flayouts%2Fapplication)
=> Fix a few validator complaints

scss/_base_typography-definitions.scss, scss/_patterns_pull-quotes.scss
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3334
- Inspect files changed. Verify value 300 changed to 100.
Screenshot:
=> Change h3 font-weight to 100

scss/_base_button.scss, scss/_base_code.scss, scss/_base_fontfaces.scss, scss/_base_forms.scss, scss/_base_tables.scss, scss/_base_typography-definitions.scss, scss/_base_typography.scss, scss/_settings_font.scss
Fixes #3308
- Pull code
- Run `./run`
- Make sure muted heading renders as expected
=> Set muted heading font weight to 300

templates/accessibility.html
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3046
- Remove some of the aspirational stuff, as it sounds somewhat patronising (others may disagree)
- Focus on what we have actually done in recent memory, rather than preaching
- Update the layout a bit
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/accessibility or [demo]
- Read the text, see if you agree with the changes
- Provide feedback :)
=> Update the accessibility guidelines page

templates/docs/patterns/icons.md
Update the documentation around using the dark-themed icons.
Related #3366
=> Clarify the usage of the dark-themed icons.

package.json
=> Bump version to 2.19.3

package.json, templates/_layouts/docs.html, templates/docs/component-status.md, templates/docs/layouts/application.md, templates/docs/patterns/buttons.md
- Pull code
- Run `./run`
- Check updated documentation
=> Prepare 2.20.0 release

package.json, templates/_layouts/docs.html
- Check the [demo](https://vanilla-framework-3451.demos.haus/docs)
- Make sure version is updated
- Check component status: https://vanilla-framework-3451.demos.haus/docs/component-status
- Check if labels in side navigation are up to date with latest changes
=> Bump version to 2.21.0

scss/_patterns_separator.scss, scss/_vanilla.scss, scss/standalone/patterns_separator.scss, templates/_layouts/docs.html, templates/docs/base/separators.md, templates/docs/component-status.md, templates/docs/examples/patterns/separator.html
Adds new separator component
Fixes #3437 
- Open [demo](https://vanilla-framework-3486.demos.haus/docs/base/separators)
- Check the separator example:
- https://vanilla-framework-3486.demos.haus/docs/examples/patterns/separator
- Review new separator documentation page: https://vanilla-framework-3486.demos.haus/docs/base/separators
=> Add separator component

package.json
Bump version of Vanilla  for hotfix release 2.22.1
=> Bump version to 2.22.1

templates/accessibility.html
Fixes broken HTML in accessibility.html
- https://validator.w3.org/nu/?doc=https%3A%2F%2Fvanillaframework.io%2Faccessibility (adjust for the right URL)
=> Fix broken HTML

README.md, templates/docs/building-vanilla.md
Improve docs about autoprefixer
Fixes #3516
- Open [demo](https://vanilla-framework-3528.demos.haus/docs/building-vanilla)
- https://vanilla-framework-3528.demos.haus/docs/building-vanilla
=> Improve docs about autoprefixer

scss/_utilities_vertically-center.scss, scss/_vanilla.scss
Fixes #3537
- Inspect percy, ensure nothing looks wrong
=> Apply !important on all properties of the .u-vertically-center utuility class

package.json, templates/_layouts/docs.html, templates/docs/component-status.md, templates/docs/layouts/fluid-breakout.md
Fixes canonical-web-and-design/vanilla-squad#974
- Open [demo](https://vanilla-framework-3555.demos.haus/docs/component-status)
- make sure version is correct
- make sure status page is updated and links work as expected: https://vanilla-framework-3555.demos.haus/docs/component-status
=> Prepare Vanilla release 2.24.0

scss/_base_forms.scss
Fix fieldset issues raised in https://github.com/canonical-web-and-design/vanilla-squad/issues/969
- check that padding is same as in cards
=> Fix fieldset issues raised in #969

package.json
Bump version to 2.28.0-rc1 for release candidate
=> Bump version to 2.28.0-rc1 for release candidate

templates/docs/examples/patterns/tooltips/_tooltips_script.js
- Updated the `is-detached` tooltip example to demonstrate better showing/hiding of tooltips
- Updated the existing JS script to position tooltips statically, rather than to move with the cursor, to aid with the above point
Fixes #2833 
- Open [demo](https://vanilla-framework-3688.demos.haus/docs/examples/patterns/tooltips/detached)
- Hover over each tooltip, see that there is a short delay before the tooltip appears
- It should be impossible to make two tooltips appear simultaneously, so see if you can prove me wrong …
=> Improve show/hiding of tooltips in JS example

webapp/app.py
- Updates @bartaz's title
- Adds @ziheliu214 as team member (sorry @wgx, your contributions are still very welcome! 😉 )
- Open [demo](https://vanilla-framework-3769.demos.haus/contribute)
- Check if the team is up to date
=> Let's make it official

scss/_base_blockquotes.scss, scss/_base_button.scss, scss/_base_forms.scss, scss/_base_hr.scss, scss/_layouts_application-panels.scss, scss/_patterns_breadcrumbs.scss, scss/_patterns_card.scss, scss/_patterns_code-snippet.scss, scss/_patterns_divider.scss, scss/_patterns_grid.scss, scss/_patterns_heading-icon.scss, scss/_patterns_lists.scss, scss/_patterns_matrix.scss, scss/_patterns_media-object.scss, scss/_patterns_modal.scss, scss/_patterns_notifications.scss, scss/_patterns_pagination.scss, scss/_patterns_pull-quotes.scss, scss/_patterns_search-and-filter.scss, scss/_patterns_side-navigation.scss, scss/_patterns_subnav.scss, scss/_patterns_switch.scss, scss/_settings_colors.scss, scss/_settings_grid.scss, scss/_settings_spacing.scss, scss/_utilities_baseline-grid.scss, templates/docs/upgrade-guide-v3.md
Review usage and fix some issues around spacing vars.
=> Spacing vars update

templates/docs/building-vanilla.md
Minor documentation fixes on how to build with Webpack.
=> Update webpack build steps

.spelling, scss/_patterns_notifications.scss, templates/docs/examples/patterns/notifications/action.html, templates/docs/examples/patterns/notifications/borderless.html, templates/docs/examples/patterns/notifications/dismissable.html, templates/docs/examples/patterns/notifications/inline.html, templates/docs/examples/patterns/notifications/modal.html, templates/docs/examples/patterns/notifications/raised.html, templates/docs/examples/patterns/notifications/time.html, templates/docs/examples/patterns/notifications/variants.html, templates/docs/patterns/notification.md
- Added documentation for action, inline, borderless, modal, raised notification variants
Fixes #3855 
- Open [demo](https://vanilla-framework-3854.demos.haus/docs/patterns/notification)
- Check that the new notification variants are documented
=> add documentation for new notification variants

.spelling, scss/_base_placeholders.scss, scss/_layouts_application.scss, scss/_patterns_notifications.scss, scss/_settings_placeholders.scss, templates/_layouts/docs.html, templates/docs/component-status.md, templates/docs/examples/patterns/notifications/action.html, templates/docs/examples/patterns/notifications/borderless.html, templates/docs/examples/patterns/notifications/caution.html, templates/docs/examples/patterns/notifications/deprecated.html, templates/docs/examples/patterns/notifications/dismissable.html, templates/docs/examples/patterns/notifications/dismissible.html, templates/docs/examples/patterns/notifications/information.html, templates/docs/examples/patterns/notifications/inline.html, templates/docs/examples/patterns/notifications/modal.html, templates/docs/examples/patterns/notifications/negative.html, templates/docs/examples/patterns/notifications/notifications.html, templates/docs/examples/patterns/notifications/positive.html, templates/docs/examples/patterns/notifications/raised.html, templates/docs/examples/patterns/notifications/time.html, templates/docs/examples/patterns/notifications/timestamp.html, templates/docs/examples/patterns/notifications/variants.html, templates/docs/patterns/notification.md
This is a feature branch that gathers the work on new notification style
- Open [demo](https://vanilla-framework-3856.demos.haus/docs/patterns/notification)
- Make sure all work as expected
- This is a feature branch, individual PRs have been reviewed and QAed already, so just a final verification
- see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-ta …
=> Update notifications component with new style and features

package.json
Prepare version for pre-release
- Check version in package.json
=> Bump version for pre-release 2.33.0-rc1

package.json
=> Bump version to 2.33.0-rc2

package.json
Prepare version for final release
=> Bump version to 2.33.0

templates/docs/patterns/modal.md
Added a heading for the modal footer so we can link directly to it.
=> Add heading for modal footer

package.json, scss/_patterns_form-password-toggle.scss, scss/_patterns_icons.scss, scss/_vanilla.scss, scss/standalone/patterns_form-password-toggle.scss, scss/standalone/patterns_forms.scss, templates/docs/base/forms.md, templates/docs/component-status.md, templates/docs/examples/patterns/forms/_script.js, templates/docs/examples/patterns/forms/password-toggle.html, templates/docs/examples/patterns/icons/icons-additional.html, templates/docs/examples/patterns/icons/icons-light.html, templates/docs/patterns/icons.md
Added a pattern for showing and hiding the value of password fields
- Open [demo](https://vanilla-framework-3899.demos.haus/docs/examples/patterns/forms/password-toggle)
- Check that the pattern matches [the spec](https://docs.google.com/document/d/1Q5i2DI801rKA4XO8MZv0dldUUGGbB6zPSWsRVLf8mk0/edit)
=> Add password toggle pattern

.circleci/config.yml
Update config to install certificates
- See the the checks build and pass
=> Circle CI config fix

package.json
Version bump for Vanilla 3.0 beta.1 prerelease
=> Bump version to 3.0-beta.1

scss/_patterns_switch.scss, templates/_layouts/examples.html, templates/docs/examples/patterns/switch.html, templates/docs/examples/utilities/baseline-grid.html, templates/docs/upgrade-guide-v3.md
Updates switch component HTML structure to be consistent with other components, most notably with checkbox.
Fixes #4112 
- Open [demo](https://vanilla-framework-4117.demos.haus/docs/examples/patterns/switch)
- Make sure switches look and work as expected
- Make sure 3.0 upgrade guide mentions changes needed for switch
- https://vanilla-framework-4117.demos.haus/docs/upgrade-guide-v3#switch
=> Update switch component to use more reliable HTML

.stylelintrc.json, package.json, yarn.lock
Updated stylelint to v14 to make sure VSCode extension works with it.
Reordered rules in stylelint config to make it more structured.
- Make sure CI checks pass
- Pull the branch locally in VSCode
- Make sure stylelint in VSCode works (try reordering some CSS props or break some other rules)
=> Update stylelint to v14

renovate.json
Add internal dependencies to renovate config, for consistency with other projects.
=> Update internal dependencies at any time

templates/docs/upgrade-guide-v3.md
Improve the docs around breakpoints
Fixes canonical-web-and-design/vanilla-squad#1173
- Open [demo](https://vanilla-framework-4207.demos.haus/docs/upgrade-guide-v3)
- Read the updated "Breakpoints" section
=> Improve the docs around breakpoints

.github/workflows/pr.yml, requirements.txt, templates/_layouts/_root.html, templates/_layouts/site.html, templates/index.html, webapp/app.py
- Remove slack from list on homepage
- Add image module and update logo section on homepage to use logo section pattern
Fixes #4211 
- Check the logo section looks ok on the home page
=> Add image module and update images

templates/docs/examples/patterns/notifications/toast.json, templates/static/js/src/demobox/app.tsx, templates/static/js/src/demobox/components/LiveDemoBox/LiveDemoBox.tsx, templates/static/js/src/demobox/components/LiveDemoBox/Switch.tsx, templates/static/js/src/demobox/components/LiveDemoBox/index.ts
- Added functionality to Live demo box
- Set default example in the JSON file
Fixes [#1205](https://github.com/canonical-web-and-design/vanilla-squad/issues/1205)
- Open [demo](https://vanilla-framework-4322.demos.haus/docs/patterns/notification)
- Check the initial default "information" example loads as expected
- Change values of all selects/switches and check the example works as expected
=> Render live demo box iframe

Dockerfile, package.json, requirements.txt, scripts/create-class-references.js, scss/_patterns_side-navigation.scss, templates/_layouts/_class-reference.html, templates/docs/patterns/notification.md, webapp/app.py, yarn.lock
=> Class reference frontend

webapp/app.py
Fixes issues with search after upgrade to 1.1.0 (https://github.com/canonical-web-and-design/canonicalwebteam.search/issues/16)
- Open [demo](https://vanilla-framework-4390.demos.haus/docs/search?q=grid&submit=)
- make sure search works
=> Fix search by providing search engine id

scss/_patterns_navigation.scss
=> Nav spacing: increase gap between logo and menu items

templates/_layouts/_header.html
Revert to old style logo.
- Open the demo link. Is the old style logo there?
=> Revert to old style logo

templates/_layouts/_header.html
Fix nav active for design pages.
- Go to /design/patterns/segmented-control
- Is the Docs global nav active?
=> Fix nav active for design

templates/docs/patterns/accordion.md
Very little change: added some headings to make the structure of the accordion docs easier to follow and consistent with other patterns (e.g. card)
- Open demo
- Go to the accordion page and check if the change makes sense
=> Update accordion docs

.github/release-drafter.yml
Adds authors to the list in release notes.
=> Add authors to release notes template

templates/contribute.html, webapp/app.py
- Fixes links to practice website
- Removes Beth from the team 😭 
Fixes #4449 
- Open [demo](https://vanilla-framework-4462.demos.haus/contribute)
- Make sure the links to Guidelines on HTML and CSS best practices work as expected
- Make sure Beth is not in the team (but is listed as contributor) - _nothing personal, Beth!_
=> Fix contribute page

.github/workflows/pr.yml, cypress.config.js, cypress/e2e/patterns/accordion.cy.js, cypress/support/commands.js, cypress/support/e2e.js, package.json, yarn.lock
- test: setup cypress
This PR will be followed by another one that will [Add Cypress to CI tests](https://github.com/canonical/vanilla-framework/issues/4541)
Fixes: https://github.com/canonical/vanilla-framework/issues/4538
- Run `yarn cypress:open` or `yarn cypress:run` and verify the example accordion test passes
- see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-release …
=> test: setup cypress

guides/release-process.md
=> update release link in readme

scss/_base_placeholders.scss
Update icon sizes to be 1.5rem. In my opinion this works better:
=> reduce social icon sizes to work better next to headings

scss/_settings_spacing.scss
Fixes https://github.com/canonical/vanilla-framework/issues/4643
=> Add !default to fontsizes map

releases.yml
Set version in releases.yml file to 3.12.1
=> Set version in releases.yml file to 3.12.1

Dockerfile, package.json
Move so called "build" dependencies (`autoprefixer`, `postcss`, `postcss-cli`, `postcss-scss`, `sass`, `yaml`) to "devDependencies".
=> Move all deps to devDeps

scss/_base_media.scss
Removed rounded corners from images
- Open [demo](https://vanilla-framework-4750.demos.haus/docs/patterns/images)
- Make sure images don't have rounded corners
=> Remove border radius from images

templates/docs/patterns/logo-section/accessibility.md
- Changed the logo section's accessibility documentation according to the copydoc: https://docs.google.com/document/d/1oVPfBXrkm6YsKRoL4MlAXO7SMKmewv7zYWHEQH9uHSI/edit
Fixes WD-6191 …
=> Update logo section component a11y documentation [WD-6191]

releases.yml
=> Fix typo in release file

scss/_base_typography-definitions.scss
- Add theme support for `u-text--muted`
Fixes [WD-8943](https://warthogs.atlassian.net/browse/WD-8943)
[WD-8943]: …
=> Add theme support for muted text

scss/_settings_colors.scss
- Remove repeated colour declaration
=> Remove repeated colours

scss/standalone/patterns_form-tick-elements.scss, templates/docs/examples/patterns/forms/checkbox-validation.html, templates/docs/examples/patterns/forms/radio-validation.html
- Add example for checkbox validation
- Add example for radio validation
Fixes [list issues/bugs if needed] https://github.com/canonical/vanilla-framework/issues/4716
[if relevant, …
=> Add validation example

.github/ISSUE_TEMPLATE/report-a-bug.md
=> Fixed typo in GH issue template (out site -> our site)

templates/docs/patterns/grid/index.md
=> Add space to grid docs

webapp/app.py
- Add @pastelcyborg (Josh) and @jmuzina (Julie) to the contributors page
- Remove [elioqoshi](https://github.com/elioqoshi) from the contributors page
- Update @bartaz job title to "Staff Web Engineer"
Closes [WD-10921](https://warthogs.atlassian.net/browse/WD-10921)
- Open [demo](https://vanilla-framework-5073.demos.haus/contribute)
- Verify that @jmuzina, @pastelcyborg have been added to the team members list
- Verify that elioqoshi is no longer in the team members list
- Verify that @bartaz job title has been updated to "Staff Web Engineer"
- if CSS class names are not changed it …
=> Update team members

templates/_macros/hero.jinja, templates/docs/examples/patterns/hero/combined.html, templates/docs/examples/patterns/hero/hero-75-25.html
Built 75-25 split hero HOC
Fixes [WD-13476](https://warthogs.atlassian.net/browse/WD-13476)
- Review [75/25 hero example](https://vanilla-framework-5230.demos.haus/docs/examples/patterns/hero/hero-75-25)
- Review [combined hero example](https://vanilla-framework-5230.demos.haus/docs/examples/patterns/hero/combined?theme=light)
[WD-13476]: https://warthogs.atlassian.net/browse/WD-13476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Hero Pattern: Build Hero 75-25 HOC

templates/_macros/hero.jinja, templates/docs/examples/patterns/hero/combined.html, templates/docs/examples/patterns/hero/hero-75-25.html, templates/docs/examples/patterns/hero/hero-fallback.html
Builds hero fallback layout
Fixes [WD-13477](https://warthogs.atlassian.net/browse/WD-13477)
- Review [fallback hero example](https://vanilla-framework-5231.demos.haus/docs/examples/patterns/hero/hero-fallback)
- Review [combined hero example](https://vanilla-framework-5231.demos.haus/docs/examples/patterns/hero/combined)
[WD-13477]: https://warthogs.atlassian.net/browse/WD-13477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Hero Pattern: Build Hero fallback HOC

webapp/app.py
Adds @advl to the team members list 
Fixes [WD-14209](https://warthogs.atlassian.net/browse/WD-14209)
- Open [demo](https://vanilla-framework-5310.demos.haus/contribute)
- Verify that @advl has been added as an "Engineering Manager"
[WD-14209]: https://warthogs.atlassian.net/browse/WD-14209?atlOrigin=eyJpIjoi …
=> Add advl to team members list

.github/actions/percy-snapshot/action.yml, .github/percy-workflow.md, .github/workflows/percy-baseline.yml, .github/workflows/percy-prepare.yml, .github/workflows/pr-percy-snapshots.yml, guides/percy-workflow.md, guides/pull-requests.md
- Adds / expands on Percy workflow documentation
- Added a dedicated Percy guide in `guides/`
- Improved comments on Percy workflow files
As a drive-by:
- Minor simplifications to Percy workflow files for improved readability
Fixes [WD-13580](https://warthogs.atlassian.net/browse/WD-13580)
- Review [Percy workflow docs](https://github.com/jmuzina/vanilla-framework/blob/percy-workflow-docs-improvement/guides/percy-workflow.md) …
=> Improve Percy workflow docs

webapp/app.py
bye pastelcyborg :(
- Open [contributors list](https://vanilla-framework-5373.demos.haus/contribute)
- See that it is updated to current team composition
=> Update contributors list

templates/docs/base/tables.md
Add content guidance for tables, capitalization and punctuation
Fixes https://github.com/canonical/vanilla-framework/issues/5115
- Open [demo](https://vanilla-framework-5376.demos.haus/docs/base/tables)
- Read the updated guidelines at the top of table page.
=> Add content guidance for tables

webapp/app.py
Corrects the team members list on the contribution page ;)
- Open [demo](https://vanilla-framework-5495.demos.haus/contribute)
- Make sure Bartek is not listed as team member anymore (but still holds his honourable place on contributors list) 😊
=> #bartaz { visibility: hidden }
