canonical/vanilla-framework

gulpfile.js
package.json

Details
===
Currently Travis isn't failing, even though there's
a syntax error in the sass.
This should fix that by making `gulp sasslint` return
an error state properly when something fails.
Done
---
- Separate `sasslint` from `sass` gulp commands
- Add FailReporter to `sasslint`
- The Gulp Sass target will now return an error status, with a useful error message
- The sass-lite target will return an error in a simpler and more useful way (without breaking watch)
QA
---
Run the following:
``` bash
npm install
node_modules/gulp/bin/gulp.js test || echo "successfully returned an error"
node_modules/gulp/bin/gulp.js sass || echo "successfully returned an error"
```
As long as the Sass still has its syntax error, you should see `successfully returned an error` after the output of each …

Travis sasslint fail state

---

.scss-lint.yml
gulpfile.js
scss/_core-grid-desktop.scss
scss/_core-grid-tablet.scss
scss/_core-grid.scss
scss/_core-mixins.scss
scss/_core-templates.scss
scss/_core.scss
scss/patterns/_blockquotes.scss
scss/patterns/_boxes.scss
scss/patterns/_buttons.scss
scss/patterns/_contextual-footer.scss
scss/patterns/_footer.scss
scss/patterns/_forms.scss
scss/patterns/_header.scss
scss/patterns/_helpers.scss
scss/patterns/_image-centered.scss
scss/patterns/_inline-logos.scss
scss/patterns/_rows.scss
scss/patterns/_search.scss
scss/patterns/_slider.scss
scss/patterns/_structure.scss
scss/patterns/_tabbed-content.scss
scss/patterns/_tooltips.scss

===
Remove any mixins and other mentions of vendor prefixes, 
to make sasslint happier.
Vendor prefixes are now taken care of by [autoprefixer](https://github.com/postcss/autoprefixer).
Done
---
- Rename `lint.yml` to the default `.scss-lint.yml` so it doesn't need specifying in `gulpfile.js` any more
- Remove mixins:
* box-shadow
* gradient
* columns
* transition
* box-sizing
* rounded-corners
* background-size
- Remove mentions of these mixins from scss files
- Remove other references to vendor prefixes
QA
---
- Make sure sass still compiles
- Check sasslint doesn't spit out any "VendorPrefix" errors
- Extra credits: Check styles still seem to look right

Remove vendor prefixes for sasslint

---

gulpfile.js

- None
- Added a small bit of logic in the gulp test task
- Run ```gulp test``` and see all the warnings and errors for all files
- Run ```gulp test --file patterns/patterns.scss``` to only lint that file

Add optional param to test to only test a single file

---

scss/patterns/_vertical-divider.scss

- None
- Disabled some linting exceptions inline
- See there are no linting issues when running ```gulp test --file patterns/_vertical-divider.scss```

Inline disabled some linting exceptions as they are required

---

gulpfile.js

- None
- Changed the path required for the test param to include scss/ so its the full path
- Run ```gulp test``` and see if checks all files
- Run ```gulp test --file scss/patterns/_image-centered.scss``` and check it only checks that file
- Try tab completing the file path as its relative

Changing test file to full path

---

scss/patterns/_tooltips.scss

- Issue: https://github.com/ubuntudesign/web-style-guide/issues/41
- Replaced the use of box-solid-grey with mid-grey
- Run ```gulp build``` and check it generates the css without an error

Fix the box-solid-grey issue

---

scss/patterns/_forms.scss
scss/patterns/_vertical-divider.scss

- None
- Linted the forms file
- Drive by on remove the vertical-divider lint disable comment
- Run ```gulp test --file scss/patterns/_forms.scss``` and check there are no warnings

Lint forms

---

README.md
package.json

Done:
- Changed name of npm dependencies script
- Update README to have commands which actually work
QA:
- Run the dependencies command from the readme.

Update readme install instructions; change "install-dependencies" to "dependencies" to save peoples fingers.

---

.install_dependencies.sh
.travis.yml
README.md
package.json

By using the `prepublish` step in `package.json`, it means .install-dependencies.sh
will be run automatically on `npm install`, simplifying setup for everyone.
This is now possible because the dependencies script should now work on travis as well
so the same dependencies script can be run anywhere.
Done
---
- Make install-dependencies script more robust
- Install dependencies on npm prepublish
* So now `npm install` will install everything in one step
* Updated README to reflect this
- Remove gem dependencies from travis yaml
QA
---
1. Check travis passes for this build
2. Delete `gulp` and `scss-lint` locally  
(`sudo npm uninstall -g gulp`, `sudo gem uninstall scss-lint`)  
Now run `npm install` and make sure `gulp` and `scss-lint` are installed

Simplify installation of dependencies

---

index.html
scss/_global-settings.scss
scss/_vanilla.scss
scss/modules/_clearfix.scss
scss/modules/_grid.scss
scss/modules/helpers/number-word.scss

I've reverse-engineered the existing grid settings to work out the formulae behind them. I've then written mixins to generate these classes from first principles.
Unfortunately the resulting code is a little difficult to understand. I've documented it where I can. Let me know if you can think of any way to improve it.
QA
--
Compile the CSS from `master` first (without my changes) and apply it to a site - e.g. canonical or ubuntu. Note how it looks.
Now compile the CSS from this branch, and apply it to the same site. Check columns and spacing looks the same on as many pages as possible.

Calculate grid columns

---

README.md

I'm not sure Gitter will ever really be much use.
We could instead just have a link to IRC? What do you think?
QA
--
See [README.md](https://github.com/nottrobin/vanilla-framework/blob/irc-badge/README.md)

Replace Gitter with IRC badge

---

gulpfile.js
package.json

Re-introduce sassdoc back into the vanilla framework.
Pull this branch down then in the root of vanilla run ```rm -rf node_modules``` and then run ```npm install```. This should install all the reuiqred modules, also look at the package.json & gulpfile to make sure all correct commands are present.
Once everything is installed correctly run ```gulp test```, ```gulp docs``` and ```gulp build```. This should cover all bases for our gulp commands. Once complete check the CSS is working & look at the sass docs to see if they built correctly.
_n/a_
_n/a_
_n/a_
_n/a_

Package dependancys

---

demo/index.html
scss/_vanilla.scss
scss/modules/_inline-logos.scss

- Added the inline-logos module
- Added new module to demo
- Linted the inline-logos module
- Run `google-chrome demo/index.html`
- Check the inline-logos section looks ok

Added inline-logos to vanilla

---

scss/_global-settings.scss

- Issue: https://github.com/ubuntudesign/vanilla-framework/issues/170
- Issue: https://github.com/ubuntudesign/vanilla-framework/issues/166
- Changed the brand color to the requested #f7f7f7
- Run `make build`
- Run `google-chrome demo/index.html`
- Check the header background is #f7f7f7 instead of #f5f5f5

Update brand color

---

scss/modules/_forms.scss

- Issue: https://github.com/ubuntudesign/vanilla-framework/issues/169
- Updated the field focus border color to the requested #888
- Changed the fieldset background color to #f7f7f7
- Run `gulp build && google-chrome demo/index.html`
- Check the focus border on the fields matches the issue
- Check the fieldset backgrounf in #f7f7f7

Update focus and fieldset color

---

scss/modules/_lists.scss

Done:
Removed the bottom margin from .list LIs
QA:
gulp build and check that lists have no undesirable styling

add zero bottom margin for li:last-of-type in .list

---

demo/index.html
scss/modules/_helpers.scss

#Done 
.priority-0/.not-for-small-fix - Add display: block; for medium + to counteract display: none; for small.
##QA
Should just need a visual or a canonical.c/ubuntu.c setup. Without display: block; the image stays hidden.

Fix not for small for medium upwards

---

scss/modules/_footer.scss

- Issue: https://github.com/ubuntudesign/vanilla-framework/issues/204
- Card: https://canonical.leankit.com/Boards/View/111185042/115694359
- Edited the hover colors in the footer to be link-color not brand-color which can lead to unlegible links
- Run `gulp check` and make sure there are no errors
- Check the demo in the link section and the footer that the links are set to link-color and the same color on hover with an underline

Style footer hover links with link-color

---

scss/modules/_media.scss

- Card: https://canonical.leankit.com/Boards/View/111185042/115595584
- Removed display block and clear both from the img element
- I found they are styled correctly in reset already to simply removed the extra styling from the media component
- Run `gulp check` and see there are no errors
- Check the demo, the image layout should still be correct.

Remove duplicated image styling

---

demo/index.html
scss/modules/_forms.scss

Done:
Removed margin and bullets from ULs in forms.
QA:
gulp build and there is a list in a form at the bottom of the form elements section in the demo.

remove margin and bullets from ULs in forms

---

scss/modules/_equal-height.scss

- Card: https://canonical.leankit.com/Boards/View/111185042/115595595
- Added width to the equal height container
- Run `make build`
- Check the equal-heights section of the demo looks ok
- Check different viewports

Made the equal-heights module full width to not wrap with site gutters

---

scss/modules/_breadcrumbs.scss
scss/modules/_header.scss
scss/modules/_rows.scss

- Issue: https://github.com/ubuntudesign/vanilla-framework/issues/209
- Card: https://canonical.leankit.com/Boards/View/111185042/115768655
- Updated the row padding to be 20px on large/medium and 10px on small screens
- Updated the logo padding to match
- Changed the contextual navigation left padding to align with content
- Check the rows have the new padding
- Check the contextual next aligns
- Check the logo aligns
- Check across all viewports

Updated page outer gutters

---

scss/modules/_header.scss

#Done 
Change ‘width’ to ‘max-width’ so the main nav doesn’t break at $breakpoint-medium
##QA
Pull this and run the site locally.
Resize your browser to 768 or less for that matter, and note that the primary nav doesn’t cause horizontal scroll.
##Details 
Card: https://canonical.leankit.com/Boards/View/111185042/116185595

Fix med main nav horizontal scroll

---

demo/index.html

#Done 
Changed the title/desc of the ‘error’ messages to match their labels.
##QA 
Should only need a visual or pull and run the demo locally and note the changes.
##Details
Card: https://canonical.leankit.com/Boards/View/111185042/116184188

Change titles of 'error' messages

---

demo/index.html
scss/modules/_breadcrumbs.scss

Add breadcrumb active class.
Change breadcrumb active class to $link-color
Pull and run gulp build, then head to the demo and check the activeness.
Wondering if font-weight: 500; (line 158 of _breadcrumbs.scss) was done on purpose?
Card: https://canonical.leankit.com/Boards/View/111185042/116328498

Add breadcrumb active class

---

scss/modules/_breadcrumbs.scss

Removed the right margin as it’s not the same as on live.
Pull the gulp build then have a look at the demo and compare with live

Refactor breadcrumb to remove right margin

---

demo/index.html
scss/modules/_breadcrumbs.scss

Remove bold on active into below navigation threshold.
Remove site specific links and make more generic/descriptive.
Pull this the gulp build, head to demo/index.html and note that the ‘active’ breadcrumb isn’t emboldened and the breadcrumb words are more descriptive of what they do.
Card: n/a

Remove bold on active

---

scss/modules/_helpers.scss

- Card: https://canonical.leankit.com/Boards/View/111185042/115936195
- Bug: https://bugs.launchpad.net/ubuntu-web-style-guide/+bug/1468878
- Changed the background position of a external icon to work with IE syntax
- Check the new ubuntu-styles work as expected for Chrome, FF, IE 11 on www.u.com and insights.u.com

Fix external icon positioning in IE 11

---

demo/index.html
scss/modules/_breadcrumbs.scss

Fix issue 227 - Second level nav not vertically centered
Run gulp build then have a look at the demo, cross reference it with the screen grab in the issue and make sure it looks better. Also not the position of the chevrons.
Issue: https://github.com/ubuntudesign/vanilla-framework/issues/227

Second level nav not vertically centered

---

scss/modules/_breadcrumbs.scss

Fix an issue where the tertiary nav is full width on small screens
Pull this branch, then ‘gulp build’, take a look at the demo and make your screen 360 px wide, ensure that the tertiary nav is inline and floating and is 50% wide.
Card: https://canonical.leankit.com/Boards/View/111185042/115595794

Changes based on implementation on u.c

---

demo/index.html
scss/modules/_typography.scss

Card: https://canonical.leankit.com/Boards/View/111185042/117885405
Add HTML strong tag example to demo
Run gulp build then head over to the demo and note that the word ‘moleskin’ in the vertical divider section is normal in font weight.

Add HTML strong tag to demo

---

demo/index.html
scss/_global-settings.scss
scss/modules/_typography.scss

- Added `base-font-family` and `heading-font-family` as global vars to other sites
- Updated the font loading to check for the existence of 'Ubuntu' in the font stack before requesting it
- Removed the google font from the header
- Open demo/index.html in a browser and check the font is not bold (particularly Ubuntu 15.10)
- Check in the inspector/network is loading the font from assets
- Remove Ubuntu from the font stack then check the font is not loaded from assets
- Card: https://canonical.leankit.com/Boards/View/111185042/118695614
- Fixes: https://github.com/ubuntudesign/vanilla-framework/issues/189 and https://github.com/ubuntudesign/vanilla-framework/issues/63

Add font family global variables with dynamic font loading

---

scss/modules/_inline-logos.scss

Add top padding to list-logos to better replicate live
Run 'gulp build' then check the demo, there should be a greater gap between the heading and the list. The issue is more noticable on ubuntu website, this change mirrors live a bit better.

Add top padding to list-logos to better replicate live

---

gulpfile.js
package.json

* Bump Gulp version to 3.9
* Bump gulp-autoprefixer version to 3.1.0
* Bump gulp-sass to version 2.1.1
* Swap out deprecated gulp-minify-css for gulp-cssnano
To test these changes, check out this branch and run `gulp` from root. All processes should run without error or warnings appear in your console. You should also load the `demo/index.html` file to ensure the page has styling.
Related to issue #278

Gulp plugin upgrades

---

scss/modules/_helpers.scss

The rules to float the element and collapse the gutter was previously only kicking in at the medium breakpoint. I've now moved the float out of this media query so it applies by default.
I also refactored the rule to move the media queries inside the selectors to remove the need to duplicate the rule selectors.
Run `gulp sass` and view the `demo/index.html` page at a width less than 768px. you should see under the heading _.touch-border_ that the placeholder image sits flush on top of the border. (see below)
Issue: #253

Ensure `.touch-border` works on small screens

---

demo/index.html

Textarea elements are styled with a form element so need to be nested inside a <form> element to display consistently like text fields.
The textarea examples in `demo/index.html` are now wrapped in <form> elements.
Load up the demo page and check that textarea widths reflect that of text field widths - 100% on small screens, 50% after the tablet breakpoint.
Fixes #255

Wrap <textrea> in <form> so they display correctly

---

scss/modules/_forms.scss

Removed Safari pseudo-class namespace.. It would appear that this pseudo-class is now deprecated for iOS9 although I can't find any evidence of that online.
Check out this branch and load `demo/index.html` - the search input example should no longer have rounded corners. Like so;
Fixes: #265

Remove rounded corners from search input example

---

scss/modules/_helpers.scss

Previously this helper was hiding any content once the large screen breakpoint was met. This fix means the content will be hidden on small screens and only appear once the medium breakpoint is hit.
Fixes: #254

Correct `.for-medium` helper so only display @>768

---

demo/index.html

Replaced link with absolute link to Ubuntu legal page
Fire up `demo/index.html` page and click the legal link in the demo page footer - it should take you to;
http://www.ubuntu.com/legal
Fixes: #288

Replace relative link with absolute link to Ubuntu legal

---

demo/index.html
scss/modules/_rows.scss

- Add styles to remove dotted borders from row-grey sections
- Add row-grey section to the demo page
Run code, check demo and see that grey row section should not have a dotted border.
Due to CSS' inability to select a preceding element, I'm raising row-grey's margin-top by 1 negative pixel to cover the preceding elements bottom border. Thoughts?
I've added `border: 0` to `.row-grey` when there is already a `.no-border` helper. Should row-grey also contain a rule to zero borders? Personally, I think yes but maybe not? 
Fixes: #294

Amend .row-grey styling to remove dotted borders

---

scss/modules/_blockquotes.scss
scss/modules/_rows.scss

- Added rules so that rows can stretch the full width of the screen with an inner wrap to constrain content to the the max-width of the site.
Check code makes sense.
Fixes: #312

Move Full Width style rules upstream

---

demo/index.html

Update assets to use new Ubuntu orange
Run gulp build then pop on over to the demo page and cross reference the changed images mentioned on the issue 'Projects we love’ this one isn’t on list I spotted it in a sweep of the projects.
Card: https://trello.com/c/8wwsIWR3
Issue: https://github.com/ubuntudesign/ubuntu-vanilla-theme/issues/22

Update assets to use new Ubuntu orange

---

scss/_global-settings.scss
scss/modules/_typography.scss

Fixes #331
Manually downsize the font-size and margin-bottom for headings on small and medium screens.  I also made the base-font variable to make these more explicit.
1. load the /demo/index.html and resize the screen to the $breakpoint-medium size and smaller to see the headings font-size and margin-bottom drop inline with live ubuntu.com
see issue #331 for more info

downsize headings font-size and margin-bottom on S and M screens

---

scss/modules/_typography.scss

Make list items font size match paragraph size of .875em (14px) on small
Run gulp build then open the demo and make sure the list items are .875em (14px) on small
Issue: https://github.com/ubuntudesign/www.ubuntu.com/issues/380

Font size fix

---

scss/modules/_blockquotes.scss

The existing end quotation mark selector relied upon two span
elements being next together, and not using any other elements
inbetween. This changes the code to explicity look for the last
span element.
For example this would work:
```
<p>
<span>&ldquo;</span>
Right quote looks fine.
<span>&rdquo;</span>
</p>`
```
And this would not work:
```
<p>
<span>&ldquo;</span>
Right quote style <strong>not</strong> applied here.
<span>&rdquo;</span>
</p>
```

Change end blockquote selector

---

demo/index.html
scss/_vanilla.scss
scss/modules/_grid-list.scss

Added `.list-grid` to framework for consistent re-use across products.
- Check code 
- Run `gulp sass` then check demo
Small screen:
Large screen:

Add .list-grid component to framework

---

demo/index.html
scss/modules/_buttons.scss

- Added external button pattern to Buttons section of demo
- Tweaked style to ensure white external icon is displayed on primary buttons
- Run code, check that buttons on demo reflect screenshot below
Fixes: #358
Related: https://github.com/ubuntudesign/www.ubuntu.com/issues/639

Add .external button pattern

---

scss/modules/_grid-list.scss

Add a max-width to grid list images to make sure they don't outgrow their place on tablet views
Pull down, check demo page across breakpoints

Add max-width to grid list images

---

scss/modules/_typography.scss

This will ensure that `<p>` tags inside `<li>` tags or vice-versa are not scaled down twice as em sizing is relative to it's parent.
Code only.
Fixes: https://github.com/ubuntudesign/www.ubuntu.com/issues/375

Change em to rem on p and li defaults

---

scss/modules/_reset.scss

Moved global styles inside @vf-reset so that they are not included in CSS unless explicitly specified.
Import VF but do not call any mixins. CSS file should be empty.
Fixes: #365

Move global styles inside vf-reset

---

scss/modules/_forms.scss

Added "not-allowed" cursor style to disabled form elements.
Run code, check `/demo` page, scroll down to disabled form elems and hover over. The cursor should appear with a small disabled icon next to it.
Fixes: #239

Add 'not-allowed' cursor style to disabled form elems

---

demo/index.html
scss/modules/_typography.scss

I have purposefully added these classes in addition to the raw element selectors. While this restricted the ability to apply a `heading-1` class to a `h2` element, it will ensure backwards compatibility and that this change is not a large breaking change.
The larger sweep of these styles, decoupling them from raw element selectors will be included in time for v1.0
Run code, navigate to /demo and check that heading 1-6 are displayed.
Fixes: #352

Add heading classes 1-6

---

scss/modules/_forms.scss

Previous to this change, when a state class was added, the corresponding border style would appear but would disappear when the input elem gained focus due to the focus style not being explicitly set and the default fallback of grey showing instead.
Run code, navigate to /demo and click through each form elem and observe that border style persists on focus.
Fixes: #188

Persist input state styles on focus

---

scss/modules/_forms.scss

Abstracted disabled styles into placeholder variable that can be used for tick elems.
Run code, check that all disabled elements on the /demo page have 50% opacity and when rolled over with the mouse, the cursor changes to be disabled.
Fixes: #218 / #239 / #303

Refactor disabled elem styles to include tick elems

---

V1_RELEASE_NOTES.md
docs/vf/overrides/_helpers.md
scss/_overrides_helpers.scss

**Note**: Travis build in `v1-dev` branch due to #433 - hopefully should be sorted this week.
- Remove `.touch-border` from the codebase
- Add `V1_RELEASE_NOTES.md` to repo to keep track of changes for V1 release.
- Ensure I have removed all references of `.touch-border`
Fixes: #431

Deprecated ‘.touch-border’

---

docs/partials/sidebar.hbt
docs/vf/layout/_clearfix.md
docs/vf/layout/_equal-height.md
docs/vf/layout/_grid.md
docs/vf/layout/_number-word.md
docs/vf/layout/_rows.md
docs/vf/layout/_vertically-center.md
docs/vf/utilities/_helpers.md

**Note**: Travis build in `v1-dev` branch due to #433 - hopefully should be sorted this week.
- Renamed 'Overrides' layer to 'Utilities'
- Renamed ''Tools' layer to 'Layout'
We first decided to renamed Overrides to Utilities as utils are actually as overrides as technically a subset of Utilities. This then meant that it was confusing to have Tools and Utilities as they are very similar to a lot of people. As the Tools are all actually layout based, it makes more sense to rename this layer 'Layout'.
Pull code and run `gulp develop` to check that there are no errors.
Fixes: #418

Rename layers of ITCSS

---

scss/_tools_clearfix.scss

- This rule was set as %placeholder which was then being called inside a mixin immediately after it which is pointless?
- We can simplify the rule itself as we no longer need to support IE 6/7 and older versions of Opera.
Ref: http://cssmojo.com/the-very-latest-clearfix-reloaded/
Fixes: #406

Simplify .clearfix layout rule

---

V1_RELEASE_NOTES.md
demo/index.html
docs/utilities/_helpers.md
scss/_layout_rows.scss
scss/_utilities_helpers.scss

Remove the util class `.no-border` as we'll be removing the presumption that certain elements have borders by default.
- Check that I've removed all instances
- Check that I haven't removed anything I should not have.

Remove .no-border

---

V1_RELEASE_NOTES.md
demo/index.html
docs/utilities/_floats.md
scss/_utilities_floats.scss
scss/_vanilla.scss

- Deprecate `.left / .right` in favour of being more descriptive utils: `.u-float--right / .u-float--left`
- Updated docs
- Sanity check code. 
- Check docs and float examples in local version of vf.io
Fixes: #424

Abstract left/right float utils

---

scss/_base_links.scss

`a:visited` text colour and bottom border becomes to `$color-mid-grey`
`a:hover / a:focused` bottom border becomes `$color-warm-grey`
If https://github.com/ubuntudesign/vanillaframework.io/pull/6 has landed, fire up your local version of vanillaframework.io and check the links match their description above.
Fixes: #448

Add base link states for :hover  / :visited

---

docs/settings/_assets-settings.md
docs/settings/_breakpoint-settings.md
docs/settings/_color-settings.md
docs/settings/_font-settings.md
docs/settings/_grid-settings.md

Removed the word 'settings' from the title front-matter in `_settings_&.md` files as these are surplus to requirements when they are pulled into the Pattern Lib sidebar as they sit under a sidebar heading which says 'Settings'.
- Fire up vf.io project and check sidebar does not contain items suffixed with ' settings'

Hygiene: Remove ‘settings’ from file titles

---

docs/utilities/_vertically-center.md
scss/_utilities_vertically-center.scss
scss/_vanilla.scss

Added a vertical centering util to that the equal height util can be simplified to only make two siblings equal height.
- Sanity check code. 
- I avoided adding an example in the docs of vf.io to demo this util as it requires a lot of scaffolding CSs to demo. I want to think about a more elegant way to demo utils like this, perhaps using Codepen embeds or similar.
Fixes: #414

Add vertical center util

---

V1_RELEASE_NOTES.md
docs/base/_typography.md
docs/settings/_font-settings.md
scss/_base_typography.scss
scss/_vanilla.scss

- Simplified base typography styles
- Remove superfluous font families
- Set up font sizing scale per breakpoint - Small: 14px / Medium: 15px / Large: 16px
- Sync with vf.io and compare docs
- Scale through breakpoints and check body copy is 14px / 15px / 16px respectively.
Note: @yaili has been doing some work on vertical rhythm - this will be finessed next week in off-site sprint.
Fixes: #391, #224

Clean up base typography

---

gulpfile.js
package.json

Catch exceptions in the Gulp sass job, so that it does not break the
watch command.
The stream will now print sass errors in line and continue to watch for new changes.

Fix leaky Gulp pipes with Plumber

---

docs/patterns/_code.md

* updated the text of the page to better explain the various code blocks
* updated the example to remove some left spaces
1. go to /patterns/code-numbered/ on the vanillaframework.io site
2. see that the indentation works
3. see that the text mentions the other two code styles

Remove doc code indentation

---

docs/base/_blockquote.md
docs/patterns/_pull-quote.md
scss/_base_blockquotes.scss
scss/_patterns_breadcrumbs.scss
scss/_patterns_pull-quotes.scss

* made blockquotes use inline quote marks based on @yaili's supplied design
* changed the right quote to be a lower quote
* updated the font sizes and margin to match the design
* made it work better with multi-line quotes
* fixed .p-pull-quote to match
* DRIVE-BY - fixed ':after' to '::after' on the breadcrumbs.scss
1. go to vanillaframework.io (locally) and look at both /base/blockquote/ and /patterns/pull-quote/ and see that the output matches the design
Fixes #488

Fix-up blockquotes and pull quotes

---

docs/utilities/_embedded-media.md
docs/utilities/_floats.md
docs/utilities/_margin-collapse.md
docs/utilities/_off-screen.md
docs/utilities/_padding-collapse.md
docs/utilities/_text-center.md
docs/utilities/_vertically-center.md
docs/utilities/_visibility.md

I missed capitalising the Util docs; corrected.
Read the changes to the docs.

Capitalisation fix for util docs' titles

---

docs/settings/_breakpoint-settings.md

* made the doc for breakpoints plural
* added a description
* added examples
1. go to /settings/breakpoints/ and see that
* Breakpoints is plural (as per original bug)
* There is now a description and example of how it is used in media queries
Fixes [vanillaframework.io bug 23](https://github.com/ubuntudesign/vanillaframework.io/issues/23)

update breakpoint doc

---

docs/settings/_font-settings.md

* removed a colon
1. go to /settings/font/ and see there are no colons
Fixes #500

removed color from font settings doc

---

docs/base/_lists.md
scss/_base_lists.scss

- Added the default definition list styling
- Check out lists in vf.io 
- At the bottom there should be definition list 
- Check the styling matches the basic style 
- Issue: https://github.com/ubuntudesign/vanilla-framework/issues/350
- Design: https://jujucharms.com/wordpress/#charm-config-debug

Define default definition list style

---

docs/layout/_number-word.md

Removed the documentation file for number word
See that the file is gone
Fixes https://github.com/ubuntudesign/vanillaframework.io/issues/25

remove number word docs

---

scss/_base_typography.scss
scss/_settings_font.scss

Change font inclusion to load from Google Fonts.
Google Fonts is more efficient at font loading and provides fonts based ont he web browser making the request. Previously this caused font errors, and we should check how it reacts in a non Ubuntu system.
When Ubuntu is not available, I have changed the default font family to load relevant system fonts from the user's OS.
- Ensure Ubuntu font loads correctly, especially in non Ubuntu OS
Fixes #462

change font inclusion and default family.

---

scss/_utilities_floats.scss
scss/_utilities_margin-collapse.scss
scss/_utilities_off-screen.scss
scss/_utilities_padding-collapse.scss
scss/_utilities_text-center.scss
scss/_utilities_vertically-center.scss
scss/_utilities_visibility.scss

With new sass linting, `no-important` rule has been globally set so individually exempting this rule in each util is no longer required.
Check that tests still pass.

Delete redundant sass-lint:disable no-important

---

docs/base/_links.md
scss/_base_links.scss

- Set the border-bottom colour and changed the transition to only the border-color.
- Add base link documentation
- Check out branch in vf.io
- Go to http://localhost:3000/base/links/
- Check link works fine on hover and outline
- Issue: https://github.com/ubuntudesign/vanilla-framework/issues/484

Base link improvements

---

scss/_patterns_footer.scss

- Fixed the font-sizes of the footer
- Load into vf.io
- Go to `http://localhost:3000/patterns/footer/`
- Check the font-size of the copyright text and links are 13px
- Check on small screens they are 12px
- Issue: https://github.com/ubuntudesign/vanilla-framework/issues/508

Update footer pattern

---

scss/_layout_clearfix.scss
scss/_patterns_breadcrumbs.scss
scss/_patterns_strip.scss
scss/_utilities_off-screen.scss
scss/_utilities_vertically-center.scss

Split out drive-bys which resolve linting warnings, largely by reordering sort order.
Check that the warnings for this files disappear by running `gulp test`

Hygiene: Fix up linting warnings

---

docs/base/_forms.md
scss/_base_forms.scss

- Remove margin-bottom on check elements so they stack nicely
- Go to http://localhost:3000/base/forms/
- Check all tick elements are aligned nicely on small screens
- Check it doesnt look like http://vf.demo.haus/base/forms/ on small screens
- Fixes: https://github.com/ubuntudesign/vanillaframework.io/issues/44

Fix stacking checkboxes

---

docs/patterns/_notification.md

- Added extra space below notification for small screens
- Documented the action area separately
- Go to http://localhost:3000/patterns/notification/
- Check the notifications dont go over the text on small screens
- Check the action documentation at the bottom of the page is correct
- Fixes: https://github.com/ubuntudesign/vanillaframework.io/issues/43

Move action documentation to a separate section

---

docs/patterns/_navigation.md
scss/_patterns_navigation.scss

Fixes https://github.com/ubuntudesign/vanilla-framework/issues/538
QA
---
Run with vanillaframework.io, check `http://localhost:3000/patterns/navigation/` in small screen size.
Practice collapsing and expanding the menu until you've got it down.

CSS only collapsible menu in small screen.

---

.gitignore
README.md
run

This means you don't need to install NPM, or node, or worry about which versions of these you have.
You also don't need to worry about doing `npm install` - the docker image will detect whether packages are up-to-date and re-install if anything has changed.
The only dependency is docker. Try it out.
QA
---
Try:
``` bash
./run -h
./run usage
./run gulp
./run gulp test
./run gulp build
./run gulp watch
```

./run script to run node commands (e.g.: gulp) inside a docker container to manage dependencies

---

docs/patterns/_navigation.md
scss/_patterns_navigation.scss

Closes #486.
To support either of the possible alternative markup forms, either using a `<ul>` or wrapping each anchor in a `<div>`, all we have to do is remove all padding and margin from those elements and make the `display: inline-block`.
As this is a common feature that you might want to do on any block-level element, I've made a utility class, `u-inline-block`, to achieve this. Although I'm not sure if we might want to expand this class to remove more than just padding and margin - e.g. we might want to do `border: 0` or `list-style-type: none`. Or is that gold-plating for now?
I have only given an example of the `<ul>` form of the markup, because I think that's the more common one, and if anyone wanted to use the `<div>` form, it would be pretty obvious how to do it from the `<ul>` …

Navigation: Support alternative markup format

---

scss/_layout_clearfix.scss
scss/_patterns_image-grid.scss
scss/_patterns_navigation.scss
scss/_vanilla.scss

- Changed clearfix so it can be extended via a placeholder as the linter dictates.
- Replaced any examples where clearfix is extended via class with placeholder
- Check code still builds
- QA with vf.io

Extend clearfix via placeholder, not class

---

.sass-lint.yml
scss/_base_forms.scss

- Re-order source order
- Also disabled  `no-universal-selectors` in sass-lint.yml as we use universal selectors in several places.
Check code

Lint base forms

---

scss/_base_typography.scss

Re-ordered source order - there are three warnings here unresolved as they are exceptions to the rule;
```
9:3  warning  * (universal) selectors are not allowed  no-universal-selectors
10:5  warning  Vendor prefixes should not be used       no-vendor-prefixes
11:5  warning  Vendor prefixes should not be used       no-vendor-prefixes
```
Check code

Lint base typography

---

.travis.yml

Change travis IRC alert settings
- The notifications are getting a little spammy in #vanilla-framework, so change to only notify when the build changes
- It would also be nice to get build alerts in #canonical-webteam, if they're not too spammy
- Remove ducksboard notifications - ducksboard is dead

Change travis IRC alert settings

---

scss/_base_typography.scss
scss/_settings_font.scss

Revert font inclusion changes, as Ubuntu light does not display correctly.
We need to investigate our font options at a later time.
Check that Ubuntu font loads correctly, confirming Ubuntu light looks correct.

Revert font inclusion changes

---

scss/_patterns_card.scss

Go to Patterns > Card in docs, scroll to Card highlighted and check it has an rgba box-shadow

Add back rgba for drop shadow

---

scss/_patterns_card.scss

Moved border from placeholder to card so it doesn't appear in card highlighted
Go to Patterns > Card and verify if both cards still have correct styling, and card highlighted has no border, only drop shadow.

Remove border from placeholder

---

scss/_base_lists.scss
scss/_vanilla.scss

- Added the block namespace to the vf mixin
- Included into the vanilla package
- Load in vf.io
- Go to http://localhost:3000/base/lists/
- Check that the lists look so ... so nice!
- Fixes: https://github.com/ubuntudesign/vanilla-framework/issues/610

Added base lists to include

---

docs/patterns/_strip.md
scss/_patterns_strip.scss

- Make default text colour on dark strip backgrounds $color-light
- Pull code
- Test on vf.io
Fixes #645

Add light text to dark strip

---

scss/_base_code.scss

Unfortunately, `scroll:auto` on `<pre>` tags does not work as expected when the `<pre>` tag has a width of 100%, it needs an explicit value.
This means that by default we have to use `white-space: pre-wrap` to ensure we don’t break the layout on small screens where a long piece of code is displayed within a `<pre>` block.
Check base/forms on vf.io and ensure that code blocks scale down as screen width declines.
Fixes #627

Make default code blocks responsive

---

docs/utilities/_equal-height.md
scss/_utilities_equal-height.scss

- Make equal height docs use theme outline class
- Add flex 1 to make equal height items fill their parent by default 
- Check code
- Sync vf.io and test util
Fixes #598

Fix up equal height docs to use theme outlines

---

docs/settings/_color-settings.md
scss/_settings_colors.scss

Tweak colours to reflect accessible palette as documented here: http://ubuntudesign.github.io/style-guides-content/vanilla/colours.html
- Cross reference new color hex code with the link above. 
- Ensure build still runs without error.
Fixes #489

Accessible colors

---

scss/_patterns_navigation.scss

Remove specificity from navigation pattern as this makes it more difficult to override further downstream. Element selectors should also not be used in the patterns layer, BEM class names should only be applied directly on the link and styled accordingly.
Test navigation pattern still works as expected across breakpoints.

Remove specificity from navigation pattern

---

scss/_base_forms.scss

Give checkboxes and radio button min-height to stop them misaligning on small screens.
Test radio buttons and checkboxes in vf.io on devices and across breakpoints
Fixes #550

Give checkboxes and radio button min-height

---

docs/patterns/_links.md
scss/_patterns_links.scss

Fixes #692
This should make the external link work much more intuitively by making it an inline element.
QA
--
See the new `/patterns/links/` documentation page - the external link icon should no longer overlap with the element next to it.

Simplify and fix p-link--external

---

scss/_base_tables.scss

Update overflow to `auto` to avoid scroll bars showing when they aren't needed in Ubuntu on small screen.
Look at tables in small screen in Ubuntu. Should no longer look like this:

Update default overflow on tables to "auto"

---

docs/patterns/_links.md
scss/_patterns_links.scss

- Add `.p-link--no-underline` class for image links
- Also correct text typos in other examples
- Sync with vf.io by going to /patterns/links/
- Check 'Link without underline' image example does not underline 
Fixes #702

Add .p-link--no-underline class for image links

---

README.md

- Remove project homepage links as it no longer exists
- Correct documentation link to point at https://docs.vanillaframework.io
Check cross docs for link change
Fixes: #698

Update docs link on README

---

docs/base/_typography.md

This value in the docs was incorrect but also, this value changes per breakpoint so cannot be represented via a single value. 
The range of font sizes across breakpoints is displayed in a table further down the page so I've removed this explicit static value.
Check code and ensure nothing has been removed that should not have bee removed.
Fixes: https://github.com/ubuntudesign/vanilla-framework/issues/708

Remove explicit font sizes from docs

---

scss/_patterns_strip.scss

Change default `.p-strip` to transparent as it should not be the same bg color as `.p-strip--light` as it is currently.
Check code
Fixes: #723

Change default .p-strip to transparent

---

scss/_patterns_strip.scss

This change will allow content to be sensibly spaced using just strips with the grid.
This change means that strips will have a bottom spacing of 2rem except when a strip pattern with a coloured background follows a strip pattern with a coloured background. This is because these strips have inherent padding and no bottom margin is needed.
To see this in action, see this Codepen: http://codepen.io/barrymcgee/pen/VPayrj
- Pull code
- Build Vanilla
- Include built CSS into a empty webpage 
- Copy markup from the Codpen above into it
- Ensure that none of the strips butt against each other.
- Switch and change the order of the strips and check webpage again.
Fixes: #734

Add spacing between .p-strip pattern

---

scss/_patterns_grid.scss

This rule was conflicting with default grid behaviour on small screen resolutions. 
This was introduced before v1 launch in an attempt to address the "double margin" issue that can appear when elements with bottom margin and top padding appear next to each other. 
I now this think would be better addressed at a component level rather than try to apply a catch all rule.
- Check code and ensure it's fully removed.
Fixes: #740

Remove collapsing margins on last-child elements

---

scss/_patterns_footer.scss

The footer [attern should not require extra markup or styling to work straight out of the box. This change gives it a default 1rem of bottom margin ensuring it does not butt off the edge of the viewport.
- pull down code
- run `gulp test` to lint code
- run docs.vf.io and navigate to 'footer' to test in-situ 
Fixes: #738

Add inherent bottom margin to .p-footer

---

scss/_patterns_lists.scss

Changed position of background image providing list tick icon so that it stays at the top left, regardless of how deep the list item expands.
- Sync with docs.vf.io
- Navigate to /patterns/lists/
- Scroll down to 'List with icons and dividers' section
- Edit a list item to increase text content so it wraps over multiple lines
- Observe that the tick remains static
Fixes: #726

Ensure list tick icon stays anchored to top left of item

---

scss/_patterns_lists.scss

Amended tick list rule to separate icon alignment between a standard list and a list with dividers which requires more spacing.
- Pull code and use this page to test the two different examples:
```html
<html>
<head>
</head>
<body>
<section class="p-strip">
<ul class="list">
<li class="p-list__item">Lorem</li>
<li class="p-list__item">Ipsum</li>
<li class="p-list__item">Dolor</li>
</ul>
</div>
</section>
<section class="p-strip">
<ul class="p-list">
<li class="p-list__item is-ticked">Lorem</li>
<li class="p-list__item is-ticked">Ipsum</li>
<li class="p-list__item is-ticked">Dolor</li>
</ul>
</div>
</<section>
<section class="p-strip">
<ul …
```

Fix ticked list icons alignment

---

scss/_patterns_inline-images.scss

Restrict width of images in `.p-inline-images`
- Pull and sync code
- Create `demo.html`
- Test using the following markup:
```html
<html>
<head>
</head>
<body>
<div class="p-strip">
<h2>Inline images</h2>
<div class="p-inline-images">
</div>
</div>
</div>
</body>
</html>
```
Fixes #724

Restrict .p-inline-images items width

---

.gitignore
docs/patterns/_headings.md
scss/_base_typography.scss
scss/_patterns_headings.scss
scss/_vanilla.scss

Add heading classes so text elements can mirror the appearance of semantic headings.
- Pull code
- Check docs entry makes sense
- Use this demo markup to test CSS classes
```html
<html>
<head>
</head>
<body>
<div class="p-strip">
<p><strong>Semantic markup without classes</strong></p>
<h1>Heading one</h1>
<h2>Heading two</h2>
<h3>Heading three</h3>
<h4>Heading four</h4>
<h5>Heading five</h5>
<h6>Heading six</h6>
</div>
</div>
<hr>
<div class="p-strip">
<p><strong>Semantic markup with overriding heading classes to alter visual weight</strong></p>
<h6 class="p-heading--one">Heading six</h6>
<h5 class="p-heading--two">Heading five</h5>
<h4 …
```

Add heading classes to mirror semantic headings

---

docs/utilities/_equal-height.md
scss/_utilities_equal-height.scss

This util should not dictate the width of it’s immediate children. This changeset fixes this.
-  Pull code
- Create demo.html and use the following markup to verify changes:
```html
<html>
<head>
</head>
<body>
<div class="p-strip">
<div class="row u-equal-height theme__outline">
<div class="col-8 theme__outline--inner" style="outline: 2px solid pink">
<p>This is a long paragraph of text - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at elit augue. Maecenas eleifend varius leo id facilisis. Nunc sit amet hendrerit nisl. Fusce posuere bibendum mi dignissim venenatis. Ut ornare quis velit ac lobortis. Vestibulum faucibus tortor hendrerit viverra. Maecenas in molestie …
```

Fix .u-equal-height width bug

---

scss/_base_forms.scss
scss/_base_typography.scss
scss/_patterns_card.scss
scss/_patterns_notifications.scss

Added sass-lint ignore rules to SCSS where we need to violate the linter but have no other choice. I've also added a note at each instance to explain why.
- There should be no warnings
Fixes #781

Add sass-lint ignore rules to remove warnings

---

docs/patterns/_inline-images.md
scss/_patterns_navigation.scss

Updated the navigation documentation to demo the markup using a list. This required a number of fixes for the navigation code base. As I fly by, I also update the markup in the docs for `inline-images` component to use a list.
- Create a demo.html with the example markup
- Run gulp develop
- Open the demo.html
- Check that the navigation works well on all screen sizes
- Check the inline-images also display correctly
- Change the markup in demo.html to match the current example in docs
- https://docs.vanillaframework.io/patterns/inline-images/
- https://docs.vanillaframework.io/patterns/navigation/
- Check that version also works well
Fixes https://github.com/ubuntudesign/vanilla-framework/issues/749
```html
<html>
<head>
<link rel="stylesheet" type="text/css" …
```

Update documentation demos for navigation and inline-images to use lists

---

docs/base/_table.md
docs/utilities/_text-align.md
scss/_utilities_content-align.scss
scss/_vanilla.scss

Updated the align utilitie class names from `u-text-align` or `u-content-align` due to the natural of css alignment aligning more then just text.
- Create a demo.html with the example markup
- Run gulp develop
- Open the demo.html
- Check that the classes do what they say they do
- Double check I have caught all renames
Fixes https://github.com/ubuntudesign/vanilla-framework/issues/794
```html
<html>
<head>
</head>
<body>
<div class="u-align--center theme__outline">
<p class="theme__outline--inner">I am centered text.</p>
</div>
<div class="u-align--left theme__outline">
<p class="theme__outline--inner">I am centered text.</p>
</div>
<div class="u-align--right theme__outline">
<p …
```

Change the align utilities class names

---

scss/_patterns_grid.scss

- Add margin-bottom to columns on small screens
- Create a `demo.html` with the example markup
- Run `gulp develop`
- Open the `demo.html`
- See that there is no margin between columns on when the grid displays columns side by side
- Scale the screen down until the columns stack
- See that the columns now have margin between them
For what it's worth, I did check how Shelves do this themselves to see if we weren't missing something. They add margin to the bottom of their columns themselves by is not added to the distributed grid.
```css
[class*="column-"] { 
margin-bottom: 1.47059em; 
}
```
Issue filed upstream: https://github.com/typeimage/shelves/issues/5
Fixes https://github.com/ubuntudesign/vanilla-framework/issues/764
```html
<html>
<head>
<link rel="stylesheet" …
```

Add margin-bottom to columns on small screens

---

scss/_patterns_footer.scss

Update `.p-footer link` colors falling out of base link changes in #717
- Pull code
- Check with following markup
```css
<html>
<head>
</head>
<body>
<footer class="p-footer" role="contentinfo">
&copy; 2016 Company name and logo are registered trademarks of Company Ltd.
<nav role="navigation">
<ul class="p-footer__links">
<li class="p-footer__item">
<a class="p-footer__link" href="#">Footer link 1</a>
</li>
<li class="p-footer__item">
<a class="p-footer__link" href="#">Footer link 2</a>
</li>
<li class="p-footer__item">
<a class="p-footer__link" href="#">Footer link 3</a>
</li>
<li class="p-footer__item">
<a class="p-footer__link" href="#">Footer link 4</a>
</li>
</ul>
<span …
```

Update .p-footer link colors

---

docs/utilities/_align.md

Rename file and doc title to remove specific reference to 'text'
Related #795

Rename _text-align.md to _align.md

---

jekyll/index.html

Added `<nav>` elements around the navigation and added `p-link--soft` to the links as this is to be used for navigation. Displayed the lists horizontally so it is easier to view without scrolling.
- Open http://127.0.0.1:4000/
- See that the lists are in columns
- Check the lists are wrapped in a nav element
- Check the links are now `p-link--soft`
Fixes https://github.com/ubuntudesign/vanilla-framework/issues/804

Update examples index layout

---

_config.yml

This parser is deprecated and surplus to requirements as we don't use markdown for examples

Remove custom markdown parser from _config.yml

---

_jekyll/_layouts/default.html

Remove wrapping grid from the example template
- Run `gulp develop`
- Open some examples up in the browser
- See that they still look ok

Remove wrapping grid from the example template

---

scss/_patterns_lists.scss

This list style is no longer needed here as it was brochure specific and has been moved downstream to the vanilla-brochure-theme.
Sanity check code.
Fixes #812

Remove vf-p-combined-list as no longer needed

---

docs/base/_code.md

Check the intro paragraph of Base > Code

Remove word 'sample' from code pattern doc

---

docs/en/patterns/buttons.md
scss/_base_button.scss
scss/_patterns_code-snippet.scss

(This was previously opened as #846 but due to rebasing bork, that PR is no longer showing changes)
- Allow base button to sit inline with text
- Edit `examples/button.html` to add a chunk of inline text before the button element, like so;
```html
<span>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</span><button>Button</button>
```
- View in browser: `http://127.0.0.1:4000/vanilla-framework/examples/base/button/` 
Fixes: #737

Allow base button to sit inline with text

---

scss/_patterns_card.scss

- Changed color of borders to `$color-mid-light`
- Correct padding so it is 20px through breakpoints
- Pull code
- Go to `http://127.0.0.1:4000/vanilla-framework/examples/patterns/card/card/`
- Go to `http://127.0.0.1:4000/vanilla-framework/examples/patterns/card/highlighted/`
- Cross-ref with[ design spec](http://127.0.0.1:4000/vanilla-framework/examples/patterns/card/highlighted/)
Fixes #843

Update .p-card to match design spec

---

scss/_base_links.scss
scss/_patterns_links.scss

- Switch bottom border on links to text-decoration
- Pull code
- Run `jekyll gulp`
- Go to:
- http://127.0.0.1:4000/vanilla-framework/examples/patterns/links/links-back-to-top/
- http://127.0.0.1:4000/vanilla-framework/examples/patterns/links/links-external/
- http://127.0.0.1:4000/vanilla-framework/examples/patterns/links/links-inverted/
- http://127.0.0.1:4000/vanilla-framework/examples/patterns/links/links-soft/
- http://127.0.0.1:4000/vanilla-framework/examples/patterns/links/links-strong/
- Check they all display in accordance with the [design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Links)
Fixes #840

Switch bottom border on links to text-decoration

---

scss/_base_button.scss

Give inline button margin-top on small screens
- Test the following markup on small screens in the button example page
```html
<span>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</span>
<button>Button</button>
```
The space between the button and inline text should be `1.2rem`, just as it would be if the `<span>` was a `<p>`
Fixes #855

Give inline button margin-top on small screens

---

.travis.yml

Remove tablet snapshot from Percy command
Sanity check code, no QA required as we're currently over Percy quota so cannot be tested

Remove tablet snapshot from Percy command

---

scss/_patterns_footer.scss
scss/_patterns_lists.scss

Prevent text-decoration:underline leaking into :after pseudo element
- Navigate to [http://127.0.0.1:3002/vanilla-framework/examples/patterns/footer/](http://127.0.0.1:3002/vanilla-framework/examples/patterns/footer/)
- Roll over liks in footer and ensure no borders appear below the dots
Before: https://cl.ly/3J3f102f1f2b
After: https://cl.ly/2p473V1A1L0e
Fixes #799

Prevent text-decoration:underline leaking into :after

---

_jekyll/_layouts/default.html

This means that mobile views can now be tested correctly.
- Pull code
- Go to a specific pattern, e.g. http://127.0.0.1:4000/vanilla-framework/
- Use a tool like Viewport Resizer to test that when on small screens, the patterns responds correctly.
Fixes #847

Add viewport zoom to example template

---

examples/patterns/breadcrumbs.html
scss/_patterns_breadcrumbs.scss

Update breadcrumb pattern to work with lists
- Pull code
- Check [http://127.0.0.1:4000/vanilla-framework/examples/patterns/breadcrumbs/](http://127.0.0.1:4000/vanilla-framework/examples/patterns/breadcrumbs/)
Fixes #827

Update breadcrumb pattern to work with lists

---

examples/patterns/links/links-external.html
examples/patterns/links/links-inverted.html
examples/patterns/links/links-soft.html
examples/patterns/links/links-strong.html
examples/patterns/links/links-without-underline.html
scss/_patterns_links.scss

- Ensure all link examples have a `href` attribute
- Prevent `:visited` color from overriding `:hover` color on `.p-link--soft`
- Pull code & `gulp jekyll`
- Check [example](http://127.0.0.1:4000/vanilla-framework/examples/patterns/links/links-soft/#) against [spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Links)
Fixes #811

811 soft link override

---

_config.yml
docs/en/patterns/form-validation.md
examples/base/forms/input.html
examples/patterns/form-validation.html
scss/_base_forms.scss
scss/_patterns_form-validation.scss
scss/_vanilla.scss

- Added form validation pattern
- Pull code
- Compare [examples](http://127.0.0.1:4005/vanilla-framework/examples/patterns/form-validation/) to the [design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Forms)
Note: The spec states the icons should be 12px from the bottom - in practice, this is not enough:
As they also need to work `<textarea>` elements also, I have vertically centred the icons instead.
Fixes #797

Add form validation pattern

---

scss/_patterns_pull-quotes.scss

Tweaked the spacing around the first quote in the pull quote pattern.
- Go to http://localhost:4321/vanilla-framework/examples/patterns/pull-quotes/
- Check the spacing now matches the [design spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Pull%20quote/pull-quote.png)
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/904

Adjust the spacing of the pull quote

---

docs/en/base/forms.md
docs/en/base/typography.md
docs/en/patterns/buttons.md
docs/en/patterns/form-validation.md
docs/en/patterns/headings.md
docs/en/patterns/notification.md
docs/en/patterns/pull-quote.md
docs/en/utilities/vertically-center.md

Found that example links without trailing slashes load over http. I'm not 100% sure why as they are linking to https. This will now make all available examples work.
- This is a strange one to QA but go to https://docs.vanillaframework.io/en/base/forms.
- Inspect the first example link
- Add a trailing slash to the href `https://vanilla-framework.github.io/vanilla-framework/examples/base/forms/form/`
- Switch to the console and run the follow command to retrigger example-js: `document.querySelectorAll('.js-example').forEach(renderExample);`
- See that the example loads correctly.
Fixes https://github.com/ubuntudesign/docs.vanillaframework.io/issues/73

Add trailing slashes to example links

---

examples/patterns/form-validation.html
scss/_patterns_form-validation.scss

- Changed icon position on form validation so it is 12px from top, not 50%
- Tweaked example to move `<textarea>` example inside form element
- Pull code & run `gulp jekyll`
- Compare [example](http://127.0.0.1:4000/vanilla-framework/examples/patterns/form-validation/) with [spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Forms/forms.png)
Fixes #912

Form validation tweaks

---

docs/en/base/typography.md
docs/en/patterns/headings.md
examples/patterns/headings/default.html
examples/patterns/headings/mixed.html

- Remove heading examples from base typography
- Clarify headings pattern and explain and how heading classes can be used on different head elements
- Pull code
- Review docs changes
- Review http://127.0.0.1:4000/vanilla-framework/examples/patterns/headings/default/
- Review http://127.0.0.1:4000/vanilla-framework/examples/patterns/headings/mixed/
Fixes #881 #831 #878

Update heading docs

---

examples/patterns/breadcrumbs.html
scss/_patterns_breadcrumbs.scss

Amended breadcrumb styling to match spec
- Pull code
- Compare [example](http://127.0.0.1:4000/vanilla-framework/examples/patterns/breadcrumbs/) to [spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Breadcrumbs)
Fixes #828

Fix up breadcrumb links

---

docs/en/patterns/headings.md

Add trailing slashes to heading doc examples
- Visually check the links have trailing slashes
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/941

Add trailing slashes to heading doc examples

---

examples/patterns/links/links-external.html

Spoace external links example using `<p>` instead of `<br>`
Check code
Fixes #946

Space external links example using <p> instead of <br>

---

docs/en/utilities/align.md

Fix broken align example link
Check the link goes to the example
Currently the example link at https://docs.vanillaframework.io/en/utilities/align goes to https://vanilla-framework.github.io/vanilla-framework/examples/utilities/content-align/ which doesn’t exist, it should go to https://vanilla-framework.github.io/vanilla-framework/examples/utilities/align/

Fix broken align link

---

examples/utilities/align.html
examples/utilities/clearfix.html
examples/utilities/equal-height.html
examples/utilities/floats.html
examples/utilities/margin-collapse.html
examples/utilities/off-screen.html
examples/utilities/vertically-center.html
scss/_patterns_card.scss

Updated example markup for utils with cards to demo their effects more visually.
Note: I had to alter the styles of `.p-card` itself to use it in this context:
- Add inherent bottom margin of 1rem to a card
- Remove bottom margin from nested cards
- Pull code
- View each of the utils at http://127.0.0.1:4000/vanilla-framework/
Fixes #942 #939

Use .p-card pattern to demo utils in docs

---

docs/en/patterns/grid.md
examples/patterns/grid/default.html
examples/patterns/grid/empty-columns.html
scss/grid/shelves.scss

- Removed redundant `.theme__outline` class
- Updated styles to include grid outline helper
- Clarified explanation docs around prefix/suffix
- Pull code
- Check grid examples
- Check docs
Fixes #853

853 Update grid docs

---

docs/en/base/typography.md

So that the table will be treated predictably by different markdown
parsers, we should add preceding and following pipes (`|`) to each line.
In my opinion this also makes it look more like a table in text as well.
I've also normalised spacing, so it looks even more like a table.
Fixes https://github.com/ubuntudesign/docs.vanillaframework.io/issues/71
QA
--
1. See the [GitHub page in my branch](https://github.com/nottrobin/vanilla-framework/blob/71-typography-tabls/docs/en/base/typography.md), check that GitHub displays the table correctly.
2. Check the page renders properly as documentation:
``` bash
snap install documentation-builder
documentation-builder --source-folder docs
```
Now open up `build/en/base/typography.html` in your browser, and see that the table looks right, with the …

Reformat typography table markdown

---

.sass-lint.yml
scss/_settings_system.scss
scss/_utilities_deprecate.scss
scss/_vanilla.scss
scss/deprecate/index.scss

Added deprecate by Salesforce as an external dependency and wired it up. Created a system_settings file which currently only contains the current latest version number. I am aware this adds to the publishing process by think it's valuable to have. 
- Pull down branch
- Run `gulp test` and check there are no errors
- Run `gulp build` and check there are no errors
- Update the buttons pattern with the snippet below:
```scss
@include deprecate('1.1.10', 'We do not support button-brand anymore') {
@include button-brand;
}
```
- Run `gulp build` and see a warning of deprecation
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/956

Add deprecate dependency to allow safe deprecation of patterns

---

scss/_base_images.scss
scss/_base_media.scss
scss/_vanilla.scss

- These base images were being imported but not included.
- Deleted the separate images file and moved into `_base_media.scss` with related <figure> styles
- Ensure no error

Switch redundant img styles into media include

---

examples/patterns/code-numbered.html
scss/_patterns_code-numbered.scss

Refactor styling to .p-code-numbered
- Pull code
- Check [example](http://127.0.0.1:4000/vanilla-framework/examples/patterns/code-numbered/) against the [spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Code/code.md)
Fixes #856

Refactor styling to .p-code-numbered

---

README.md

This option does not work due to unresolved issue with ./run scripts.

Remove ./run start instructions from README

---

scss/_patterns_links.scss

Removed nested mixin declaration from _patterns_links.scss. A fix to node-sass has made this illegal: https://github.com/sass/node-sass/issues/1459
- Pull code
- Run `sass --no-cache --style=extended scss/build.scss build/css/build.scss`
- Ensure no errors
Fixes #1016

Remove nested mixin declaration from _patterns_links.scss

---

scss/_global_functions.scss
scss/_patterns_buttons.scss

Add contrast-text-color function on `.p-button--brand` so dark buttons don't have dark text and vice-versa
- View http://127.0.0.1:4000/vanilla-framework/examples/patterns/buttons/brand/
- Change `$color-brand` to a dark color like `#000`
- Observe the button text color change to a light color
Fixes #991

Add contrast-text-color function on .p-button--brand

---

.travis.yml

Becuase the #travis slack room no longer exists. Also deleting #canonical-webteam room ping as it's pretty much redundant.

Update travis.yml to point at #general slack room

---

docs/metadata.yaml

- Added ref to Vanilla logo
- Added favicon ref
- Removed site title
- Pull this branch
- Run local docs
- Check lcoal site for logo and favicon
Fixes https://github.com/ubuntudesign/docs.vanillaframework.io/issues/85,
Fixes https://github.com/canonical-websites/vanillaframework.io/issues/12

Add logo and favicon src to docs metadata

---

docs/en/patterns/links.md
examples/patterns/links/links-without-underline.html
scss/_patterns_links.scss

- Deprecated redundant `.p-link--no-underline`
- Added examples to docs of soft, strong & inverted link patterns
- Run local docs and check those examples are imported
Fixes #984, Fixes #983

Update links example

---

docs/en/settings/color-settings.md
docs/en/utilities/vertically-center.md
examples/patterns/inline-images.html
gulp/lint.js
scss/_patterns_inline-images.scss

Updated the inline-images pattern to match the image sizes as closely as possible using the spacing variables. Deprecated the `__img` element as it doesn't always target the image. Created `__item` as a generic replacement.
- Pull code and run `gulp jekyll`
- Go to http://127.0.0.1:4000/vanilla-framework/examples/patterns/inline-images/
- Check that the logos are similar to the spec with the following caveat (padding: 48px as its the largest spacing we have)
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1039

Update inline images pattern

---

scss/_patterns_navigation.scss

Removed margin-bottom from the navigation pattern
- Pull code and run `gulp jekyll`
- Go to http://127.0.0.1:4000/vanilla-framework/examples/patterns/navigation/fixed-width/
- Check that the navigation no longer has margin-bottom
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/982

Remove margin from navigation pattern

---

docs/en/base/forms.md
docs/en/patterns/form-validation.md
docs/en/patterns/notification.md
docs/en/settings/color-settings.md
examples/patterns/form-validation.html
examples/patterns/notifications/caution.html
scss/_patterns_form-validation.scss
scss/_patterns_notifications.scss
scss/_settings_colors.scss
scss/_vanilla.scss

Renamed warning to caution and deprecated the warning classes and colour.
- Pull down code and run `gulp jekyll`
- Go to http://127.0.0.1:4000/vanilla-framework/examples/patterns/notifications/caution/
- Check that the notification is now caution, not warning.
- Check the documentation is correct
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/979

Rename warning to caution

---

scss/_base_button.scss

Added an override to the external icon in the button pattern. Put the media query above children selectors.
- Pull code and run `gulp jekyll`
- Add to the examples/button/base.html:
```html
<a href="" class="p-button--base">
<span class="p-link--external">
External button
</span>
</a>
<a href="" class="p-button--positive">
<span class="p-link--external">
External button
</span>
</a>
```
- Go to http://127.0.0.1:4000/vanilla-framework/examples/patterns/buttons/base/
- Check the external link is the same color as the text
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1025

Buttons with external links have incorrect colour

---

scss/_patterns_form-validation.scss

Replace caution icon image 
The current .is-caution image being request in _patterns_form-validation.scss doesn’t exist and is causing the Travis CI checks on developer.ubuntu.com https://travis-ci.org/canonical-websites/developer.ubuntu.com/builds/226822666?utm_source=github_status&utm_medium=notification 
The image being requested should have been this one https://assets.ubuntu.com/v1/c41194d3-icon-warning.svg
For the sake of consistency in naming I’ve uploaded a new image to the asset manager
Check that the new image https://assets.ubuntu.com/v1/db30f04c-icon-caution.svg exists and that it’s the same as https://assets.ubuntu.com/v1/c41194d3-icon-warning.svg, also check that it’s being requested in  _patterns_form-validation.scss

Caution icon 404 travis checks fix

---

scss/_base_typography.scss

Set the base font size to always be the font-base-size across all breakpoints.
- I believe this review is just a code review
- Then check the percy output to see if anything has broken
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1053

Remove the base font size change on small screens

---

docs/en/base/typography.md
scss/_base_typography.scss
scss/_settings_font.scss

Added the ability to import Cyrillic, Greek and Latin fonts which are enabled via a font setting.
- Pull branch and run `./run`
- Edit the `headings.md ` file in docs by changing the text of one of the headings to "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧ"
- Go to http://0.0.0.0:8101/vanilla-framework/examples/base/headings/
- Inspect the heading and go to computed styles and scroll to the bottom and see what the rendered font is. Check it's not Ubuntu.
- Add the following to line 46 of `_base_typography.scss`
``` scss
$font-allow-cyrillic-greek-latin: true;
```
- Refresh the headings page and see the Cyrillic font is rendered by Ubuntu
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/699

Add support for Cyrillic, Greek and Latin fonts

---

docs/en/utilities/vertically-center.md
scss/_utilities_vertically-center.scss

Limited the vertical align utility to medium and large screens. Added a note to the documentation of the vertical align utility.
- Pull branch and run `./run serve`
- Go to http://0.0.0.0:8101/vanilla-framework/examples/utilities/vertically-center/
- Check that is works as before
- Scale to small screen and see that item is no longer vertically aligned
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1110

Vertically center should not affect all breakpoints

---

scss/_base_button.scss

Changed the default button styling to match the neutral button styling. Updated the button animation to use the new animation mixin.
- Pull this branch and run `./run`
- Go to http://0.0.0.0:8101/vanilla-framework/examples/base/button/
- Check that is matches the [neutral spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Buttons/buttons.md#common)
- See that the background transition on hover.
- Check the other button are not affected.
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1097
http://vanilla-framework-default-button.demo.haus/vanilla-framework/

Update default button styling to neutral

---

examples/patterns/lists/lists-stepped.html
scss/_patterns_lists.scss

Refactor and fix the bullet number alignment issue.
- Pull down this branch
- Run `./run`
- Go to http://0.0.0.0:8101/vanilla-framework/examples/patterns/lists/lists-stepped/
- Check that the 99 is aligned in the bullet
- Check that the stepped list pattern looks the same as the live version at https://vanilla-framework.github.io/vanilla-framework/examples/patterns/lists/lists-stepped/
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1105
Partly fixes https://github.com/vanilla-framework/vanilla-brochure-theme/issues/81

Align double digit stepped list

---

scss/_settings_breakpoints.scss

Quick fix to add the missing semi colon to the breakpoint settings.
- Check code and maybe see Vanilla runs fine.

Add the missing semi colon to the breakpoint settings

---

README.md

Update README to reflect new local dev port
- Pull code
- Check you can view site at http://0.0.0.0:8101/vanilla-framework/
Fixes #1096

Update README to reflect new local dev port

---

.gitignore
docs/en/metadata.yaml
docs/en/settings/spacing-settings.md

Add docs for spacing settings
- Pull code
- Build and view docs as per https://github.com/vanilla-framework/vanilla-framework#building-documentation-pages
- Check that 'Settings  > Spacing' section is correct and reflects https://github.com/vanilla-framework/vanilla-framework/blob/develop/scss/_settings_spacing.scss
Fixes #1048

Add docs for spacing settings

---

Gemfile
Gemfile.lock
examples/patterns/navigation/dark.html
examples/patterns/navigation/light.html
scss/_patterns_navigation.scss

- Bumped jekyll gem version to 3.5.0
- Tweaked 'Menu' button on S screens to that it is always centred, regardless of how big the logo in the pattern is
- Pull code
- Go to http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/dark/
- Ensure Menu toggle is centred on small screen no matter how high you make the logo
- Go to http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/light/
- Ensure Menu toggle is centred on small screen no matter how high you make the logo
Fixes #1103

Vertically align 'Menu' toggle on S screens

---

scss/_patterns_navigation.scss

Make sure nav pattern last item has bottom border
- Pull code
- Reduce the screen width to small screen breakpoint
- Go to http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/dark/
- Open menu and verify the last item has a bottom border
- Go to http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/light/
- Open menu and verify the last item has a bottom border
Fixes #1104 
Dark: http://vanilla-framework-1104-s-screen-nav-border.demo.haus/vanilla-framework/examples/patterns/navigation/dark/
Light: http://vanilla-framework-1104-s-screen-nav-border.demo.haus/vanilla-framework/examples/patterns/navigation/light/

Make sure nav pattern last item has bottom border

---

scss/_base_forms.scss

Remove padding jump from input elements between breakpoints
- Pull code
- Go to: http://0.0.0.0:8101/vanilla-framework/examples/base/forms/input/
- Ensure there is no jump in input fields between breakpoints
http://vanilla-framework-fix-input-padding-jump.demo.haus/
This was raised as part of a review point for #1086

Remove padding jump from input elements

---

index.html
scss/_patterns_vertical-spacing.scss

Targeting single elements within rows and adding the spacing required. 
- Pull code
- Edit one of the examples with the following example:
``` html
<section class="p-strip--dark">
<h2>Title</h2>
</div>
<div class="col-6">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
</div>
<div class="col-6">
</div>
</div>
</section>
<section class="p-strip is-bordered">
<div class="col-4 p-card">
<p>Lorem ipsum dolor …
```

Add padding to single element in rows

---

examples/patterns/inline-images.html
scss/_patterns_inline-images.scss

Replace wrapping div with and unordered list
Reduce gutters
- run locally
- see the change via jekyll
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1084

Fix gutters and layout of inline images pattern

---

scss/_patterns_navigation.scss

Remove header top margin introduced with the new vertical rhythm https://github.com/vanilla-framework/vanilla-framework/pull/1095
[See issue 1140 for details](https://github.com/vanilla-framework/vanilla-framework/issues/1140) 
Fixes #1140

Remove header top margin

---

docs/en/index.md

Fixes #1139.
After some discussion on [a PR](https://github.com/vanilla-framework/vanilla-framework/pull/1136#discussion_r125323595) and in Slack it was decided that we should advise `--save-dev` instead of `--save`, because the end-user is most likely to be writing a website rather than a Sass module - and in that case they probably want to add Vanilla to `devDependencies` rather than `dependencies`. And in any case, that is simply the more cautious thing to do and therefore a better thing to recommend.

As discussed, recommend --save-dev

---

scss/_base_forms.scss
scss/_base_vertical-spacing.scss
scss/_vanilla.scss
scss/base.scss

Allow correct spacing between consecutive fieldset
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/forms/fieldset/
- Edit the example html file and copy/paste the fieldset so there are two in the page
- Verify that the space between the two consecutive fieldsets is `1.5rem`
Fixes #1081

Allow correct spacing between consecutive fieldset

---

scss/_patterns_navigation.scss

Add bottom border to L screen navigation
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/light/
- Verify bottom border on L breakpoints is correct
http://vanilla-framework-1150-nav-btn-border.demo.haus/vanilla-framework/examples/patterns/navigation/light/
Fixes #1150

Add bottom border to L screen navigation

---

scss/_base_button.scss

..thus saving 4kb of redundant CSS and making the mixin far more modular and re-usable.
- Cleaned up re-usable button CSS code to include a pattern into the mixin.
- Upon this change 4kb has been saved from the un-minified CSS and saved 20 microseconds on build.
- Pull code
- Look at all button styles and check for any regressions. Network time of the style.css file should also be improved as well as file size.
#1147

Changing the buttons mixin to use a placeholder

---

scss/_base_code.scss

User stylesheets tend to add `1em` of margin-top onto `<pre>` tags by default. This change will zero top margin on `<pre>` elements
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/code/
- Paste the following into `/examples/base/code.html`
```
<div id="getting-started" class="p-strip is-bordered is-deep"> <div class="row"> <div class="col-12"> <h2>Quick start</h2> </div> </div> <div class="row"> <div class="col-5"> <p>The recommended method of including Vanilla Framework in your project is via NPM. You can then simply include the framework in your SCSS files and compile.</p> <p>For other methods, please see the <a href="#">advanced usage docs.</a></p> </div> <div class="col-7 prefix-1">
<pre><code>npm install --save-dev vanilla-framework …
```

Zero top margin on `<pre>` elements

---

docs/en/metadata.yaml

Added themes to the docs navigation
- Pull code
- Switch over to your docs.vanillaframework.io branch
- Create a file callled `build-local` with the follow content:
```bash
echo 'Building vanilla-frameworks documentation'
documentation-builder --base-directory ../vanilla-framework/docs  \
--site-root '/en/'  \
--output-path .  \
--template-path template.html  \
--tag-manager-code 'GTM-K92JCQ'  \
--no-link-extensions \
--force
echo 'Completed vanilla-framework documentation build'
echo 'Build vanilla-brochure-theme documentation'
documentation-builder --base-directory ../vanilla-brochure-theme/docs \
--site-root '/en/vanilla-brochure-theme' \
--output-path 'en/vanilla-brochure-theme' \
--template-path template.html \
--tag-manager-code 'GTM-K92JCQ'  \
--no-link-extensions \
--force
mv …
```

Add themes to the navigation

---

scss/_base_vertical-spacing.scss

Targeting **only** single elements within rows and adding the spacing required. 
- Pull code
- Edit one of the examples with the following example:
``` html
<section class="p-strip--dark">
<h2>Title</h2>
</div>
<div class="col-6">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
</div>
<div class="col-6">
</div>
</div>
</section>
<section class="p-strip is-bordered">
<div class="col-4 p-card">
<p>Lorem …
```

Improve the single element padding

---

docs/en/metadata.yaml

Update the brochure theme link in the themes navigation
- Pull code
- `cd` to your docs.vanillaframework.io branch
- Create a file called `build-local` and add the content below:
```bash
BLUE='\033[1;34m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
echo "${BLUE}Clearing build${NC}"
rm -rf en
echo "${GREEN}Build removed${NC}"
echo "${BLUE}Building vanilla-frameworks documentation${NC}"
documentation-builder --base-directory ../vanilla-framework/docs  \
--site-root '/en/'  \
--output-path .  \
--template-path template.html  \
--tag-manager-code 'GTM-K92JCQ'  \
--no-link-extensions \
--force
echo "${GREEN}Completed vanilla-framework documentation build${NC}"
echo "${BLUE}Build vanilla-brochure-theme documentation${NC}"
documentation-builder --base-directory ../vanilla-brochure-theme/docs \ …
```

Update the brochure link in navigation

---

scss/_patterns_pull-quotes.scss

Remove color from the pull quote pattern.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/en/patterns/pull-quote
- Check the pull quote looks the same as https://docs.vanillaframework.io/en/patterns/pull-quote
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1166

Remove color from pull quotes pattern

---

scss/_base_forms.scss

Reduce specificity of base form input styling
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/buttons/brand/
- Add the following snippet to the above HTML file:
```
<input class="p-button--brand" type="submit" />
```
- Verify that the button background is $color-brand (in this case, grey)
Fixes #1080

Reduce specificity of base form input styling

---

scss/_base_forms.scss
scss/_settings_colors.scss

Remove background color rules from fieldsets
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/strips/strips-dark/
- Add a fieldset to the `.p-strip--dark` example:
```
<div class="p-strip--dark">
<fieldset>
<form class="" action="index.html" method="post">
<input type="text">
<input type="text">
<input type="text">
<input type="text">
<input type="text">
</form>
</fieldset>
</div>
</div>
```
Fixes #1113

Remove background color rules from fieldsets

---

examples/patterns/matrix.html
scss/_patterns_matrix.scss

Remove right/left padding from Matrix pattern
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/matrix/
- Check that the pattern has no right or left padding
Fixes #1066

Remove right/left padding from Matrix pattern

---

scss/_patterns_navigation.scss

- moved padding from `.p-navigation__link` to `<a>` element to make click area larger
- removed unnecessary font size change between breakpoints
- made sure to support navigation `<a>` links both nested in list elements and used directly with `.p-navigation__link` class
- Pull code
- Go to navigation example (light or dark)
- Clicking on any part of navigation item should work (not just on link text)
Fixes #1154

Making whole navigation items clickable

---

docs/en/base/code.md
docs/en/base/forms.md
docs/en/base/typography.md
docs/en/patterns/lists.md
docs/en/patterns/pull-quote.md

Updated 'Related' headings to h3's on a few pages.
- Pull code
- Check the pages referenced in https://github.com/ubuntudesign/docs.vanillaframework.io/issues/87
Before Related heading there is a `<hr />` that was present on *some* pages. I've added the `<hr />` to any that didn't have it.

Converted a mixture of styles to consistent h3s

---

scss/_patterns_breadcrumbs.scss

Changed `inline-block` into float not to depend on whitespace between inline breadcrumb items.
- Pull code
- Go to breadcrumbs example page
- Breadcrumbs should look the same as before
Removing whitespace from HTML between breadcrumb items should not affect breadcrumb spacing.
Fixes #1146

Fixed spacing of inline whitespace in breadcrumbs

---

examples/patterns/breadcrumbs.html
scss/_patterns_breadcrumbs.scss

Removed custom link style from breadcrumbs pattern, so breadcrumbs links now have regular link style (as per spec).
- Pull code
- Go to breadcrumbs example
- Breadcrumbs link should have style as [in spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Breadcrumbs)
Fixes #1034

Updated breadcrumbs link style

---

scss/_patterns_matrix.scss

Fix issue 1072:  p-matrix__img should be max-width: 60px, not a calculation
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/matrix/
- Check the Matrix pattern in s/m and large
- Went for 3.75rem rather than 60px
Fixes #1072

Fix 10720 matrix image size

---

docs/en/patterns/strip.md

Added link to grid pattern from strip docs.
- Pull code
- Regenerate docs
- Go to Strip pattern docs page
- It should link to Grid pattern page
Fixes #1035

Added link to grid pattern from strip docs page

---

scss/_patterns_strip.scss

Remove explicit color setting from strip mixin. 
This is because including this as part of the strip mixin menas it is overriding --color variants of strip further downstream.
- Verify there are no visual changes via Percy
https://github.com/vanilla-framework/vanilla-brochure-theme/issues/99

Remove explicit color setting from strip mixin

---

docs/en/patterns/grid.md
examples/patterns/grid/empty-columns.html
examples/patterns/grid/nested.html
scss/_patterns_grid.scss

Add nested columns info to docs
- Pull code
- Check nested columns example at: http://0.0.0.0:8101/vanilla-framework/examples/patterns/grid/nested/
- Jump into docs.vf.io
- Change line 11 in `build-html` to `git clone https://github.com/barrymcgee/vanilla-framework --branch 992-nested-grid-docs`
- Run `./build-html`
- Run `caddy`
- View http://127.0.0.1:8543/en/patterns/grid
Fixes #992

Add nested columns info to docs

---

scss/_patterns_navigation.scss

Remove hover underline from navigation links
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/light/
- Hover over links and verify there is no underline
Fixes #1063

Remove hover underline from navigation links

---

docs/en/index.md

Removed toc boolean from the homepage
- Pull https://github.com/ubuntudesign/docs.vanillaframework.io
- Modify build-html:11:
`git clone https://github.com/Lukewh/vanilla-framework --branch remove-toc-from-homepage`
- Run ./build-html
- Run caddy
- Open http://127.0.0.1:8543/en/
- Ensure tables of content doesn't appear on the homepage, but does on other pages.
Fixes https://github.com/vanilla-framework/vanilla-docs-theme/issues/48

Removed toc from homepage

---

docs/metadata.yaml

Updated favicon to be png. Svg's only work in firefox and safari, apparently.
- Pull https://github.com/ubuntudesign/docs.vanillaframework.io
- Modify build-html:11:
`git clone https://github.com/Lukewh/vanilla-framework --branch update-favicon`
- Run ./build-html
- Run caddy
- Open http://127.0.0.1:8543/en/
- See favicon!
Fixes https://github.com/ubuntudesign/docs.vanillaframework.io/issues/90

point to png favicon

---

scss/_base_hr.scss

Add margin top/bottom to `<hr>` as without explicit margin settings, vertical rhythm rules will add a large top margin.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/hr/
- Check that margin top and bottom is `1rem`
Fixes #1180

Add margin top/bottom to <hr>

---

docs/en/patterns/matrix.md

Add note to Matrix docs on empty columns. This is because list items must be added to the Matrix pattern in multiples of three otherwise you'll get missing borders.
- Pull code
- Open https://docs.vanillaframework.io/en/patterns/matrix
- Remove content from the last Matrix list item
- Verify that correct borders persist
Fixes #1065

Add note to Matrix docs on empty columns

---

docs/en/base/code.md
docs/en/base/forms.md
docs/en/base/typography.md
docs/en/index.md
docs/en/patterns/code-numbered.md
docs/en/patterns/code-snippet.md
docs/en/patterns/grid.md
docs/en/patterns/lists.md
docs/en/patterns/navigation.md
docs/en/patterns/notification.md
docs/en/patterns/pull-quote.md

- Remove any related links with trailing slash
- Remove duplicate word
- Fix broken link
- Switch into docs.vanillaframework.io repo
- Change line 11 in `build-html` to 
```
git clone https://github.com/barrymcgee/vanilla-framework --branch 1184-broken-links-sweep
```
- Run `./build-html` in that repo, followed by `caddy`
- Check each page and ensure all links are correct
Fixes #1184

Broken links sweep

---

examples/patterns/navigation/dark.html
examples/patterns/navigation/light.html

Add aria and accessibility improvements to navigation pattern
Note: This does not include all the changes as recommended by @richmccartney in his Codepen as I don't think we should add state aria markup that will be invalid unless custom JS scripting is added. 
The reason for this is that many people will copy/paste the navigation snippet from the docs without ever writing the JS needed to make the aria state labels work correctly thus making sites more confusing for screen readers etc. to that end, I've only added aria labels that will always be correct, with or without JS.
- Pull code
- Review aria changes
- Review http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/dark/
- Review http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigatio …

Add aria and accessibility improvements to navigation pattern

---

docs/en/base/typography.md
examples/base/small.html
scss/_base_typography.scss

Note: @spencerbygraves Please see @yaili's note on #1046 before reviewing.
Small text should be 14px through all breakpoints
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/small/
- Check text size is 14px through all breakpoints
Fixes #1046

Small text should be 14px through all breakpoints

---

docs/en/patterns/divider.md
examples/patterns/divider.html
scss/_patterns_divider.scss
scss/_vanilla.scss

Copied over the divider pattern and accompanying documentation from the brochure theme. 
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/divider/
- Check it looks like https://vanilla-framework.github.io/vanilla-brochure-theme/examples/patterns/divider/
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1208

Combine brochure theme divider pattern

---

docs/en/metadata.yaml

Added a link to the parent site within docs.
- Pull code
- `cd` to your docs.vanillaframework.io branch 
- Update build-html to:
```bash
BLUE='\033[1;34m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
echo "${BLUE}Clearing build${NC}"
rm -rf en
echo "${GREEN}Build removed${NC}"
echo "${BLUE}Building vanilla-frameworks documentation${NC}"
documentation-builder --base-directory ../vanilla-framework/docs  \
--site-root '/en/'  \
--output-path .  \
--template-path template.html  \
--tag-manager-code 'GTM-K92JCQ'  \
--no-link-extensions \
--force
echo "${GREEN}Completed vanilla-framework documentation build${NC}"
echo "${BLUE}Build vanilla-brochure-theme documentation${NC}"
documentation-builder --base-directory ../vanilla-brochure-theme/docs \
--site-root '/en/vanilla-brochure-theme/index' \ …
```

Docs link to the parent website

---

examples/templates/vertical-spacing.html
index.html
scss/_base_vertical-spacing.scss

Disable vertical spacing on `u-equal-height` 
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/templates/vertical-spacing/
- Check that the Guidelines section `u-equal-height` has no margin-bottom.
- Check that the "Title" in the Title section has margin-bottom
- Check that the button at the end of the last strip has margin-top
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1152

Make u-equal-height immune to vertical spacing

---

examples/base/sub.html
examples/base/sup.html
scss/_base_typography.scss

Made the positioning of a `sup` and `sub` relative to the element not root.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/sup/
- Check that both `sup`s in the title and paragraph text is correct
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1109

Improve sup and sub positioning

---

docs/en/patterns/muted-heading.md
examples/patterns/muted-heading.html
scss/_patterns_muted-heading.scss
scss/_vanilla.scss

Ported the muted-heading pattern, example and docs.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/muted-heading/
- Check it matches https://vanilla-framework.github.io/vanilla-brochure-theme/examples/patterns/muted-heading/ but left aligned as there was an amendment to the pattern since the last release
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1212

Port the muted-heading pattern from brochure theme

---

docs/en/metadata.yaml
docs/en/patterns/heading-icon.md
examples/patterns/heading-icon.html
scss/_patterns_heading-icon.scss
scss/_vanilla.scss

Copied over the heading-icon pattern and accompanying documentation from the brochure theme. 
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/heading-icon/
- Check it looks like https://vanilla-framework.github.io/vanilla-brochure-theme/examples/patterns/heading-icon/
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1209

Port the brochure header-icon pattern

---

docs/en/metadata.yaml

Removed the themes section from the docs
- Pull code
- Switch over to your docs.vanillaframework.io branch
- Run `documentation-builder --source-folder '../vanilla-framework/docs' --output-path .` _replacing the source-folder with a path to your clone of vanilla-framework
- Open http://127.0.0.1:8543/en/
- Check there is no Themes section
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1240

Remove the brochure theme docs link

---

docs/en/utilities/image-position.md
examples/utilities/image-position/bottom-left.html
examples/utilities/image-position/bottom-right.html
examples/utilities/image-position/bottom.html
examples/utilities/image-position/left.html
examples/utilities/image-position/right.html
examples/utilities/image-position/top-left.html
examples/utilities/image-position/top-right.html
examples/utilities/image-position/top.html
scss/_utilities_image-position.scss
scss/_vanilla.scss

Migrated the `image-position` util from brochure theme with its accompanying docs and examples.
- Pull code
- Go through the image-position util examples and check they do what they say on the tin
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1215

Port the image position util from brochure theme

---

docs/en/patterns/lists.md
examples/patterns/lists/lists-stepped-detailed.html
scss/_patterns_lists.scss

Ported the list stepped detailed pattern from the brochure theme with its docs and example.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/lists/lists-stepped-detailed/
- Check it looks the same as https://vanilla-framework.github.io/vanilla-brochure-theme/examples/patterns/lists/stepped-list-detailed/
- Check example and docs are ok
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1213

Port the list stepped detailed pattern from brochure theme

---

docs/en/patterns/strip.md
examples/patterns/strips/accent.html
examples/patterns/strips/deep.html
examples/patterns/strips/image.html
examples/patterns/strips/is-bordered.html
examples/patterns/strips/shallow.html
examples/patterns/strips/strips-dark.html
examples/patterns/strips/strips-light.html
scss/_global_functions.scss
scss/_patterns_strip.scss
scss/_settings_colors.scss

Migrate the strip patterns from the brochure theme with their accompanied examples and docs.
- Pull code
- Check the strip variants are correct
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1214

Port the strip pattern from brochure theme

---

examples/patterns/footer.html
examples/patterns/navigation/dark.html
examples/patterns/navigation/light.html

Remove redundant role attributes from navigation and footer examples as these will throw warnings from the [HTML validator](https://validator.w3.org/nu/)
See: https://validator.w3.org/nu/?acceptlanguage=&doc=https%3A%2F%2Fvanillaframework.io%2Faccessibility

Remove redundant role attributes from examples

---

scss/_patterns_heading-icon.scss

Fixes #1272
Remove the specific color style rule from .p-heading-icon as it does not specify a background color. This means that if a strip has a dark background and has set a light text color, using this pattern does not override it.
- Pull code
- There should be no Percy changes
- Edit the strip accent pattern to use this markup and verify text is legible:
```
<section class="p-strip--accent">
<h2>.p-strip--accent</h2>
</div>
<div class="col-12">
<div class="p-heading-icon">
<div class="p-heading-icon__header">
<h3 class="p-heading-icon__title">Lorem ipsum dolor</h3>
</div>
<p>sit amet, consectetur adipisicing elit. Enim excepturi, repudiandae blanditiis odio perferendis …
```

Remove specific color from p-heading-icon

---

docs/en/metadata.yaml
docs/en/patterns/table-expanding.md
examples/patterns/tables/table-expanding.html
scss/_patterns_table-expanding.scss
scss/_vanilla.scss

- Ports over the expanding table pattern.
- Creates html and docs
- Pull code
- Open table expanding a view the component
Fixes #1234

Adding SCSS, html examples and docs for the expanding table.

---

docs/en/metadata.yaml
docs/en/patterns/tooltips.md
examples/patterns/tooltips.html
scss/_patterns_tooltips.scss
scss/_vanilla.scss

- Porting over the tooltips SCSS from Vanilla dashboard theme
- Creating examples and documentation content
- Pull code
- View tooltips pattern http://0.0.0.0:8101/vanilla-framework/examples/patterns/tooltips/
Fixes #1238

1238 port tooltips pattern

---

docs/en/metadata.yaml
docs/en/patterns/table-sortable.md
examples/patterns/tables/table-sortable.html
scss/_patterns_table-sortable.scss
scss/_vanilla.scss

- Ports over the table sorting styles
- creates html examples and docs
- Pull code
Fixes #1236

Adding SCSS, examples and docs for table sorting.

---

scss/_patterns_form-validation.scss

`$sp-x-small` variable inside `calc` in forms validation pattern was not compiling properly, so it needed to be interpolated.
- Pull code
- Check compiled styles of form validation pattern, $sp-x-small value should be compiled (not visible as variable).

Interpolate variable in calc so it compiles correctly

---

scss/_patterns_switch.scss

Replaced the placeholder extend in the switch pattern with the few styling values that were required.
**Do not extend a placeholder on a pseudo selector - leads to madness**
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/card/card/
- Check that looks ok
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/switch/
- Check that looks ok

Remove the card placeholder from switch pattern

---

scss/_global_functions.scss

Set the default color for the external link to $color-link instead of inherit.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/links/links-external/
- Copy the HTML from the codepen into the example and refresh
- The link in the copy should be the link color not the same as the text
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1274

Made the default external link color the link color

---

scss/_base_vertical-spacing.scss

Fix the spacing between headers and p's.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/headings/
- Copy the following mark up into the page:
```html
<div class="p-strip--light is-bordered is-deep">
<div class="row p-divider">
<div class="col-6 p-divider__block">
<div class="u-equal-height">
<div class="col-4">
<h3><a href="https://www.ubuntu.com" class="p-link--external">Explore ubuntu.com</a></h3>
<p>On ubuntu.com you’ll find more information about the platform, our services, our management tools and our partner&nbsp;programs.</p>
</div>
<div class="col-2 u-vertically-center u-hide--small">
</div>
</div>
</div>
</div>
<div class="col-3 p-divider__block">
<h3><a href="/services">Learn more about …
```

Remove the nesting before headings with siblings

---

scss/_base_typography.scss

Add back the font smoothing for Macs
- Check the code is the same as was removed here:
https://github.com/vanilla-framework/vanilla-framework/commit/4da454bc79e64b08e8975b6ffca0abc45c8b9dd7#diff-835de81767074b6c90941c47335f0fd9L106

Add font-smoothing back

---

examples/patterns/navigation/light.html
scss/_patterns_navigation.scss

Set the navigation logo to a set height.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/light/
- Check that the logo image is `32px` and has `8px` top and bottom height
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1037

Set the height of the navigation logo

---

scss/_patterns_inline-images.scss

Update the styling of the inline-images pattern to match the common usage across our sites. We currently copy a "hack" for inline-images between sites and this branch means it can stop.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/inline-images/
- Check that it looks ok
- Check the code matches the hack that is being copied around: https://github.com/canonical-websites/www.ubuntu.com/blob/b788fd6162c2f86fd5408ddd09a3c2940d5a3550/static/sass/_pattern_inline-images.scss#L23
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1168

Set inline-image styling to its general useage

---

scss/_patterns_card.scss

- Remove large bottom margin from card header
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/card/card/
- Ensure card pattern matches the spec
Fixes #1280

Remove large bottom margin from card header

---

.spelling
docs/en/patterns/links.md

The need for autoprefixing surprised me. So I'm adding documentation about it.
``` bash
documentation-builder --source-folder docs
xdg-open build/en/patterns/links.html || open build/en/patterns/links.html
```
Look at the documentation - check there's a note under `p-link-external` about autoprefixer.

Add a note about the need for an autoprefixer

---

scss/_base_code.scss
scss/_patterns_tabs.scss
scss/_patterns_tooltips.scss

- Update border color of base code block
- Disable linting warnings for unavoidable abberations
- Pull code
- Check border color of base code matches [spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Code/code.md)
Fixes #1307

Update code block color

---

docs/en/patterns/table-expanding.md

Add trailing slash to table expanding import
- Pull code
- Check table expanding displays in docs
Fixes #1326

Add trailing slash to table expanding import

---

docs/en/metadata.yaml
docs/en/patterns/muted-heading.md
examples/patterns/headings/muted.html

Add p-muted-heading to docs
- Pull code
- Import this branch into your local vf.io 
- Verify that `.p-muted-header` displays correctly
Fixes #1328

Add p-muted-heading to docs

---

scss/_patterns_navigation.scss

Update the light navigation to a white background
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/light/
- Check that the navigation is white
Fixes https://github.com/ubuntudesign/vanilla-design/issues/87

Update the light navigation to a white background

---

scss/_patterns_media-object.scss

Removed unnecessary additonal padding from large media object
- Pull code
- Go to Media Object - Large example
- Pattern should use default vanilla margins (no additional padding).
As part of #1343 review additional padding was added to large variant of media object pattern.
It caused a bug where media pattern had unnecessary double spacing when used inside of a stripe pattern:
This PR removes unnecessary additional padding and let's media object use default values of Vanilla spacing defined in horizontal rhythm rules:
NOTE:
Because of #1338 adding `.u-no-margin--bottom` is needed in some context to avoid unexpected bottom margin.

Removed unnecessary additonal padding from large media object.

---

scss/_patterns_links.scss

Set the scale of the icon to `em`s instead of `rem`s. Hotfixed the vendor prefix on the mask.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/links/links-external/
- Check the icon is ok and scales as you change the font-size of the link.
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1311
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1351

External link icon to scale with text

---

scss/_patterns_navigation.scss

Increase threshold for text color contrast in navigation pattern
- Pull code
- Verify navigations pattern display correctly
Fixes #1373

Increase threshold for text color contrast in navigation pattern

---

scss/_base_forms.scss

Align the height of selects to match inputs and buttons. Set the vertical spacing to match an input instead of having its own padding.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/forms/selects/
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/forms/input/
- Check they both align 
Fixes https://github.com/ubuntudesign/vanilla-design/issues/37

Aligned the select styling to match inputs and buttons

---

docs/en/metadata.yaml
docs/en/patterns/navigation.md
examples/patterns/navigation/default.html

Set the default navigation pattern to full width and updated the documentation to describe how you can restrict the navigation width. Drive by to update the `Divider` in the documentation navigation.
- Pull code
- Check that the navigation is full width
- Check the documentation has a note about using `.row`
Fixes https://github.com/ubuntudesign/vanilla-design/issues/90

Set the default header to full width

---

scss/_patterns_lists.scss

Remove the border-bottom from the last item of a split list
- Pull code
- Add the following to the `lists-split` example:
```html
<ul class="p-list is-split">
<li class="p-list__item is-ticked">Lorem</li>
<li class="p-list__item is-ticked">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean nec ipsum augue. Ut arcu erat, lacinia sit amet justo quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
<li class="p-list__item is-ticked">Dolor</li>
<li class="p-list__item is-ticked">Aenean nec ipsum augue. Ut arcu erat, lacinia sit amet justo quis.</li>
<li class="p-list__item is-ticked">Ipsum</li>
<li class="p-list__item is-ticked">Ut arcu erat, lacinia sit amet justo quis.</li>
</ul>
```
- Open …

Remove the border bottom from the last item of a split list

---

docs/en/patterns/links.md
examples/templates/external-links.html
scss/_base_button.scss
scss/_patterns_links.scss
scss/_patterns_strip.scss

Removed the cross-linking of strips and external links and used currentColor to use the strip color to style the external link. Created a layout to test all combinations of the external link.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/templates/external-links/
- Check that all external links are styled as expected.
_There is some issues with base button but that is out of scope for this issue_
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1378

Decouple strips from external links

---

scss/_patterns_tabs.scss

Remove the font-size of the tab items which sets it to 16px by default.
- Pull code
- Check that the font is `16px`
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1407

Increase the font-size of the tabs pattern

---

scss/_base_forms.scss

-  Updated checkbox/radio spacing to $sp-small (0.75rem)
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/forms/radio-buttons/ and http://0.0.0.0:8101/vanilla-framework/examples/base/forms/checkboxes/
- Check that the margin-right for both radio buttons and checkboxes is 0.75rem

1412 - Update checkbox/radio spacing to $sp-small (0.75rem)

---

docs/en/metadata.yaml

- Updated metadata.yaml to match work completed on new categorisation on docs.vf.io
- Links remain the same just a reorder and grouping of components
- Design issue found [here](https://github.com/ubuntudesign/vanilla-design/issues/118) which was the outcome from Documentation workshop
- Pull code
- @nottrobin or @WillMoggridge to create/share demo of PR so I can review before going live.

Edit metadata.yaml to update/reorder categories on docs.vf.io

---

scss/_patterns_links.scss

- Replaced instances of CSS mask in `p-link--external` with a mixin for each colour the link can be
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/links/links-external/
- Check that the external links look good in all major browsers
Fixes #1380 
Previously in IE11:

1380: Replace .p-link--external CSS masks with background-image mixins

---

examples/patterns/accordion.html

- Fixed the [accordion example](https://vanilla-framework.github.io/vanilla-framework/examples/patterns/accordion/) not allowing an open panel to close on click. This should by extension fix the example on the [docs page](https://docs.vanillaframework.io/en/patterns/accordion)
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/accordion/
- Check that you can close an open panel
- Remove `<li>` elements so there's only one left on the page and check if it works
Fixes #1423

1423: Fix accordion example not closing on click

---

docs/en/utilities/spin.md

- Fixed spin example link in the spin.md file, which should allow the documentation builder to embed the example on the [docs page](https://docs.vanillaframework.io/en/utilities/spin)
- Pull code
- Build a static docs page using `documentation-builder`
- Add the script `<script src="https://assets.ubuntu.com/v1/7db7c898-example-1.0.5.js"></script>` to the bottom of docs/build/en/utilities/spin.html and open it in a browser
- Check that the spinner example and accompanying code is shown
Fixes #1438 
**Page should look like this:**

1438: Fix spin animation link in docs

---

examples/patterns/forms/form-help-text.html
examples/patterns/forms/form-inline.html
examples/patterns/forms/form-stacked.html
scss/_patterns_form-help-text.scss
scss/_patterns_forms.scss
scss/_vanilla.scss

Added .p-form-help-text, based on spec here: https://github.com/ubuntudesign/vanilla-design/tree/master/Forms.
- Pull code
- Visit:
- http://0.0.0.0:8101/vanilla-framework/examples/patterns/forms/form-help-text/
- http://0.0.0.0:8101/vanilla-framework/examples/patterns/forms/form-inline/
- http://0.0.0.0:8101/vanilla-framework/examples/patterns/forms/form-stacked/
- Ensure all forms look OK.
https://github.com/vanilla-framework/vanilla-framework/issues/1447

Added p-form-help-text, updated stacked and inline examples

---

scss/_patterns_icons.scss

- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/icons/icons-light/
- Modify one of the icon `i` tags by removing the `--[name]` prefix
- Ensure the `i` still has the correct size and background properties set
Implements https://github.com/vanilla-framework/vanilla-framework/issues/1432

Added base icon layout to .p-icon

---

scss/_patterns_links.scss

- Created separate mixins for browsers that do and don't support CSS masks (IE is a special case that doesn't support the `@supports` conditional, and therefore has no icon. I think this is fine, and much better than a random block)
- Fixed external link icon wrapping in both versions
- Fixed `<br>` tag misalignment in both versions
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/templates/external-links/
- Check that the external link icon wraps with the last word in the link, rather than by itself
- In Firefox, check that the icon is still next to the text when followed by a `<br>` tag
- Browser test the colours of the icon matching the text
Fixes #1276, fixes #1426 
**Before:**
**After:**

1276: Fix external link icon wrapping

---

examples/patterns/lists/lists-mid-dot.html
scss/_patterns_lists.scss

- Made dots in `.p-inline-list--middot` centred for all font-sizes by changing rems to ems
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/lists/lists-mid-dot/
- Check that the dots are properly centred between the list items
- Change the font-size and check that the dots properly scale and remain centred
Fixes #1434

1434: Fix middot centering (use em instead of rem)

---

docs/en/metadata.yaml

- Updated metadata.yaml to fix issue [here](https://github.com/vanilla-framework/vanilla-framework/issues/1482) from multiple raised bugs
- Links remain the same just moving Headings component to sit under Text category
- Updated title from Headings back to Typography
- Pull code
- @nottrobin or @WillMoggridge to create/share demo of PR so I can review before going live

Move 'Headings' component into 'Text' category on docs.vf.io

---

scss/_base_button.scss

- Changed the breakpoint for 100% width on buttons from `$breakpoint-medium` (768px) to `$breakpoint-x-small` (460px) as per original [issue](https://github.com/vanilla-framework/vanilla-framework/issues/1427)
- Pull code
- Resize the browser window width to 460px (which is $breakpoint-x-small) and check that the button does not change
- Resize the browser window width to 459px and check that the button fills the width of the window
Fixes #1427

1427: Set breakpoint for 100% width on buttons to x-small

---

scss/_patterns_list-tree.scss

- Combined the `background-image` for `p-list-tree[aria-hidden="false"]::after` into a single line, which will fix a parsing error in vanilla react
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/list-tree/
- Check that the list tree pattern still works fine
Fixes #1475

1475: Fix list-tree expander icon

---

scss/_base_tables.scss

- Updated base_tables.scss vertical spacing from 1rem to 0.75rem to match design [spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Table/table.md)
- Pull code
- Open the following pages:
- http://0.0.0.0:8101/vanilla-framework/examples/base/table/
- http://0.0.0.0:8101/vanilla-framework/examples/patterns/tables/table-expanding/
- http://0.0.0.0:8101/vanilla-framework/examples/patterns/tables/table-mobile-card/
- http://0.0.0.0:8101/vanilla-framework/examples/patterns/tables/table-sortable/
- Check that the cells in each of the table variants (i.e. `<td>` elements) has a padding-top and padding-bottom of 0.75rem, as per [spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Table/table.md)
Fixes #1433

1433: Update table v-spacing to $sp-small to match design spec

---

.sass-lint.yml
docs/en/patterns/slider.md
examples/patterns/slider/slider-input.html
examples/patterns/slider/slider.html
scss/_patterns_slider.scss
scss/_vanilla.scss

- Built slider component as per #1455 
- Includes styling for Chrome, Firefox and IE/Edge browsers
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/slider/
- Check that the component matches the spec (#1455)
- Check that everything looks right in all browsers that we support ([link](https://github.com/canonical-webteam/practices/blob/master/coding/browser-support.md))
Fixes #1472 
- Each browser has a different method of rendering `input type="range` with their own pseudo-selectors and therefore requires custom styling (and a slight change to the linter)
- IE and Edge have a bug where the input thumb's shadow is one(!) pixel to the right
- Chrome (webkit) does not support filled in progress bars for `input type="range"` in CSS, so in …

1472: Build slider component

---

.gitignore
_config.yml
docs/app.py
docs/routing.py
docs/template.html
package.json
requirements.txt

Adding Flask app to serve docs.
An update to ./run will come later to allow it to be served through it as a secondary site.
- Pull code
(Can't use ./run just yet 😞)
- `yarn run build-docs`
- Install python from requirements.txt in your favourite Python env manager
- `FLASK_APP=docs/app.py flask run`
- Follow address in terminal

Add Flask app to serve docs

---

scss/_patterns_links.scss

- Added `-webkit-mask` to `@support` checks
- Added `-webkit-mask` to external link pattern
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/templates/external-links/
- Check that external link patterns still look good in Chrome, Firefox and Edge (IE doesn't support the `@supports` tag)
Fixes #1481

1481: Add -webkit prefix to mask check in external link pattern

---

scss/_patterns_media-object.scss

- Fixed .p-media-object--large aspect ratio sizing
- Fixed a small bug in Firefox where image width was calculated relative to the container div width
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/media-object/media-object/
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/media-object/media-object-large/
- For both default and large media objects check that the icons show in Firefox as well as Chrome
- For both default and large media objects check that non-square images keep their aspect ratio (test very wide and very tall images)
- You can change the image sizes by editing the img src attribute to whatever dimensions you want to test
Fixes #1474

1474: Fix large media object aspect ratio sizing

---

scss/_utilities_show.scss
scss/_utilities_visibility.scss

- Changed `display: block` to `display: inherit` in u-show and u-visible to keep styling consistent
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/utilities/hide/
- Open http://0.0.0.0:8101/vanilla-framework/examples/utilities/show/
- Check that both still work as expected
- Change any of the `<div>` tags in the example pages to something that doesn't have a `display: block` property, such as a `<span>` or `<table>` and check that the `display` property is not overtwritten
Fixes #1479

1479: Change u-show and u-visible to display: inherit

---

examples/patterns/forms/form-inline.html

- Fixed a bug in the `.p-form--inline` example where form inputs would not baseline align with a button
- Fixed minor labelling bugs in the same example
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/forms/form-inline/
- Check that the inputs align along the length of the form (it can help to change the `background-color` of the forms to something other than white)
- Test using browsers listed in the [Browser Support doc](https://github.com/canonical-webteam/practices/blob/master/coding/browser-support.md)
Fixes #1429

1429: Fix alignment bugs in inline form example

---

scss/_patterns_tabs.scss

- Added a transparent border-bottom to `.p-tabs__link` by default, which should address styling issues if no tabs are selected and if the tab list extends over two lines
- Made it possible to click through the arrow on small screen tab pattern
- Changed overflow on small screen tabs to `auto`, so the horizontal scrollbar only appears when necessary
- Pull code
- Remove `aria-selected="true"` from the markup of the selected tab
- Check that the height of the tab list does not change on hover
- Refresh
- Add extra `<li class="p-tabs__item" role="presentation">` until the tab list wraps around
- Check that the second row of tabs do not jump around on hover
- Refresh
- Resize window to small …

Tab pattern fixes

---

docs/en/metadata.yaml

- Added slider details to `docs/en/metadata.yaml`
- Pull code
- Open http://0.0.0.0:8104/
- Check that the slider pattern can be found in the side nav under 'Interactive Elements'
- Check that clicking on it directs to /en/patterns/slider
- Check that the slider docs page is explained well
Fixes #1516

1516: Add Slider to docs navigation

---

docs/en/metadata.yaml
docs/en/patterns/search-box.md
examples/patterns/search-box/default.html
examples/patterns/search-box/navigation.html
scss/_patterns_navigation.scss
scss/_patterns_search-box.scss
scss/_vanilla.scss

- Built search box component as per [specs](https://github.com/ubuntudesign/vanilla-design/tree/master/Search)
- Includes Default and Navigation examples
- Added docs page for the search box component (and included it in the side nav this time)
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/search-box/default and http://0.0.0.0:8101/vanilla-framework/examples/patterns/search-box/navigation
- Check that the component matches the [specs](https://github.com/ubuntudesign/vanilla-design/tree/master/Search)
- Check that everything looks right in all browsers that we support ([link](https://github.com/canonical-webteam/practices/blob/master/coding/browser-support.md))
- `cd` into the docs folder and run `./run`
- Open http://0.0.0.0:8104/
- Check that …

1517: Build search box component

---

examples/patterns/tooltips.html
scss/_patterns_tooltips.scss

- Removed `max-width` from tooltips so the content can set its own line-breaks
- Edited the example to show different widths of tooltips
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/tooltips/
- Check that there are tooltip messages that are wider than 330px and they word-wrap correctly
Fixes #1509

1509: Remove tooltips max-width

---

scss/_base_typography.scss
scss/_utilities_content-align.scss

- Added margin overrides to `.u-align` utilities to account for `max-width` inclusion
- Added a small mixin for base typography so that if a parent `<div>` has a `.u-align` utility it properly defines the margins
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/utilities/align/
- Check that the three paragraphs in the cards are aligned as expected
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/headings/default/
- Add the class `u-align--center` to the `<body>` tag
- Check that all the headings align to the centre, and that they keep their max-widths (so there should be margins left and right of the heading)
Fixes #1478, fixes #1526

1526: Fix content alignment utilities

---

docs/en/patterns/notification.md
examples/patterns/notifications/notifications.html
scss/_patterns_notifications.scss

- Added `.p-notification__close` element to the notification pattern (optional) as per the [new design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Notifications)
- Edited default notification example to show it in action
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/notifications/notifications/
- Check that the close button follows the [new design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Notifications)
- Check that the example works (closes the notification on click)
Fixes #1477

1477: Add close button to notification pattern

---

examples/patterns/navigation/default.html
scss/_patterns_navigation.scss

- Updated header navigation to reflect [new design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Navigation)
- Updated example to show selected state, and added aria tags
- Pull code
- Check that it follows the [new design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Navigation)
Fixes #1459

1459: Update header navigation to new design spec

---

examples/patterns/navigation/sidebar.html
scss/_patterns_navigation.scss

- Removed inline styles from sidebar navigation example
- Removed `position: absolute` from sidebar content as it should be dictated by the grid
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/sidebar/
- Check there are no inline styles in the markup
- Check that the pattern still works properly
Fixes #1533, fixes #1542

Minor sidebar navigation fixes

---

scss/_patterns_code-snippet.scss

- Changed border color of `.p-code-snippet` to `$color-mid-light` to match [design spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Code/code.md)
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/code-snippet/
- Check that the border color of the pattern (including the inner one) is now `#cdcdcd` instead of `#666666`
Fixes #1556

1556: Change code-snippet border to mid-light

---

docs/en/patterns/icons.md

Remove duplicate instance of icons in docs
- Pull code
- Run docs
- View 'Icons' section
- Ensure there are no duplicates
Fixes #1568

Remove duplicate instance of icons in docs

---

scss/_patterns_links.scss

Update hover color of strong link
- Pull code
- Ensure strong link hover is blue link color
Fixes #1575

Update hover color of strong link

---

scss/_patterns_navigation.scss

- Added height: auto to sidebar nav so it isn't always 3rem
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/sidebar/
- Check that the height of the sidebar nav is the entire component, not 3rem

Fix sidebar nav having a constant height

---

scss/_patterns_notifications.scss

- Disabled a single line of sass linting because the Jenkins sass lint throws a fit with negative value variables

Fix notifications.scss linting error

---

docs/template.html

Now that docs.vanillaframework.io has the same header navigation as the rest of vanillaframework.io ([vanillaframework.io#117](https://github.com/canonical-websites/vanillaframework.io/issues/117)), with the “Vanilla” wordmark linked to [vanillaframework.io/](https://vanillaframework.io/), it’s redundant to link to vanillaframework.io in the sidebar as well.

Removes sidebar link to vanillaframework.io

---

docs/en/metadata.yaml

Fixes #1590 by creating a “Tables” category for “Table”, “Table sortable”, “Table expanding”, and “Table mobile card”.

Creates “Tables” category

---

docs/template.html

Added a `title` to the input to change the hover tooltip. I could not remove the required without making the reset button always visible. This seems to resolve the issue though.
- Pull code
- Run `cd docs`
- Run `./run`
- Hover over the search box and see it says "Search the documentation" instead of "Please fill in this field."
- Enter some characters and see the reset (cross) icon appears
Fixes https://github.com/canonical-websites/vanillaframework.io/issues/124

Add a title to the search input in the docs template

---

.travis.yml
tests/file-size-lint.sh

Add filesize check to CI with a threshold
- Run `./run clean`
- Run `tests/file-size-lint.sh` and see that it errors because it cant find the build file
- Run `tests/file-size-lint.sh` and see it passes and outputs the current file size of the build with the threshold
_The threshold is set to 400kb which is way to high. Lets half that and more as soon as possible_

Add file size check to CI

---

docs/en/base/forms.md
docs/en/metadata.yaml

- Fixed an error where Form Validation did not render an example
- Removed redundant Forms pages in the docs from the `metadata.yaml`
- Pull code
- Run `cd docs && ./run serve --watch`
- Open http://0.0.0.0:8104
- Check that the navigation has "Forms" in the sidebar nav under "Interactive elements", and there is no mention of "Forms layout" or "Form validation"
- Check that Form validation example renders

Remove redundant Form docs pages

---

examples/patterns/navigation/default.html
examples/patterns/search-box/navigation.html
scss/_patterns_navigation.scss

- Set a height of 3rem on navigation logos
- Made it so logo can be between 1.5rem (24px) and 2rem (32px) in height
- Updated nav examples to depict 24px high Vanilla logo
- Pull code
- Check that the nav looks the same
- Delete `<div class="p-navigation__banner">` from the DOM and check that the nav height is still 3rem
- Undo, now delete `<nav class="p-navigation__nav" role="menubar">` and check that the nav height is still 3rem
- Undo, now remove `width="95"` from the nav logo, and check that the logo reaches the max-height (32px) and is still vertically centered
Fixes #1658

1658: Fix issue with navigation logo sizing

---

scss/_patterns_card.scss

- Added a max-height of 2rem to img elements in a .p-card__header div
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/card/header/
- Check that the header image has a max-height of 2rem
Fixes #1659

Re-add max-height of card header image

---

scss/_base_lists.scss
scss/_base_typography.scss

Aims to address https://github.com/vanilla-framework/vanilla-framework/issues/1673
Since the uls on insights have no classes and I understand they are coming from a cms, so classes cannot be added, I've added the default vertical spacing to them. This will need to be overriden in cases where it is not necessary with the no margin bottom utility.
- Pull code
Fixes #1673 

Increase space under ul to address issue on insights page 

---

scss/_patterns_navigation.scss

fix row in nav when no p-navigation__row class is present

---

examples/utilities/align.html
scss/_base_typography.scss
scss/_utilities_content-align.scss

- Separated `.u-align-text` from `u-align`
- Removed `u-align` utilities from base typography file
- Updated "Align" example to reflect the separation
- **Note:** this will necessitate some markup updates in the uncommon instances where we use centered and right-aligned text
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/utilities/align/
- Check that it all looks good
Fixes #1677

Separate u-align and u-align-text utilities

---

scss/_utilities_vertically-center.scss

- Added an `img` child selector to `u-vertically-center` to override the default `align-self: flex-start` behaviour
- Go to http://www.ubuntu.com-pr-2859.run.demo.haus/cloud/public-cloud
- Open Chrome Dev Tools and change `align-self: flex-start` to `align-self: center` from the card img elements
- Check they are now vertically centered
- Check Percy that I haven't inadvertently broken anything
Fixes #1669 
Fix applied on [vanilla test on ubuntu](http://www.ubuntu.com-pr-2859.run.demo.haus/cloud/public-cloud)

Make u-vertically-center work with img elements

---

scss/_patterns_code-snippet.scss

- Set `margin-bottom` and `margin-top` to 0 on `.p-code-snippet__action`
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/code-snippet/
- Edit the HTML so that there is a `<p>` before the code snippet and check the button is still aligned
- Add a second p-code-snippet and check the buttons are aligned
- Change the `<div>`s to `<p>`s and check the buttons are aligned
Fixes #1721

1721: Remove margins on .p-code-snippet__action

---

scss/_patterns_heading-icon.scss
scss/_settings_spacing.scss

- Reverted the work done on #1745 as it was causing issues on several instances of the heading icon pattern (see screenshot)
- Rewrote the pattern slightly to make it compatible with the new spacing variables
- Added heading icon sizes to `$icon-sizes` map
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/heading-icon/
- Check that the heading icon pattern looks as it does on https://vanilla-framework.github.io/vanilla-framework/examples/patterns/heading-icon/ (there will be some minor spacing differences, but the icon itself should be identical)

Revert heading icon changes from #1745, and amend with new spacing

---

docs/en/base/forms.md
examples/patterns/card/header.html
examples/patterns/image/bordered.html
examples/patterns/image/shadowed.html
examples/patterns/inline-images.html
examples/patterns/matrix.html
examples/patterns/media-object/media-object-circ-img.html
examples/patterns/media-object/media-object-large.html
examples/patterns/media-object/media-object.html
examples/patterns/strips/accent.html
examples/patterns/strips/deep.html
examples/patterns/strips/image.html
examples/patterns/strips/is-bordered.html
examples/patterns/strips/shallow.html
examples/patterns/tables/table-expanding.html
examples/utilities/align.html
examples/utilities/image-position/bottom-left.html
examples/utilities/image-position/bottom-right.html
examples/utilities/image-position/bottom.html
examples/utilities/image-position/left.html
examples/utilities/image-position/right.html
examples/utilities/image-position/top-left.html
examples/utilities/image-position/top-right.html
examples/utilities/image-position/top.html

- Removed "Related" links from Forms page (there used to be separate pages, but they're now consolidated so are unnecessary not to mention 404ing)
- Reverted Align utility example page to reflect Vanilla 1.6.7, and will re-update when 1.7.0 is released
- Updated all instances of placeholder images with the new url over https
- Pull code
- Check that the Forms page has no related links
- Check that the Align page has the old markup (i.e. 3 full width cards, "This text is centre-aligned" etc)
- Check that images still load okay, for example in the inline images component, or the card etc
Fixes #1756, fixes #1758

Fixes for various Vanilla docs bugs

---

scss/_base_code.scss

- Removed default text behaviour from `<code>` as it's meant to be purely inline.
- Added vertical padding (`$spv-intra`) to `<pre>` blocks
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/code/
- Check that there is 0.5rem vertical padding on the `<pre>`
- Check that there is no margin or padding on the `<code>`
Fixes #1765

Remove margin and padding from <code> + add vertical padding to <pre>

---

index.html

- Prettified index.html
- Made strip shallow instead of deep
- Pull code
- Check out the reduced vertical space

Reduce vertical spacing on examples directory + prettify markup

---

scss/_settings_grid.scss
scss/_settings_spacing.scss

- Added `!default` to all settings so they can be defined in a separate settings file and loaded in before Vanilla
- Pull code
- Open `_vanilla.scss` and add a line at the top that overwrites one of values that now have `!default`, for example:
``` scss
$grid-max-width: 1500px;
```
or
``` scss
$sp-unit-ratio: 1;
```
- Check that the changes take effect on http://0.0.0.0:8101/vanilla-framework/

Add !default to all settings

---

examples/patterns/matrix.html
scss/_patterns_matrix.scss

- Removed negative margin on consecutive `.p-matrix__desc` so vertical spacing is like two normal paragraphs
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/matrix/
- Add a second `<p class="p-matrix__desc">Short description</p>` to any of the matrix cells
- Check that the space between the two paragraphs is the same as any two consecutive `<p>`
Fixes #1772

Remove negative margin from consecutive .p-matrix__desc

---

scss/_base.scss
scss/_base_placeholders.scss
scss/_global_functions.scss
scss/_patterns_card.scss
scss/_patterns_tabs.scss
scss/_settings.scss
scss/_settings_placeholders.scss
scss/_vanilla.scss

- Moved the `vf-b-placeholders` include from `vanilla.scss` to `base.scss`
- Alphabetised the imports and includes in `base.scss` and `vanilla.scss` (except for `vf-p-navigation`, which is placed first due to how `@at-root` is used in the sidebar navigation pattern)
- Created a settings file for the base placeholders, where you can change things like box-shadow, border-radius, and highlight bar thickness (like the one in https://vanilla-framework.github.io/vanilla-framework/examples/patterns/notifications/positive/) that are used across multiple components
- Namespaced the base placeholders to prevent conflicts with other scss frameworks (if anyone ever decides to use Vanilla with something else)
- Pull code
- Run `./run test` and check there are no errors
- Check Percy that nothing has …

Minor codebase cleanup

---

scss/_base_typography.scss
scss/_patterns_lists.scss
scss/_patterns_matrix.scss
scss/_patterns_media-object.scss
scss/_settings_breakpoints.scss
scss/_settings_spacing.scss

- Made it so headings decrease in size once a certain screen size threshold is reached, which is `$breakpoint-medium` by default (i.e. `$breakpoint-heading-threshold: $breakpoint-medium !default`)
- Added nudges, sp-after and sp-before values for mobile headings to their respective maps, e.g. `$nudge--h1-mobile: .2rem`. This is to ensure the new heading sizes sit on the baseline grid, as well as anything that follows one.
- Added media queries to patterns that were affected by the change in heading sizes, to ensure the spacing looked right (media object, matrix, stepped list)
- The new mobile headings follow a different power scale to the originals. The large headings increase by 2 for each step up in size, while the mobile headings increase by 1.5.
**Note:** The pow() function doesn't …

Reduce headings sizes for smaller screens

---

scss/_base_code.scss

- Changed the `white-space` property of `<pre>` blocks `pre-wrap` instead of `nowrap`
- This fixes a bug where a `<pre>` block without `<code>` lines show up as a single long line of code
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/code/
- Open dev tools and create a pre block with multiple lines of code without `<code>`, e.g.
``` html
<pre>
Code line 1
Code line 2
</pre>
```
- Check that the code block renders over multiple lines correctly

Give pre blocks white-space: pre-wrap

---

docs/en/base/typography.md
docs/en/metadata.yaml
docs/en/settings/breakpoint-settings.md
docs/en/settings/placeholder-settings.md
docs/en/settings/spacing-settings.md
docs/en/utilities/functions.md

- Updated Typography page with new type scale
- Updated Breakpoints page to include `$breakpoint-heading-threshold`
- Updated Spacing settings page with new spacing variables
- Created a Placeholders settings page
- Created a Functions page
- Renamed 'Global navigation' to 'Navigation' (which I think makes more sense)
- Pull code
- Navigate to the following pages and check that they load alright and the copy makes sense
- http://0.0.0.0:8104/en/base/typography
- http://0.0.0.0:8104/en/settings/breakpoint-settings
- http://0.0.0.0:8104/en/settings/placeholder-settings
- **http://0.0.0.0:8104/en/settings/spacing-settings** (variable names are likely to change in the next release, which will mostly involve renaming/refactoring and minimal if any design changes)
- …

Update docs copy with 1.7.0 content

---

package.json
scss/_settings_system.scss

- Bumped version number to 1.7.0
- This will be released early tomorrow morning (10/05), alongside the docs and vf.io

Bump version to 1.7.0

---

docs/en/base/typography.md
docs/en/settings/spacing-settings.md

- Fixed the modular scale points in the typography page
- Fixed the name of `$spv-inter--deep-scaleable`
- Pull code
- `cd docs && ./run`
- Check that the fixes on the typography page and spacing page have been applied

Fix errors in Vanilla docs

---

scss/_patterns_buttons.scss

Darken neutral bg hover color by 10%
@kwm14 Despite http://scg.ar-ch.org/ saying that using `darken(#F7F7F7, 10%)` should produce `#dddddd`, Chrome Inspector reports it as `#dedede` 🤷🏻‍♂️
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/buttons/neutral/
- Verify hovering over neutral button produces a background color of `#dbdbdb`
Fixes #1802

Darken neutral bg hover color by 10%

---

scss/_base_forms.scss
scss/_settings_spacing.scss

- Added extra `padding-right` to `select`s so that the chevron does not overlap text
- Created a new spacing variable `$sph-intra--expanded` which is used here, and will probably be reused wherever there are 1rem icons used as backgrounds
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/forms/selects/
- Add a bunch of text to the first `select` option, e.g:
``` html
<option value="" disabled="disabled" selected="">Select an option Select an option Select an option Select an option</option>
```
- Check that the text and chevron don't overlap
Fixes #1563

Add padding-right to select so chevron does not overlap text

---

docs/en/patterns/icons.md

This space was preventing the 'Design' h3 from parsing correctly.
- Pull code
- Run docs
- Check icons page
- Scroll to bottom, verify heading parses correctly

Remove space from heading hashes

---

docs/static/sass/styles.scss

- Removed custom table styling from Docs sass
- Added padding-left to colour column on Color page
- Pull code
- Open http://0.0.0.0:8104/en/settings/color-settings
- Check that the cells in the colour column have .5rem padding on the left
- Open any page with iframes and check that they have `margin-top: 1rem`

Vanilla docs styling fixes

---

scss/_patterns_pull-quotes.scss

- Reduced pull quote size from h3 to h4
- Refactored `_patterns_pull-quotes.scss` to work with new size, removed redundancies and made use of new spacing variables.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/pull-quotes/
- Check that the quote is extended from the heading-4 placeholder
- Check large and small screens for any design mistakes (design [here](https://github.com/ubuntudesign/vanilla-design/tree/master/Quotes))
Fixes #1779

Reduce pull quote paragraph size + small refactor

---

examples/base/forms/form.html
scss/_base_forms.scss
scss/_base_placeholders.scss
scss/_global_functions.scss
scss/_patterns_card.scss
scss/_patterns_contextual-menu.scss
scss/_patterns_icons.scss
scss/_patterns_inline-images.scss
scss/_patterns_lists.scss
scss/_patterns_modal.scss
scss/_patterns_navigation.scss
scss/_patterns_notifications.scss
scss/_patterns_switch.scss
scss/_patterns_tabs.scss
scss/_settings_colors.scss
scss/_utilities_clearfix.scss
scss/_utilities_hide.scss

- Added settings import to `_base-placeholders.scss` in case you wanted to be super selective about what you include from base
- Removed reference to `%p-button--positive` from base form and replaced with in situ version
- Moved `%u-hide-text` to `_base-placeholders` (encapsulation for switch + icon components)
- Moved `%clearfix` to `_base-placeholders` (encapsulation for list and inline image components)
- Moved `%p-card` to `_base-placeholders`, and extended p-card--highlighted, modal and contextual menu from this placeholder
- Updated highlight bar function so that you can choose position (top or bottom) and whether you want it to sit on top of borders, so it can be used for notification, tab and navigation (and in future p-card--featured)
- Rewrote Notification component to use …

Fix Vanilla component interdependencies

---

examples/patterns/tables/table-expanding.html

- Fixed table expanding example
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/tables/table-expanding/
- Check that when you click the "Show" button the text changes back and forth from "Hide"
Fixes #1592

Fix table expanding example not changing button text

---

scss/_base_button.scss

- Fixed button spacing inside paragraph tags - they should now be spaced identically whether in a `<div>`, `<p>` or not in a container.
- Fixed a bug where if several buttons are placed inline and wrap to a new line, the new line has `margin-left`
- Aligned button text to baseline grid
- Pull code
- Open `/_jekyll/_layouts/default.html` and change `VF_ENV` to `"DEV"`
- `./run`
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/buttons/brand/
- Change any of the `<p>` containers with buttons to `<div>` and check that nothing changes visually (margins and paddings change behind the scenes)
- Add a `<p>` with text before all the button containers, and check again that nothing changes visually if you change them to/from `<div>`s
- Copy and paste a few buttons inside one of the …

Fix button spacing inside paragraph tags

---

examples/patterns/contextual-menu.html

- Added a function to the contextual menu example that closes an open dropdown if you click outside of it
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/contextual-menu/
- Click the `Link`s on the page and check that they close if you click outside of them
Fixes #1593

Fix contextual menu example

---

docs/en/index.md
docs/en/utilities/functions.md
docs/package.json
docs/template.html
docs/yarn.lock

- Updated the Vanilla docs to version 1.7.1 (I will automate this soon, I swear :sweat_smile:)
- Added `Highlight bar` function to Functions page
- Pull code, `cd docs && ./run`, http://0.0.0.0:8104/en/
- Check that the dropdown says 1.7.1 and the hotlink on the index page says 1.7.1
- Go to http://0.0.0.0:8104/en/utilities/functions and check that the Highlight bar function is there

Update Docs to 1.7.1

---

_jekyll/_layouts/default.html
examples/patterns/switch.html
scss/_base_forms.scss
scss/_patterns_switch.scss

- Converted the `.p-switch` component to a checkbox so it can be used without JS
- Updated example page with new markup and removed JS
- Deprecated the old button version, to be removed in v2.0.0
- Changed the baseline grid switch to the new checkbox version
- Aligned the switch component to the baseline grid
- Fixed the focus colour
- Added `width: fit-content` to `<label>`s so you can't click way outside the label to get the input to trigger
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/switch/
- Check that it behaves exactly like https://vanilla-framework.github.io/vanilla-framework/examples/patterns/switch/ (there will be a small difference in vertical spacing)
- Test on Chrome, IE, Edge and Firefox < v58
- Turn on the baseline …

Convert .p-switch from button to checkbox

---

_jekyll/_layouts/default.html
examples/utilities/baseline-grid.html
scss/_utilities_baseline-grid.scss

- Simplified `.u-baseline-grid` utility used in the Vanilla examples pages
- Added an example page
- Pull code
- Check that there is a switch in the bottom-right that can turn on/off the baseline grid
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/headings/default/
- Check that the baseline grid is lined up with the headings
- Open `.env` and change the second line to `JEKYLL_ENV=production`
- Terminate local server and re `./run`
- Check that the switch is no longer present

Simplify baseline utility + add example page

---

scss/_patterns_strip.scss

Apply negative margin of 1px to compensate for height of border.
- Pull code

Align bordered strip to baseline grid using a negative margin

---

examples/patterns/accordion.html

- Added `type="button"` attribute to each button so that if an accordion is placed within a form, it does not trigger submit behaviour.
- Changed names of ids and labels to make them more generic, making cutting and pasting from example section easier.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/accordion/
- Check accordion example and ensure it still works as expected

Update accordion example to be more agnostic

---

examples/patterns/accordion.html

Use event delegation when attaching the accordion panel click event to allow for easier manipulation of the accordion after pageload.

Update accordion example JS to use event delegation.

---

scss/_utilities_image-position.scss

- Added `overflow: hidden` to `u-image-position`
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/utilities/image-position/top-right/
- Change the image dimensions to 500x500
- Check that it doesn't overflow the strip
Fixes #1379

Hide overflow in u-image-position container

---

docs/en/building-vanilla.md
docs/en/customising-vanilla.md
docs/en/index.md
docs/en/metadata.yaml

- Added a "Building Vanilla" page, with info on:
- Using Vanilla with node-sass, gulp-sass, Webpack and Git submodules
- Added a "Customising Vanilla" page, with info on:
- How to configure settings
- How to import components modularly
- Moved the Git submodules section from the "Get started" page to the "Building Vanilla" page
- Updated the index page (moved "What's new" and "Getting help" to be inline, added a Download CTA, included `yarn` as package manager)
- Pull code, `cd docs && ./run`
- Check that the homepage no longer has the Git submodules section, and has a Download button
- Go to http://0.0.0.0:8104/en/building-vanilla
- Check for any spelling, grammar or information errors
- Run through the instructions for the build tools and check that they …

Add Advanced usage page to Vanilla docs

---

docs/static/js/scripts.js
docs/static/sass/styles.scss
docs/template.html

- Updated Vanilla docs sidebar with new [design](https://github.com/vanilla-framework/vanilla-framework/issues/1814)
- Simplified JavaScript
- Made table of contents sticky
- Pull code, `cd docs && ./run`
- Open http://0.0.0.0:8104/
- Check that the sidebar matches the new [design](https://github.com/vanilla-framework/vanilla-framework/issues/1814) - remember to check active state
- Check that it sticks to the top of the screen on desktop, and works as it did before on mobile (sits just below the main nav)
- Check that the search still works on desktop and mobile
- Go to a page with a Table of contents (e.g. Functions) and check that it sticks to the top of the page
Fixes #1814

Update docs with new sidebar design

---

scss/_base_placeholders.scss
scss/_global_functions.scss

- Updated `vf-highlight-bar` to allow left/right placement
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/notifications/notifications/
- Check that the highlight bar is on the top
- Open `scss/_patterns_notifications.scss`
- Change line 26 to `@include vf-highlight-bar($color-mid-dark, left);`
- Reload page and check that the highlight bar is on the left
- Change line 26 to `@include vf-highlight-bar($color-mid-dark, right);`
- Reload page and check that the highlight bar is on the right

Update highlight bar function to allow left/right placement

---

scss/_patterns_code-numbered.scss

- Fixed a styling issue where an empty `.p-code-numbered` block would cut off half the number
- Simplified the Sass and used new spacing variables where possible
- Increased spacing between code lines from .25rem to .5rem
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/code-numbered/
- Replace the `<pre>` with an empty code-numbered block:
``` html
<pre class="p-code-numbered"><code><span class="code-line"></span></code></pre>
```
- Check that the number on the left is aligned properly
Fixes #1597

Fix empty p-code-numbered styling

---

docs/en/base/typography.md
examples/patterns/headings/default.html
examples/patterns/headings/mixed.html

- Rewrote "Heading classes" section of typography docs page to more clearly describe what they do
- Changed the "Headings / Default" and "Headings / Mixed" examples to show the markup
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/headings/default/
- Check that the page shows the markup and is clearer on what the class is doing
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/headings/mixed/
- Check that the page shows the markup and is clearer on what the class is doing
- Run the docs app (`cd docs && ./run`)
- Go to http://0.0.0.0:8104/en/base/typography
- Check that the copy under "Heading classes" and "Mixed heading classes" is understandable
- **Note:** The examples on the docs page will show the old example (no …

Rewrite heading classes examples to be clearer

---

examples/patterns/inline-images.html
scss/_patterns_inline-images.scss

This change ensures that images that are wider than the space allocated to them on small screens do not overflow.
Before this change: https://cl.ly/3r2B3z1E1i36
After this change: https://cl.ly/1d2x2g1Y1l0n
- Pull code
- Ensure Inline Images pattern works as expected across breakpoints

Fix inline image aspect ratio and crop bug

---

docs/template.html

- Updated the [example-js](https://github.com/canonical-webteam/example-js) script to 1.1.0, which includes a "Copy to clipboard" button
- Included relevant stylesheet in the template head
- Pull code
- Go to any page with a large example (e.g. http://0.0.0.0:8104/en/base/table)
- Check that the example markup has a copy button in the top-right, and there is a scrollbar
- Check that clicking the copy button and pasting into a text editor works

Update example-js to 1.1.0

---

gulp/lint.js
gulp/parker.js

- Set performance benchmarks and thresholds according to #1858 
- Changed variable name `benchmarks` to `metrics` which I think makes more sense
- Updated report to show a different colour based on result:
- Under benchmark: green
- Over benchmark, under threshold: yellow
- Over threshold: red (and test fails)
- Removed the `console.log` from `gulp/lint.js`
- Pull code
- Run `./run test`
- Check that everything passes
- Open `gulp/parker.js` and change one of the thresholds to something that will fail
- Run `./run test` and check that it fails
- Run `./run exec yarn report` and check that a simple report is generated that shows metrics that pass benchmarks (green), pass thresholds (yellow), and fail (red)
Fixes #1858

Set performance benchmarks and thresholds

---

docs/en/patterns/images.md

Fix broken link for 'Images' design spec that currently 404s.
Fix broken links in this issue #1871

Fix broken design spec link

---

docs/en/patterns/inline-images.md

Fix broken link for 'Inline images' design spec that currently 404s.
- Update design link title from 'Image design' to 'Inline image design'
Fix broken links in this issue #1873

Fix broken design spec link and update link title

---

scss/_base_typography.scss

- Changed h1 font-weight to 100 (thin)
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/headings/default/
- Check that the top heading has `font-weight: 100`
Fixes #1841

Change h1 font-weight to 100

---

scss/_patterns_tooltips.scss

- Changed padding in tooltip message to be .5rem top and bottom
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/tooltips/
- Hover over any of the buttons
- Check that the padding-top is the same as padding-bottom (0.5rem)
Fixes #1882

1882: Fix padding in tooltip message

---

scss/_base_media.scss
scss/_patterns_matrix.scss

- Removed `align-self: flex-start;` from `img` tags
- Added it to the `.p-matrix__image` pattern
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/matrix/
- Change one of the placeholder images to non-square dimensions (e.g. 120x60)
- Check that the aspect ratio is maintained in all screen sizes
Fixes #1880

1880: Remove align-self from img tags

---

examples/patterns/media-object/media-object-large.html
scss/_patterns_media-object.scss

- Moved placeholders outside media object mixin so they can be invoked without including the whole pattern
- Updated the Media object - large example with a meta-list-item
- Made the media object spacing more flexible and reliable. You should now get nice spacing whether the content comes before or after the metadata, or whether either is present at all.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/media-object/media-object/
- Turn on the baseline grid and make sure all text sits on it nicely (check small + large screens)
- Move `<p class="p-media-object__content">` below the metadata and check that the spacing is good, and the text still sits on the baseline (check small + large screens)
- Open …

1879: Make media object spacing more reliable

---

scss/_base_tables.scss

- Fixed targetting of th and td in tables for padding-right
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/table/
- Give one of the "Header row" cells the class `u-align--right`
- Check that it has 1rem padding-right
Fixes #1883

1883: Fix right-aligned th spacing

---

scss/_base_placeholders.scss
scss/_global_functions.scss
scss/_patterns_footer.scss
scss/_patterns_navigation.scss

- Fixed a bug where mobile navigation menu would get messed up if used in conjunction with a sticky footer
- Fixed a bug where `$sticky-footer: true` wasn't applying `margin-top: auto`
- Removed active state from mobile menu navigation
- Moved `%pseudo-bar` styles to the `vf-highlight-bar` mixin, which is the only case in which it's used
- Pull code
- Open `scss/_vanilla.scss` and add at the top: `$sticky-footer: true`
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/default/ **in Firefox**
- Add the following code just after the `<header>`:
``` html
<footer class="p-footer">
<p>© 2018 Company name and logo are registered trademarks of Company Ltd.</p>
<nav class="p-footer__nav">
<ul class="p-footer__links">
<li class="p-footer__item"> …
```

1892: Fix mobile navigation menu on Firefox

---

scss/_global_functions.scss
scss/_patterns_accordion.scss
scss/_patterns_icons.scss

- Included `vf-url-friendly-color` function in `vf-icon` mixins, so that `#`s become `%23` (so Firefox can render them properly)
- Changed `vf-url-friendly-color` function to return `$color` on fail, for backwards compatibility
- Removed `vf-url-friendly-color` from accordion pattern
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/icons/icons-light/ **in Firefox**
- Check that the icons show up as normal
- Confirm that Percy shows no changes
Fixes #1856

Make icon mixins encode "#" by default

---

examples/patterns/code-snippet.html

Added Js to the code snippet example so it works as intended and the JS can be used for reference.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/code-snippet/
- Click the copy button and verify 'sudo apt-get update' has been added to your clipboard
- Add more than one code snippet to the page and ensure you can copy each different value respectively

Add JS to code snippet example

---

scss/_patterns_accordion.scss
scss/_patterns_icons.scss
scss/_patterns_navigation.scss

- Made each icon pattern its own mixin, e.g. `vf-p-icon-plus` - this allows you to import each icon individually instead of being forced to import all 32.
- Fixed a bug in the sidebar navigation pattern that caused the minus icon to have `display: none` if included before `vf-p-navigation`
- Changed the selector for light icons from `[class$="--dark"] &`, to  `[class*="--dark"] &, &.is-light`. This means that icons inside a `p-strip--dark` will appear light regardless of where the `--dark` suffix appears in the class name (i.e. `p-strip--dark some-other-class` works now). Also you can give an icon a state class `is-light` which will turn the icon into its lighter variation
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/icons/icons-lig …

Make each icon pattern its own mixin

---

examples/patterns/contextual-menu.html

- Rewrote contextual menu example code with ES6 syntax
- Added a listener for the `esc` key to close all menus
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/contextual-menu/
- Check that the links open a contextual menu on click
- Check that clicking outside it closes the menu
- Check that pressing esc closes an open menu
- Resize the screen vertically so that there is a scrollbar
- Click the contextual menu links and check that the page does not scroll automatically
Fixes #1825, fixes #1826

Rewrite contextual menu example with ES6 syntax

---

docs/en/index.md
docs/en/metadata.yaml
docs/en/utilities/baseline-grid.md
docs/en/utilities/functions.md
docs/package.json
docs/template.html
docs/yarn.lock

- Updated the docs app with 1.8.0 content, namely:
- Updated the vanilla-framework package to 1.8.0
- Updated the Functions page with the latest versions of the functions
- Added a page for the Baseline grid utility
- Pull code
- Check that the version in the dropdown is 1.8.0
- Check that all links on the index page work
- Go to http://0.0.0.0:8104/en/utilities/functions and check that the functions match those found in `scss/_global_functions.scss`
- Go to http://0.0.0.0:8104/en/utilities/baseline-grid and check that the page works and is clear what it does

Update Vanilla docs with 1.8.0 content

---

scss/_patterns_tabs.scss

Remove the inline-block whitespace between tabs. Make the scrolling auto so it only shows when its needed.
- Pull code
- Check there are no spaces between the tab items on all screen sizes
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1898
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1899

Remove the inline-block whitespace between tabs

---

examples/patterns/search-box/navigation.html
examples/templates/maas-layout.html

Remove `role="menubar"` from `<nav>` elements in example layouts
- Pull code
#1944

Remove role="menubar" from <nav> in example templates and patterns

---

scss/_patterns_tabs.scss

Add a faded background to the tab arrow. 
Made the placement of the arrow more logical.
- Pull code
- Shrink the screen till the arrow goes over the text
- See there is a white gradient behind the arrow
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1900

Add a faded background to the tab arrow

---

scss/_settings_placeholders.scss

* Added missing `!default` flag at the end of values from `_settings_placeholders.scss`;
- Pull code
- Open `_vanilla.scss` and add a line at the top that overwrites one of values from `_settings_placeholders.scss` 
- Check that the changes take effect on http://0.0.0.0:8101/vanilla-framework/
* Related to issue #1950

Fix missing 'default' flag in placeholders settings (#1950)

---

docs/en/patterns/buttons.md
examples/patterns/buttons/icon.html
scss/_base_button.scss
scss/_patterns_buttons.scss

Add a button state class `has-icon` which stops the button from going full width on small screens.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/buttons/icon/
- Check that the button never goes full width at any screen size
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1922
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1902

Add button has-icon state class

---

docs/en/base/typography.md
examples/base/sub-headings.html

- Approved in WG group [here](https://github.com/ubuntudesign/vanilla-squad/issues/279
)
- Document sub-headings
- Pull code
- Fixes issue here: https://github.com/ubuntudesign/vanilla-squad/issues/279

Add sub-heading example to documentation

---

docs/en/settings/color-settings.md

- Update 'Value' text color on background so it's accessible
- Removed color: `#fff` from `$color-mid-light` and `$color-mid`
- Pull code

Update accessible text on docs example

---

scss/_base_lists.scss
scss/_patterns_lists.scss

- Update border-bottom style and colour
- Updated on - `.p-list--divided` and `.p-definition-list`
- Pull code
- Original issue here: https://github.com/vanilla-framework/vanilla-framework/issues/1954

Update bottom border on list components

---

docs/entrypoint
docs/requirements.txt

- Since we're no longer using Flask, we don't need `entrypoint`, or the extra dependencies in `requirements.txt`.
- Use the latest documentation-builder
QA
--
`./run`, go to http://localhost:8104 and check the site runs.

Remove unnecessary entrypoint files

---

docs/Dockerfile

This is so we can use `netstat` in a `livenessProbe` to check a process is running on port 80.

Add net-tools

---

scss/_base_forms.scss
scss/_patterns_search-box.scss

Update the existing styling to help with UI contrast, making form elements distinct from dividing lines etc.
- Update border colour to `$color-mid`
- Add a focused state with border-color `$color-mid-dark`
- Pull code
Original issue here: https://github.com/vanilla-framework/vanilla-framework/issues/1933

Update form state and border colors

---

scss/_base_button.scss
scss/_patterns_buttons.scss
scss/_settings_placeholders.scss

Updates to button styling and a new active (pressed) state.
- Update `base` and `neutral` button from normal text by using link blue `$color-link`
- Change the border radius to `4px` to make them look different to text fields
- Update border colour on `neutral` button to `$color-mid`
- Added an `active` state to all buttons
- Pull code
- Check buttons look good on styles:
- Base, Neutral, Brand, Positive and Negative
Fixes issues here: https://github.com/vanilla-framework/vanilla-framework/issues/1932

Button styling and state updates

---

examples/patterns/contextual-menu.html
scss/_patterns_contextual-menu.scss

Since buttons have a margin-bottom by default the dropdown was displaying way below the button.
- Added margin-bottom: `$spv-intra;` to toggle so it's applied across link and button
- Updated example layout to show both buttons and links
- Pull code
- Check button and link margin between contextual menu 
- Fixes issue raised here: https://github.com/vanilla-framework/vanilla-framework/issues/1927

Consistent margin applied to link and button on p-contextual-menu

---

examples/patterns/media-object/media-object-circ-img.html
examples/patterns/media-object/media-object.html
scss/_patterns_icons.scss
scss/_settings_spacing.scss

Updated various icon sizes across the framework and tidied the icon size list.
- Pull code
- [Media object](http://vanilla-framework-pr-1999.run.demo.haus/vanilla-framework/examples/patterns/media-object/media-object/ ) - Check that icon is 3rem
- [Heading icon](http://vanilla-framework-pr-1999.run.demo.haus/vanilla-framework/examples/patterns/heading-icon/) - Check large/medium screens: 3rem, Small screens: 2rem
-  [Social icons](http://vanilla-framework-pr-1999.run.demo.haus/vanilla-framework/examples/patterns/icons/icons-social/) - Check that icon is 2rem
- Confirm that no unexpected changes are in [Percy](https://percy.io/vanilla-framework/vanilla-framework/builds/1033224)
- Thank @deadlight for manually adding …

1887 icon sizes

---

scss/_patterns_tooltips.scss

Removed the minimum width for tooltips
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/tooltips/
- Use the inspector to make the text of one of the tooltips one character
- See that the tooltip fits to the text
Fixes #1959

Remove min-width for tooltips

---

docs/en/patterns/code-copyable.md

- Updated docs link example so it doesn't 404
- Pull code
- Check that correct link is displaying
- https://vanilla-framework.github.io/vanilla-framework/examples/patterns/code-snippet/
Fixes issue https://github.com/vanilla-framework/vanilla-framework/issues/1965

Example docs link updated

---

examples/base/table.html
examples/patterns/tables/table-expanding.html
examples/patterns/tables/table-mobile-card.html
examples/patterns/tables/table-sortable.html
examples/templates/maas-layout.html

Remove obsolete `<table>` scope attributes as they were made obsolete by HTML5 [1]
[1] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td#attr-scope
- Check through the code and ensure only scope attributes have been removed
- Check that no SCSS uses this attribute as a styling hook

Remove obsolete <table> scope attributes

---

examples/patterns/heading-icon/heading-icon-stacked.html
examples/patterns/heading-icon/heading-icon.html
scss/_patterns_heading-icon.scss

Added stacked heading-icon variant.
- Pull code
- See that there are now two variants of the heading-icon pattern:
- Heading icon / Default
- Heading icon / Stacked
- Check them against the design in #1903 
Fixes #1903

Add a stacked variant of headings with icons

---

docs/en/patterns/heading-icon.md

Added example to documentation for new component.
- Pull code
- Check you can see Heading icon stacked example
Fixes issue #1903

Add new heading icon stacked example

---

examples/base/forms/checkboxes.html
examples/base/forms/radio-buttons.html
scss/_base_forms.scss

- Updated checkbox style to match [design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Forms)
- Updated radio button to match [design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Forms)
- Updated the examples page to show checked, unchecked and disabled
- Pull code, `./run`
- Go to http://0.0.0.0:8101/vanilla-framework/vanilla-framework/examples/base/forms/checkboxes/
- Check that it matches the [design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Forms)
- Go to http://0.0.0.0:8101/vanilla-framework/vanilla-framework/examples/base/forms/radio-buttons/
- Check that it matches the [design spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Forms)
- Check that the new designs look the same cross-browser, according to …

Update checkboxes and radio buttons to match design spec

---

scss/_settings_breakpoints.scss
yarn.lock

- Original discussions can be found here: ubuntudesign/vanilla-design#289
- Updated max-width values on: 
- `$breakpoint-large` to 1036px
- `$breakpoint-medium` to 772px
- Pull code
- Check new values match on breakpoints `large` and `medium`
- Fixes issues here - https://github.com/vanilla-framework/vanilla-framework/issues/1931

Update max-width values on breakpoints

---

Gemfile.lock
scss/_base_button.scss
scss/_patterns_buttons.scss
scss/_patterns_icons.scss

- Reverted top and bottom button padding to match form input elements
- Changed left and right padding to `.75rem/12px`
- Pull code
- Go to http://0.0.0.0:8101/vanilla-framework/examples/patterns/buttons/icon/
- Check that the button with only icon is square (note it's not a *perfect* square - 38 x 36.78)
- Go to http://0.0.0.0:8101/vanilla-framework/examples/patterns/forms/form-inline/
- Check that the buttons are the same height as the form inputs
- Check both in Chrome and Firefox because there's some weirdness with how each determine inline-block spacing
Fixes #2016

2016 - Update button paddings with and without icon

---

scss/_patterns_notifications.scss

Made the close icon work when placed in all kinds of notificaitons
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/notifications/notifications/
- See that the close button is displayed correctly
- Modify `patterns/notifications/notifications.html` and give the notification the `--positive` modifier
- See that the close button still works!
Fixes #1928

Fix close button styling for all variants of notification

---

scss/_base_blockquotes.scss
scss/_base_typography.scss

Fix the bottom spacing of blockquotes.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/blockquotes/
- See that the bottom spacing is now good 
Fixes #1988

Fix spacing at bottom of blockquotes

---

docs/en/patterns/lists.md
examples/patterns/lists/lists-stepped-detailed.html
examples/patterns/lists/lists-stepped.html
scss/_patterns_lists.scss

Made stepped lists support `<h1>` to `<h6>` 
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/lists/lists-stepped/
- See that there are now two sizes
Fixes #1889

Stepped list update

---

scss/_patterns_strip.scss

Changed the borders on strips - which caused issues with the baseline grid - by making p-strip position: relative by default and use %vf-pseudo-border--bottom
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/strips/is-bordered/
- See that the strip is bordered
- Add another strip to the markup with the "--light" modifier and see that the border is visible
- High five me
Fixes #2045

Fix strip borders

---

scss/_base_typography.scss

Update `<abbr>` cursor style to "help"
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/abbr/
- Hover over the abbreviation
- See the 'help' cursor
Fixes #1962

Update <abbr> cursor to 'help'

---

docs/en/base/forms.md
examples/patterns/forms/form-validation.html
scss/_patterns_form-validation.scss

Added a way of handling select dropdowns with validation states.
This requires additional markup but is the cleanest option I can find.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/forms/form-validation/
- See the dropdown error state (other states can be seen by changing the parent's class)
Fixes: #2044

Add a method of handling form validation for select dropdowns

---

scss/_patterns_navigation.scss

Used the lighten function to lighten the on-hover colour of nav items in darker instances of navigation
- Pull code
- See that the navigation is light with slightly darker hover states on the nav items
- Edit /scss/build.scss
- Add a new line at the beginning of the file: ```$color-navigation-background: #001;```
- Wait for the CSS to be rebuilt
- Refresh the demo
- See that the nav is very dark blue and a lighter blue on hover
- Experiment with other colours
Fixes #1604

Make hover state visible when navigation background is a darker colour

---

docs/en/404.md
docs/nginx.conf

Added a 404 page very much like the main site one but with the docs sidebar
- Pull code
- cd into /docs
- `./run build`
- `docker build --tag vanilla-docs --build-arg COMMIT_ID=nope  .`
- `docker run -ti -p 8099:80 vanilla-docs`
- go to: http://localhost:8099/not-a-real-page
- See the error
Fixes https://github.com/canonical-websites/vanillaframework.io/issues/175

Add 404 page content and updage nginx config to use it

---

scss/_base_forms.scss

Unhide reset buttons by default
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/forms/form/
- Inspect the submit button and change the type to "reset"
- See that the button remains visible
Fixes #2067

Remove default hiding of reset buttons

---

scss/_utilities_sticky-footer.scss

Updates `height: 100%` into `min-height: 100vh` for sticky footer.
Using `height: 100%` was causing layout issues (forcing body to always have the height of the viewport). For example https://github.com/canonical-webteam/global-nav/issues/62
Using `min-height: 100%` didn't do the trick, but it seems new viewport units can do what we need.
Now `html` and `body` will have minimum height of the viewport when there is little content, and will grow larger when content doesn't fit on the screen.
- Pull code
- Enable $sticky-footer
- Create an example page with sticky footer
- Check if sticky footer works

Use 100vh instead of height 100% on body with sticky footer

---

docs/template.html

- Added Usabilla code snippet
- Created a feedback form for https://docs.vanillaframework.io/en/ following same style added to https://vanillaframework.io/en/
- ./run
- Go to https://docs.vanillaframework.io/en/
- Check you can see 'Site feedback' button bottom right of your viewport
- Click and see if feedback modal is working
- Fixes: https://github.com/ubuntudesign/vanilla-squad/issues/487

Add Usabilla to documentation site

---

scss/_patterns_card.scss

currently, ^= selector doesn't apply when .p-card is preceded by another class. Switching to *= fixes that.
Change selector from ^= to *=
- Pull code
- Verify that prepending a class to the p-card div doesn't cancel the small margin on the last-child text element of a card

card p:last-child – fix selector from "starts with" to "contains"

---

scss/_base.scss
scss/_base_forms.scss
scss/_base_tables.scss
scss/_settings_spacing.scss

Corrects vertical rhythm by setting the line-height of table headers to 1rem (from 1.25rem)
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/base/table/
- Turn baseline grid on
- Observe table row borders sitting properly on baseline grid

Override th line-height to keep table borders on the baseline grid

---

docs/en/patterns/icons.md
examples/patterns/icons/icons-dark.html
examples/patterns/icons/icons-light.html
examples/patterns/icons/icons-social.html

- Updated the icon table to include classes
- New visual layout
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/icons/
- Check that all three of the examples in the list are updated correctly on documentation
- Light / Dark / Social
- Fixes #2058

Updates to 'Icons' layout on docs

---

docs/en/settings/color-settings.md

- Updated docs color page to use card styles
- Pull code and `cd` into `/docs`
- Run `./run`
- Open http://0.0.0.0:8104/en/settings/color-settings
- Check that the page looks super flash

Update docs color page to use card styles

---

docs/en/patterns/icons.md
examples/patterns/icons/icons-social.html

Remove Google + icons from Documentation as it's soon to be canned.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/icons/icons-social/
- Check Google+ is no longer visible
- Check documentation: patterns/icons#share-icons and see that Google+ is no longer visible too
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/2143

Remove Google + icons 

---

examples/patterns/tooltips.html
scss/_patterns_tooltips.scss

- Updated tooltip styling to reposition left- and right-aligned variants (this brings the pointing arrow to the edge of the element, which is especially important for smaller elements like icons). See #1791 for more detail.
- Updated example tooltip markup to avoid cropping
- Pull code
- Go to http://0.0.0.0:8101/vanilla-framework/examples/patterns/tooltips/
OR
- Go to https://vanilla-framework-vanilla-framework-pr-2152.run.demo.haus/vanilla-framework/examples/patterns/tooltips/
Fixes #1791 
Fixes #2066

1791 tooltip placement

---

scss/_utilities_vertically-center.scss

Remove media query so that .u-vertically-center works at all viewports
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/utilities/vertically-center/
- Resize to a mobile viewport and see that the example is vertically centred
Fixes #2132

Remove media query so that .u-vertically-center works at all viewports

---

scss/_base_typography.scss

Added the paragraph max width to labels for consistency in typographic elements.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/forms/form-help-text/
- Inspect the element and add enough words for the label to wrap
- See that it's now wrapping sooner
Fixes #2154

Add max-width to <label> elements

---

scss/_base_button.scss
scss/_base_forms.scss
scss/_base_hr.scss
scss/_base_placeholders.scss
scss/_base_tables.scss
scss/_patterns_accordion.scss
scss/_patterns_buttons.scss
scss/_patterns_card.scss
scss/_patterns_code-copyable.scss
scss/_patterns_contextual-menu.scss
scss/_patterns_divider.scss
scss/_patterns_lists.scss
scss/_patterns_matrix.scss
scss/_patterns_navigation.scss
scss/_settings_placeholders.scss
scss/_settings_spacing.scss
scss/_utilities_vertical-spacing.scss

To be able to change the :root font-size on a breakpoint, we need to remove any variables that assume 1 rem is a constant value. This is because any calculations will be wrong once that value changes from 16 to e.g. 18.
In our case, the only such variable is $px, which is used where the presence of a bordr shouldn't ypset the vertical rhythm. E.g. the padding on a button is calculated as
```{padding top in rems} -  $px, where $px is .0625rem (1/16 of a rem)```
This pr changes these calculations to:
```calc(#{rem-value} - 1px)```
In some places as in the checkbox, px values are converted to rem values, so they scale properly as well.
- Pull code
- Verify nothing looks broken …

Remove  $px  var in preparation for font-size change

---

scss/_patterns_tooltips.scss

Completes the work started in https://github.com/vanilla-framework/vanilla-framework/pull/2164
for the issue described here:  https://github.com/ubuntudesign/vanilla-squad/issues/509
- Pull code
- QA code and verify it doesn't lead to visual regressions
Replaces tooltip values in px with rems

unhardcode tooltip triangle dimensions and offsets

---

docs/en/metadata.yaml
docs/en/utilities/no-print.md
examples/utilities/no-print.html
gulp/parker.js
scss/_utilities_no-print.scss
scss/_vanilla.scss

Added `u-no-print` utility
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/utilities/no-print/
- Pretend to print the page and see that one of the paragraphs doesn't show in the preview (don't really print, think of the :deciduous_tree:!)
- `cd docs`
- `./run`
- See that the [documentation exists](http://0.0.0.0:8104/en/utilities/no-print)
Fixes #1982

Add u-no-print utility to exclude elements from printed pages

---

scss/_base_forms.scss
scss/_base_typography-definitions.scss
scss/_base_typography.scss
scss/_patterns_article-pagination.scss
scss/_patterns_lists.scss
scss/_settings_breakpoints.scss
scss/_settings_font.scss
scss/_settings_spacing.scss

• Add a flag to increase font-size at a given breakpoint (currently 1440px)
• Add nudge value adjustments to headings that require it at the bigger font-size (18px)
• [drive-by] Fix inaccurate mobile nudges for h1 and h3
• [drive-by] Add space-after to h4 on mobile consistent with other headings
- Pull code
– QA both code and visually in percy
Implements https://github.com/ubuntudesign/vanilla-squad/issues/511

Add optional font-size increase on a breakpoint

---

scss/_base_code.scss
scss/_settings_spacing.scss

Change white space on ```<pre>``` from pre-wrap to pre. This prevents code from wrapping when element is not wide enough.
Before:
After: 
1. Go to code example on the demo
2. Resize Screen so code sample becomes longer than available width.
3. Observe lack of wrapping
Fixes #2032 
Fixes #1986

Fix pre and code white space (fixes #1986) and removes white space styling from <code> 

---

examples/templates/tick-element-comparison.html
scss/_base_forms.scss
scss/_base_typography.scss

Checkboxes, radio buttons and their labels are not aligned to the baseline grid. This PR corrects that.
It also adds a class called ```.is-inline-label```, which removes the padding top (nudge that aligns text to the baseline grid). This is useful when you want to align the label to text that is not wrapped in a tag, e.g. ```<td>text here</td>```
In addition, it fixes #2186 
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/templates/tick-element-comparison/
- Turn baseline grid on
- Verify all text sticks to the baseline grid
The example above also shows that the vertical space between checkboxes / radios matches the space between paragraph and button.

Align tick elements to baseline grid

---

docs/en/patterns/pull-quote.md
examples/patterns/pull-quotes/default-image.html
scss/_base_blockquotes.scss
scss/_patterns_pull-quotes.scss
scss/_settings_spacing.scss

Add image heading option for pull-quotes
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/pull-quotes/default-image/
- To see other sizes change the `p-pull-quote` class to `p-pull-quote--small` or `p-pull-quote--large`
Fixes #1961

Add image option to pull quotes

---

scss/_base_button.scss

Set top, left, and right margin to 0 explicitly to override the 2px margin added by safari on mac.
- Pull code
- Open any button example in safari
- Observe buttons have all but bottom margin set to 0
Fixes #2191

Fix margin in Safari

---

docs/en/patterns/breadcrumbs.md
examples/patterns/breadcrumbs.html

- Updated parts of the copy
- Check content matches copy doc [here](https://docs.google.com/document/d/1FK485n4m21iCU_yt3DrsAcBPeiukpWUUQZLX4_PGXSM/edit#heading=h.ifh1f0ulklnm)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/breadcrumbs
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/breadcrumbs
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/379

Update docs/breadcrumbs page content

---

scss/_base_typography-definitions.scss
scss/_settings_font.scss
scss/_settings_spacing.scss

1) Best practices recommend allowing the browser to control font-size. In order to do that, the root font-size needs to be set to 1rem. 
2) Move the last remaining font setting (font-size) into a map in the settings_spacing file. This is for consistency with the rest, and to make it easier to survey the font-sizes all in one place.
- Pull code
- [in chrome](https://support.google.com/chrome/answer/96810?hl=en-GB); In firefox go to about:preferences > general > change default font-size
- observe how everything scales

Font size improvement

---

docs/en/patterns/navigation.md
examples/patterns/navigation/default.html
examples/patterns/navigation/subnav.html

- Updated copy and remove sidebar navigation (as it will be deprecated)
- Check content matches copy doc [here](https://docs.google.com/document/d/1FK485n4m21iCU_yt3DrsAcBPeiukpWUUQZLX4_PGXSM/edit#heading=h.b0krna2wthn0)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/navigation/
- Pull code
- Run ./run
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/navigation/default/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/subnav/
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/345

Update docs/navigation page content

---

examples/templates/typographic-spacing.html
scss/_base_typography-definitions.scss
scss/_settings_spacing.scss

Due to browser rounding, text elements start to drift from the baseline grid after a few hundred lines.
To minimise this, I'm adding a small constant that forces the rounding to happen so that text stays on the baseline. 
- Pull code
- Paste 1000 lines of text in any heading style (or checkout this [file ](https://github.com/lyubomir-popov/vanilla-framework/blob/thousand-line-test/examples/templates/typographic-spacing.html) that includes a script to generate text)
- Observe no drift from baseline

Baseline fixes

---

docs/en/patterns/links.md
examples/patterns/links/links-external.html
examples/patterns/links/links-strong.html
examples/templates/external-links.html
scss/_base_forms.scss
scss/_patterns_links.scss

Completely removed the `.p-link--strong` class
Drive-by: fixed a lint issue
- Pull code
- See that the strong link doesn't appear in the list
- `cd docs && ./run`
- See that there are no references to the removed style
Fixes #1996

Remove strong link

---

.travis.yml
scss/_utilities_baseline-grid.scss
scss/_utilities_embedded-media.scss

Un-nest class names in utils. 
Keep classes in full unless absolutely necessary.
- Pull code
- No visual changes
Fixes #2089

Un-nest elements in utils

---

examples/patterns/code-numbered.html
scss/_patterns_accordion.scss
scss/_patterns_article-pagination.scss
scss/_patterns_aside.scss
scss/_patterns_breadcrumbs.scss
scss/_patterns_code-copyable.scss
scss/_patterns_code-numbered.scss
scss/_patterns_contextual-menu.scss
scss/_patterns_divider.scss
scss/_patterns_form-validation.scss
scss/_patterns_heading-icon.scss
scss/_patterns_headings.scss
scss/_patterns_image.scss
scss/_patterns_inline-images.scss
scss/_patterns_links.scss
scss/_patterns_list-tree.scss
scss/_patterns_lists.scss
scss/_patterns_matrix.scss
scss/_patterns_media-object.scss
scss/_patterns_modal.scss
scss/_patterns_notifications.scss
scss/_patterns_pagination.scss
scss/_patterns_pull-quotes.scss
scss/_patterns_search-box.scss
scss/_patterns_slider.scss
scss/_patterns_switch.scss
scss/_patterns_table-mobile-card.scss
scss/_patterns_tooltips.scss

Unnested sass used solely to generate classnames.
e.g.:
```
.foo {
color: #990000;
&__bar {
padding: 0;
}
}
```
becomes:
```
.foo {
color: #990000;
}
.foo__bar {
padding: 0;
}
```
This was a decision taken following discussion in a developer catch up. Key benefits include:
- Full classnames are now searchable in files
- Nesting depths are reduced
- Generated CSS is closer to the source SASS, allowing more mindful CSS generation
Also fixed some class names that weren't proper BEM.
- Pull code
- See no visual differences
Fixes #2091

Pattern nesting

---

docs/en/patterns/heading-icon.md
examples/patterns/heading-icon/heading-icon-small.html
examples/patterns/heading-icon/heading-icon-stacked.html
examples/patterns/heading-icon/heading-icon.html

- Check content matches copy doc [here](https://docs.google.com/document/d/1BaY3k01-6zvhC67PMxZD44IKHs4_pTpPm_ix98rHW98/edit#heading=h.m8r6djutwkm5)
- Pull code
- Check http://0.0.0.0:8104/en/patterns/heading-icon
- Pull code
- Run ./run
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/heading-icon/heading-icon/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/heading-icon/heading-icon-stacked/
- Check http://0.0.0.0:8101/vanilla-framework/examples/patterns/heading-icon/heading-icon-small/
- Fixes https://github.com/ubuntudesign/vanilla-design/issues/356

Update docs/heading icon page content

---

docs/sass/styles.scss

Fixed the docs sidebar width by swapping for a raw value instead of a setting which is used in the code numbered pattern. This is the only use of this variable so lets keep it simple. 
- Pull code
- Run `cd docs/`
- Check that the navigation has a decent width
- Check that the navigation continues to work on small screens
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/2258
Before:
After:

Fix the docs sidebar width

---

docs/package.json
docs/template.html
docs/yarn.lock

Reverted the TOC classes and bumped the version of Vanilla to v1.8.1
- Pull code
- Run `cd docs/`
- Open http://0.0.0.0:8104/en/base/forms
- Check that the TOC is styled nicely and matched the screenshots in the issue.
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/2260

Reverted the TOC classes

---

docs/en/settings/animation-settings.md
scss/_utilities_animations.scss

Added overrides to stop animations if the user has set the prefer-reduced-motion flag.
- Set the setting in your operating system - [Mac OS instructions](http://osxdaily.com/2018/12/17/how-reduce-motion-mac-disable-animations/)
- Check that you are using a [supported browser](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#Browser_compatibility)
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/icons/icons-light/
Fixes #2116

Add override to remove motion when the user has set prefer-reduced-motion

---

scss/_patterns_accordion.scss

Moved the icons to the left of the accordion pattern and modified padding to match
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/examples/patterns/accordion/
- See that the icons are on the left and that padding looks good when expanded
Fixes #2008

Swap the icons in accordions to the left

---

examples/base/code.html
scss/_base_code.scss

Added a highlight to inline code elements
- Pull code
- http://0.0.0.0:8101/vanilla-framework/examples/base/code/
- See that the lower example matches the [spec](https://github.com/ubuntudesign/design-vanilla-framework/blob/master/Code/code.md)
Fixes #2040

Add a highlight to inline code elements

---

_jekyll/_layouts/default.html
index.html

- Little zhoosh of our examples page
- Update hero banner, heading titles and type hierarchy
- Link styling
- Pull code
- Look at the new shiny layout
- Downtime

Vanilla examples page zhoosh

---

docs/en/patterns/tabs.md
examples/patterns/tabs.html

Updated the tabs example to put it in a row to show how to have it sit properly with other content.
I also updated the docs to mention it.
- Pull code
- See that it now has gutters
Fixes #1894

Update the tabs example to include nesting within a row and update docs

---

docs/_layouts/default.html
docs/redirects.map

Add back the hidden searchable `docs-list-sorted`, so the search box at the top of the nav works again.
QA
--
`./run`, go to http://0.0.0.0:8101/, try searching the nav.

Fix nav search

---

scss/_base_forms.scss
scss/_patterns_icons.scss
scss/_patterns_subnav.scss

- Replace old icon with guillemette.
- Change select icon color from legacy platform grey (#888) to currently used #666.
- Fix size to match chevrons in subnav.
Add pointer-events: none on icon so the pointer doesn't change to regular mouse pointer when you hover on it.
- Pull code
- QA subnav and select
Fixes: https://github.com/canonical-web-and-design/vanilla-framework/issues/2189

Replace chevron icon with guillemette

---

scss/_patterns_strip.scss

Fix selector so "someclass  p-strip is-shallow" works. Currently, p-strip needs to be the first class for this rule to apply:
[class^='p-strip'].is-shallow 
changed to [class*='p-strip'].is-shallow 
- Pull code
- Verify that preceding p-strip in the markup by another rule doesn't cancel the effect of e.g. "is-shallow"

fix strip selector so class order doesn't matter

---

scss/_patterns_card.scss

I noticed a few places on ubuntu.com (when run on 2.0 alpha) where this happens:
This pr fixes the border to appear after the white space.
- Pull code
- Open card example, add header class, observe correct position of border

remove duplicate code. convert margin to padding so it pushes border down

---

scss/_patterns_lists.scss

Fix icon position when text wraps.
- Pull code
- Open http://192.168.64.7:8101/examples/patterns/lists/lists-dividers-ticked/
- Resize to force wrap; observe icon is properly aligned with text.
Fixes #2313

fix tick position

---

scss/_patterns_grid.scss
scss/_patterns_lists.scss
scss/_utilities_layout.scss
scss/_vanilla.scss

Often content doesn't need to align to grid columns, but needs to be restrained by the fixed-width used by the grid. To provide that functionality separately, I've extracted fixed-width behaviour from .row into a placeholder, then .row and a new .u-fixed-width class extend that. 
- Pull code
- Change row to u-fixed-width in any example. Observe how content within stays aligned to the fixed-width of the site.

Fixed width class

---

docs/examples/patterns/buttons/base.html
scss/_base_button.scss

Rename incorrect ".is--disabled" class to ".is-disabled" to match class name rules elsewhere in the project
- Pull code
- http://0.0.0.0:8101/examples/patterns/buttons/base/
- See that the disabled buttons both look similar
Fixes #2236

Fix base buttons class - .is--disabled to .is-disabled

---

docs/examples/patterns/tooltips.html
scss/_patterns_tooltips.scss

Fixed tooltips so that they only need one class.
- Pull code
- Open http://0.0.0.0:8101/examples/patterns/tooltips/
- See that they look the same
Fixes #2324

Refactor tooltips so that they no longer require class duplication

---

scss/_patterns_grid.scss
scss/_patterns_lists.scss

col-* classes do not explicitly have display set to block; this leads to situations like this:
This pr corrects that.
QA percy screenshots

Block cols

---

scss/_base_tables.scss
scss/_patterns_accordion.scss

Fix cacordion line bottom and lack of margin under p; also fix table line-height at largest breakpoint (it was inheriting from html, instead of being set to paragraph line-height)
- Pull code
- QA /examples/patterns/accordion/
Fixes 2289

Fix 2289 (accordion)

---

docs/patterns/grid.md

Updated the grid docs section on empty columns
- Pull code
- http://0.0.0.0:8101/patterns/grid/
- Check that the formatting in the "Empty columns" section looks good

Docs: reformat and clarify grid docs

---

docs/examples/patterns/forms/form-stacked.html
scss/_patterns_forms.scss

Remove hardcoded css widths; update example to use the grid
- Pull code
- QA /examples/patterns/forms/form-stacked/
Fixes #1921

Stacked form: replace hardcoded layout with grid classes

---

scss/_patterns_navigation.scss

Fixes #1740.
- Pull code
- Open /examples/patterns/navigation/subnav/
- Add enough text to make menu item longer than 20 em
- Observe ellipsis

Ellipsise nav links longer than 20em

---

docs/examples/patterns/grid/bordered.html

Before:
After:
- Pull code
- Open /examples
- Verify grid example name is correct

correct name of grid bordered row example

---

scss/_base_placeholders-margin-collapse.scss
scss/_base_typography-definitions.scss
scss/_utilities_margin-collapse.scss

- Includes the referenced margin collapse utility into the typography base definitions
- Create a new folder `mkdir test`
- init a new npm repo `cd test && npm init` and just press enter on all questions
- install node-sass `npm i node-sass`
- create a file styles.scss `mkdir syles.scss` and include the following content:
```
@import "node_modules/vanilla-framework/scss/base_typography";
@include vf-b-typography;
```
- run node-sass on the file and make sure it transpiles `npx node-sass styles.scss`
The base typography definitions are using a mixin that is defined in the margin collapse utility.
In order to make the typography includable in isolation it needs to include all referenced functionality.
**This is the error without this fix**

Includes the referenced margin collapse utility into typography

---

docs/patterns/heading-icon.md

Updated the heading-icon docs to include the examples and updated the examples to include a line break to give additional spacing at the top.
- Pull code
- Open http://0.0.0.0:8101/patterns/heading-icon/
- See that the examples look good
Fixes #2349

Docs: correct the path for the heading-icon examples. 

---

README.md

The instructions should recommend `@include vanilla` over `build` (as they already do in `docs/index.md`)

Update README to match docs/index.md

---

scss/_patterns_navigation.scss
scss/_patterns_subnav.scss
scss/_patterns_tabs.scss
scss/_settings_colors.scss

There should be no visual changes to the navigation, the code is just restructured
- Pull code
- http://0.0.0.0:8101/examples/patterns/navigation/default/
- See that the navigation looks good
- Change $color-navigation-background in `_settings_colors.scss` to #000
- http://0.0.0.0:8101/examples/patterns/navigation/default/
- See that the colours still work together
Fixes #2046

Add new variable - with default values - for navigation border and text colours

---

docs/examples/base/table.html
docs/examples/patterns/list-tree.html
scss/_base_tables.scss

• We're missing row border styling on tfoot trs. I've updated the css and markup to fix that.
• add vertical-align:top to td and th
• Drive by: remove leftover p-link--strong references
- Pull code
- Open /examples/base/table/
- Verify vertical align and tfoot styling work as expected

tfoot border, remove leftover strong link references

---

.spelling
CONTRIBUTING.md
README.md
docs/_layouts/default.html
docs/building-vanilla.md
docs/index.md
docs/patterns/grid.md
docs/patterns/navigation.md
package.json
scss/_patterns_subnav.scss
tests/parker.js
yarn.lock

Replace Gulp toolset with native NPM scripts
Drive by update to the repo address
Fixes some spelling mistakes to get lint passing
Bumped the filesize threshold form 175kb to 200kb to pass linting 
- Pull code
- Run `./run clean`
- Run `./run test`
- Run `./run watch`
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2371

Kill gulp with fire

---

scss/_base_typography.scss
scss/_settings_font.scss

we have two sass maps called font-sizes, one dealing with the font-size increas on bigger screens, the other contianing font-sizes for headings. I've renamed the latter to base-font-size as it only changes the computed value of 1rem.
Currently the font-size increase doesn't happen, because apparently the headings one overwrites the previously defined one,  and the rules silently fail.
- Pull code
- Verify on screens >1681px the font-size increase happens.

Fix map name conflict

---

scss/_patterns_navigation.scss

Made the navigation elements full width at smaller screens
- Pull code
- Open http://0.0.0.0:8101/examples/patterns/navigation/default/
- Resize the browser to the smallest viewport
- Interact with the nav and see that it's full-width

Fix nav styling at smaller viewports so that it's full-width

---

docs/index.md
yarn.lock

Updated all references to version 1.8.1 as the latest version of the framework to 2.0.0
- Pull code
- See that 2.0.0 is mentioned in the content
*NOTE* The links will be broken until the framework is deployed

Update 1.8 refs

---

scss/_base_placeholders.scss
scss/_base_typography.scss
scss/_patterns_grid.scss
scss/_settings_font.scss
scss/_settings_grid.scss

Add !default at the end of grid col variables, so they can be overriden. Useful for something like the migration temp scss file, the goal of which is to produce a pr that is mergeable with the least amount of changes.

Make grid col names overrideable

---

docs/_layouts/default.html
docs/settings/table-layout.md
scss/_base_tables.scss
scss/_settings_tables.scss
scss/_utilities_layout.scss

Address feedback on https://github.com/canonical-web-and-design/vanilla-framework/pull/2384 (part 1)
- Pull code
- Verify if statement is corrected
– Check text in /settings/table-layout/ is updated to omit the part mentioning 'requires setting explicit widths', Vanilla is capitalised, and properties are in backticks

address feedback on #2384 (part 1)

---

docs/patterns/icons.md

- Fixed `p-icon--contextual-menu` as it was missing
- Updated to `p-icon--drag` in the table
- Added `p-icon--anchor` to the list
- Pull code
- Scroll to Icons and check `p-icon--drag` and `p-icon--anchor` now feature in the list, check standard and standard dark table list.
- Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2385 and https://github.com/canonical-web-and-design/vanilla-framework/issues/2386

Update docs icon examples

---

scss/_patterns_lists.scss

Moved the lists placeholders to that they are available when composing vanilla components, rather than including all components
- Pull code
- Edit `scss/build.scss' to the following:
```
// Import Vanilla framework
@import 'vanilla';
// Include base Vanilla styles
@include vf-base;
// Include the components you want
@include vf-p-buttons;
@include vf-p-forms;
@include vf-p-links;
```
- Run `./run`
- See that there are no longer errors
Fixes #2391

Refactor lists sass so that placeholders are in global scope

---

docs/index.md
package.json
scss/_settings_system.scss

Bumped the version of the framework to 2.1.0
- Pull code
- Run `./run`
- See that the links and references have been updated on the homepage

Bump framework version to 2.1.0

---

docs/examples/patterns/tables/table-expanding.html

Fixed extra double-primes in expanding table code example
- Pull code
- Look at the expanding table docs section
- See that there are no extra symbols 
If you go to https://docs.vanillaframework.io/base/tables/#expanding and look at the code example for expanding table you should see instances of `"=""` on the `th` and `td` elements

fix extra double-primes in expanding table code example

---

scss/_settings_grid.scss

$grid-gutter-column-ratio is no longer used. Grid gutters are now defined in https://github.com/canonical-web-and-design/vanilla-framework/blob/588530e9ecf7090acbb9a9953e527c905ada8917/scss/_settings_grid.scss#L14, so this var can be removed
- Pull code
- verify var has been deleted and there are no remaining references to it

remove var that is no longer used

---

docs/examples/patterns/grid/nested-medium.html
scss/_patterns_grid.scss

- The selector for rows inside col-* classes was too specific (.col-9>.row). So it wouldn't apply when we have .row>.col-9>.p-card>.row as there's a div in between. I've stripped the ">" from the selectors to remedy that.
- Drive by typo fix in nested columns example
- Drive by fix order of classes in generated css, to prevent this from happening: (.col-3 .row should be defined after .col-6 .row, as you can't have a col-6 inside a col-3b but you can have col-3 inside col-6)
- Pull code
- Open examples/patterns/grid/nested/
- Ensure nesting works as expected when you resize
- Insert a div in between one of the parent .col-* divs and a child .row; ensure this also works as expected
[if relevant, include a …

Ensure nested rows get correct column count when not direct children of cols

---

docs/base/forms.md

Update text in the checkboxes section of the documentation
- Go to https://docs.vanillaframework.io/base/forms/#checkbox
- See that the first paragraph states that checkboxes can appear in four states, but only lists three
- Also see that the text refers to the listed states as both
- Pull code
- Go into docs directory (`cd docs`)
- Run `./run serve`
- Open http://0.0.0.0:8104/en/base/forms#checkbox
- See that the first paragraph makes sense

Fix misleading text in checkbox docs

---

docs/patterns/grid.md
scss/_settings_grid.scss

Grid gutters in vf 2.0 are fixed, not percentage The values they are fixed to are adjusted per breakpoint. THe desktop breakpoint was set too high - 2.5rem, when in fact 2rem would match the older grid closer. I've changed it to 2 rem to reflect that.
- Pull code
- Open /examples/patterns/grid/default/
- Verify grid gutters are 2rem

update grid gutter to 2rem, as it is a closer match to vf 1.8

---

.travis.yml

- Removed `1600px` viewport from Percy as it's eating up bandwidth and our Snapshots
- Pull code
- Check viewport has been removed on a Percy diff
- Originally put in for testing larger screen breakpoints for v2.0.0

Remove 1600px viewport from Percy

---

scss/_patterns_icons.scss

Added default variables for overriding background and foreground colours on the social media icons
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/examples/patterns/icons/icons-social/
- Hover over the icons and check the colours
Extra credit:
- override the variables `$color-social-icons-foreground` and `$color-social-icons-background` to see the colours change
Fixes #2402

Add variables for social media icon colours.

---

docs/index.md
package.json
scss/_settings_system.scss

Bumped the version of Vanilla Framework to 2.2.0 in all the relevant places ahead of the release
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101
- Check everything still runs

Bumped Vanilla version to 2.2.0

---

docs/settings/animation-settings.md

Add missing vf- prefix to animation example
- Pull code

Add missing vf- prefix to animation example

---

docs/_layouts/default.html

Fix the navigation bug in docs where the duplicate nav is visible on page load
- Pull code
- Run `./run`
- See that the docs sidebar ends with the "resources" section
- Test the search box still works

Hide second navigation list in docs side nav on page

---

docs/_layouts/default.html
docs/base/code.md
docs/component-status.md
docs/patterns/accordion.md
docs/patterns/menu-button.md
docs/patterns/navigation.md
docs/patterns/pagination.md
package.json
yarn.lock

*Note:* This is @kwm14's work that I've put together into a single branch.
- Added the new status page
- Added status labels to the docs nav
- Upped vanilla-framework dep used by the docs to 2.2.0 so that the label component was available
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/component-status/
- Review the page content
- See the labels in the left-hand nav
Fixes #2413 
Fixes #2414

Add new status page and labels. Update doc vanilla dependency to 2.2.0

---

docs/sass/styles.scss

- Updated `.p-sidebar-nav__item .is-active::before` color to `$color-accent`
- Pull code
- Run `./run`
- See that the active link in the sidebar has a newly selected color
- Fixes #2216

Update sidebar active link

---

scss/_patterns_grid.scss

Done
Decrease scope of .row * to .row > *, so that it only affects direct children of .row
- Pull code
- Copy the markup and .grid-component style into an example
- Verify Left and right appear side by side instead of stacked.
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2444

decrease scope of selector so only direct children of .row  span full width

---

scss/_patterns_card.scss

Fix the p-card rules for margins to be less greedy
- Pull code
- Run `./run`
- Open a random example: e.g. http://0.0.0.0:8101/examples/base/abbr/
- Inspect the page and replace the markup with the example from [bartaz's codepen](https://jsfiddle.net/bartaz/8zcbj56k/)
- See that the spacing is better
*note*: The last element in a p-card in this sort of useage may have too much margin. u-no-margin--bottom can be applied if needed.
Fixes #2447

Make p-card's spacing rules less greedy

---

scss/_patterns_icons.scss

- Update icon colors to `$color-mid-dark` so the icon set matches
- Pull code
- Open http://0.0.0.0:8101/examples/patterns/icons/icons-light/
- See that the color of the icons look the same
- Fixes https://github.com/canonical-web-and-design/design-vanilla-framework/issues/404
- Fixes #2221

Update icon colours to $color-mid-dark

---

scss/_patterns_lists.scss

Fixed the issue where the circular background of stepped list bullets went "rugby ball shaped" when the heading wrapped over two lines
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/examples/patterns/lists/lists-stepped-detailed/
- Resize browser until the headings wrap and see that the bullets stay circular
Fixes #2424

Stop bullets from beforming when the title wraps

---

docs/index.md
package.json
scss/_settings_system.scss

Bumped the version of Vanilla Framework to 2.3.0 in all the relevant places ahead of the release
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101
- Check everything still runs

Bump Vanilla version to 2.3.0

---

docs/_layouts/default.html
docs/base/reset.md
docs/settings/table-layout.md

- Updated nav item in side-bar from 'Structure' to 'Layout'
- Added `hr` to /rest and /table-layout pages so it's consistent with all other component pages
- Pull code
- Check under settings there is an item called 'Layout'
- Check `hr` under the title on http://0.0.0.0:8101/base/reset/
- Check `hr` under the title on http://0.0.0.0:8101/settings/table-layout/
Fixes #2427 
Fixes #2428

Update heading title and dividers

---

docs/_layouts/default.html

- Add 'Labels' to docs search list
- Pull code
- Type labels in the search bar and see that the result appears
Fixes #2471

Fix label search result

---

docs/index.md

- Added `hr` under the page heading
- Removed dividing lines between sections so it's consistent with the rest of the documentation site
- Added `br` between sections as they were too tight 
- Updated download link to use `p-button is-inline`
- Update `What's new` to 'Release notes' in heading and renamed links, added another list and release date
- Moving social links to bottom od the page and reordered so it matches marketing site
- Pull code
- Scroll down the homepage and check out its full glory 💯 
Fixes old styling

Rejig homepage layout

---

docs/examples/patterns/buttons/base.html
docs/examples/patterns/buttons/brand.html
docs/examples/patterns/buttons/icon.html
docs/examples/patterns/buttons/negative.html
docs/examples/patterns/buttons/neutral.html
docs/examples/patterns/buttons/positive.html

- Remove `<p>` from all button examples
- No longer needed as 2.0 fixes buttons to sit inline 👍 
- Pull code
- Open http://0.0.0.0:8101/patterns/buttons/
- Check that all examples are no longer nested inside a `<p>` tag
- /buttons/#base
- /buttons/#positive
- /buttons/#negative
- /buttons/#brand
- /buttons/#icon
Fixes #2158

Remove <p> nesting in button examples

---

docs/patterns/navigation.md

- Fix broken link filed by @lilyvidenova on Usabilla 👍 
- Pull code
- Open http://0.0.0.0:8101/patterns/navigation/#sub-navigation-new
- Click _sub-navigation example_ link inside the note notification
- Make sure it points to here: https://docs.vanillaframework.io/examples/patterns/navigation/subnav/

Fix 404 broken link

---

docs/patterns/icons.md

- Updated dark style icon examples
- Move status icons into its own section 
- Fixed paddings between sections
- Updated layout of share icons into an inline list 
- Pull code
- Open http://0.0.0.0:8101/patterns/icons/
- Scroll down the page and notice http://0.0.0.0:8101/patterns/icons/#dark-theme has been updated to just show a few examples rather than duplicating our standard icon set
- New section http://0.0.0.0:8101/patterns/icons/#alert 
- Updated to inline rather than stacked links http://0.0.0.0:8101/patterns/icons/#share
Fixes https://github.com/canonical-web-and-design/design-vanilla-framework/issues/417

Reorder and add sections to icons page

---

docs/_layouts/default.html

- Match /docs footer with marketing site footer
- Link style and layout
- Date updates automatically
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework
- Check the footer styling matches what is seen on https://vanillaframework.io/
- #consitency

Consistent footers

---

docs/sass/styles.scss

- Removed `border-right: 1px solid #cdcdcd` as it's not needed, the background color supplies a divide between the content
- Updated background color to `$color-mid-x-light`
- Pull code
- See updated sidebar color 👀

Docs sidebar refresh

---

docs/_layouts/default.html
docs/index.md
docs/sass/styles.scss

- Updated homepage hero heading
- Updated homepage subheading
- Removed rogue `<div>` on the bottom of the page #random
- Pull code
- Check new homepage hero heading and subheading
- Consistent with other documentation sites
- Snap documentation, Juju documentation and MAAS documentation

Update homepage hero headings

---

docs/patterns/icons.md

Added information about `is-light` modifier for icons.
- Pull code, `./run serve --watch`
- Or https://vanilla-framework-canonical-web-and-design-pr-2500.run.demo.haus/patterns/icons/
- Go to icon docs, section about dark background
- Learn about `is-light` modifier class

Document usage of `is-light` for icons.

---

docs/examples/templates/typographic-spacing.html
scss/_base_button.scss
scss/_base_forms.scss
scss/_base_lists.scss
scss/_base_placeholders-margin-collapse.scss
scss/_base_typography-definitions.scss
scss/_base_typography.scss
scss/_patterns_card.scss
scss/_patterns_code-copyable.scss
scss/_patterns_form-help-text.scss
scss/_patterns_form-validation.scss
scss/_patterns_forms.scss
scss/_patterns_heading-icon.scss
scss/_patterns_icons.scss
scss/_patterns_inline-images.scss
scss/_patterns_lists.scss
scss/_patterns_matrix.scss
scss/_patterns_media-object.scss
scss/_patterns_tabs.scss
scss/_settings_spacing.scss

This is a work in progress branch that aims to:
- make text spacing slightly simplified
- make shallow strip match the standard bottom spacing on the majority of elements. This means go from 2rem to 1.5rem; 
- make headings slightly more spaced from generic divs like images etc, which was requested in https://github.com/canonical-web-and-design/vanilla-framework/issues/2420
- makes spacing under button match that under inputs and many other elements
- Pull code
- Open examples/templates/typographic-spacing/ and scroll to the bottom
- Inspect the examples showing headings and paragraphs with different parents matching those in the same parents:
- Verify the image sits further from the heading:
- QA percy for visual changes

Spacing adjustment

---

docs/_layouts/examples.html

Add a light pink baseline-grid background as a visual aid.
- helps see where a pattern begins, and where it ends
- helps see if it is on the baseline grid or not
- helps distinguish between 1rem example padding and actual example, useful for components that are flush with the page - like the nav, strips, etc.
- Pull code
- Open any of the examples

Add baseline grid background

---

docs/examples/patterns/buttons/icon.html
scss/_patterns_buttons.scss

- Fixes #2485.
- Changes icon color in positive buttons from grey to white
- Pull code
- Open examples/patterns/buttons/icon/
- Verify positive button does not go full-width on mobile

Fix positive buttons with icons

---

docs/examples/patterns/navigation/default.html
docs/examples/patterns/navigation/full-width.html
docs/examples/patterns/navigation/subnav.html
docs/examples/patterns/search-box/navigation.html
docs/patterns/navigation.md
scss/_base_forms.scss
scss/_patterns_navigation.scss
scss/_patterns_subnav.scss
scss/_settings_spacing.scss

- Pull code
- Open /examples/patterns/navigation/subnav/
- Add this under the nav and verify chevrons align:
```<div class="u-fixed-width"><div class="u-float-right"><select name="" id=""></select></div></div>```
- Currently, we remove the padding on the row wrapping nav contents, and apply that padding on the first / last element. This is prone to breaking, and needs to be applied to a variety of elements - search, right aligned dropdowns, etc. Note that it means all fixed width navs need the class p-navigation__row.
This pr reinstates the regular margins of a row, but uses .p-navigation__row for clarity - as a row comes with grid-gaps which get in the way as reported in #2483.
It also partially fixes #2480, by ensuring …

Fix spacing in navigation and subnav patterns

---

scss/_patterns_lists.scss

Correct inline list margins.
- Pull code
- Open examples/patterns/lists/lists-inline/
- Verify margin is now 1rem
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2525

fix list item margins

---

docs/examples/patterns/icons/icons-dark.html
docs/examples/patterns/icons/icons-light.html
scss/_patterns_accordion.scss
scss/_patterns_icons.scss
scss/_patterns_pagination.scss

A few mixins were invoked in the global scope, resulting in the css appearing above the reset rules. I've experimentally deleted them to see if this will result in any diffs.
- Pull code

Delete mixin invocations that dump into the beginning of build.css

---

scss/_base_forms-tick-elements.scss
scss/_settings_themes.scss

Apply theming mechanism to tick elements (checkbox, radio)
Fixes #2083 by adding a white background to the checkbox
- Pull code
- Open examples/base/forms/checkboxes/, examples/base/forms/aligned-radio/
- Change body background to a dark grey, verify checkbox stands out due to white background
- change the key forms in $theme-default--dark to true; verify borders and text color for checkboxes and radios switches to the dark theme

Themify tick elements

---

docs/examples/patterns/navigation/subnav.html
docs/patterns/navigation.md
scss/_patterns_subnav.scss

Added a variant for right-aligned nav dropdowns
- Pull code
- Open http://0.0.0.0:8101/examples/patterns/navigation/subnav/
- Look at the right-hand dropdown (add more text if you want the effect to be clearer)
Fixes #2479

Add support for right-aligned subnavs

---

docs/examples/utilities/hide.html

Update `u-hide` example to mention that it can be used without modifiers.

Update `u-hide` example

---

scss/_patterns_navigation.scss
scss/_patterns_tabs.scss

Explicitly set line-height on nav and tabs, so they stay aligned to baseline grid after bump in fontsize at $breakpoint-x-large (>1680px).
In firefox, look at the following examples on a screen > 1680px:
- https://docs.vanillaframework.io/examples/patterns/tabs/
- https://docs.vanillaframework.io/examples/patterns/navigation/subnav/
Verify borders fall onto baseline grid 
Compare with https://docs.vanillaframework.io/examples/patterns/navigation/subnav/ to see the difference.
Before:
After:
Fixes #2543

fix vr issue in nav and tabs

---

scss/_base_tables.scss

Add a small amount of padding using a transparent bottom border to space elements below tables.
- Pull code
- Go to the tables example
- Duplicate the table with the inspector
- See that there is some padding between the tables
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2491

Add padding below tables

---

scss/_patterns_navigation.scss
scss/_settings_colors.scss

Fix https://github.com/canonical-web-and-design/vanilla-framework/issues/2554
- Pull code
- Open dark nav example
- Verify background color is #333

Update nav in dark theme to use #333

---

scss/_patterns_subnav.scss
tests/parker.js

Added dark mode for subnavs
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/examples/patterns/navigation/subnav/
- Change the "nav" entry to "true" in `_settings_themes.scss`
- Open http://0.0.0.0:8101/examples/patterns/navigation/subnav/
- See the nav in dark mode
Fixes #2478 
*NOTE*: There's no docs for the themes yet, that will be added in another PR

Add dark theme support to subnavs

---

docs/_layouts/examples.html
docs/base/typography.md
scss/_base_fontfaces.scss
scss/_base_typography.scss
scss/_settings_font.scss

- created a set of subset fonts for the Ubuntu typeface
- they can be optionally added via a `$font-use-subset-latin: true;` setting. but will give users a ~66% font size savings to download.
- the default is exactly want it is today
- I also created non-google hosted subset fonts for cyrillic, greek, and latin (not sure why we need latin)
- Removed the `$font-import: 'http://fonts.gstatic.com/s/ubuntu/v9/' !default;` setting as it is no longer used
- added a `$font-display-option: false !default;` setting and added the logic to allow users to easily add that option in `_base_typography.scss`
- Updated the `typography.md` documentation to reflect these changes
- preloading the subset fonts in `examples.md`, but this can be removed or extended
- Pull code
- Set combinations of the above …

Add subset latin fonts

---

docs/examples/patterns/buttons/icon.html
docs/patterns/buttons.md
scss/_patterns_buttons.scss

Fix icons in buttons. 
Document is-light/dark classes. 
Add more icon button examples
- Pull code
- Open http://0.0.0.0:8101/examples/patterns/buttons/icon/
- Check that the buttons all render correctly
Fixes #2552

Fix icons in buttons. Document is-light/dark classes. Add more icon button examples

---

docs/patterns/navigation.md
scss/_base_forms-tick-elements.scss
scss/_base_hr.scss
scss/_base_typography-max-widths.scss
scss/_base_typography.scss
scss/_patterns_navigation.scss
scss/_patterns_search-box.scss
scss/_patterns_subnav.scss
scss/_settings_colors.scss
scss/_settings_themes.scss

- Restore ability to override nav background colour with `$color-navigation-background`;
- Convert colours map to a variables for easier overriding
- Pull code
- Open examples/patterns/navigation/default/, verify it looks as expected
- Open examples/patterns/navigation/default-dark/, verify it looks as expected
- Run any other website like ubuntu.com with ./run --node-module {PATH_TO_VANILLA}
- In the other website, set `$color-navigation-background` to a value above and a value below the threshold (70) `hsl(350, 100%, {INSERT_VALUE_HERE});`
- Observe text colour switch between dark and light 
- Add is-dark/is-light classes, observe they also work
- inside vanilla's `_settings_themes.scss`, change the value of the key 'nav' from false to true; repeat above …

Theming correction

---

docs/base/details.md

- Fixed the title of the Details page in docs.
- Pull code
- Open http://0.0.0.0:8101/base/details/
- Admire a title that matches the component.
Fixes #2579

#2579 - Fix Details title in docs.

---

scss/_patterns_search-box.scss

- Added padding to search box so text doesn't go underneath.
- Pull code
- Open 0.0.0.0:8101/examples/patterns/search-box/default/
- Add enough text to the search box input so it reaches the reset button
- Check that the text doesn't go underneath
Fixes #1960

#1960 - Add padding to search box so text doesn't go underneath.

---

scss/_patterns_form-validation.scss

- Rearranged select validation so that error > caution > success in the cases where it has multiple validation classes. This can happen in MAAS where a caution is shown when a certain option is selected, but a server error could occur when trying to save.
- Pull code
- Open http://0.0.0.0:8101/examples/patterns/forms/form-validation/
- Change the class of any validaion divs to `p-form-validation is-error is-caution is-success`
- Check that the error state is shown
- Change the class to `p-form-validation is-caution is-success`
- Check that the caution state is shown
- Change the class to `p-form-validation is-success`
- Check that the success state is shown
Fixes #2475

#2475 - Rearrange select validation priorities.

---

docs/patterns/navigation.md
docs/settings/color-settings.md
scss/_base_forms-tick-elements.scss
scss/_base_hr.scss
scss/_patterns_navigation.scss
scss/_patterns_search-box.scss
scss/_patterns_subnav.scss
scss/_settings_themes.scss

- Expand the color page to include information about the newly introduced theming mechanism
- Replace color theming map with variables for easier override
- Pull code
- In color-settings.md, check that the copy makes sense
- In color-settings.md, check that the described way of altering a theme works
- In color-settings.md, check that the described way of applying is-dark / is-light classes works
- If the above seem agreeable, build the documentation and check if it looks ok
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2331

doc page for theming

---

package.json
yarn.lock

Updated the docs version of vanilla to 2.4.1
- Pull code
- Check that the styling looks good
Fixes #2562

Update docs vanilla dependency to 2.4.1

---

docs/examples/base/blockquotes.html

Fixes #2597.
- Removes `<span>` elements from `<blockquote>` example, and trailing+leading spaces.
- Fixes nested quote marks.

Removes <span> elements from <blockquote> example

---

docs/settings/color-settings.md

- Add links to components that have the ability to theme
- Updated reference of _patterns_ to _components_
- Add **In progress** label to section to match navigation
- Pull code
- Open http://0.0.0.0:8101/settings/color-settings/#color-theming
- View updates listed above

Update links and references for color-theming

---

docs/patterns/icons.md

- Added "Accessibility Callout" to the icons documentation page
- Originally discovered by @barrymcgee 🔍  
- Pull code
- Open http://0.0.0.0:8101/patterns/icons/#accessibility
- Read through content and example to check callout makes sense 😉 
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2573

Add icons accessibility callout

---

docs/examples/base/font-weights.html
docs/examples/base/forms/select-multiple.html
docs/examples/base/forms/textarea.html
docs/examples/patterns/article-pagination.html
docs/examples/patterns/code-copyable.html
docs/examples/patterns/code-numbered.html
docs/examples/patterns/grid/bordered.html
docs/examples/patterns/grid/nested-medium.html
docs/examples/patterns/grid/nested-small.html
docs/examples/patterns/grid/nested.html
docs/examples/patterns/icons/icons-dark.html
docs/examples/patterns/icons/icons-light.html
docs/examples/patterns/icons/icons-social.html
docs/examples/patterns/image/bordered.html
docs/examples/patterns/image/shadowed.html
docs/examples/patterns/lists/lists-stepped-detailed.html
docs/examples/patterns/lists/lists-stepped.html
docs/examples/patterns/media-object/media-object-circ-img.html
docs/examples/patterns/media-object/media-object-large.html
docs/examples/patterns/media-object/media-object.html
docs/examples/patterns/navigation/default-dark.html
docs/examples/patterns/navigation/subnav.html
docs/examples/patterns/pagination/pagination-disabled.html
docs/examples/patterns/strips/deep.html
docs/examples/patterns/strips/is-bordered.html
docs/examples/patterns/strips/shallow.html
docs/examples/patterns/tables/table-expanding.html
docs/examples/patterns/tables/table-mobile-card.html
docs/examples/patterns/tables/table-sortable.html

- Drive-by to review and update page titles based on the raised issue
- Hopefully, when we push out a new release next iteration it will fix the regression so that the page titles are displayed and don't repeat as seen currently
- [Vanilla documentation](https://docs.vanillaframework.io/base/typography/)
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/examples/
- See that page titles are more consistent
- Amended grouping in places
- Fixed spelling
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2585

Consistent page titles

---

docs/base/code.md

- Edited intro to component
- Add 'Do' and 'Don't' basic usage guidelines
- Plan to update component next cycle, so this is an initial drive-by before we make future updates
- Pull code
- Open http://0.0.0.0:8101/base/code/#copyable
- Check the copy for 'Do' and 'Don't' and that links work
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2568

Add usage to code-copyable

---

docs/settings/layout-settings.md
docs/settings/spacing-settings.md
docs/utilities/align.md
docs/utilities/baseline-grid.md
docs/utilities/clearfix.md
docs/utilities/embedded-media.md
docs/utilities/equal-height.md
docs/utilities/floats.md
docs/utilities/hide.md
docs/utilities/image-position.md
docs/utilities/margin-collapse.md
docs/utilities/no-print.md
docs/utilities/off-screen.md
docs/utilities/padding-collapse.md
docs/utilities/show.md
docs/utilities/vertically-center.md

- Added a section in the context menu called 'Import' to components
- Provides import snippet to paste into your project
- Links to Customising Vanilla page for further information
- Pull code
- Check 'Import' section applied to specific utilities
- http://0.0.0.0:8101/utilities/align/#import
- http://0.0.0.0:8101/utilities/baseline-grid/#import
- http://0.0.0.0:8101/utilities/clearfix/#import
- http://0.0.0.0:8101/utilities/embedded-media/#import
- http://0.0.0.0:8101/utilities/equal-height/#import
- http://0.0.0.0:8101/utilities/floats/#import
- http://0.0.0.0:8101/utilities/hide/#import
- http://0.0.0.0:8101/utilities/image-position/#import
- http://0.0.0.0:8101/utilities/margin-collapse/#import
- …

Add import snippet to utilities documentation

---

.spelling
docs/base/typography.md
docs/examples/utilities/max-width-unset.html
scss/_base_typography-max-widths.scss
scss/_patterns_notifications.scss
scss/_settings_spacing.scss
scss/_utilities_max-width.scss
scss/_vanilla.scss

- Add documentation entry on max-width
- Add example
- Add unset utility
- Pull code
- Open examples/utilities/max-width-unset/
- Verify example max width is overriden
- Open typography.md
- Check copy makes sense
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2586

Documentation entry on max-width; u-no-max-width utility

---

.spelling
docs/_layouts/default.html
docs/examples/patterns/buttons/icon.html
docs/examples/utilities/font-metrics.html
docs/utilities/baseline-grid.md
docs/utilities/font-metrics.md
scss/_base_button.scss
scss/_base_forms.scss
scss/_patterns_buttons.scss
scss/_patterns_icons.scss
scss/_patterns_search-box.scss
scss/_settings_font.scss
scss/_utilities_font-metrics.scss
scss/_vanilla.scss

- Fix horizontal position of icons within buttons
- Fix vertical-align of icons next to text
- Add font-metrics utility
- Document font-metrics utility
- Small improvement of the baseline-grid doc page
- Add Examples to the documentation home nav
- Pull code
- Verify button position in examples/patterns/buttons/icon/ is correct
- View font-metrics examples/utilities/font-metrics/ page, verify it look ok
- View utilities/font-metrics/, proof copy
Fixes #2555

Fix icons inside buttons; add font-metrics utility

---

scss/_patterns_table-expanding.scss

****
Before:
After:
- Pull code
- Open /examples/patterns/tables/table-expanding/
- Verify buttons look like the second image above

Table expanding panel: Prevent children with defined margins from stretching 

---

docs/base/typography.md
docs/settings/breakpoint-settings.md

- Document font size increase
- Update modular scale information which was not entirely correct
- Fix breakpoint typo
- Pull code
- Open base/typography/
- Proof copy
Fix #2620
Fix https://github.com/canonical-web-and-design/vanilla-framework/issues/2623

Document font-size bump, clarify type scale, fix breakpoint typo

---

docs/_layouts/default.html

- Removed 'Coding standards' page from documentation site as this page is no longer live
- Pull code
- Notice that 'Coding standards' has been removed from the navigation to match navigation structure on https://vanillaframework.io/

Remove coding standards page from docs nav

---

docs/examples/patterns/tables/table-sortable.html
scss/_patterns_table-sortable.scss

Sortable table: replace chevron icon with new one
Add role attribute to `<th>`s; 
- Pull code
- Open examples/patterns/tables/table-sortable/
- Click on a column header, verify sorting icon that appears is the new chevron
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2634

Replace old chevron with new; Add missing role to markup

---

scss/_patterns_notifications.scss

Fix https://github.com/canonical-web-and-design/vanilla-framework/issues/2512
Fix caution icon position when text wraps (currently it is vertically centered within the height of the wrapped text)
1 Pull code
2 Run `./run serve --watch`
3 Open http://192.168.64.2:8101/examples/patterns/notifications/notifications/ and http://192.168.64.2:8101/examples/patterns/notifications/caution/
4 Verify icon for caution in the caution example, and close button in the other example, are properly vertically centered within available space.
5 Set $multi to 1
6 Repeat step 4

Fix notification icon position

---

docs/examples/patterns/tables/table-mobile-card.html
scss/_base_tables.scss
scss/_patterns_table-mobile-card.scss

- Fix p-table--mobile-card to look like card.
- Move breakpoint at which switch happens to $breakpoint-medium so it is visible in the example
- Update card example to be more complex
- Pull code
- Open /examples/patterns/tables/table-mobile-card/
- Verify cards looks ok
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2163

fix mobile card table

---

scss/_patterns_contextual-menu.scss
tests/parker.js

Fixes  #2081
Fixes #2053
- Pull code
- Open examples/patterns/contextual-menu/with-indicator/
- Open menu, tab through links and verify they get the vanilla blue focus state

Contextual menu: add focus state to links; expand to fit content until it hits its max-width

---

docs/examples/templates/tick-element-comparison.html
scss/_base_forms.scss
scss/_settings_spacing.scss

Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2497
- Pull code
- set $multi to 1
- Open http://192.168.64.2:8101/examples/templates/tick-element-comparison/
- Verify margin-bottom on the inputs is .7rem

Increase input margin bottom by .5rem

---

scss/_patterns_form-validation.scss

FIx #2521
- Pull code
- Open examples/patterns/forms/form-validation/
- See that longe text doesn't overlap icons

Validation fields: prevent text from overlapping validation icons

---

docs/examples/patterns/tables/table-sortable.html

Fix the table sorting pattern functionality on Chrome
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/base/tables
- Click the sortable table headings on both Firefox and Chrome
- See that the table sorts correctly
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2635
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2661

Fix the table sorting pattern functionality on Chrome

---

scss/_base_tables.scss

- Pull code
- Open any table example, e.g. /examples/patterns/tables/table-sortable/
- Delete everything after the thead
- Verify border on thead tr does not disappear
Fix https://github.com/canonical-web-and-design/vanilla-framework/issues/2662

Prevent table header border from disappearing when tbody contains no rows

---

docs/examples/patterns/icons/icons-social.html
docs/patterns/icons.md
scss/_patterns_icons.scss

- Added new social email icon
- Pull code
- Open http://0.0.0.0:8101/examples/patterns/icons/icons-social/ 
- You should see a new email icon on the examples page, but as we can't serve this push due to docs being on a previous release of our framework you won't see the icon on the docs page
Fixes https://github.com/canonical-web-and-design/design-vanilla-framework/issues/424

Add new social email icon

---

scss/_patterns_lists.scss

- Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2649
- Removes a couple of unnecessary left indents
- Pull code
- Open patterns/lists/lists-stepped/,  /patterns/lists/lists-stepped-detailed/
- Verify they content is aligned with titles:

Indent p-stepped-list__content

---

scss/_patterns_lists.scss

Fixes #2557 by reverting to 2.3.0 styling of inline lists
- Pull code
- Open /examples/patterns/lists/lists-mid-dot/
- QA middot position
The problem was that the display property was changed to inline-flex, which misaligns the dot. This reverts it to inline.
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2557

Fix middot position as it was in 2.3.0

---

package.json
yarn.lock

Updated version of Vanilla used by the docs to 2.5.0
- Pull code
- Make sure site looks ok
Fixes #2646

Bump version of Vanilla used by the docs

---

scss/_settings.scss
scss/deprecate/_index.scss

Renamed `deprecate/index.scss` to `_index`, so it's not built into CSS.
Moved importing system settings to beginning of the file, so the `app-version` is defined before it's used by `deprecate`.
- Pull code
- Only `build.css` should be built, not `deprecate/index.css`

Don't build deprecate util, fix setting app-version before it's used

---

docs/_layouts/default.html
docs/base/typography.md
docs/component-status.md
docs/settings/color-settings.md
docs/utilities/font-metrics.md
docs/utilities/table-cell-padding-overlap.md
docs/utilities/truncate.md

- removed old component status labels and entries from component status page
- added newly added and updated components and utilities from 2.5.0
- Pull code
- Open http://0.0.0.0:8101/component-status/ or demo https://vanilla-framework-canonical-web-and-design-pr-2693.run.demo.haus/component-status/
- Check if current status of all new features from 2.5.0 are listed
- Check labels in the side navigation*
- Check for labels in the relevant pages
\* note "Table cell padding overlap" doesn't have "New" icon in the side navigation, because it doesn't fit next to long title

Update component status 2.5.0

---

docs/examples/patterns/accordion.html
docs/examples/patterns/code-copyable.html
docs/examples/patterns/contextual-menu/default.html
docs/examples/patterns/contextual-menu/with-indicator.html
docs/examples/patterns/modal.html
docs/examples/patterns/navigation/subnav.html
docs/examples/patterns/notifications/notifications.html
docs/examples/patterns/slider/slider-input.html
docs/examples/patterns/slider/slider.html

Fixes #2604 
Fixes #2298
Updated (or maybe downgraded?) all JavaScript in the examples not to use ES6 and other modern API to make sure they work in most browsers (including IE10/11) without transpilation.
This mostly involved getting rid or `const`, `let` and `forEach`.
- Pull code
- Open http://0.0.0.0:8101/vanilla-framework/ or demo https://vanilla-framework-canonical-web-and-design-pr-2698.run.demo.haus/
- Check all the patterns with the JS in examples, make sure they still work
- Ideally test them in IE10 or IE11
Patterns updated in this PR:
Other patterns with JS (not affected by this PR, still worth QAing):

Convert Vanilla JS in examples to ES5

---

.github/PULL_REQUEST_TEMPLATE.md

Removed /vanilla-framework/ from test URL as it 404s.

Remove old path from testing URL

---

docs/_config.yml
docs/index.md

Stores latest Vanilla version number in jekyll config to have less places needing updating on 
release.
Also prepares us to being able to inject latest version of Vanilla CSS into CodePen examples.
- Pull code
- Open http://0.0.0.0:8101/ or https://vanilla-framework-canonical-web-and-design-pr-2703.run.demo.haus/
- Check if hotlink and download instructions are correct for latest version of Vanilla

Store Vanilla version in jekyll config

---

scss/_patterns_subnav.scss

Fixes selector for :focus and :visited links in subnav to give them correct colour.
- Pull code
- Open http://0.0.0.0:8101/ or demo https://vanilla-framework-canonical-web-and-design-pr-2708.run.demo.haus/
- Open subnav examples [/examples/patterns/navigation/subnav/]( https://vanilla-framework-canonical-web-and-design-pr-2708.run.demo.haus/examples/patterns/navigation/subnav/)
- Click on links in the dropdowns
- Make sure their colour is black even when visited (they shouldn't use visited blue link colour)

Fix :visited link styles in subnav

---

docs/examples/patterns/accordion.html
docs/examples/patterns/code-copyable.html
docs/examples/patterns/contextual-menu/default.html
docs/examples/patterns/contextual-menu/with-indicator.html
docs/examples/patterns/list-tree.html
docs/examples/patterns/modal.html
docs/examples/patterns/navigation/subnav.html
docs/examples/patterns/notifications/notifications.html
docs/examples/patterns/slider/slider-input.html
docs/examples/patterns/slider/slider.html
docs/examples/patterns/tables/table-expanding.html
docs/examples/patterns/tables/table-sortable.html
docs/examples/utilities/baseline-grid.html

Fixes #2700 
Makes JS code of the examples more consistent in terms of:
- making sure JS it attached to all instances of components on the page
- making sure JS doesn't error if there is no given pattern on the page
- giving all JS examples similar structure of functions
- making sure JS uses `aria-` attributes where applicable
Affected examples:
- accordion
- code copyable
- contextual menu
- list tree
- modal
- notification
- baseline grid
- table expanding
- slider
- sortable table
- subnav
- Pull code
- Open http://0.0.0.0:8101/ or demo https://vanilla-framework-canonical-web-and-design-pr-2707.run.demo.haus/
- Make sure all the example pages work without errors in the console
- Make sure all the examples work in docs (CodePen)

Consistent JS examples in docs

---

.travis.yml

Making sure bundler v.1.16.6 is installed on travis to make the builds run properly.
Since the end of December builds on Travis were (kind of randomly) [failing](https://travis-ci.org/canonical-web-and-design/vanilla-framework/builds/633315089) with
```
/home/travis/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.16.6) required by your /home/travis/build/canonical-web-and-design/vanilla-framework/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.6`
```
This PR makes sure that bundler 1.16.6 (version used in Gemfile) is installed in travis.
- Check if travis builds pass …

Install bundler@1 on travis

---

.travis.yml
package.json
renovate.json
yarn.lock

pretty-quick@2 requires version of node that we can't install on jenkins
Reverted pretty-quick to version 1, so it doesn't require node >9.
- Make sure build passes on travis and jenkins ([it does](https://jenkins.canonical.com/webteam/view/vanilla-framework/job/docs.vanillaframework.io-staging/98/console))

Keep pretty-quick on v1.11.1

---

scss/_patterns_code-copyable.scss

Exploicitly set margin top and bottom of the input in code-copyable to 0, as safari is adding 2px.
- Pull code
- Open /examples/patterns/code-copyable/
- Verify no gap appearsa above/beneath button
Fixes #2690

Fix code-copyable (#2690)

---

scss/_patterns_navigation.scss

Subtract a pixel from nav breakpoints that are not overriden by a min-width query further down.
- Pull code
- Open a navigation example, e.g. examples/patterns/navigation/default-dark/
- Resize window to 772px, verify nav displays like this:
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/2696

Adjust breakpoints to fix midbreakpoint failure (#2696)

---

docs/component-status.md

Removed unnecessary inline margin from the table, that was causing weird spacing issues in Firefox (and Percy).
- Pull code
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2733.run.demo.haus/)
- Go to [Component Status](https://vanilla-framework-canonical-web-and-design-pr-2733.run.demo.haus/component-status/) page in Firefox
- Reload couple of times, spacing should not change in the table between reloads
- Make sure percy doesn't complain about this page anymore

Fix Firefox issues with component status table

---

docs/component-status.md

Follow up to #2733
Removes inline margin from another table as well that was forgot during merge.
- Pull code
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2738.run.demo.haus/)
- Go to [components status page](https://vanilla-framework-canonical-web-and-design-pr-2738.run.demo.haus/component-status/)
- There should be no inline margin on tables

Remove unnecessary margin

---

docs/_includes/patterns/code-copyable.html
docs/_includes/patterns/code-numbered.html
docs/examples/individual/code-copyable.html
docs/examples/individual/code-numbered.html
scss/individual/patterns_code-copyable.scss
scss/individual/patterns_code-numbered.scss

Makes sure code patterns' styles can be built separately.
Adds example pages for individually built code components.
- Pull code
- Check if existing (full vanilla) examples still work as before
- [copyable](https://vanilla-framework-canonical-web-and-design-pr-2739.run.demo.haus/examples/patterns/code-copyable/)
- [numbered](https://vanilla-framework-canonical-web-and-design-pr-2739.run.demo.haus/examples/patterns/code-numbered/)
- Check if new individual examples work and look same as full vanilla ones
- [copyable](https://vanilla-framework-canonical-web-and-design-pr-2739.run.demo.haus/examples/individual/code-copyable/)
- [numbered](https://vanilla-framework-canonical-web-and-design-pr-2739.run.demo.haus/examples/individual …

Add example pages for individually built code components

---

docs/_includes/patterns/media-object/media-object-circ-img.html
docs/_includes/patterns/media-object/media-object-large.html
docs/_includes/patterns/media-object/media-object.html
docs/examples/individual/media-object/media-object-circ-img.html
docs/examples/individual/media-object/media-object-large.html
docs/examples/individual/media-object/media-object.html
scss/individual/patterns_media-object.scss

Makes sure media object styles can be built separately.
Adds example pages for individually built media object.
- Pull code
- Check if existing (full vanilla) examples still work as before
- [default](https://vanilla-framework-canonical-web-and-design-pr-2737.run.demo.haus/examples/patterns/media-object/media-object/)
- [large](https://vanilla-framework-canonical-web-and-design-pr-2737.run.demo.haus/examples/patterns/media-object/media-object-large/)
- [circle](https://vanilla-framework-canonical-web-and-design-pr-2737.run.demo.haus/examples/patterns/media-object/media-object-circ-img/)
- Check if new individual examples work and look same as full vanilla ones
- [default](https://vanilla-framework-canonical-web-and-design-pr-2 …

Add example pages for individually built media object

---

.travis.yml
Dockerfile

Node 12 is LTS, and it's used in the run script
``` bash
DOCKER_BUILDKIT=1 docker build --tag docs.vanillaframework.io .
docker run -ti -p 8177:80 docs.vanillaframework.io
```
Go to http://localhost:8177, see the site

Use node 12 in image build

---

docs/_includes/patterns/icons/icons-dark.html
docs/_includes/patterns/icons/icons-light.html
docs/_includes/patterns/icons/icons-social.html
docs/examples/individual/icons/icons-dark.html
docs/examples/individual/icons/icons-light.html
docs/examples/individual/icons/icons-social.html
scss/individual/patterns_icons.scss

- Makes sure icons build independently from other components.
- Removes dependency on list pattern in example HTML
- Uses inline dark background (in "dark" example) to remove dependency on strip pattern
Fixes #2206 
- Pull code
- Make sure icon examples with full Vanilla show all icons correctly
- [light](https://vanilla-framework-canonical-web-and-design-pr-2734.run.demo.haus/examples/patterns/icons/icons-light/)
- [dark](https://vanilla-framework-canonical-web-and-design-pr-2734.run.demo.haus/examples/patterns/icons/icons-dark/)
- [social](https://vanilla-framework-canonical-web-and-design-pr-2734.run.demo.haus/examples/patterns/icons/icons-social/)
- Make sure icon examples with individual icons CSS look the same as full …

Encapsulate icons styles and examples

---

docs/_includes/patterns/article-pagination.html
docs/_includes/patterns/pagination/pagination-disabled.html
docs/_includes/patterns/pagination/pagination-truncated.html
docs/_includes/patterns/pagination/pagination.html
docs/examples/individual/article-pagination.html
docs/examples/individual/pagination/pagination-disabled.html
docs/examples/individual/pagination/pagination-truncated.html
docs/examples/individual/pagination/pagination.html
docs/examples/patterns/pagination/pagination-disabled.html
docs/examples/patterns/pagination/pagination-truncated.html
docs/examples/patterns/pagination/pagination.html
scss/individual/patterns_article-pagination.scss
scss/individual/patterns_pagination.scss

Makes sure pagination styles can be build individually, adds examples for them.
Fixes #2209
- Pull code
- Check if previous examples full Vanilla examples look as before:
[pagination](https://vanilla-framework-canonical-web-and-design-pr-2744.run.demo.haus/examples/patterns/pagination/pagination/)
[disabled pagination](https://vanilla-framework-canonical-web-and-design-pr-2744.run.demo.haus/examples/patterns/pagination/pagination-disabled/)
[truncated pagination](https://vanilla-framework-canonical-web-and-design-pr-2744.run.demo.haus/examples/patterns/pagination/pagination-truncated/)
[article pagination](https://vanilla-framework-canonical-web-and-design-pr-2744.run.demo.haus/examples/patterns/pagination/article-pagination/) …

Encapsulate pagination

---

docs/examples/patterns/navigation/subnav-dark.html
scss/_patterns_subnav.scss

Fixes #2752 
Fixes #2753 
- Pull code
- Go to [dark subnavigation example](https://vanilla-framework-canonical-web-and-design-pr-2761.run.demo.haus/examples/patterns/navigation/subnav-dark/)
- Make sure subnav background is the same as main nav
- Make sure there is no light border around dark subnav dropdown
- On small screen there should be no additional indent and no border around subnav items

Dark sub navigation fixes

---

scss/_base_placeholders.scss
scss/_patterns_navigation.scss

Fixes #2767
Updates specificity of navigation style selectors to fix issue with full width navigation not taking whole 100% of screen.
- Pull code
- Go to [full width navigation example](https://vanilla-framework-canonical-web-and-design-pr-2768.run.demo.haus/examples/patterns/navigation/full-width/) on a wide screen
- Make sure nav takes whole width
- Make sure other nav examples are constrained by grid width

Update specificity of navigation styles to fix issue with full width nav

---

docs/examples/index.html
docs/examples/individual/index.html

Follow up on discussion on https://github.com/canonical-web-and-design/vanilla-framework/pull/2763#issuecomment-577161459
This moves individual CSS examples to separate page (tab) not to clutter original examples page.
- Pull code
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2769.run.demo.haus/)
- Go to [examples page](https://vanilla-framework-canonical-web-and-design-pr-2769.run.demo.haus/examples/)
- Examples page should show only full Vanilla CSS examples
- Click on a tab to go to individual examples page

Add separate page with individual CSS examples

---

docs/_layouts/default.html
docs/_layouts/examples.html

Marks "Examples" page selected in main nav.
Adds favicon to example pages
Fixes #2723 
Fixes #2725
- Pull code
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2778.run.demo.haus/)
- Go to [Examples page](https://vanilla-framework-canonical-web-and-design-pr-2778.run.demo.haus/examples)
- "Examples" should be marked selected in main nav instead of "Docs"
- Go to any example page, it should have favicon

Example pages fixes

---

scss/_patterns_navigation.scss

Updated navigation links animation to only include color, background color and opacity props.
Fixes #2770 
- Pull code
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2783.run.demo.haus/)
- Go to one of [navigation examples](https://vanilla-framework-canonical-web-and-design-pr-2783.run.demo.haus/examples/patterns/navigation/default/)
- Reload couple of times (with or without dev tools open)
- There should be no animation visible on load
- Hover on navigation items
- There should still be a subtle navigation when color of nav item changes

Only animate necessary props in navigation links

---

docs/_includes/base/forms/aligned-checkboxes.html
docs/_includes/base/forms/aligned-radio.html
docs/base/forms.md
scss/_base_forms-tick-elements.scss
scss/_base_tables.scss
scss/_base_typography-definitions.scss

- Make the column header text smaller and slightly more bold (regular weight instead of light),
as agreed in https://github.com/canonical-web-and-design/vanilla-framework/issues/2501
- Add .5rem padding at the top to make the text vertically centered in the header
- Add is-table-header class to the aligned checkboxes and radios examples
- Pull code
- Open /examples/base/table/, examples/base/forms/aligned-checkboxes/, examples/base/forms/aligned-radios/
- Verify the table headers, checkboxes and radios looks as in the screenshots bellow:
Fix https://github.com/canonical-web-and-design/vanilla-framework/issues/2501
Before:
After:

Update look of table header to match #2501

---

docs/examples/utilities/fixed-width-container.html
docs/patterns/grid.md
scss/_base_grid-definitions.scss
scss/_base_placeholders.scss
scss/_utilities_layout.scss

- Fix https://github.com/canonical-web-and-design/vanilla-framework/issues/2784
- Minor refactor
- Pull code
- Open any example page 
- add `.u-fixed-width` inside a '.row'
- observe padding is cleared

Ensure nested fixed-witdh containers clear their side padding

---

docs/_layouts/default.html
docs/base/forms.md
docs/base/typography.md
docs/component-status.md
docs/patterns/contextual-menu.md
docs/patterns/slider.md
docs/utilities/font-metrics.md
docs/utilities/table-cell-padding-overlap.md
docs/utilities/truncate.md

Update component status page and labels for 2.6.0 release.
- Pull code
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2787.run.demo.haus/)
- Go to [component status page](https://vanilla-framework-canonical-web-and-design-pr-2787.run.demo.haus/component-status/), make sure recent changes are listed
- Check if corresponding changes are marked in side navigation with labels
- Check if corresponding changes are marked with labels in the page contents

Update component status as for v2.6.0

---

docs/_config.yml
docs/index.md
package.json
yarn.lock

Upgraded Vanilla docs to 2.6.0 release
- Pull code
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2789.run.demo.haus/)
- Make sure docs work
- Make sure install page shows 2.6.0 as latest release
- Make sure CodePen examples in docs use 2.6.0 release

Upgrade docs site to Vanilla 2.6.0

---

.travis.yml
docs/examples/utilities/image-position/left.md
package.json
snapshots.js
yarn.lock

Updates travis configuration to build and run docs as flask based app.
Adds a script to get all the links from docs and snapshot them to Percy (using PercyScript).
- make sure travis build passes
- make sure snapshots of all pages (all docs and examples) are submitted to Percy
NOTE: 
Percy shows 383 missing snapshots agains 381 new snapshots.
Missing snapshots are 404 page (which crawler doesn't find obviously) and old code-snippets page, which in Jekyll site was an empty HTML with a redirect.

Update Travis and Percy configs to run on Flask docs

---

redirects.yaml

Add redirects for previous locations of static resources
https://vanilla-framework-canonical-web-and-design-pr-2809.run.demo.haus/css/styles.css should be /static/css/styles.css
https://vanilla-framework-canonical-web-and-design-pr-2809.run.demo.haus/js/examples.js should be /static/js/examples.js 
https://vanilla-framework-canonical-web-and-design-pr-2809.run.demo.haus/build/css/build.css should be /static/build/css/build.css

Add redirects for previous locations of static resources

---

docs/examples/patterns/contextual-menu/dark.html
docs/examples/patterns/contextual-menu/light.html
docs/patterns/contextual-menu.md
scss/_patterns_contextual-menu.scss
scss/_settings_themes.scss

Juju [need ](https://github.com/canonical-web-and-design/juju-squad/issues/1097#issuecomment-581959672) a themed version of the contextual menu. This pr implements the theming mechanism, providing light and dark theme. Once this is merged, in juju a blue-ish theme can be created in the same way.
- Pull code
- Open examples/patterns/contextual-menu/with-indicator
- add class is-dark, QA
- open _settings_themes.scss, change the value of $theme-default-p-contextual-menu to 'dark'
- QA
-add class is-light, QA again

Themify contextual menu

---

docs/search.html
requirements.txt
webapp/app.py

Make use of [canonicalwebteam.search v0.2.0](https://pypi.org/project/canonicalwebteam.search/) to provide search results at /search?q={query}.
I've added docs.vanillaframework.io to [our Custom Search engine](https://cse.google.com/cse/setup/basic?cx=009048213575199080868:i3zoqdwqk8o)
**NB:** This is to implement the back-end only. The HTML and styling for the search results page is only preliminary, and I haven't linked to `/search` from anywhere, so I'm hoping it's okay to merge this PR without a visual review and get @bartaz or something to do the styling of the search results page in a future PR, when they also add the search box.
QA
--
Get the "Custom Search API key" from [the Google Cloud Platform console](https://console.cloud.google.com/apis/credentials?project=ubuntu-search-15308 …

Add /search to docs site

---

scss/_patterns_search-box.scss

- Fixed placement of search input within form element on IE11
- Open the demo in [Browserstack](https://www.browserstack.com/), on IE11
- See that the search input isn't out of place (compare to [live version](https://docs.vanillaframework.io/examples/patterns/search-box/default))
Fixes: https://github.com/canonical-web-and-design/ubuntu.com/issues/6587
IE11 before fix:
IE11 after fix:

fix search input placement in IE11

---

docs/_layouts/default.html
docs/search.html
docs/static/scss/styles.scss

Moves search box to main nav.
Updates custom styling of mobile navigation toggles.
Fixes #2806 
To run search locally you need search API token. See https://github.com/canonical-web-and-design/vanilla-framework/pull/2812
Appearance of search box itself can be tested on demo server, but the search results page will throw an error.
- Pull code
- Run `./run`
- See search box appearing in main nav instead of side bar
- Check on different screen widths (on small screens search box is inside 'About' menu with rest of navigation)

Move search box to main nav

---

README.md
package.json
yarn.lock

Uses node-sass watch directly to only rebuild files that are affected by changes.
Fixes #2781 
- Pull code
- To watch on Vanilla framework run `./run watch`
- All Vanilla css should be built and then watch should wait for changes
- Only files affected by the change should be rebuilt
- To watch on docs styles run `./run exec yarn watch:docs-scss`
- Any change to docs custom styles (/static/scss/*) should trigger rebuilt

Improve watch script

---

docs/_layouts/default.html
docs/component-status.md
docs/index.md
docs/patterns/contextual-menu.md
package.json
scss/_settings_system.scss

- Bumps version to 2.7.0
- Updates component status for 2.7 release.
- Removes nonexistent contextual menu light example from docs page
- Pull code
- Run `./run`
- On home page make sure 2.7.0 is listed as latest release (link to GH will not work until release is done)
- Go to component status page
- Check if side navigation labels are in line with component status

Update docs to 2.7.0

---

requirements.txt

Go to `/_status/check` and check you see a `cache-control: no-store` header or something.

Update flask-base to prevent caching of _status endpoints

---

.github/PULL_REQUEST_TEMPLATE.md
.github/release-drafter.yml
.github/workflows/release-drafter.yml

Updates release drafter template.
Uses Release Drafter as GH Actions Workflow.
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/771
There is no way to QA it until it's merged and runs on GH, so trust in code review...

Update release drafter template, use it as GH Workflow

---

package.json
sass-functions.js
scss/_settings_system.scss

Adds a Sass function to read version from package.json, so it doesn't have to be updated in multiple places on release.
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/772 
- Pull code
- Scss should build without any errors
- Update version field in package.json to 3.0.0
- `./run build`
- Deprecation warnings should show up during the build

Pass Vanilla version from package.json to scss

---

.github/workflows/publish-on-release.yml

Add GitHub workflow to build Vanilla and publish it to npm and assets server when release in GitHub is created.
Fixes #2327
Fixes #2328 
There is no good way to QA it in place until it's merged and release is triggered.
You can review [test run of the workflow](https://github.com/bartaz/vanilla-framework/actions/runs/42250611) in the fork.
Note - test run fails to publish, because version in package.json didn't change, but you can review if all steps are called correctly.

Add workflow to publish Vanilla to npm and assets on release

---

docs/_layouts/default.html
docs/index.html

Removes manually maintained list of latest releases from docs home page, replaces it with a link to GH release notes.
This will help us avoid the need to update this list with every single release.
Adds a link to release notes (with current version) to sidebar nav and footer.
Fixes #2823 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or try [demo](https://vanilla-framework-canonical-web-and-design-pr-2842.run.demo.haus/) (if it works...)
- There should be no list of latest releases, but a link to release notes on GH (below download button)
- There should be a "What's new" link in sidebar and "Vanilla v.X.X.X" in footer

Update docs home page to remove list of latest releaes

---

.github/workflows/publish-on-release.yml

Uses `release published` event instead of `created` to properly release Vanilla when release is published on GH.
No way to QA it other than merging and trying on a repo...

Fix release workflow to be triggered on release publish event

---

scss/_patterns_links.scss

Fixes #2728 
- Pull code
- Run `./run`
- See external links on Safari and Edge
Note: I don't have a machine to install Edge, somebody QA on Edge. Thanks

Fix external link background leaking

---

docs/examples/templates/typographic-spacing.html
scss/_base_lists.scss

Adds bottom margin to definition list to make it consistent with other list patterns.
Adds list examples to typography template example page.
Fixes #2791 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2849.run.demo.haus/)
- Go to [definition list example](https://vanilla-framework-canonical-web-and-design-pr-2849.run.demo.haus/examples/base/lists/definition-list), make sure there is bottom margin
- Go to [typography example](https://vanilla-framework-canonical-web-and-design-pr-2849.run.demo.haus/examples/templates/typographic-spacing), find "List styles and spacing", make sure they display correctly

Add bottom margin to definition list

---

scss/_base_typography-definitions.scss

Fix margin between paragraph with heading class and following paragraph.
Fixes #2835 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2856.run.demo.haus/)
- Check typography examples, they should work as expected
- Check [codepen demo](
https://codepen.io/bartoszopka/pen/abOBOOq?=true) which uses styles from this PR
- Make sure all headings are properly aligned

Only compensate margin on pararaphs that don't have heading classes

---

site/_layouts/default.html

Fixes selecting Docs/Examples in main nav
- Pull code
- Run `./run`
- Go to standalone examples
- Only Examples should be selected, not Docs
- Go to any docs page, Docs should be selected, not Examples

Fix highlighting link for standalone examples

---

.github/ISSUE_TEMPLATE/report-a-bug.md
templates/_layouts/_footer.html
templates/_layouts/docs.html
templates/_layouts/site.html
templates/static/js/scripts.js

- Updates the footer on vanilla site to correctly link to vanilla framework repo
- Reuses same footer in both layouts
- Fixes errors in script when elements are not in the layout
Fixes #2916
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2917.run.demo.haus/)
- Go to home page
- Make sure links in the footer work

Make footer consistent between site and docs layouts

---

webapp/app.py

Point search to vanillaframeowork.io/docs rather than docs.vanillaframework.io
Fixes #2907 
- Pull code
- Run `./run` and open http://0.0.0.0:8101/docs
- Search for something
- search results should contain results for vanillaframework.io/docs rather than docs.vanillaframework.io

Update search site URL

---

scss/_patterns_subnav.scss

Removes border from subnav dropdowns
Fixes #2765 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2925.run.demo.haus/)
- Check subnav examples (light and dark) if they look ok

Remove border from subnav dropdowns

---

scss/_base_placeholders.scss
scss/_patterns_accordion.scss
scss/_patterns_lists.scss
scss/_patterns_side-navigation.scss
scss/_settings_colors.scss
scss/_vanilla.scss
scss/standalone/patterns_side-navigation.scss
templates/_layouts/docs.html
templates/docs/component-status.md
templates/docs/examples/patterns/side-navigation/default.html
templates/docs/examples/patterns/side-navigation/docs.html
templates/docs/patterns/navigation.md

- adds basic version of side navigation
- adds examples and simple docs
Fixes #2860 
Fixes #2861
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2915.run.demo.haus/docs/examples/patterns/side-navigation/default)
- Check new side navigation pattern examples, make sure they work correctly
- [default](https://vanilla-framework-canonical-web-and-design-pr-2915.run.demo.haus/docs/examples/patterns/side-navigation/default)
- [docs](https://vanilla-framework-canonical-web-and-design-pr-2915.run.demo.haus/docs/examples/patterns/side-navigation/docs)
- make sure side nav documentation is added: https://vanilla-framework-canonical-web-and-design-pr-2915.run.demo.haus/docs/patterns/navigation/#side-navigation
- NOTE: codepen will …

Add side navigation component with default styling

---

scss/_patterns_label.scss

As label component is used mostly inline alongside text or in paragraphs it shouldn't have margin of it's own (as it usually needs to be removed with u-no-margin).
- Pull code
- Run `./run` http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2929.run.demo.haus/)
- Review Percy to see how spacing on labels is affected

Remove bottom margin from label component

---

scss/_patterns_side-navigation.scss
scss/standalone/patterns_side-navigation.scss
templates/_layouts/docs.html
templates/docs/examples/patterns/side-navigation/default.html
templates/docs/examples/patterns/side-navigation/docs.html
templates/docs/patterns/navigation.md

Add right side status icons/labels to side navigation.
Part of #2862 
- `./run` or [demo](https://vanilla-framework-canonical-web-and-design-pr-2928.run.demo.haus/docs/examples/patterns/side-navigation/default)
- Check if labels and icons are displayed correctly on different levels of navigation

Side navigation status labels and icons

---

scss/_patterns_side-navigation.scss
templates/docs/examples/patterns/side-navigation/icons.html
templates/docs/patterns/navigation.md

Adds side navigation variant with icons on the left.
Fixes #2862 
- Run `./run` or [demo](https://vanilla-framework-canonical-web-and-design-pr-2932.run.demo.haus/docs/examples/patterns/side-navigation/icons)
- Make sure side nav works correctly with right side icons
- Make sure side nav default variant is not affected
- Make sure there are [docs](https://vanilla-framework-canonical-web-and-design-pr-2932.run.demo.haus/docs/patterns/navigation#side-navigation) describing the use of variant with icons
- please note CodePen example will show unstyled side nav, because it was not published yet

Add side navigation variant with icons on the left

---

scss/_patterns_side-navigation.scss

In side navigation with icons on left align group border with text rather than icon
- Run `./run` or [demo](https://vanilla-framework-canonical-web-and-design-pr-2935.run.demo.haus/docs/examples/patterns/side-navigation/icons)
- Check [side navigation with icons example](https://vanilla-framework-canonical-web-and-design-pr-2935.run.demo.haus/docs/examples/patterns/side-navigation/icons)
- Border between groups should be aligned with text rather than icons
- Make sure [variant without icons](https://vanilla-framework-canonical-web-and-design-pr-2935.run.demo.haus/docs/examples/patterns/side-navigation/default) is not affected

Align side navigation group border with text

---

scss/_patterns_label.scss
templates/docs/examples/patterns/side-navigation/_default.html
templates/docs/examples/patterns/side-navigation/_icons.html
templates/docs/examples/patterns/side-navigation/_script.js
templates/docs/examples/patterns/side-navigation/default.html
templates/docs/examples/templates/maas-docs-grid.html
templates/docs/examples/templates/maas-docs.html
templates/docs/examples/templates/maas-layout.html
templates/docs/examples/templates/snapcraft-publicise.html
webapp/app.py

Adds more examples for side navigation
Fixes #2865
- Run `./run` or [demo]
- Clicking on side nav in these examples is possible (JS is now added to make them interactive without navigating to other pages)
Check updated side nav examples (with wrapping, truncating, icons, etc):
https://vanilla-framework-canonical-web-and-design-pr-2937.run.demo.haus/docs/examples/patterns/side-navigation/default
MAAS current custom docs layout: https://vanilla-framework-canonical-web-and-design-pr-2937.run.demo.haus/docs/examples/templates/maas-docs
MAAS docs in grid: https://vanilla-framework-canonical-web-and-design-pr-2937.run.demo.haus/docs/examples/templates/maas-docs-grid
Snapcraft publicise: https://vanilla-framework-canonical-web-and-design-pr-2937.run.demo.haus/docs/examples/templates/snapcraft-pub …

Side navigation examples 

---

scss/_patterns_side-navigation.scss
scss/standalone/patterns_side-navigation.scss

Merge #2937 first
Updates left side spacing of side navigation items to follow grid margin values on different screen sizes.
- Run `./run` or [demo](https://vanilla-framework-canonical-web-and-design-pr-2940.run.demo.haus/docs/examples/patterns/side-navigation/default)
- Check side nav examples, make sure spacing on left side follows the grid margin on different screen sizes:
- [variants](https://vanilla-framework-canonical-web-and-design-pr-2940.run.demo.haus/docs/examples/patterns/side-navigation/default)
- [MAAS docs](https://vanilla-framework-canonical-web-and-design-pr-2940.run.demo.haus/docs/examples/templates/maas-docs)
- [MAAS in grid](https://vanilla-framework-canonical-web-and-design-pr-2940.run.demo.haus/docs/examples/templates/maas-docs-grid)
- …

Align side navigation item to grid margins

---

package.json

Makes sure pretty-quick only checks commited files, not autofixes them.
Removes outdated package.json comments.
- Pull code, (`yarn install` if you haven't set up vanilla before)
- Make some changes that would fail prettier (remove `;` in any SCSS file)
- Try to commit this change
- Precommit hook should fail and prevent the commit

Prevent pretty-quick from commiting changes in husky hook

---

scss/docs/docs.scss
templates/_layouts/docs.html
templates/static/js/scripts.js

Updates Vanilla docs to use new side navigation
Fixes #2864 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2936.run.demo.haus/docs)
- Review docs side navigation, make sure it works as expected on different screen sizes

Update Vanilla docs to use new side navigation

---

scss/_base_forms-tick-elements.scss
scss/_base_hr.scss
scss/_patterns_contextual-menu.scss
scss/_patterns_grid.scss
scss/_patterns_navigation.scss
scss/_patterns_search-box.scss
scss/_patterns_subnav.scss
scss/_vanilla.scss
templates/docs/examples/patterns/contextual-menu/dark.html
templates/docs/examples/patterns/contextual-menu/default.html
templates/docs/examples/patterns/navigation/subnav-dark.html
templates/docs/examples/patterns/navigation/subnav.html

Fixes #2894 
Update theme implementation in patterns to use mixins.
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2942.run.demo.haus/examples)
- There should be no change in visuals

Dark theme clean up

---

scss/_base_grid-definitions.scss
scss/_patterns_grid.scss
scss/_patterns_lists.scss
scss/docs/docs.scss
templates/_layouts/docs.html
templates/docs/examples/patterns/grid/default.html
templates/docs/examples/patterns/grid/responsive.html

Adds basic fallback implementation of grid for IE11 using flexbox.
For large screens (12 column grid) simplified flexbox based grid should be applied in IE11.
For smaller screens columns just render one under another.
Fixes #2685 
You can use [ignore whitespace](https://github.com/canonical-web-and-design/vanilla-framework/pull/2943/files?w=1) mode on GitHub when reviewing the code to avoid confusing diff where stuff got nested into `@supports`.
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2943.run.demo.haus/)
- Check grid examples:
- [basic](https://vanilla-framework-canonical-web-and-design-pr-2943.run.demo.haus/docs/examples/patterns/grid/default)
- [nested](https://vanilla-framework-canonical-web-and-design-pr-294 …

Add basic flexbox implementation of grid for IE

---

scss/_base_forms-tick-elements.scss
scss/_patterns_contextual-menu.scss
scss/_patterns_navigation.scss
scss/_patterns_search-box.scss
scss/_patterns_side-navigation.scss
scss/_patterns_subnav.scss
scss/_settings_colors.scss
scss/_settings_themes.scss
templates/docs/examples/base/hr-dark.html
templates/docs/examples/base/hr.html
templates/docs/examples/patterns/side-navigation/_default.html
templates/docs/examples/patterns/side-navigation/_icons.html
templates/docs/examples/patterns/side-navigation/dark.html

Adds dark theme for side navigation component.
Updates themes' color variable names to be more consistent.
Updates dark theme colors to use opacity.
Consistently use text color for side navigation active item border (rather than brand color).
Fixes #2863 
- Run `./run` or [demo](https://vanilla-framework-canonical-web-and-design-pr-2950.run.demo.haus/docs/examples/patterns/side-navigation/dark)
- Review [dark side navigation example](https://vanilla-framework-canonical-web-and-design-pr-2950.run.demo.haus/docs/examples/patterns/side-navigation/dark)
- Review [light side navigation example](https://vanilla-framework-canonical-web-and-design-pr-2950.run.demo.haus/docs/examples/patterns/side-navigation/default) - because active element border color changed
- Review other dark patterns …

Dark theme for side navigation dark

---

scss/_patterns_buttons.scss

Fixes selector to match all buttons with modifiers
Fixes #2938
- Run `./run or [demo](https://vanilla-framework-canonical-web-and-design-pr-2962.run.demo.haus/docs/examples/patterns/buttons/inline)
- Go to [inline button example](https://vanilla-framework-canonical-web-and-design-pr-2962.run.demo.haus/docs/examples/patterns/buttons/inline) - make sure button has margin on left side

Fix selector to match all buttons with modifiers

---

templates/index.html

Adds latest blog post to Vanilla home page
Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/774
- Pull code
- Run `./run`
- Go to home page and check if latest blog post is listed

Update listing of latest blog posts on home page

---

scss/_patterns_buttons.scss
scss/_patterns_card.scss

Updates the use of `[class^=]` attribute selector to `[class*=]` to make sure class name doesn't need to start with given value.
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2973.run.demo.haus/docs/examples/patterns/buttons/icon)
- Make sure there are no regressions (in Percy)
- Go to [button example with icon](https://vanilla-framework-canonical-web-and-design-pr-2973.run.demo.haus/docs/examples/patterns/buttons/icon). Change order or class names to "has-icon p-button", everything should look the same

Fix class attribute selectors

---

renovate.json

Updates `renovate.json` to use similar grouping config as maas-ui.
- Compare with https://github.com/canonical-web-and-design/maas-ui/blob/master/renovate.json

Update renovate.json based on maas-ui

---

.circleci/config.yml

Update Circle CI config to fail early when server doesn't run.
When running server fails, Circle CI job should fail before attempting to run screenshots for Percy:
https://app.circleci.com/pipelines/github/canonical-web-and-design/vanilla-framework/170/workflows/573e06ae-dbf1-42d3-9f82-aa80da350560/jobs/195
When server runs correctly, Circle CI should pass and send screenshots to Percy:
https://app.circleci.com/pipelines/github/canonical-web-and-design/vanilla-framework/171/workflows/d867e64a-e990-4d77-a1c8-9df1c4e2c0c3/jobs/196

Make sure Circle CI fails if server doesn't run

---

scss/_patterns_side-navigation.scss
templates/docs/examples/templates/maas-docs-grid.html

Adds sticky positioning to side navigation when page is scrolled.
When side navigation is longer than screen size it's separately scrolled.
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2993.run.demo.haus/docs/examples/templates/maas-docs-grid)
- Check [docs example with sticky navigation](https://vanilla-framework-canonical-web-and-design-pr-2993.run.demo.haus/docs/examples/templates/maas-docs-grid)
- Make sure side nav works as expected
- Check if mobile view is not affected

Sticky side navigation

---

templates/docs/examples/patterns/media-object/media-object-large.html

Don't rely on images from juju charms in examples, because screenshots will timeout when juju api is down
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2997.run.demo.haus/)
- CI jobs should pass
- Go to [large media object example](https://vanilla-framework-canonical-web-and-design-pr-2997.run.demo.haus/docs/examples/patterns/media-object/media-object-large), it should render icon from assets server

Don't rely on icon from juju charms

---

templates/docs/patterns/notification.md

Removed confusing sentence about margin in notification.
Fixes #2986
- Pull code
- Run `./run`
- Go to notification with action docs. Make sure margin is not mentioned.

Removed confusing sentence about margin in notification.

---

templates/docs/base/forms.md

- Linked from the description of 100% width to the section on how to override it
- Changed “Input” (which could cover many control types) to “Single-line text field”
- Merged “HTML5” (which could cover all control types) with the previous section
- Dropped “`color`” from the list of `input type`s that Vanilla styles, because it hasn’t since #2061
- Changed “Textarea” to “Multi-line text field”, to match the section above
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs/base/forms

Disambiguates “Input”, “HTML5”, and “Textarea”

---

templates/_layouts/docs.html
templates/docs/examples/index.html
templates/docs/examples/layouts/documentation.html
templates/docs/layouts/documentation.md

Needs #2988 
Adds documentation layout example and documentation page about documentation layout structure.
Fixes #2953
DEMO: https://vanilla-framework-canonical-web-and-design-pr-2996.run.demo.haus/docs/layouts/documentation
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-2996.run.demo.haus/docs/layouts/documentation)
- Go to [documentation layout page](https://vanilla-framework-canonical-web-and-design-pr-2996.run.demo.haus/docs/layouts/documentation), check if it has enough information
- Check [documentation layout example](https://vanilla-framework-canonical-web-and-design-pr-2996.run.demo.haus/docs/examples/layouts/documentation) if it has good structure to be used as a base for documentation sites to copy from

Documentation layout documentation

---

templates/docs/examples/patterns/notifications/information.html

Removes “Information:” from the Information notification example, to avoid people thinking that it’s boilerplate they’re supposed to include.
[Inspired by [ubuntu.com#6695](https://github.com/canonical-web-and-design/ubuntu.com/pull/6695).]

Changes notification example to not use “Information:”

---

templates/_layouts/docs.html

Remove duplicated side-navigation id from the template to make sure automatic scrolling to #side-navigation works properly
- Pull code
- Run `./run` or [demo](https://vanilla-framework-canonical-web-and-design-pr-3015.run.demo.haus/docs/patterns/navigation)
- Go to [Navigation page](https://vanilla-framework-canonical-web-and-design-pr-3015.run.demo.haus/docs/patterns/navigation)
- Click on [Side navigation](https://vanilla-framework-canonical-web-and-design-pr-3015.run.demo.haus/docs/patterns/navigation#side-navigation) sub item in side navigation
- Make sure the page scroll to side navigation part of documentation
- Go directly to [Side navigation](https://vanilla-framework-canonical-web-and-design-pr-3015.run.demo.haus/docs/patterns/navigation#side-navigation)
- Make sure page loads …

Remove duplicated side-navigation id from the template

---

scss/_patterns_modal.scss
templates/docs/examples/patterns/modal/_script.js
templates/docs/examples/patterns/modal/default.html
templates/docs/examples/patterns/modal/modal-scroll.html
templates/docs/patterns/modal.md

- Makes modal fixed to the window, so it's not affected by body scroll.
- Updates the styling to make modal dialog itself scrollable if it has more content than fits on the screen.
- Adds the border under modal header as per new design #2801
Fixes #2970
Fixes #2801
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-3018.run.demo.haus/docs/examples/patterns/modal/modal-scroll)
- Open [scrollable modal example](https://vanilla-framework-canonical-web-and-design-pr-3018.run.demo.haus/docs/examples/patterns/modal/modal-scroll)
- make sure large modal works on different screen sizes
- Open existing [modal example](https://vanilla-framework-canonical-web-and-design-pr-3018.run.demo.haus/docs/examples/patterns/modal/default)
- …

Fix scrolling with modal

---

scss/_base_tables.scss
templates/docs/examples/patterns/tables/table-colored-rows.html
templates/docs/examples/templates/firefox-grid-table-bug.html

- Use proper margins at the bottom of the tables instead of transparent borders (to fix the issue with height of last row #2971)
- Add new example with coloured rows (so Percy can keep track of it)
- Add separate example to cover Firefox (pre 75) [issue with growing table margins](https://bugzilla.mozilla.org/show_bug.cgi?id=1492315)
Fixes #2971
- Run `./run` or [demo](https://vanilla-framework-canonical-web-and-design-pr-3019.run.demo.haus/)
- Go to tables examples, make sure they work as expected:
- [base table](https://vanilla-framework-canonical-web-and-design-pr-3019.run.demo.haus/docs/examples/base/table)
- [colored table](https://vanilla-framework-canonical-web-and-design-pr-3019.run.demo.haus/docs/examples/patterns/tables/table-colored-rows)
- [expanding …

Properly use margin bottom on tables

---

templates/_layouts/docs.html

Added the missing `id` to the navigation element.
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3022
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs
- Shrink your screen to mobile size
- Click the navigation toggle and check it works.

Fix the small screen side navigation

---

templates/_layouts/docs.html

Follow up on #3023 and #3015 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-3024.run.demo.haus/docs/patterns/navigation)
- Make sure Vanilla documentation side navigation toggle works on mobile
- Make sure link to ["Side navigation"](https://vanilla-framework-canonical-web-and-design-pr-3024.run.demo.haus/docs/patterns/navigation#side-navigation) part of ["Navigation"](https://vanilla-framework-canonical-web-and-design-pr-3024.run.demo.haus/docs/patterns/navigation) page works

Make sure side navigation id doesn't collide with side navigation docs

---

templates/static/js/example.js
templates/static/js/scripts.js

Makes sure side navigation drawer closes when clicking on in-page anchors
Fixes some small JS issues in IE11.
Fixes #3025
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-3028.run.demo.haus/)
- On small screen (mobile)
- Go to documentation page with sections like [Code](https://vanilla-framework-canonical-web-and-design-pr-3028.run.demo.haus/docs/base/code)
- Open side navigation drawer
- Click on any page subsection (like Copyable)
- Side navigation drawer should close, page should scroll to chosen section

Close side navigation drawer on anchor click

---

scss/_patterns_tabs.scss

Fixes issue with tabs chevron appearing above other elements because of z-index.
Fixes issue that bottom border of tabs on small screens was scrolling off screen when tabs were scrolled.
Fixes #3027 
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo](https://vanilla-framework-canonical-web-and-design-pr-3029.run.demo.haus/)
- Go to [tabs](https://vanilla-framework-canonical-web-and-design-pr-3029.run.demo.haus/docs/examples/patterns/tabs), make sure they work as expected
- Go to CodePen https://codepen.io/bartoszopka/pen/JjYyaQE
- Resize the screen to make it smaller so that contextual menu appears above tabs chevron.
- Contextual menu should over the chevron.
https://cdpn.io/bartoszopka/debug/ExVveBy/VGkWNxzxLexA
https://cdpn.io/bartoszopka/debug/JjYyaQE/dXAqBNoNLPek

Fix z-index collisiton and bottom border in tabs on small screens

---

templates/static/js/scripts.js

Fixes JS error in console caused by side navigation script on search result pages
Fixes #3009
To QA you need search API key, see #2812 for details.
- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/docs
- Go to search results page
- There should be no error in console

Fix JS error on search results page

---

templates/docs/patterns/navigation.md
templates/docs/settings/color-settings.md

Fixes #2966 
Clarifies documentation about colors used by side navigation component
- Check [Side navigation documentation about color theming](https://vanilla-framework-canonical-web-and-design-pr-3051.run.demo.haus/docs/patterns/navigation#side-navigation)
- Check [Color theming](https://vanilla-framework-canonical-web-and-design-pr-3051.run.demo.haus/docs/settings/color-settings#color-theming) documentation, verify it's updated

Clarify side navigation color theming documentation

---

scss/_base_forms-range.scss
scss/_base_forms-tick-elements.scss
scss/_base_forms.scss
scss/_base_links.scss
scss/_patterns_buttons.scss
scss/_patterns_modal.scss
scss/_patterns_pagination.scss
scss/_patterns_switch.scss
scss/_settings_colors.scss
templates/docs/examples/base/forms/range.html
templates/docs/examples/patterns/slider/slider-input.html
templates/docs/settings/color-settings.md

- Update link blues for all states
- Make checkboxes, switch, radios etc use the link blue
Drive-by's:
- remove border radius from inputs, something we had agreed a long time ago but never implemented
- Update focus state bar thickness for some components which had it hardcoded to 2px. The correct variable is $bar-thickness, which is 3px.
Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3042
- Pull code
- Run `./run`
- Open as many examples as possible, QA link colour and focus states. E.g.:
docs/examples/patterns/buttons/icon
docs/examples/patterns/forms/form-inline
docs/examples/patterns/forms/form-stacked
docs/examples/patterns/forms/form-validation
Open the pagination specifically, verify visited (or other link colours) do not show when the buttons are in …

Update blue link colours

---

scss/_base_button.scss
scss/_base_forms-range.scss
scss/_base_forms-tick-elements.scss
scss/_base_forms.scss
scss/_patterns_buttons.scss
scss/_settings_colors.scss
templates/docs/examples/templates/tick-element-comparison.html

- adjust border color of interactive elements to meet AA on #f7f7f7 and lighter backgrounds; 
- small color refactor linking variables that should change in sync with each other
- update tick element template example to include more components in different states
Fixes #3057 
- Pull code
- Run `./run`
- QA forms examples, as many as possible; bare minimum: http://192.168.64.2:8101/docs/examples/templates/tick-element-comparison - border should be #717171 in all states

Adjust border color of interactive elements to meet AA 
